///////////////////////////////////////////////////////////////////////
// General Mage script.                                              //
// Nearly no cheat!                                                  //
// Script doesn't look your level, resistances and saving throws     //
//   to determine which target is the best for one spell             //
// It only looks what happens during the fight.                      //
// However, there are some "cheats"                                  //
// For power words, script look hit points. player can't but can get //
//   an approximate number.                                          //
// Script looks which potion you drink. player can't but can         //
//   sometimes find what it is, by looking for animation             //
///////////////////////////////////////////////////////////////////////

IF
  See([PC])
  NumTimesTalkedTo(0)
THEN
  RESPONSE #100
    StartDialog("_ANDRIS",[PC])
END

///////////////////////////////////////////////////////////////////////
// Threat Detection
//
// Attacked? Spell cast on me? Someone shouted a warning?
///////////////////////////////////////////////////////////////////////
IF
  !Allegiance(Myself,ENEMY)
  OR(12)
    AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
    AttackedBy([PC],DEFAULT)
    AttackedBy([FAMILIAR],DEFAULT)
    AttackedBy([ALLY],DEFAULT)
    AttackedBy([CONTROLLED],DEFAULT)
    AttackedBy([CHARMED],DEFAULT)
    SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
    SpellCastOnMe([PC],0)
    SpellCastOnMe([FAMILIAR],0)
    SpellCastOnMe([ALLY],0)
    SpellCastOnMe([CONTROLLED],0)
    SpellCastOnMe([CHARMED],0)
THEN
  RESPONSE #100
    Enemy()
    Shout(99)
    Continue()
END

IF
  Heard([ANYONE],99)
  Allegiance(Myself,NEUTRAL)
  !Class(Myself,INNOCENT)
THEN
  RESPONSE #100
    Enemy()
    MoveToObject(LastHeardBy(Myself))
    Continue()
END

IF
  Heard([ANYONE],99)
  !See(NearestEnemyOf(Myself))  
  !Class(Myself,INNOCENT)
THEN
  RESPONSE #100
    MoveToObject(LastHeardBy(Myself))
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Just after resting, everything is reset and creature is healed
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_PrepTimer","LOCALS")
  Global("ap_initialize","LOCALS",1)
THEN
  RESPONSE #100
    Rest()
    ApplySpellRES("JA#HEAL",Myself)
    SetGlobal("ap_initialize","LOCALS",0)
END


///////////////////////////////////////////////////////////////////////
// Initialize variables & timers
///////////////////////////////////////////////////////////////////////
IF
  Global("ap_initialize","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("ap_initialize","LOCALS",1)
    SetGlobal("ap_prepspells","LOCALS",0)
    SetGlobal("ap_contigency","LOCALS",0)
    SetGlobal("ap_sequencer","LOCALS",0)
    SetGlobal("ap_buffdone","LOCALS",0)
    SetGlobal("ap_startcombat","LOCALS",0)
    SetGlobalTimer("ap_globe","LOCALS",0)
    SetGlobalTimer("ap_weaponprot","LOCALS",0)
    SetGlobalTimer("ap_cast","LOCALS",0)
    SetGlobalTimer("ap_PrepTimer","LOCALS",2400)
END


/////////////////////////////////////////////////////////////////////
// Mages always cast their long protection spells before combat
// (long = 1 turn per level, and in general more than 5 turns)
// Also some long duration weapons & summons
////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Stoneskin
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_STONE_SKIN)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Protection from fire
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_PROTECTION_FROM_FIRE)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_FIRE)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Protection from cold
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_PROTECTION_FROM_COLD)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_COLD)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Protection from eletricity
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_PROTECTION_FROM_ELECTRICITY)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ELECTRICITY)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Protection from acid
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_PROTECTION_FROM_ACID)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ACID)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Protection from magical energy
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Armor
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_ARMOR)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_ARMOR)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Ghost armor
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_GHOST_ARMOR)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_GHOST_ARMOR)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Spirit armor
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_SPIRIT_ARMOR)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_SPIRIT_ARMOR)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Strength
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_STRENGTH)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_STRENGTH)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Melf meteor
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_MELF_METEOR)
  CheckStatLT(Myself,20,LEVEL)  
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_MELF_METEOR)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Animate Dead
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
  HaveSpell(WIZARD_ANIMATE_DEAD)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_ANIMATE_DEAD)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// End of long protection spells 
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_prepspells","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("ap_prepspells","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Counter silence
/////////////////////////////////////////////////////////////////////
IF
  StateCheck(Myself,STATE_SILENCED)
  HaveSpell(WIZARD_VOCALIZE)  
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_VOCALIZE)
END


/////////////////////////////////////////////////////////////////////
// See an enemy ? Alert nearby allies
/////////////////////////////////////////////////////////////////////
IF
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("ap_shout","LOCALS")
THEN
  RESPONSE #100
    Shout(99)
    SetGlobalTimer("ap_shout","LOCALS",30)
    SetGlobal("ap_startcombat","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Do nothing if no enemy is detected and no combat started
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_startcombat","LOCALS",0)
  !Detect(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    NoAction()
END


/////////////////////////////////////////////////////////////////////
// Shouts (credits to Echon)
/////////////////////////////////////////////////////////////////////
IF
  HasItem("_POTN08",Myself)  // Potion of Healing
  HPPercentGT(Myself,50)
  Heard([EVILCUTOFF],4)
  !HasItem("_POTN08",LastHeardBy(Myself))  // Potion of Healing
  !HasItem("_POTN17",LastHeardBy(Myself)) // Elixir of Health
THEN
  RESPONSE #100
    GiveItem("_POTN08",LastHeardBy(Myself))  // Potion of Healing
END

IF
  HasItem("_POTN17",Myself)  // Elixir of Health
  HPPercentGT(Myself,50)
  Heard([EVILCUTOFF],4)
  !HasItem("_POTN08",LastHeardBy(Myself))  // Potion of Healing
  !HasItem("_POTN17",LastHeardBy(Myself))  // Elixir of Health
THEN
  RESPONSE #100
    GiveItem("_POTN17",LastHeardBy(Myself))  // Elixir of Health
END

IF
  !HasItem("_POTN08",Myself)  // Potion of Healing
  !HasItem("_POTN17",Myself) // Elixir of Health
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("ShoutHealing","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("ShoutHealing","LOCALS",12)
    Shout(4)
END

IF
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("ShoutHealing","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("ShoutHealing","LOCALS",12)
    Shout(2)
END

IF
  See(NearestEnemyOf(Myself))
  !Heard([EVILCUTOFF],51)
  !GlobalTimerNotExpired("ShoutSeeEnemy","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("ShoutSeeEnemy","LOCALS",30)
    VerbalConstant(Myself,BATTLE_CRY)
    Shout(51)
END

IF
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  Heard([EVILCUTOFF],51)
  !GlobalTimerNotExpired("ShoutSeeEnemy2","LOCALS")
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("ShoutSeeEnemy2","LOCALS",30)
    Shout(51)
    MoveToObject(LastHeardBy(Myself))
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  Heard([EVILCUTOFF],51)
  !GlobalTimerNotExpired("ShoutSeeEnemy2","LOCALS")
  Exists(LastHeardBy(LastHeardBy(Myself)))
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("ShoutSeeEnemy2","LOCALS",30)
    Shout(51)
    MoveToObject(LastHeardBy(LastHeardBy(Myself)))
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  Heard([EVILCUTOFF],51)
  !GlobalTimerNotExpired("ShoutSeeEnemy2","LOCALS")
  Exists(LastHeardBy(LastHeardBy(LastHeardBy(Myself))))
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("ShoutSeeEnemy2","LOCALS",30)
    Shout(51)
    MoveToObject(LastHeardBy(LastHeardBy(LastHeardBy(Myself))))
    SetInterrupt(TRUE)
END

IF
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  Heard([EVILCUTOFF],51)
  !GlobalTimerNotExpired("ShoutSeeEnemy2","LOCALS")
  Exists(LastHeardBy(LastHeardBy(LastHeardBy(LastHeardBy(Myself)))))
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobalTimer("ShoutSeeEnemy2","LOCALS",30)
    Shout(51)
    MoveToObject(LastHeardBy(LastHeardBy(LastHeardBy(LastHeardBy(Myself)))))
    SetInterrupt(TRUE)
END


/////////////////////////////////////////////////////////////////////
// Special escape for Shandalar
/////////////////////////////////////////////////////////////////////
IF
  HPLT(Myself,40)
  HaveSpell(WIZARD_DIMENSION_DOOR)
  See(NearestEnemyOf(Myself))
  CheckStatGT(Myself,25,LEVEL)
THEN
  RESPONSE #100
    ReallyForceSpell(Myself,WIZARD_IMPROVED_MANTLE)
    ReallyForceSpell(Myself,WIZARD_GATE)
    ReallyForceSpell(Myself,DRYAD_TELEPORT)
END


/////////////////////////////////////////////////////////////////////
// Chain contigencies for level 20+
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_contigency","LOCALS",0)
  CheckStatGT(Myself,19,LEVEL)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    DisplayString(Myself,26328) // Chain Contingency
    ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    Wait(1)
    ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    Wait(1)
    ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    SetGlobal("ap_contigency","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Chain contigencies for level 18-20
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_contigency","LOCALS",0)
  CheckStatGT(Myself,17,LEVEL)
  CheckStatLT(Myself,20,LEVEL)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    DisplayString(Myself,26328) // Chain Contingency
    ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)
    ReallyForceSpell(Myself,WIZARD_MORDENKAINENS_SWORD)    
    ReallyForceSpell(Myself,WIZARD_IMPROVED_MANTLE)
    SetGlobalTimer("ap_weaponprot","LOCALS",24)
    SetGlobal("ap_contigency","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Contigency for level 15-17
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_contigency","LOCALS",0)
  CheckStatGT(Myself,14,LEVEL)
  CheckStatLT(Myself,18,LEVEL)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    DisplayString(Myself,84763) // Contingency Released
    ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_ANIMATE_DEAD)
    SetGlobal("ap_contigency","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Contigency for level 12-14
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_contigency","LOCALS",0)
  CheckStatGT(Myself,11,LEVEL)
  CheckStatLT(Myself,15,LEVEL)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    DisplayString(Myself,84763) // Contingency Released
    ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
    SetGlobalTimer("ap_globe","LOCALS",66)
    SetGlobal("ap_contigency","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Minor sequencer for level 7-14 (except necromancer)
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_sequencer","LOCALS",0)
  GlobalTimerExpired("ap_cast","LOCALS")
  CheckStatGT(Myself,6,LEVEL)
  CheckStatLT(Myself,14,LEVEL)
  !CheckStat(Myself,4096,KIT)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",2)
    DisplayString(Myself,8635) // Minor Sequencer Activated
    ReallyForceSpell(Myself,WIZARD_SHIELD)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    SetGlobal("ap_sequencer","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Minor sequencer for necromancers level 7-14
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_sequencer","LOCALS",0)
  GlobalTimerExpired("ap_cast","LOCALS")
  CheckStatGT(Myself,6,LEVEL)
  CheckStatLT(Myself,14,LEVEL)
  CheckStat(Myself,4096,KIT)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",2)
    DisplayString(Myself,8635) // Minor Sequencer Activated
    ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_HORROR)
    Wait(1)
    ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_HORROR)
    SetGlobal("ap_sequencer","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Spell sequencer for level 14-15
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_sequencer","LOCALS",0)
  GlobalTimerExpired("ap_cast","LOCALS")
  CheckStatGT(Myself,13,LEVEL)
  CheckStatLT(Myself,16,LEVEL)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",2)
    DisplayString(Myself,25951) // Spell Sequencer
    ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
    ReallyForceSpell(Myself,WIZARD_SPIRIT_ARMOR)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)
    SetGlobalTimer("ap_globe","LOCALS",78)
    SetGlobal("ap_sequencer","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Spell trigger for level 16+
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_sequencer","LOCALS",0)
  GlobalTimerExpired("ap_cast","LOCALS")
  CheckStatGT(Myself,15,LEVEL)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",2)
    DisplayString(Myself,26243) // Spell Trigger
    ReallyForceSpell(Myself,WIZARD_TRUE_SIGHT)    
    ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    SetGlobalTimer("ap_weaponprot","LOCALS",24)
    SetGlobalTimer("ap_globe","LOCALS",90)
    SetGlobal("ap_sequencer","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Timestop sequence
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_TIME_STOP)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",18)
    Spell(Myself,WIZARD_TIME_STOP)
    Wait(1)
    Spell(Myself,WIZARD_IMPROVED_ALUCRITY)
    UseItem("_POTN55",Myself) // Potion of Superior Healing
    Spell(NearestEnemyOf(Myself),WIZARD_GREATER_MALISON)
    Spell(NearestEnemyOf(Myself),WIZARD_DRAGONS_BREATH)
    Spell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    Spell(Myself,WIZARD_ENERGY_BLADES)
    Spell(Myself,WIZARD_SPELL_TRAP)
END


/////////////////////////////////////////////////////////////////////
// Friends
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_FRIENDS)
THEN
  RESPONSE #100
    JoinParty()
END


/////////////////////////////////////////////////////////////////////
// Improved mantle
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_IMPROVED_MANTLE)
  GlobalTimerExpired("ap_weaponprot","LOCALS")
  See(NearestEnemyOf(Myself))  
  HitBy([ANYONE],CRUSHING)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_IMPROVED_MANTLE)
    SetGlobalTimer("ap_weaponprot","LOCALS",24)
END


/////////////////////////////////////////////////////////////////////
// Mantle
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_MANTLE)
  GlobalTimerExpired("ap_weaponprot","LOCALS")
  See(NearestEnemyOf(Myself))  
  HitBy([ANYONE],CRUSHING)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_MANTLE)
    SetGlobalTimer("ap_weaponprot","LOCALS",24)
END


/////////////////////////////////////////////////////////////////////
// Protection from magical weapons
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  GlobalTimerExpired("ap_weaponprot","LOCALS")
  See(NearestEnemyOf(Myself))  
  HitBy([ANYONE],CRUSHING)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    SetGlobalTimer("ap_weaponprot","LOCALS",24)
END


/////////////////////////////////////////////////////////////////////
// Stoneskin (recast when have less than 2 stoneskins)
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_STONE_SKIN)
  CheckStatLT(Myself,2,STONESKINS)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_STONE_SKIN)
END


/////////////////////////////////////////////////////////////////////
// Healing potions
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HasItemEquiped("POTN55",Myself) // Potion of Superior Healing
  HPPercentLT(Myself,50)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    UseItem("POTN55",Myself) // Potion of Superior Healing
END

IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HasItemEquiped("_POTN52",Myself) // Potion of Extra Healing
  HPPercentLT(Myself,60)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    UseItem("_POTN52",Myself) // Potion of Extra Healing
END

IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HasItemEquiped("_POTN17",Myself) // Elixir of Health
  OR(2)
    HPPercentLT(Myself,30)
    StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    UseItem("_POTN17",Myself) // Elixir of Health
END

IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HasItemEquiped("_POTN08",Myself) // Potion of Healing
  HPPercentLT(Myself,30)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    UseItem("_POTN08",Myself) // Potion of Healing
END


/////////////////////////////////////////////////////////////////////
// Dimension door at will
/////////////////////////////////////////////////////////////////////
IF
  Global("AndrisBehavior","FW1009",0)
  See(NearestEnemyOf(Myself))
  GlobalTimerExpired("dimension","LOCALS")
THEN
  RESPONSE #100
    ForceSpellPoint([2002.1554],WIZARD_DIMENSION_DOOR)
    SetGlobal("AndrisBehavior","FW1009",1)
    SetGlobalTimer("dimension","LOCALS",18)
END

IF
  Global("AndrisBehavior","FW1009",1)
  See(NearestEnemyOf(Myself))
  GlobalTimerExpired("dimension","LOCALS")
THEN
  RESPONSE #100
    ForceSpellPoint([2041.1137],WIZARD_DIMENSION_DOOR)
    SetGlobal("AndrisBehavior","FW1009",2)
    SetGlobalTimer("dimension","LOCALS",18)
END

IF
  Global("AndrisBehavior","FW1009",2)
  See(NearestEnemyOf(Myself))
  GlobalTimerExpired("dimension","LOCALS")
THEN
  RESPONSE #100
    ForceSpell([ANYONE],WIZARD_DIMENSION_DOOR)
    SetGlobalTimer("dimension","LOCALS",18)
END


/////////////////////////////////////////////////////////////////////
// Are there any enemies that try to escape, follow them
// It's not about sight but memory (I saw that enemy going in that dir.)
/////////////////////////////////////////////////////////////////////
IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  !StateCheck(LastAttackerOf(Myself),STATE_INVISIBLE)
  Range(LastAttackerOf(Myself),70)
THEN
  RESPONSE #100
    MoveToObject(LastAttackerOf(Myself))
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  Range(LastSeenBy(Myself),70)
THEN
  RESPONSE #100
    MoveToObject(LastSeenBy(Myself))
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  !StateCheck(Player1,STATE_INVISIBLE)
  Range(Player1,70)
THEN
  RESPONSE #100
    MoveToObject(Player1)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  !StateCheck(Player2,STATE_INVISIBLE)
  Range(Player2,70)
THEN
  RESPONSE #100
    MoveToObject(Player2)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  !StateCheck(Player3,STATE_INVISIBLE)
  Range(Player3,70)
THEN
  RESPONSE #100
    MoveToObject(Player3)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  !StateCheck(Player4,STATE_INVISIBLE)
  Range(Player4,70)
THEN
  RESPONSE #100
    MoveToObject(Player4)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  !StateCheck(Player5,STATE_INVISIBLE)
  Range(Player5,70)
THEN
  RESPONSE #100
    MoveToObject(Player5)
    Continue()
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !See(NearestEnemyOf(Myself))
  !StateCheck(Player6,STATE_INVISIBLE)
  Range(Player6,70)
THEN
  RESPONSE #100
    MoveToObject(Player6)
    Continue()
END


/////////////////////////////////////////////////////////////////////
// Do nothing if no enemy is detected
/////////////////////////////////////////////////////////////////////
IF
  !Detect(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    NoAction()
END


/////////////////////////////////////////////////////////////////////
// Tenser Transformation when no more weapon protections
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_TENSERS_TRANSFORMATION)  
  !HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !HaveSpell(WIZARD_STONE_SKIN)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",72)
    Spell(Myself,WIZARD_TENSERS_TRANSFORMATION)
END


/////////////////////////////////////////////////////////////////////
// Shadow door
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  !StateCheck(Myself,STATE_INVISIBLE)
  HaveSpell(WIZARD_SHADOW_DOOR)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_SHADOW_DOOR)
END


/////////////////////////////////////////////////////////////////////
// Improved invisibilty
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  !StateCheck(Myself,STATE_INVISIBLE)
  HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)
END


/////////////////////////////////////////////////////////////////////
// Invisibility
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  !StateCheck(Myself,STATE_INVISIBLE)
  HaveSpell(WIZARD_INVISIBILITY)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_INVISIBILITY)
END


/////////////////////////////////////////////////////////////////////
// Potion of invisibility
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  !StateCheck(Myself,STATE_INVISIBLE)  
  HasItem("_POTN10",Myself) // Potion of Invisibility
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    UseItem("_POTN10",Myself) // Potion of Invisibility
END


/////////////////////////////////////////////////////////////////////
// Invisibility on 3 meters
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  !StateCheck(Myself,STATE_INVISIBLE)
  HaveSpell(WIZARD_INVISIBILITY_10_FOOT)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_INVISIBILITY_10_FOOT)
END


/////////////////////////////////////////////////////////////////////
// Protection from normal weapons
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
END


/////////////////////////////////////////////////////////////////////
// Globe of invulnerability
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)  
  GlobalTimerExpired("ap_globe","LOCALS")
  CheckStat(Myself,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
    SetGlobalTimer("ap_globe","LOCALS",66)
END


/////////////////////////////////////////////////////////////////////
// Minor globe of invulnerability
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
  CheckStat(Myself,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
    SetGlobalTimer("ap_globe","LOCALS",54)
END


/////////////////////////////////////////////////////////////////////
// Spell immunity : Invocation
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SPELL_IMMUNITY_INVOCATION)  
  GlobalTimerExpired("ap_globe","LOCALS")
  CheckStat(Myself,0,MINORGLOBE)
  !HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
  !HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_SPELL_IMMUNITY_INVOCATION)
END


/////////////////////////////////////////////////////////////////////
// Spell immunity : Enchantment
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SPELL_IMMUNITY_ENCHANTMENT)  
  GlobalTimerExpired("ap_globe","LOCALS")
  CheckStat(Myself,0,MINORGLOBE)  
  !HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
  !HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_SPELL_IMMUNITY_ENCHANTMENT)
END


/////////////////////////////////////////////////////////////////////
// Blur
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_BLUR)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_BLUR)
END


/////////////////////////////////////////////////////////////////////
// Fire shield red
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_FIRE_SHIELD_RED)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_FIRE_SHIELD_RED)
END


/////////////////////////////////////////////////////////////////////
// Mirror image
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_MIRROR_IMAGE)  
  !StateCheck(Myself,STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_MIRROR_IMAGE)
END


/////////////////////////////////////////////////////////////////////
// True sight
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_TRUE_SIGHT)
END


/////////////////////////////////////////////////////////////////////
// Protection from evil
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_PROTECTION_FROM_EVIL)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_PROTECTION_FROM_EVIL)
END


/////////////////////////////////////////////////////////////////////
// Improved haste
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_IMPROVED_HASTE)
  !StateCheck(Myself,STATE_HASTED)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_IMPROVED_HASTE)
END


/////////////////////////////////////////////////////////////////////
// Haste
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_HASTE)
  !StateCheck(Myself,STATE_HASTED)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_HASTE)
END


/////////////////////////////////////////////////////////////////////
// Wraith form
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_WRAITH_FORM)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_WRAITH_FORM)
END


/////////////////////////////////////////////////////////////////////
// Other potions
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HasItem("_POTN09",Myself) // Potion of Heroism
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    UseItem("_POTN09",Myself) // Potion of Heroism
END

IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HasItem("_POTN14",Myself) // Oil of Speed
  !StateCheck(Myself,STATE_HASTED)
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    UseItem("_POTN14",Myself) // Oil of Speed
END


/////////////////////////////////////////////////////////////////////
// If all buffing spells are done, combat can start
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_buffdone","LOCALS",0)
  !HaveSpell(WIZARD_BLUR)
  !HaveSpell(WIZARD_FIRE_SHIELD_RED)
  !HaveSpell(WIZARD_TRUE_SIGHT)
  !HaveSpell(WIZARD_PROTECTION_FROM_EVIL)
  !HaveSpell(WIZARD_IMPROVED_HASTE)
  !HaveSpell(WIZARD_HASTE)
  !HaveSpell(WIZARD_WRAITH_FORM)
THEN
  RESPONSE #100
    SetGlobal("ap_buffdone","LOCALS",1)
END

IF
  Global("ap_buffdone","LOCALS",0)
  !StateCheck(Myself,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobal("ap_buffdone","LOCALS",1)
    SetGlobalTimer("ap_dimension","LOCALS",18)
END


/////////////////////////////////////////////////////////////////////
// Not ready to attack, wait
/////////////////////////////////////////////////////////////////////
IF
  Global("ap_buffdone","LOCALS",0)
THEN
  RESPONSE #100
    NoAction()
END
  

/////////////////////////////////////////////////////////////////////
// Now, it's time to kill things
// Priorities are:
//   Remove magic on buffed people
//   Power word
//   Charm/dominate the best fighter
//   Destroy mage's defense
//   Disable spells
//   Damage spells
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Find a target that has something to dispel
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  OR(5)
    CheckStatGT(SixthNearestEnemyOf(Myself),18,STR)
    HasImmunityEffects(SixthNearestEnemyOf(Myself))
    CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
    CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
    CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  OR(5)
    CheckStatGT(FifthNearestEnemyOf(Myself),18,STR)
    HasImmunityEffects(FifthNearestEnemyOf(Myself))
    CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
    CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
    CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  OR(5)  
    CheckStatGT(FourthNearestEnemyOf(Myself),18,STR)
    HasImmunityEffects(FourthNearestEnemyOf(Myself))
    CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
    CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
    CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  OR(5)
    CheckStatGT(ThirdNearestEnemyOf(Myself),18,STR)  
    HasImmunityEffects(ThirdNearestEnemyOf(Myself))  
    CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
    CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
    CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  OR(5)
    CheckStatGT(SecondNearestEnemyOf(Myself),18,STR)
    HasImmunityEffects(SecondNearestEnemyOf(Myself))
    CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
    CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
    CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  OR(5)  
    CheckStatGT(NearestEnemyOf(Myself),18,STR)
    HasImmunityEffects(NearestEnemyOf(Myself))
    CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
    CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
    CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Remove magic
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  OR(5)
    CheckStatGT(LastSeenBy(Myself),18,STR)
    HasImmunityEffects(LastSeenBy(Myself))
    CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
    CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
    CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END


/////////////////////////////////////////////////////////////////////
// Breach
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_BREACH)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  OR(4)
    HasImmunityEffects(LastSeenBy(Myself))
    CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
    CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
    CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)
END


/////////////////////////////////////////////////////////////////////
// Begin of block:
// Power word kill
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  HPLT(SixthNearestEnemyOf(Myself),60)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  HPLT(FifthNearestEnemyOf(Myself),60)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  HPLT(FourthNearestEnemyOf(Myself),60)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  HPLT(ThirdNearestEnemyOf(Myself),60)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  HPLT(SecondNearestEnemyOf(Myself),60)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  HPLT(NearestEnemyOf(Myself),60)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_KILL)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  HPLT(LastSeenBy(Myself),60)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
END
/////////////////////////////////////////////////////////////////////
// End of block:
// Power word kill
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Begin of block:
// Power word blind
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(SixthNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(SixthNearestEnemyOf(Myself),PALADIN_ALL)
    Class(SixthNearestEnemyOf(Myself),RANGER_ALL)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(FifthNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(FifthNearestEnemyOf(Myself),PALADIN_ALL)
    Class(FifthNearestEnemyOf(Myself),RANGER_ALL)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(FourthNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(FourthNearestEnemyOf(Myself),PALADIN_ALL)
    Class(FourthNearestEnemyOf(Myself),RANGER_ALL)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(ThirdNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(ThirdNearestEnemyOf(Myself),PALADIN_ALL)
    Class(ThirdNearestEnemyOf(Myself),RANGER_ALL)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(SecondNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(SecondNearestEnemyOf(Myself),PALADIN_ALL)
    Class(SecondNearestEnemyOf(Myself),RANGER_ALL)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(NearestEnemyOf(Myself),FIGHTER_ALL)
    Class(NearestEnemyOf(Myself),PALADIN_ALL)
    Class(NearestEnemyOf(Myself),RANGER_ALL)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  OR(3)
    Class(LastSeenBy(Myself),FIGHTER_ALL)
    Class(LastSeenBy(Myself),PALADIN_ALL)
    Class(LastSeenBy(Myself),RANGER_ALL)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
END
/////////////////////////////////////////////////////////////////////
// End of block:
// Power word blind
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Begin of block:
// Power word stun
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(SixthNearestEnemyOf(Myself),30)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(FifthNearestEnemyOf(Myself),30)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(FourthNearestEnemyOf(Myself),30)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(ThirdNearestEnemyOf(Myself),30)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(SecondNearestEnemyOf(Myself),30)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(NearestEnemyOf(Myself),30)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_STUN)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(LastSeenBy(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
END
/////////////////////////////////////////////////////////////////////
// End of block:
// Power word stun
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Begin of block:
// Power word silence
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SILENCED)
  CheckStatLT(SixthNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(4)
    Class(SixthNearestEnemyOf(Myself),DRUID_ALL)
    Class(SixthNearestEnemyOf(Myself),BARD_ALL)
    Class(SixthNearestEnemyOf(Myself),CLERIC_ALL)
    Class(SixthNearestEnemyOf(Myself),MAGE_ALL)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SILENCED)
  CheckStatLT(FifthNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(4)
    Class(FifthNearestEnemyOf(Myself),DRUID_ALL)
    Class(FifthNearestEnemyOf(Myself),BARD_ALL)
    Class(FifthNearestEnemyOf(Myself),CLERIC_ALL)
    Class(FifthNearestEnemyOf(Myself),MAGE_ALL)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SILENCED)
  CheckStatLT(FourthNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(4)
    Class(FourthNearestEnemyOf(Myself),DRUID_ALL)
    Class(FourthNearestEnemyOf(Myself),BARD_ALL)
    Class(FourthNearestEnemyOf(Myself),CLERIC_ALL)
    Class(FourthNearestEnemyOf(Myself),MAGE_ALL)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SILENCED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  OR(4)
    Class(ThirdNearestEnemyOf(Myself),DRUID_ALL)
    Class(ThirdNearestEnemyOf(Myself),BARD_ALL)
    Class(ThirdNearestEnemyOf(Myself),CLERIC_ALL)
    Class(ThirdNearestEnemyOf(Myself),MAGE_ALL)  
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SILENCED)
  CheckStatLT(SecondNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  OR(4)
    Class(SecondNearestEnemyOf(Myself),DRUID_ALL)
    Class(SecondNearestEnemyOf(Myself),BARD_ALL)
    Class(SecondNearestEnemyOf(Myself),CLERIC_ALL)
    Class(SecondNearestEnemyOf(Myself),MAGE_ALL)  
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(NearestEnemyOf(Myself),STATE_SILENCED)
  CheckStatLT(NearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  OR(4)
    Class(NearestEnemyOf(Myself),DRUID_ALL)
    Class(NearestEnemyOf(Myself),BARD_ALL)
    Class(NearestEnemyOf(Myself),CLERIC_ALL)
    Class(NearestEnemyOf(Myself),MAGE_ALL)  
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_SILENCE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
  CheckStatLT(LastSeenBy(Myself),49,SPELLFAILUREPRIEST)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  OR(4)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),MAGE_ALL)  
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)
END
/////////////////////////////////////////////////////////////////////
// End of block:
// Power word silence
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Begin of block:
// Power word sleep
/////////////////////////////////////////////////////////////////////
IF
  !Race(SixthNearestEnemyOf(Myself),ELF)
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(SixthNearestEnemyOf(Myself),21)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(FifthNearestEnemyOf(Myself),ELF)
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(FifthNearestEnemyOf(Myself),21)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(FourthNearestEnemyOf(Myself),ELF)
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(FourthNearestEnemyOf(Myself),21)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(ThirdNearestEnemyOf(Myself),ELF)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(ThirdNearestEnemyOf(Myself),21)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(SecondNearestEnemyOf(Myself),ELF)
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(SecondNearestEnemyOf(Myself),21)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(NearestEnemyOf(Myself),ELF)
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(NearestEnemyOf(Myself),21)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_POWER_WORD_SLEEP)
  !Race(LastSeenBy(Myself),ELF)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  HPLT(LastSeenBy(Myself),21)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SLEEP)
END
/////////////////////////////////////////////////////////////////////
// End of block:
// Power word sleep
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Find a fighter to charm/dominate
/////////////////////////////////////////////////////////////////////
IF
  !Race(SixthNearestEnemyOf(Myself),ELF)
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(SixthNearestEnemyOf(Myself),30)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(SixthNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(SixthNearestEnemyOf(Myself),PALADIN_ALL)
    Class(SixthNearestEnemyOf(Myself),RANGER_ALL)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(FifthNearestEnemyOf(Myself),ELF)
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(FifthNearestEnemyOf(Myself),30)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(FifthNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(FifthNearestEnemyOf(Myself),PALADIN_ALL)
    Class(FifthNearestEnemyOf(Myself),RANGER_ALL)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(FourthNearestEnemyOf(Myself),ELF)
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(FourthNearestEnemyOf(Myself),30)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(FourthNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(FourthNearestEnemyOf(Myself),PALADIN_ALL)
    Class(FourthNearestEnemyOf(Myself),RANGER_ALL)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(ThirdNearestEnemyOf(Myself),ELF)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(ThirdNearestEnemyOf(Myself),30)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(ThirdNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(ThirdNearestEnemyOf(Myself),PALADIN_ALL)
    Class(ThirdNearestEnemyOf(Myself),RANGER_ALL)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(SecondNearestEnemyOf(Myself),ELF)
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(SecondNearestEnemyOf(Myself),30)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(SecondNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(SecondNearestEnemyOf(Myself),PALADIN_ALL)
    Class(SecondNearestEnemyOf(Myself),RANGER_ALL)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(NearestEnemyOf(Myself),ELF)
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(NearestEnemyOf(Myself),30)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(NearestEnemyOf(Myself),FIGHTER_ALL)
    Class(NearestEnemyOf(Myself),PALADIN_ALL)
    Class(NearestEnemyOf(Myself),RANGER_ALL)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Great Malison before trying a charm spell
/////////////////////////////////////////////////////////////////////  
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_GREATER_MALISON)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END


/////////////////////////////////////////////////////////////////////
// Dire charm
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_DIRE_CHARM)
  !Race(LastSeenBy(Myself),ELF)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  HPPercentGT(LastSeenBy(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  OR(3)
    Class(LastSeenBy(Myself),FIGHTER_ALL)
    Class(LastSeenBy(Myself),PALADIN_ALL)
    Class(LastSeenBy(Myself),RANGER_ALL)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_DIRE_CHARM)
END


/////////////////////////////////////////////////////////////////////
// Charm person
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_CHARM_PERSON)  
  !Race(LastSeenBy(Myself),ELF)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  HPPercentGT(LastSeenBy(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  OR(3)
    Class(LastSeenBy(Myself),FIGHTER_ALL)
    Class(LastSeenBy(Myself),PALADIN_ALL)
    Class(LastSeenBy(Myself),RANGER_ALL)
  See(LastSeenBy(Myself))  
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_CHARM_PERSON)
END

IF
  !Race(SixthNearestEnemyOf(Myself),ELF)
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(SixthNearestEnemyOf(Myself),30)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(SixthNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(SixthNearestEnemyOf(Myself),PALADIN_ALL)
    Class(SixthNearestEnemyOf(Myself),RANGER_ALL)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(FifthNearestEnemyOf(Myself),ELF)
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(FifthNearestEnemyOf(Myself),30)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(FifthNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(FifthNearestEnemyOf(Myself),PALADIN_ALL)
    Class(FifthNearestEnemyOf(Myself),RANGER_ALL)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(FourthNearestEnemyOf(Myself),ELF)
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(FourthNearestEnemyOf(Myself),30)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(FourthNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(FourthNearestEnemyOf(Myself),PALADIN_ALL)
    Class(FourthNearestEnemyOf(Myself),RANGER_ALL)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(ThirdNearestEnemyOf(Myself),ELF)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(ThirdNearestEnemyOf(Myself),30)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(ThirdNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(ThirdNearestEnemyOf(Myself),PALADIN_ALL)
    Class(ThirdNearestEnemyOf(Myself),RANGER_ALL)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(SecondNearestEnemyOf(Myself),ELF)
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(SecondNearestEnemyOf(Myself),30)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(SecondNearestEnemyOf(Myself),FIGHTER_ALL)
    Class(SecondNearestEnemyOf(Myself),PALADIN_ALL)
    Class(SecondNearestEnemyOf(Myself),RANGER_ALL)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Race(NearestEnemyOf(Myself),ELF)
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  HPPercentGT(NearestEnemyOf(Myself),30)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    Class(NearestEnemyOf(Myself),FIGHTER_ALL)
    Class(NearestEnemyOf(Myself),PALADIN_ALL)
    Class(NearestEnemyOf(Myself),RANGER_ALL)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

/////////////////////////////////////////////////////////////////////
// Domination
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_DOMINATION)
  !Race(LastSeenBy(Myself),ELF)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  HPPercentGT(LastSeenBy(Myself),30)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  OR(3)
    Class(LastSeenBy(Myself),FIGHTER_ALL)
    Class(LastSeenBy(Myself),PALADIN_ALL)
    Class(LastSeenBy(Myself),RANGER_ALL)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_DOMINATION)
END


/////////////////////////////////////////////////////////////////////
// *********************  Disabling spells *********************** //
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Level 6+ spells
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Symbol fear
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SYMBOL_FEAR)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)
END


/////////////////////////////////////////////////////////////////////
// Bigbys Clenched Fist
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)
END


/////////////////////////////////////////////////////////////////////
// Primastic Spray
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_PRISMATIC_SPRAY)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)
END


/////////////////////////////////////////////////////////////////////
// Finger of death
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_FINGER_OF_DEATH)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
END


/////////////////////////////////////////////////////////////////////
// Death spells
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_DEATH_SPELL)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
END


/////////////////////////////////////////////////////////////////////
// Disintegrate
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_DISINTEGRATE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_DISINTEGRATE)
END


/////////////////////////////////////////////////////////////////////
// Death fog
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_DEATH_FOG)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_FOG)
END


/////////////////////////////////////////////////////////////////////
// Level 4-5 spells
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Chaos
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_CHAOS)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_CHAOS)
END


/////////////////////////////////////////////////////////////////////
// Hold monsters
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_HOLD_MONSTER)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_HOLD_MONSTER)
END


/////////////////////////////////////////////////////////////////////
// Teleport field
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_TELEPORT_FIELD)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_TELEPORT_FIELD)
END


/////////////////////////////////////////////////////////////////////
// Level 3- spells
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
  !StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
  !StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
  !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  !StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Great Malison before trying anything else
/////////////////////////////////////////////////////////////////////  
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_GREATER_MALISON)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END


/////////////////////////////////////////////////////////////////////
// Emotion
/////////////////////////////////////////////////////////////////////  
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END


/////////////////////////////////////////////////////////////////////
// Web
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_WEB)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  OR(2)
    CheckStat(Myself,1,MINORGLOBE)
    HasItemEquiped("_RING09",Myself) // Ring of Free Action
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_WEB)
END


/////////////////////////////////////////////////////////////////////
// Slow
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_SLOW)
END


/////////////////////////////////////////////////////////////////////
// Stinking cloud
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_STINKING_CLOUD)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  OR(2)
    CheckStat(Myself,1,MINORGLOBE)
    CheckStatGT(Myself,99,RESISTPOISON)
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END


/////////////////////////////////////////////////////////////////////
// Horror
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_HORROR)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_HORROR)
END


/////////////////////////////////////////////////////////////////////
// Glitterdust
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_GLITTERDUST)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END


/////////////////////////////////////////////////////////////////////
// Sleep
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SLEEP)
  !Race(LastSeenBy(Myself),ELF)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_SLEEP)
END


/////////////////////////////////////////////////////////////////////
// Spook
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SPOOK)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END


/////////////////////////////////////////////////////////////////////
// Wand of paralyzation
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HasItemEquiped("_WAND04",Myself) // Wand of Paralyzation
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  RandomNum(4,1) // 25% to use
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    UseItem("_WAND04",LastSeenBy(Myself)) // Wand of Paralyzation
END


/////////////////////////////////////////////////////////////////////
// Wand of fear
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HasItemEquiped("_WAND02",Myself) // Wand of Frost
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  RandomNum(4,1) // 25% to use
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    UseItem("_WAND02",LastSeenBy(Myself)) // Wand of Fear
END


/////////////////////////////////////////////////////////////////////
// *********************  Summoning spells *********************** //
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Planatar
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SUMMON_PLANATAR_GOOD)
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_SUMMON_PLANATAR_GOOD)
END


/////////////////////////////////////////////////////////////////////
// Mordenkainen sword
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_MORDENKAINENS_SWORD)
  RandomNum(4,1) // 25% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_MORDENKAINENS_SWORD)
END


/////////////////////////////////////////////////////////////////////
// Squeleton
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_ANIMATE_DEAD)
  RandomNum(4,1) // 25% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_ANIMATE_DEAD)
END


/////////////////////////////////////////////////////////////////////
// Hakeashar
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SUMMON_HAKEASHAR)
  RandomNum(4,1) // 25% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_SUMMON_HAKEASHAR)
END


/////////////////////////////////////////////////////////////////////
// Spider
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SPIDER_SPAWN)
  RandomNum(4,1) // 25% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_SPIDER_SPAWN)
END


/////////////////////////////////////////////////////////////////////
// Monsters
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_MONSTER_SUMMONING_2)
  RandomNum(4,1) // 25% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_MONSTER_SUMMONING_2)
END


/////////////////////////////////////////////////////////////////////
// Melf meteor
/////////////////////////////////////////////////////////////////////  
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_MELF_METEOR)
  !HasItem("melfmet",Myself) // Melf's Minute Meteor
  !HasItem("eneblade",Myself) // Energy Blade
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(Myself,WIZARD_MELF_METEOR)
END


/////////////////////////////////////////////////////////////////////
// *********************  Damaging spells ************************ //
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Level 6+ spells
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Dragon breath
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_DRAGONS_BREATH)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(5,1) // 80% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END


/////////////////////////////////////////////////////////////////////
// Abi dalzims horrid wilting
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(4,1) // 75% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END


/////////////////////////////////////////////////////////////////////
// Chain Lightning
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_CHAIN_LIGHTNING)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END


/////////////////////////////////////////////////////////////////////
// Wand of frost
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HasItemEquiped("_WAND06",Myself) // Wand of Frost
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  RandomNum(1,4) // 25% to use
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    UseItem("_WAND06",LastSeenBy(Myself)) // Wand of Frost
END


/////////////////////////////////////////////////////////////////////
// Level 4-5 spells
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Sun fire
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SUN_FIRE)
  Range(LastSeenBy(Myself),10)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_SUN_FIRE)
END


/////////////////////////////////////////////////////////////////////
// Cone of cold
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_CONE_OF_COLD)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END


/////////////////////////////////////////////////////////////////////
// Level 3- spells
/////////////////////////////////////////////////////////////////////
IF
  !CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  !StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Skull trap
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_SKULL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  OR(2)
    CheckStatGT(Myself,50,MAGICDAMAGERESISTANCE)
    CheckStat(Myself,1,MINORGLOBE)
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_SKULL_TRAP)
END


/////////////////////////////////////////////////////////////////////
// Fireball
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_FIREBALL)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  OR(2)
    CheckStatGT(Myself,70,RESISTFIRE)
    CheckStat(Myself,1,MINORGLOBE)
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_FIREBALL)
END


/////////////////////////////////////////////////////////////////////
// Lightning bolt
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_LIGHTNING_BOLT)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  OR(2)
    CheckStatGT(Myself,99,RESISTELECTRICITY)
    CheckStat(Myself,1,MINORGLOBE)
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END


/////////////////////////////////////////////////////////////////////
// Vampiric touch
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_VAMPIRIC_TOUCH)
  Range(LastSeenBy(Myself),10)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)
END


/////////////////////////////////////////////////////////////////////
// Flame arrow
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_FLAME_ARROW)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END


/////////////////////////////////////////////////////////////////////
// Agannazar scorcher
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
    Wait(6)
END


/////////////////////////////////////////////////////////////////////
// Magic missile
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5) // Wizard shield
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END


/////////////////////////////////////////////////////////////////////
// Melf acid arrow
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END


/////////////////////////////////////////////////////////////////////
// Chromatic orb
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_CHROMATIC_ORB)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(2,1)  // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END


/////////////////////////////////////////////////////////////////////
// Larloch minor drain
/////////////////////////////////////////////////////////////////////
IF
  GlobalTimerExpired("ap_cast","LOCALS")
  HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
  !CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  See(LastSeenBy(Myself))
  !RandomNum(2,1) // 50% to cast
THEN
  RESPONSE #100
    SetGlobalTimer("ap_cast","LOCALS",6)
    Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
END


/////////////////////////////////////////////////////////////////////
// Find a slept target. this only work for PC's enemies            //
// because sleeping creatures are not considered as enemies        //
/////////////////////////////////////////////////////////////////////
IF
  !StateCheck(Player6,STATE_CHARMED)
  CheckStat(Player6,0,SANCTUARY)
  StateCheck(Player6,STATE_SLEEPING)
  See(Player6)
  False()
THEN
  RESPONSE #100
END

IF
  !StateCheck(Player5,STATE_CHARMED)
  CheckStat(Player5,0,SANCTUARY)
  StateCheck(Player5,STATE_SLEEPING)
  See(Player5)
  False()
THEN
  RESPONSE #100
END

IF
  !StateCheck(Player4,STATE_CHARMED)
  CheckStat(Player4,0,SANCTUARY)
  StateCheck(Player4,STATE_SLEEPING)
  See(Player4)
  False()
THEN
  RESPONSE #100
END

IF
  !StateCheck(Player3,STATE_CHARMED)
  CheckStat(Player3,0,SANCTUARY)
  StateCheck(Player3,STATE_SLEEPING)
  See(Player3)
  False()
THEN
  RESPONSE #100
END

IF
  !StateCheck(Player2,STATE_CHARMED)
  CheckStat(Player2,0,SANCTUARY)
  StateCheck(Player2,STATE_SLEEPING)
  See(Player2)
  False()
THEN
  RESPONSE #100
END

IF
  !StateCheck(Player1,STATE_CHARMED)
  CheckStat(Player1,0,SANCTUARY)
  StateCheck(Player1,STATE_SLEEPING)
  See(Player1)
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Safe attack, target is sleeping
/////////////////////////////////////////////////////////////////////
IF
  Allegiance(Myself,Enemy)
  !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)  
  StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
  See(LastSeenBy(Myself))  
THEN
  RESPONSE #100
    //AttackReevaluate(LastSeenBy(Myself),15)
    AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Find a helpless target to attack
/////////////////////////////////////////////////////////////////////
IF
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(2)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
    CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(2)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
    CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(2)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
    CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  OR(2)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
    CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  OR(2)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
    CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)  
  OR(2)
    StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
    CheckStatGT(NearestEnemyOf(Myself),0,HELD)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Safe attack, target can't escape
/////////////////////////////////////////////////////////////////////
IF
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)  
  OR(2)
    StateCheck(LastSeenBy(Myself),STATE_STUNNED)
    CheckStatGT(LastSeenBy(Myself),0,HELD)
  See(LastSeenBy(Myself))  
THEN
  RESPONSE #100
    //AttackReevaluate(LastSeenBy(Myself),15)
    AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Find something to attack, which has bonus on to hit
/////////////////////////////////////////////////////////////////////
IF
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)  
  OR(3)
    StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
    StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
    StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// target is easier to hit
/////////////////////////////////////////////////////////////////////
IF
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)  
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_SLOWED)
    StateCheck(LastSeenBy(Myself),STATE_BLIND)
    StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  See(LastSeenBy(Myself))  
THEN
  RESPONSE #100
    //AttackReevaluate(LastSeenBy(Myself),15)
    AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Find something to attack, which hasn't control of itself
/////////////////////////////////////////////////////////////////////
IF
  CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  OR(3)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)  
  OR(3)
    StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
    StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Easy attack, target hasn't control of itself
/////////////////////////////////////////////////////////////////////
IF
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)  
  OR(3)
    StateCheck(LastSeenBy(Myself),STATE_PANIC)
    StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
    StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
THEN
  RESPONSE #100
    //AttackReevaluate(LastSeenBy(Myself),15)
    AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Random attack (priority on melee range target)
/////////////////////////////////////////////////////////////////////

// three melee target
IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,1)
  OR(3)
    See(NearestEnemyOf(Myself))
    See(SecondNearestEnemyOf(Myself))
    See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,2)
  OR(3)
    See(SecondNearestEnemyOf(Myself))
    See(NearestEnemyOf(Myself))
    See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,3)
  OR(3)
    See(NearestEnemyOf(Myself))
    See(ThirdNearestEnemyOf(Myself))
    See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,4)
  OR(3)
    See(ThirdNearestEnemyOf(Myself))
    See(NearestEnemyOf(Myself))
    See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,5)
  OR(3)
    See(SecondNearestEnemyOf(Myself))
    See(ThirdNearestEnemyOf(Myself))
    See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,6)
  OR(3)
    See(ThirdNearestEnemyOf(Myself))
    See(SecondNearestEnemyOf(Myself))
    See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

// two melee target
IF
  !Range(ThirdNearestEnemyOf(Myself),8)
  Range(SecondNearestEnemyOf(Myself),8)
  RandomNum(2,1)
  OR(2)
    See(NearestEnemyOf(Myself))
    See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Range(ThirdNearestEnemyOf(Myself),8)
  Range(SecondNearestEnemyOf(Myself),8)
  RandomNum(2,2)
  OR(2)
    See(SecondNearestEnemyOf(Myself))
    See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

// one melee target
IF
  !Range(SecondNearestEnemyOf(Myself),8)
  Range(NearestEnemyOf(Myself),8)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(LastSeenBy(Myself),8)
  See(LastSeenBy(Myself))
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  //!GlobalTimerNotExpired("ap_attack","LOCALS")
THEN
  RESPONSE #100
    //SetGlobalTimer("ap_attack","LOCALS",6)
    EquipMostDamagingMelee()
    AttackOneRound(LastSeenBy(Myself))
END


// No target in melee range, pick a random one
IF
  RandomNum(8,1)
  See(NearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,2)
  See(FourthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,3)
  See(SixthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,4)
  See(FourthNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,5)
  See(SixthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,6)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,7)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(WeakestOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,8)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(MostDamagedOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Range(LastSeenBy(Myself),5)
  CheckStat(LastSeenBy(Myself),0,SANCTUARY)
  //!GlobalTimerNotExpired("ap_attack","LOCALS")
THEN
  RESPONSE #100
    //SetGlobalTimer("ap_attack","LOCALS",6)
    EquipRanged()
    AttackOneRound(LastSeenBy(Myself))
END