/////////////////////////////////////////////////////////////////////
// Stream of frost
/////////////////////////////////////////////////////////////////////
IF
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),5)
  !GlobalTimerNotExpired("ja#streamoffrost","LOCALS")
THEN
  RESPONSE #100
    ForceSpellRES("ja#FROST",LastSeenBy(Myself))
    SetGlobalTimer("ja#streamoffrost","LOCALS",18)
END
