DEFINE_PATCH_FUNCTION clear_proficiencies BEGIN
    LPF DELETE_CRE_EFFECT
        INT_VAR
            opcode_to_delete = 233
    END
    PATCH_FOR_EACH ~bg1_prof~ IN ~0x6e~ ~0x6f~ ~0x70~ ~0x71~ ~0x72~ ~0x73~ ~0x74~ ~0x75~ BEGIN
        WRITE_BYTE %bg1_prof% 0
    END
END

DEFINE_PATCH_FUNCTION set_movement_speed
    INT_VAR
        value = 99
BEGIN
    PATCH_IF value < 99 BEGIN
        LPF DELETE_CRE_EFFECT
            INT_VAR
                opcode_to_delete = 126
        END
        LPF DELETE_CRE_EFFECT
            INT_VAR
                opcode_to_delete = 176
        END
        LPF ADD_CRE_EFFECT
            INT_VAR
                opcode     = 176
                target     = 1
                timing     = 9
                parameter1 = value
                parameter2 = 1
        END
    END
END
