// The Shield spell and amulet should protect from RR/aTweaks' cloned Magic Missile
DEFINE_ACTION_FUNCTION magic_missile_shield BEGIN
  ACTION_IF !FILE_CONTAINS_EVALUATED (spwi114.spl "RR#WI112") BEGIN
  COPY_EXISTING ~spwi114.spl~ ~override~ // Shield (WIZARD_SHIELD)
    READ_LONG  0x64 "abil_off" ELSE 0
    READ_SHORT 0x68 "abil_num" ELSE 0
    READ_LONG  0x6a "fx_off"   ELSE 0
    SET "delta" = 0
    FOR (index = 0 ; index < abil_num ; index = index + 1) BEGIN
      READ_SHORT ("%abil_off%" + 0x1e + (0x28 * "%index%")) "abil_fx_num"
      READ_SHORT ("%abil_off%" + 0x20 + (0x28 * "%index%")) "abil_fx_idx"
      SET "abil_fx_idx" = ("%abil_fx_idx%" + "%delta%")
      WRITE_SHORT ("%abil_off%" + 0x20 + (0x28 * "%index%")) "%abil_fx_idx%"
      FOR (index2 = 0 ; index2 < abil_fx_num ; index2 = index2 + 1) BEGIN
      READ_SHORT ("%fx_off%" +        (0x30 * ("%abil_fx_idx%" + "%index2%"))) "opcode"
      READ_ASCII ("%fx_off%" +        (0x30 * ("%abil_fx_idx%" + "%index2%"))) "resref"
      READ_ASCII ("%fx_off%" + 0x14 + (0x30 * ("%abil_fx_idx%" + "%index2%"))) "resref"
        PATCH_IF (("%opcode%" = "206") AND ("%resref%" STRING_EQUAL_CASE ~SPWI112~)) BEGIN           // effect #206: Protection from Spell
          READ_ASCII ("%fx_off%" +        (("%abil_fx_idx%" + "%index2%") * 0x30)) "clone_fx" (0x30) // clone effect
          SET "index2"= "%abil_fx_num%" // kills loop
          INSERT_BYTES            ("%fx_off%" +        ("%abil_fx_idx%" * 0x30)) 0x30                // new effect
            WRITE_EVALUATED_ASCII ("%fx_off%" +        ("%abil_fx_idx%" * 0x30)) "%clone_fx%"        // cloned effect
            WRITE_ASCII           ("%fx_off%" + 0x14 + ("%abil_fx_idx%" * 0x30)) "RR#WI112" #8       // resref (RR/aTweaks cloned Magic Missile)
          SET "delta" = "%delta%" + 1
          WRITE_SHORT ("%abil_off%" + 0x1e + (0x28 * "%index%")) ("%abil_fx_num%" + 1)
        END
      END
    END
  BUT_ONLY_IF_IT_CHANGES

  COPY_EXISTING ~amul15.itm~   ~override~ // Shield Amulet
    READ_LONG  0x64 "abil_off" ELSE 0
    READ_SHORT 0x68 "abil_num" ELSE 0
    READ_LONG  0x6a "fx_off"   ELSE 0
    SET "abil_length" = 0x38
    SET "fx_delta" = 0
    FOR (index = 0 ; index < abil_num ; index = index + 1) BEGIN // start iterating through abilities
      READ_SHORT  ("%abil_off%" + 0x1e + ("%abil_length%" * "%index%")) "abil_fx_num"
      READ_SHORT  ("%abil_off%" + 0x20 + ("%abil_length%" * "%index%")) "abil_fx_idx"
      SET "abil_fx_idx" = ("%abil_fx_idx%" + "%fx_delta%")
      WRITE_SHORT ("%abil_off%" + 0x20 + ("%abil_length%" * "%index%")) ("%abil_fx_idx%")
      FOR (index2 = 0 ; index2 < abil_fx_num ; index2 = index2 + 1) BEGIN
        READ_SHORT ("%fx_off%" +        (0x30 * ("%abil_fx_idx%" + "%index2%"))) "opcode"
        READ_LONG  ("%fx_off%" + 0x08 + (0x30 * ("%abil_fx_idx%" + "%index2%"))) "param2"
        PATCH_IF (("%opcode%" = "142") AND ("%param2%" = "15")) BEGIN // display shield icon
          READ_ASCII ("%fx_off%" +        (0x30 * ("%abil_fx_idx%" + "%index2%"))) "clone" (48) // clone fx
          INSERT_BYTES            ("%fx_off%" +        (0x30 * "%abil_fx_idx%")) 0x30           // insert new effect
            WRITE_EVALUATED_ASCII ("%fx_off%" +        (0x30 * "%abil_fx_idx%")) "%clone%"      // clones effect
            WRITE_SHORT           ("%fx_off%" +        (0x30 * "%abil_fx_idx%")) "206"          // effect #206: Protection from Spell
            WRITE_LONG            ("%fx_off%" + 0x04 + (0x30 * "%abil_fx_idx%")) "0"            // param1: 0 (empty strref)
            WRITE_LONG            ("%fx_off%" + 0x08 + (0x30 * "%abil_fx_idx%")) "0"            // param2: 0
            WRITE_ASCII           ("%fx_off%" + 0x14 + (0x30 * "%abil_fx_idx%")) ~RR#WI112~ #8  // resref (RR/aTweaks cloned Magic Missile)
          SET "fx_delta" = "%fx_delta%" + 1
          SET "abil_fx_num" = "%abil_fx_num%" + 1
          WRITE_SHORT  ("%abil_off%" + 0x1e + ("%abil_length%" * "%index%")) "%abil_fx_num%"
          SET "index2" = "%abil_fx_num%" // kills loop
        END
      END
    END
    BUT_ONLY_IF_IT_CHANGES

    COPY_EXISTING ~amul15.itm~   ~override~                                          // Shield Amulet - just in case the amulet was changed by a mod (IRR or item pack)
      LPF CLONE_EFFECT
        INT_VAR silent = 1 match_opcode = 206 
        STR_VAR match_resource = ~spwi112~ resource = ~RR#WI112~
      END

  END
END

// Fire Salamander immunities (these apply for the noble variety too, but not for Frost Salamanders)
DEFINE_PATCH_FUNCTION fire_salamander_immunities BEGIN
  LPF charm_immunity END
  LPF sleep_immunity END
  LPF hold_immunity END 
  LPF fire_spell_immunities END
  LPF extraplanar_traits END
END

// Water Elemental effect
DEFINE_PATCH_FUNCTION add_water_elemental_effects BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "SPL" BEGIN
    PATCH_FAIL ~Function add_water_elemental_effects was not configured for spell, file: %SOURCE_RES%~
  END
  LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=52 parameter1=0x02000000 parameter2=0x2 END // Character tint
  LPF ADD_EFFECT_CRE_ITM_SPL INT_VAR opcode=66 parameter1=100 END // Translucency
  LPF entangle_immunities END
  LPF web_immunity END
END


// Set enchantment, and account for detectable enchantment from DS
DEFINE_PATCH_FUNCTION set_enchantment INT_VAR enchantment = 1 BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "ITM" BEGIN
    WRITE_LONG 0x60 enchantment
    READ_LONG 0x6a eo
    done = 0
    FOR (i = 0; i < SHORT_AT 0x70; ++i) BEGIN
      READ_SHORT eo + 0x30 * i       type
      READ_LONG  eo + 0x30 * i + 0x8 prof
      PATCH_IF type = 233 AND prof = 109 BEGIN
        WRITE_LONG eo + 0x30 * i + 0x4 enchantment
        done = 1
      END
    END
    PATCH_IF !done BEGIN
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode=233 target=1 parameter1=enchantment parameter2=109 timing=2 END
    END
  END
END


// Will increase the priority of a single script matching the regexp script to the first empty script slot.
// Script slots with scripts matching the regexp kill will be treated as empty.
DEFINE_PATCH_FUNCTION promote_script STR_VAR script = "^$" kill = "^$" BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "CRE" AND SOURCE_SIZE > 0x2d3 BEGIN
    FOR (o = 0x248; o < 0x270; o += 0x8) BEGIN
      READ_ASCII o s1
      PATCH_IF "%s1%" STRING_MATCHES_REGEXP "%script%" = 0 BEGIN
        FOR (p = 0x248; p < 0x270 AND p < o; p += 0x8) BEGIN
          READ_ASCII p s2
          PATCH_IF "%s2%" STRING_EQUAL "" OR "%s2%" STRING_EQUAL_CASE none OR "%s2%" STRING_MATCHES_REGEXP "%kill%" = 0 BEGIN
            WRITE_ASCII  o "" #8
            WRITE_ASCIIE p "%s1%" #8
            p = SOURCE_SIZE
            o = SOURCE_SIZE
          END
        END
      END
    END
  END ELSE PATCH_FAIL "promote_script: incorrect signature or below minimum file size (%SOURCE_FILE%)"
END


DEFINE_PATCH_FUNCTION make_summon STR_VAR slot = boots BEGIN
  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE "CRE" AND SOURCE_SIZE > 0x2d3 BEGIN
    WRITE_LONG 0x14 0                                                // No experience from summons
    WRITE_BYTE 0x275 6                                               // Gender: Summon
    WRITE_BYTE 0x10 (THIS BOR BIT1) BAND 0xfb                        // Set 'No corpse' (BIT1) and unset 'Permanent Corpse' (BIT2)
    ADD_CRE_ITEM rr#dinv #0 #0 #0 "unstealable&undroppable" "%slot%" // item for keeping summons from being killed before the summoning is done
    ADD_MEMORIZED_SPELL rr#usumn #0 innate (1)                       // 'Unsummon' spell
    WRITE_ASCIIL SCRIPT_OVERRIDE "" "" "" "" ""                      // Clear all scripts; correct scripts are set by the specialised code
  END ELSE PATCH_FAIL "make_summon: incorrect signature or below minimum file size (%SOURCE_FILE%)"
END


DEFINE_PATCH_FUNCTION fiend_summoning_spell
INT_VAR
  duration = 120
STR_VAR
  lawful = rr#scorn
  lcneutral = fl#sarca
  chaotic = spcaco
BEGIN
  LPF DELETE_SPELL_EFFECT INT_VAR opcode_to_delete = 177 END
  SET $p1("%lawful%") = 16    // MASK_LAWFUL
  SET $p1("%lcneutral%") = 32 // MASK_LCNEUTRAL
  SET $p1("%chaotic%") = 48   // MASK_CHAOTIC
  PATCH_FOR_EACH resource IN "%lawful%" "%lcneutral%" "%chaotic%" BEGIN
    LPF ADD_SPELL_EFFECT INT_VAR opcode=177 target=1 parameter1=$p1("%resource%") parameter2=8 resist_dispel=2 duration STR_VAR resource END
  END
END


