DEFINE_ACTION_FUNCTION get_sectype STR_VAR f_Label = "" RET f_Value BEGIN
  LAF get_from_file_by_row_count STR_VAR f_Label f_File = msectype.2da RET f_Value = f_Value END
END

DEFINE_ACTION_MACRO load_secondary_types BEGIN
  ACTION_IF !VARIABLE_IS_SET fl#Disease OR !IS_AN_INT fl#Disease BEGIN
    LAF get_sectype STR_VAR f_Label = fl#Disease RET fl#Disease = f_Value END
  END
  ACTION_IF !VARIABLE_IS_SET fl#Fear OR !IS_AN_INT fl#Fear BEGIN
    LAF get_sectype STR_VAR f_Label = fl#Fear RET fl#Fear = f_Value END
  END
  ACTION_IF !VARIABLE_IS_SET fl#Poison OR !IS_AN_INT fl#Poison BEGIN
    LAF get_sectype STR_VAR f_Label = fl#Poison RET fl#Poison = f_Value END
  END
  OUTER_SET DiseaseSecType = fl#Disease
  OUTER_SET FearSecType = fl#Fear
  OUTER_SET PoisonSecType = fl#Poison
  OUTER_SET $f_ImmunitySecType(78) = DiseaseSecType
  OUTER_SET $f_ImmunitySecType(24) = FearSecType
  OUTER_SET $f_ImmunitySecType(25) = PoisonSecType
  OUTER_SET $f_RemoveSecType(79) = DiseaseSecType
  OUTER_SET $f_RemoveSecType(161) = FearSecType
  OUTER_SET $f_RemoveSecType(11) = PoisonSecType
END

// Called from integrate_sectypes
DEFINE_PATCH_FUNCTION integrate_sectypes_inner BEGIN
  READ_LONG  0x64 ao
  READ_SHORT 0x68 na
  READ_LONG  0x6a eo
  READ_SHORT 0x6e ei1
  READ_SHORT 0x70 gne

  PATCH_IF "%SOURCE_EXT%" STRING_EQUAL_CASE itm BEGIN
    FOR (i=0;i<gne;++i) BEGIN
      READ_SHORT eo + 0x30*(ei1 + i)       type ELSE 999
      READ_LONG  eo + 0x30*(ei1 + i) + 0x8 p2   ELSE 999

      //This works as long as we always insert the new effects in front of the ones that trigger the insertion of a new effect
      PATCH_IF type = 206 BEGIN
        READ_ASCII eo + 0x30 * (ei1 + i) + 0x14 rr ELSE nil
        TO_LOWER rr
        SET $onequip_immunity("%rr%") = 1
      END

      //On-equip immunity
      PATCH_IF type = 101 AND VARIABLE_IS_SET $f_ImmunitySecType("%p2%") BEGIN
        PHP_EACH f_AddSecType AS file => SecTypeToAdd BEGIN
          PATCH_IF "%file%" STRING_MATCHES_REGEXP ".*\.spl$" = 0 AND SecTypeToAdd = $f_ImmunitySecType("%p2%") BEGIN
            INNER_PATCH "%file%" BEGIN
              READ_ASCII 0 spell (STRING_LENGTH "%file%" - 4)
            END
            TO_LOWER spell
            PATCH_IF !VARIABLE_IS_SET $onequip_immunity("%spell%") BEGIN
              INSERT_BYTES   eo + 0x30 * (ei1 + i)        0x30
                WRITE_SHORT  eo + 0x30 * (ei1 + i)        206 //protection from spell
                WRITE_BYTE   eo + 0x30 * (ei1 + i) + 0x2  1
                WRITE_BYTE   eo + 0x30 * (ei1 + i) + 0xc  2
                WRITE_BYTE   eo + 0x30 * (ei1 + i) + 0x12 100
                WRITE_ASCIIE eo + 0x30 * (ei1 + i) + 0x14 "%spell%" #8
              ++i
              ++gne
            END
          END
        END
      END
    END
  END

  WRITE_SHORT 0x70 gne
  ei = gne = 0 ? 0 : ei1 + gne //Some mod files have illegal values for ei1, but the engine disregards the illegal value because gne is 0; we do the same
  ne = 0
  al = "%SOURCE_EXT%" STRING_EQUAL_CASE itm ? 0x38 : 0x28

  //Check for effects to remove e.g. fear or disease and effects that grant immunity to e.g. fear or disease
  FOR (i=0;i<na AND ao + na*al < SOURCE_SIZE;++i) BEGIN
    ei += ne
    WRITE_SHORT ao + al*i + 0x20 ei
    READ_SHORT  ao + al*i + 0x1e ne
    FOR (j=0;j<ne;++j) BEGIN
      READ_SHORT eo + 0x30*(ei + j)        type   ELSE 999
      READ_BYTE  eo + 0x30*(ei + j) + 0x2  target ELSE 0
      READ_BYTE  eo + 0x30*(ei + j) + 0x3  power  ELSE 0
      READ_LONG  eo + 0x30*(ei + j) + 0x4  p1     ELSE 999
      READ_LONG  eo + 0x30*(ei + j) + 0x8  p2     ELSE 999
      READ_BYTE  eo + 0x30*(ei + j) + 0xc  timing ELSE 0
      READ_BYTE  eo + 0x30*(ei + j) + 0xd  dr     ELSE 0
      READ_LONG  eo + 0x30*(ei + j) + 0xe  time   ELSE 0

      //This works as long as we always insert the new effects in front of the ones that trigger the insertion of the new effect
      PATCH_IF type = 221 BEGIN
        SET $extended_sectype_immunity("%i%" "%p2%") = 1
      END
      PATCH_IF type = 206 BEGIN
        READ_ASCII eo + 0x30 * (ei + j) + 0x14 rr ELSE nil
        TO_LOWER rr
        SET $extended_spell_immunity("%i%" "%rr%") = 1
      END

      PATCH_IF VARIABLE_IS_SET $f_RemoveSecType("%type%") BEGIN
        check = $f_RemoveSecType("%type%")
        PATCH_IF !VARIABLE_IS_SET $extended_sectype_immunity("%i%" "%check%") BEGIN
          INSERT_BYTES  eo + 0x30*(ei + j)        0x30
            WRITE_SHORT eo + 0x30*(ei + j)        221 //remove sec type
            WRITE_BYTE  eo + 0x30*(ei + j) + 0x2  target
            WRITE_BYTE  eo + 0x30*(ei + j) + 0x3  power
            WRITE_LONG  eo + 0x30*(ei + j) + 0x4  9
            WRITE_LONG  eo + 0x30*(ei + j) + 0x8  $f_RemoveSecType("%type%")
            WRITE_BYTE  eo + 0x30*(ei + j) + 0xc  1
            WRITE_BYTE  eo + 0x30*(ei + j) + 0x12 100
          ++ne
          ++j
        END
      END

      PATCH_IF type = 101 AND VARIABLE_IS_SET $f_ImmunitySecType("%p2%") BEGIN
        PHP_EACH f_AddSecType AS file => SecTypeToAdd BEGIN
          PATCH_IF "%file%" STRING_MATCHES_REGEXP ".+\.spl$" = 0 AND SecTypeToAdd = $f_ImmunitySecType("%p2%") BEGIN
            INNER_PATCH "%file%" BEGIN
              READ_ASCII 0 spell (STRING_LENGTH "%file%" - 4)
            END
            TO_LOWER spell
            PATCH_IF !VARIABLE_IS_SET $extended_spell_immunity("%i%" "%spell%") BEGIN
              INSERT_BYTES   eo + 0x30*(ei + j)        0x30
                WRITE_SHORT  eo + 0x30*(ei + j)        206 //protection from spell
                WRITE_BYTE   eo + 0x30*(ei + j) + 0x2  target
                WRITE_BYTE   eo + 0x30*(ei + j) + 0x3  power
                WRITE_BYTE   eo + 0x30*(ei + j) + 0xc  timing
                WRITE_BYTE   eo + 0x30*(ei + j) + 0xd  dr
                WRITE_LONG   eo + 0x30*(ei + j) + 0xe  time
                WRITE_BYTE   eo + 0x30*(ei + j) + 0x12 100
                WRITE_ASCIIE eo + 0x30*(ei + j) + 0x14 "%spell%" #8
              ++ne
              ++j
            END
          END
        END
      END

    END
    WRITE_SHORT ao + al*i + 0x1e ne
  END
END


DEFINE_PATCH_FUNCTION integrate_sectype_cre BEGIN
  READ_LONG 0x2c4 eo

  // First, check out what's already there
  FOR (i = 0; i < LONG_AT 0x2c8; ++i) BEGIN
    p = eo + 0x108 * i + 0x8
    READ_LONG p fx ELSE 999
    PATCH_IF fx = 206 BEGIN // Protecton from spell
      READ_ASCII p + 0x14 rr ELSE nil
      TO_LOWER rr
      SET $extended_spell_immunity("%rr%") = 1
    END
    PATCH_IF fx = 101 BEGIN // Immunity to effect
      READ_LONG p + 0x10 p2 ELSE 999
      SET $immunities("%p2%") = 1
    END
  END

  // Then we see what, if anything, we need to do
  PHP_EACH immunities AS fx => i BEGIN
    PATCH_IF VARIABLE_IS_SET $f_ImmunitySecType("%fx%") BEGIN
      PHP_EACH f_AddSecType AS file => SecTypeToAdd BEGIN
        PATCH_IF "%file%" STRING_MATCHES_REGEXP ".+\.spl$" = 0 AND SecTypeToAdd = $f_ImmunitySecType("%fx%") BEGIN
          INNER_PATCH "%file%" BEGIN
            READ_ASCII 0 spell (STRING_LENGTH "%file%" - 4)
          END
          TO_LOWER spell
          PATCH_IF !VARIABLE_IS_SET $extended_spell_immunity("%spell%") BEGIN
            LPF ADD_CRE_EFFECT
              INT_VAR
                opcode = 206
                target = 1
                timing = 9
              STR_VAR
                resource = EVAL "%spell%"
            END
          END
        END
      END
    END
  END
END


//Add the SecTypes to items and spells that should grant immunity or be able to remove them
//Needs the three arrays:
//f_AddSecType(file) = SecType -> Associates a SecType with a specific file. Items and spells that grant immunity to e.g. disease will grant immunity to this particular file (spell) as well. Creatures with immunity effects will also be affected.
//f_ImmunitySecType(opcode) = SecType -> opcode is the opcode used to determine if a spell/item should grant immunity to the file (spell).
//f_RemoveSecType(opcode) = Secype -> opcode is the opcode used to determine if a spell/item should cure the secondary type.
//E.g. is your secondary type covers disease you would have:
//f_AddSecType(YourDisease-causingSpell.spl) = YourDiseaseSecType
//f_ImmunitySecType(78) = YourDiseaseSecType
//f_RemoveSecType(79) = YourDiseaseSecType
DEFINE_ACTION_FUNCTION integrate_sectypes BEGIN
  COPY_EXISTING_REGEXP GLOB ~.+\.\(spl\|itm\)$~ override
    PATCH_IF SOURCE_SIZE > 0x71 BEGIN
      LPF integrate_sectypes_inner END
    END
  BUT_ONLY
  COPY_EXISTING_REGEXP GLOB ~.+\.cre$~ override
    PATCH_IF SOURCE_SIZE > 0x2d3 BEGIN
      LPF integrate_sectype_cre END
    END
  BUT_ONLY
END
