export const ConstitutionTable = [
  { con: 1, warriorHp: -3, hp: -3 },
  { con: 2, warriorHp: -2, hp: -2 },
  { con: 3, warriorHp: -2, hp: -2 },
  { con: 4, warriorHp: -1, hp: -1 },
  { con: 5, warriorHp: -1, hp: -1 },
  { con: 6, warriorHp: -1, hp: -1 },
  { con: 7, warriorHp: 0, hp: 0 },
  { con: 8, warriorHp: 0, hp: 0 },
  { con: 9, warriorHp: 0, hp: 0 },
  { con: 10, warriorHp: 0, hp: 0 },
  { con: 11, warriorHp: 0, hp: 0 },
  { con: 12, warriorHp: 0, hp: 0 },
  { con: 13, warriorHp: 0, hp: 0 },
  { con: 14, warriorHp: 0, hp: 0 },
  { con: 15, warriorHp: 1, hp: 1 },
  { con: 16, warriorHp: 2, hp: 2 },
  { con: 17, warriorHp: 3, hp: 2 },
  { con: 18, warriorHp: 4, hp: 2 },
  { con: 19, warriorHp: 5, hp: 2 },
  { con: 20, warriorHp: 5, hp: 2 },
  { con: 21, warriorHp: 6, hp: 2 },
  { con: 22, warriorHp: 6, hp: 2 },
  { con: 23, warriorHp: 6, hp: 2 },
  { con: 24, warriorHp: 7, hp: 2 },
  { con: 25, warriorHp: 7, hp: 2 },
];
