import figureSet from "figures";
import { getAllSpells } from "../../config/spells/spell-names";
import { GLOBAL_CONFIG } from "../../config/generate";
import { CreatureAbility } from "../model/creature/ability";
import { CreatureAdjustment } from "../model/creature/adjustment";
import { Game } from "../model/creature/game";
import { BaseCreature, Creature, CreatureAutoGenerate } from "../model/creature/creature";
import { CreatureData } from "../model/creature/data";
import {
  AttackPerRoundFigtherTable,
  AttackPerRoundProficiencyTable,
  AttackPerRoundTable,
} from "../model/game-data/attack-per-round";
import { DexterityTable } from "../model/game-data/dexterity";
import { SAVING_THROWS } from "../model/game-data/saving-throws";
import { StrengthTable } from "../model/game-data/strength";
import { Thac0Table } from "../model/game-data/thac0";
import { ClassIdentifier } from "../model/ids/class";
import { Actions } from "../model/script/actions";
import { ItemAbilityLocationEnum, ProficiencyTypeEnum } from "../model/spell-item/effect.enums";
import { Weapon } from "../model/spell-item/spell-item";
import hitPointService from "./hit-point.service";
import itemService from "./item.service";
import kitService from "./kit.service";
import logService from "./log.service";
import monsterFilesService from "./monster-files.service";
import translationService from "./translation.service";
import weaponService from "./weapon.service";
import spellService from "./spell.service";

const ID_CAST_ACTION_NAMES = new Set(["Spell", "SpellNoDec", "ForceSpell", "ReallyForceSpell"]);
type IdCastActionName = "Spell" | "SpellNoDec" | "ForceSpell" | "ReallyForceSpell";
type IdCastAction = Extract<Actions.Action, { name: IdCastActionName }>;

export interface CsvFinding {
  file: string;
  game?: Game;
  detail: string;
}

const GENERIC_SCRIPTS_REMOVED = new Set(
  GLOBAL_CONFIG.tpaConstants.genericScriptsToRemove.map((s) => s.toUpperCase()),
);

class CreatureService {
  check(creature: Creature) {
    this.checkData({
      creature,
      base: creature,
      isAdjustment: false,
    });
    for (const a of creature.adjustments) {
      this.checkData({
        creature,
        base: a,
        isAdjustment: true,
      });
    }
  }

  checkData(p: { creature: Creature; base: BaseCreature; isAdjustment: boolean }): void {
    const data = p.base.data;
    logService.log(
      `base files: ${JSON.stringify(
        p.isAdjustment
          ? (p.base as unknown as { files: string[] }).files
          : p.creature.fileNames,
      )}`,
    );
    kitService.applyKit(p.creature, p.isAdjustment ? p.base : undefined);
    this.checkDualWielding({ ...p, data });
    this.checkDexterityArmorClassBonus(data);
    this.checkMovement(p);
    this.transformAttackPerRound(data);
    this.autogenerateData({
      data,
      autoGenerate: p.creature.autoGenerate,
      creature: p.creature,
      parent: p.isAdjustment ? p.creature.data : undefined,
    });
  }

  checkWeapons(creature: Creature) {
    for (const item of creature.items) {
      if (item.header?.location === ItemAbilityLocationEnum.Weapon) {
        const weapon = item as Weapon;
        weaponService.checkWeapon(creature, weapon, this.getWeaponLevel(creature, weapon));
      }
    }
  }

  /**
   * A weapon's enchantment must fit the level of whichever creature(s) explicitly equip it: the
   * base creature (if it's in its default loadout), and any adjustment that re-equips it via its
   * own `items.equipped` (e.g. Treant's per-level branches). An adjustment that never mentions
   * the weapon at all still ends up wielding it in-game (an unoverridden slot keeps the base's
   * item) but must NOT influence the enchantment - the item is only authored/leveled for the
   * creature(s) that explicitly claim it, and boosting it for an adjustment that merely inherits
   * it would over-enchant every other (often weaker) owner of that same shared item.
   */
  private getWeaponLevel(creature: Creature, weapon: Weapon): number {
    const baseLevel = creature.data.level1.pnpValue;
    const isBaseOwner = creature.data.items.equipped.some((e) => e.file === weapon.file);
    const levels: number[] = isBaseOwner ? [baseLevel] : [];

    for (const adjustment of creature.adjustments) {
      if (adjustment.noWeapon) continue;
      if (adjustment.data.items.equipped.some((e) => e.file === weapon.file)) {
        levels.push(adjustment.data.level1?.pnpValue ?? baseLevel);
      }
    }

    return levels.length ? Math.max(...levels) : baseLevel;
  }

  memorizedSpellFiles(creature: Creature): string[] {
    return [...new Set(this.getSpellGroups(creature).flatMap((g) => g.files))];
  }

  checkSpellAbilities(creature: Creature): void {
    const groups = this.getSpellGroups(creature);
    const allAbilities = [
      ...creature.behavior.abilities,
      ...creature.behavior.customCodes.flatMap((c) => c.abilities),
    ];
    const abilityResources = new Set(allAbilities.flatMap((a) => this.getAbilityCastFiles(a)));
    const memorizedFiles = new Set(groups.flatMap((g) => g.files));
    for (const group of groups) {
      for (const file of group.files) {
        if (abilityResources.has(file)) continue;
        const spellName = spellService.getSpellName(file);
        const spellText = spellName ? ` (${spellName})` : "";
        logService.error(
          `${translationService.from(creature.name)}: spell '${file}'${spellText} is memorized in '${group.label}' but has no matching ability - it will never be cast.`,
        );
      }
    }
    for (const resource of abilityResources) {
      if (memorizedFiles.has(resource)) continue;
      const spellName = spellService.getSpellName(resource);
      const spellText = spellName ? ` (${spellName})` : "";
      logService.warn(
        `${translationService.from(creature.name)}: ability references spell '${resource}'${spellText} which isn't memorized anywhere.`,
      );
    }
  }

  checkDuplicateAbilities(creature: Creature): void {
    const seen = new Set<string>();
    for (const ability of creature.behavior.abilities) {
      const resolvedFile = this.getAbilityCastFiles(ability)[0];
      const signature = this.stableStringify({
        resource: resolvedFile,
        triggers: ability.triggers,
        targets: ability.targets,
      });
      if (seen.has(signature)) {
        const spellName = ability.resource
          ? spellService.getSpellName(ability.resource)
          : undefined;
        const spellText = spellName ? ` (${spellName})` : "";
        logService.error(
          `${translationService.from(creature.name)}: duplicate ability for '${ability.resource ?? ability.name}'${spellText} - the same spell and trigger context is listed twice.`,
        );
        continue;
      }
      seen.add(signature);
    }
  }

  checkDialog(creature: Creature): boolean {
    if (!creature.behavior.dialog.length) return true;
    const rows = monsterFilesService.getDialogRows(creature.id).filter((r) => r.deathvar);
    if (!rows.length) {
      logService.error(
        `${translationService.from(creature.name)}: behavior defines dialog but ` +
          `creatures.csv has no entry with a deathVar for this creature.`,
      );
      return false;
    }
    let ok = true;
    for (const dialog of creature.behavior.dialog) {
      if (!rows.some((r) => r.deathvar.toLowerCase() === dialog.toLowerCase())) {
        logService.error(
          `${translationService.from(creature.name)}: creatures.csv deathvar '${dialog}' not found.`,
        );
        ok = false;
      }
    }
    return ok;
  }

  // Case-insensitive: WeiDU/Infinity Engine resrefs are case-insensitive on disk, but
  // creature.files can mix casing (CSV-sourced entries are always uppercase, while
  // hand-authored adjustment references keep whatever case the author originally used) - see
  // e.g. undead.ts's Ghast/Shadow adjustments referencing lowercase "ghastgsu"/"va#shdgl"
  // against a CSV-supplied uppercase "GHASTGSU"/"VA#SHDGL" base file.
  checkAdjustmentFiles(creature: Creature): boolean {
    let ok = true;
    for (const adjustment of creature.adjustments) {
      for (const file of adjustment.files) {
        const entry = creature.files.find((k) => k.name.toUpperCase() === file.toUpperCase());
        if (!entry) {
          logService.error(
            `${translationService.from(creature.name)}: adjustment references unknown file '${file}' (not in creature.files).`,
          );
          ok = false;
          continue;
        }
        if (adjustment.game && entry.game && entry.game !== adjustment.game) {
          logService.error(
            `${translationService.from(creature.name)}: adjustment file '${file}' is not available in ${adjustment.game}.`,
          );
          ok = false;
        }
      }
      if (adjustment.game && this.adjustmentHasUngatedEffects(adjustment)) {
        logService.error(
          `${translationService.from(creature.name)}: game-tagged adjustment for '${adjustment.files.join(", ")}' also sets a field that is not game-gated (noWeapon / scriptName / script.location / effects.remove array / spells.removeKnown:false / spells.removeMemorized:false). Split it into a non-game entry.`,
        );
        ok = false;
      }
    }
    return ok;
  }

  private adjustmentHasUngatedEffects(a: CreatureAdjustment): boolean {
    const d = a.data;
    // `summon` is NOT in this list: weiduCreatureService.patchScripts gates a game-tagged summon
    // adjustment's script assignment per game (summon script in that game, normal script
    // otherwise), and its xpv=0 write already rides inside handleAdjustment's PATCH_IF GAME_IS.
    // Real CreatureAdjustment.data always has script/effects/spells (class instances with
    // defaults), but the optional chains harden against hand-built fixtures that omit them.
    /* eslint-disable @typescript-eslint/no-unnecessary-condition */
    return [
      a.noWeapon,
      a.scriptName,
      d.script?.location !== undefined,
      Array.isArray(d.effects?.remove),
      d.spells?.removeKnown === false,
      d.spells?.removeMemorized === false,
    ].some(Boolean);
    /* eslint-enable @typescript-eslint/no-unnecessary-condition */
  }

  private stableStringify(value: unknown): string {
    return JSON.stringify(value, (_key: string, val: unknown) =>
      val && typeof val === "object" && !Array.isArray(val)
        ? Object.keys(val)
            .sort((a, b) => a.localeCompare(b))
            .reduce((sorted: Record<string, unknown>, k) => {
              sorted[k] = (val as Record<string, unknown>)[k];
              return sorted;
            }, {})
        : val,
    );
  }

  getAbilityCastFiles(ability: CreatureAbility): string[] {
    if (ability.resource !== undefined) return [ability.resource];
    return ability.actions
      .filter((a): a is IdCastAction => ID_CAST_ACTION_NAMES.has(a.name))
      .map((a) => this.resolveSpellIdToFile(a.params[1]))
      .filter((file): file is string => file !== undefined);
  }

  private resolveSpellIdToFile(id: string): string | undefined {
    const spells = getAllSpells();
    return spells.find((s) => s.id === id)?.file;
  }

  private getSpellGroups(creature: Creature): { label: string; files: string[] }[] {
    const groups: { label: string; files: string[] }[] = [];
    const defaultFiles = [...new Set(creature.data.spells.memorized.map((s) => s.file))];
    if (defaultFiles.length) groups.push({ label: "default", files: defaultFiles });
    for (const variant of creature.data.spells.spellbooks ?? []) {
      const files = [...new Set(variant.memorized.map((s) => s.file))];
      if (files.length) groups.push({ label: variant.mod, files });
    }
    creature.adjustments.forEach((adjustment, index) => {
      const files = [...new Set(adjustment.data.spells.memorized.map((s) => s.file))];
      if (files.length) groups.push({ label: `adjustment #${index}`, files });
    });
    return groups;
  }

  getAttacksPerRound(value: number): {
    apr: number;
    value: number;
    doubleApr: boolean;
  } {
    const item = AttackPerRoundTable.find((t) => t.apr === value);
    if (!item) {
      throw new Error(`attack per round not found in table: ${value}`);
    }
    return item;
  }

  /**
   * PnP fighters gain extra attacks per round beyond the raw `apr` stat: a specialization bonus
   * from weapon proficiency rank (AttackPerRoundProficiencyTable, "FIGHTER" class only - only the
   * highest threshold the rank meets contributes, e.g. rank 5/grand mastery gets just its own +1.5,
   * not also the rank-2 tier's +0.5), and a level bonus (AttackPerRoundFigtherTable, any class
   * whose identifier contains "FIGHTER" - e.g. FIGHTER_MAGE - but not PALADIN/RANGER, which are
   * separate class identifiers). The level table IS cumulative - every threshold met contributes
   * (level 13 gets both the level-7 and level-13 bonuses), matching the real PnP fighter attack
   * progression (3/2 at 7th, 2/1 at 13th).
   *
   * `proficiencyType` is undefined when no equipped weapon is known to the doc pipeline (e.g.
   * Tazok/half-ogre in lib/creatures/ogres.ts, whose weapon comes straight from its own .cre file
   * rather than an addWeapon() call) - in that case the creature's own highest proficiency rank is
   * used as the best available approximation of the weapon it's actually specialized in, rather
   * than silently dropping the specialization bonus to 0.
   */
  getFighterAttackBonus(p: {
    class: ClassIdentifier | undefined;
    level: number;
    proficiencyType: ProficiencyTypeEnum | undefined;
    proficiencies: { type: ProficiencyTypeEnum; value: number }[];
  }): number {
    let bonus = 0;
    if (p.class === "FIGHTER") {
      const rank =
        p.proficiencyType !== undefined
          ? (p.proficiencies.find((x) => x.type === p.proficiencyType)?.value ?? 0)
          : Math.max(0, ...p.proficiencies.map((x) => x.value));
      const highestMet = AttackPerRoundProficiencyTable.filter((t) => rank >= t.proficiency).reduce<
        (typeof AttackPerRoundProficiencyTable)[number] | undefined
      >((best, t) => (!best || t.proficiency > best.proficiency ? t : best), undefined);
      bonus += highestMet?.value ?? 0;
    }
    if (p.class?.includes("FIGHTER")) {
      bonus += AttackPerRoundFigtherTable.filter((t) => p.level >= t.level).reduce(
        (sum, t) => sum + t.value,
        0,
      );
    }
    return bonus;
  }

  getStrengthBonus(data: Partial<CreatureData>): {
    hit: number;
    damage: number;
  } {
    if (data.strength === undefined) return { hit: 0, damage: 0 };
    const exStrength = data.exceptionalStrength ?? 0;
    const item = StrengthTable.find((t) => {
      const checkStr = t.str === data.strength;
      const checkStrEx =
        t.strEx === undefined || (exStrength >= t.strEx[0] && exStrength <= t.strEx[1]);
      return checkStr && checkStrEx;
    });
    if (!item) {
      throw new Error(`strength not found in table: ${data.strength}/${exStrength}`);
    }
    return item;
  }

  getFinalArmorClass(base: BaseCreature) {
    if (base.data.dexterity === undefined || base.data.ac === undefined)
      throw new Error(`can't calculate final AC because of missing data`);
    return base.data.ac + this.getDexterityArmorClassBonus(base.data);
  }

  private checkDualWielding(p: {
    creature: Creature;
    base: BaseCreature;
    isAdjustment: boolean;
    data: CreatureData;
  }): void {
    if (!p.isAdjustment && this.hasOffhandWeapon(p.creature)) {
      logService.log(`${figureSet.arrowRight} dual wielding detected`);
      p.creature.attack.dualWielding = true;
    }
    if (!p.creature.attack.dualWielding || p.isAdjustment) return;
    if (!p.data.apr) {
      throw new Error("Attacks per round need to be set for dual wielding flag");
    }
    p.data.apr -= 1;
    logService.log(`${figureSet.arrowRight} setting dual wield: ${p.data.apr} APR +1 offhand`);
  }

  private hasOffhandWeapon(creature: Creature): boolean {
    const equippedItem = creature.data.items.equipped.find((i) =>
      itemService.isSlotIncluded([i], "SHIELD"),
    );
    const item = creature.items.find((i) => i.file === equippedItem?.file);
    return item?.header?.location === ItemAbilityLocationEnum.Weapon;
  }

  private checkMovement(p: { creature: Creature; base: BaseCreature; isAdjustment: boolean }) {
    const data = p.base.data;
    if (!data.movement && !p.isAdjustment) throw new Error("movement not set !");
    const movement = data.movement ?? p.creature.data.movement;
    if (data.kit === "BARBARIAN") {
      data.movement = movement.clone();
      data.movement.bonus += 2;
      logService.log(
        `${figureSet.arrowRight} movement increased to ${data.movement.getGameValue()} (barbarian): `,
      );
    }
  }

  private transformAttackPerRound(data?: Partial<CreatureData>) {
    if (!data?.apr) return;
    const apr = this.getAttacksPerRound(data.apr);
    data.apr = apr.value;
    if (apr.doubleApr) data.doubleApr = apr.doubleApr;
    if (data.movement) {
      data.movement.hasImprovedHaste = apr.doubleApr;
    }
  }

  private autogenerateData(p: {
    autoGenerate: CreatureAutoGenerate;
    data: Partial<CreatureData>;
    creature: Creature;
    parent: CreatureData | undefined;
  }) {
    if (p.autoGenerate.hitPoints && p.data.hp === undefined) {
      this.autogenerateHitPoints({
        data: p.data,
        creature: p.creature,
        parent: p.parent,
      });
    }
    if (p.autoGenerate.thac0 && p.data.thac0 === undefined) {
      this.autogenerateThac0(p.data, p.parent);
    }
    if (p.data.saveBreath === undefined) {
      this.autogenerateSavingThrows({
        data: p.data,
        parent: p.parent,
        options: p.autoGenerate.savingThrows,
      });
    }
  }

  private autogenerateHitPoints(p: {
    data: Partial<CreatureData>;
    creature: Creature;
    parent?: CreatureData;
  }) {
    const value = hitPointService.getHitPoints(p);
    if (value) p.data.hp = value;
  }

  private autogenerateThac0(data: Partial<CreatureData>, parent?: CreatureData) {
    let level = data.level1?.pnpValue;
    if (!level && !parent) throw new Error(`Can't generate thac0 because level1 is unknown`);
    else if (!level) return;
    if (!!data.bonusHp && data.bonusHp >= 3) {
      level++;
      logService.log(`${figureSet.arrowRight} calculating THAC0 as a level ${level} creature`);
    }
    const item = Thac0Table.find((t) => t.level === level);
    if (!item) {
      throw new Error(`thac0 not found in table for level ${level}`);
    }
    if (data.thac0 !== undefined)
      logService.warn(
        `level: ${level}, hp bonus: ${data.bonusHp ?? 0}, thac0: ${data.thac0}, calculated: ${item.thac0}`,
      );
    else data.thac0 = item.thac0;
  }

  convertMovement(movement: number): number {
    // aVENGER was using a coef of 0.75
    return Math.round(movement * 0.8);
  }

  private getSavingThrows(p: Exclude<CreatureAutoGenerate["savingThrows"], undefined>) {
    let key: keyof typeof SAVING_THROWS = "fighter";
    if (p.classe === "DRUID" || p.classe === "CLERIC") key = "priest";
    else if (p.classe === "MAGE") key = "wizard";
    const table = SAVING_THROWS[key];
    const saves = table.find((t) => p.level >= t.levels[0] && p.level <= t.levels[1]) as {
      saveDeath: number;
      saveWand: number;
      savePolymorph: number;
      saveBreath: number;
      saveSpell: number;
    };
    if (key !== "fighter")
      logService.log(
        `${figureSet.arrowRight} Level: ${p.level}, class: ${
          p.classe ?? "none"
        }, saving throws table: ${key}, ${JSON.stringify(saves)}`,
      );
    return {
      saveDeath: saves.saveDeath - (p.bonus?.saveDeath ?? 0),
      saveWand: saves.saveWand - (p.bonus?.saveWand ?? 0),
      savePolymorph: saves.savePolymorph - (p.bonus?.savePolymorph ?? 0),
      saveBreath: saves.saveBreath - (p.bonus?.saveBreath ?? 0),
      saveSpell: saves.saveSpell - (p.bonus?.saveSpell ?? 0),
    };
  }

  private autogenerateSavingThrows({
    data,
    parent,
    options,
  }: {
    data: Partial<CreatureData>;
    parent?: CreatureData;
    options: CreatureAutoGenerate["savingThrows"];
  }) {
    const level = data.level1;
    if (!level && !parent)
      throw new Error(`Can't generate saving throws because level1 is unknown`);
    else if (!level) return;
    const classe = data.class ?? parent?.class;
    const saves = this.getSavingThrows({
      level: options?.level ?? level.pnpValue,
      classe: options?.classe ?? classe,
      bonus: options?.bonus,
    });
    data.saveDeath = saves.saveDeath;
    data.saveWand = saves.saveWand;
    data.savePolymorph = saves.savePolymorph;
    data.saveBreath = saves.saveBreath;
    data.saveSpell = saves.saveSpell;
  }

  private checkDexterityArmorClassBonus(data: Partial<CreatureData>) {
    if (data.dexterity === undefined || data.ac === undefined) return;
    const bonus = this.getDexterityArmorClassBonus(data);
    if (bonus) {
      // Natural AC (before the dexterity bonus is re-applied by the engine) can never be worse
      // than 10, the unarmored baseline - so cap it there even if subtracting the bonus would
      // otherwise push it past that ceiling (e.g. a creature whose listed AC already equals 10).
      const newAc = Math.min(data.ac - bonus, 10);
      logService.log(
        `${figureSet.arrowRight} AC reduced to ${newAc} (was ${
          data.ac
        }) because of dexterity bonus (${bonus})`,
      );
      data.ac = newAc;
    }
  }

  private getDexterityArmorClassBonus(data: Partial<CreatureData>): number {
    if (data.dexterity === undefined) return 0;
    const item = DexterityTable.find((t) => t.dex === data.dexterity);
    if (!item) {
      throw new Error(`dexterity not found in table: ${data.dexterity}`);
    }
    return item.ac;
  }

  private adjustmentsForFile(creature: Creature, file: string): CreatureAdjustment[] {
    const upper = file.toUpperCase();
    return creature.adjustments.filter((a) => a.files.some((f) => f.toUpperCase() === upper));
  }

  findPersistingItems(creature: Creature): CsvFinding[] {
    const findings: CsvFinding[] = [];
    for (const f of creature.files) {
      const row = monsterFilesService.getCreatureRow(f.name, f.game);
      if (!row) continue;
      const removed = new Set(
        [
          ...creature.data.items.remove,
          ...this.adjustmentsForFile(creature, f.name).flatMap((a) => a.data.items.remove),
        ].map((r) => r.toUpperCase()),
      );
      const persisting = row.items.filter((it) => !removed.has(it.file.toUpperCase()));
      if (persisting.length) {
        findings.push({
          file: f.name,
          game: f.game,
          detail: `${f.name} (${persisting.map((it) => `${it.file} ${it.slot}`).join(", ")})`,
        });
      }
    }
    return findings;
  }

  findLevelGaps(creature: Creature): CsvFinding[] {
    const findings: CsvFinding[] = [];
    for (const f of creature.files) {
      const row = monsterFilesService.getCreatureRow(f.name, f.game);
      if (!row || row.level === undefined) continue;
      let level = creature.data.level1?.pnpValue;
      for (const a of this.adjustmentsForFile(creature, f.name)) {
        if (a.data.level1 !== undefined) level = a.data.level1.pnpValue;
      }
      if (level === undefined) continue; // no base and no adjustment level → nothing to compare
      if (Math.abs(row.level - level) > 2) {
        findings.push({
          file: f.name,
          game: f.game,
          detail: `${f.name} (csv ${row.level} / def ${level})`,
        });
      }
    }
    return findings;
  }

  findOriginalScripts(creature: Creature): CsvFinding[] {
    const findings: CsvFinding[] = [];
    for (const f of creature.files) {
      const row = monsterFilesService.getCreatureRow(f.name, f.game);
      if (!row) continue;
      const removed = new Set(
        [
          ...creature.data.script.remove,
          ...this.adjustmentsForFile(creature, f.name).flatMap((a) => a.data.script.remove),
        ].map((s) => s.toUpperCase()),
      );
      const kept = row.scripts.filter((s) => {
        const v = s.value.toUpperCase();
        return v !== "NONE" && !removed.has(v) && !GENERIC_SCRIPTS_REMOVED.has(v);
      });
      if (kept.length) {
        findings.push({
          file: f.name,
          game: f.game,
          detail: `${f.name} (${kept.map((s) => `${s.slot}=${s.value}`).join(", ")})`,
        });
      }
    }
    return findings;
  }

  checkAgainstCsv(creature: Creature): void {
    this.reportCsvFinding(
      creature,
      this.findPersistingItems(creature),
      "validatedItems",
      "warn",
      "unremoved source items",
    );
    this.reportCsvFinding(
      creature,
      this.findLevelGaps(creature),
      "validatedLevel",
      "warn",
      "level gap > 2 vs creatures.csv",
    );
    this.reportCsvFinding(
      creature,
      this.findOriginalScripts(creature),
      "validatedScript",
      "info",
      "original scripts retained",
    );
  }

  private reportCsvFinding(
    creature: Creature,
    findings: CsvFinding[],
    column: "validatedItems" | "validatedLevel" | "validatedScript",
    level: "warn" | "info",
    label: string,
  ): void {
    const shown = findings.filter(
      (f) => !monsterFilesService.getCreatureRow(f.file, f.game)?.[column],
    );
    if (!shown.length) return;
    const name = translationService.from(creature.name);
    logService[level](`${name}: ${label} — ${shown.map((f) => f.detail).join("; ")}`);
  }
}

const creatureService = new CreatureService();
export default creatureService;
