// Ghostwalk Spider

// Initiate dialog
IF
	Global("JA_DIALOG","LOCALS",0)
	Name("C#LCCENS",Myself)
	NumTimesTalkedTo(0)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("JA_DIALOG","LOCALS",1)
		FaceObject([PC])
		StartDialogueNoSet([PC])
END

// Init
IF
	Global("JA_INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",0)
		SetGlobal("JA_PRECAST_LONG","LOCALS",0)
		SetGlobal("JA_PRECAST_MID","LOCALS",0)
		SetGlobalTimer("JA_REST","LOCALS",2400)
		SetGlobal("JA_INIT","LOCALS",1)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA_INIT","LOCALS",1)
	GlobalTimerExpired("JA_REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_INIT","LOCALS",0)
		Rest()
END

// Precast Stoneskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPWI408")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPWI408",Myself)
		RemoveSpellRES("SPWI408")
		Continue()
END

// Precast Ironskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPPR506")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPPR506",Myself)
		RemoveSpellRES("SPPR506")
		Continue()
END

IF
	Global("JA_PRECAST_LONG","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_PRECAST_LONG","LOCALS",1)
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.SPIDER],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA_COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA_HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA_HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA_COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.SPIDER],99)
	InMyArea([EVILCUTOFF.0.SPIDER])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA_COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.SPIDER],99)
	InMyArea([EVILCUTOFF.0.SPIDER])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA_COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Web Tangle
IF
	HaveSpellRES("jas0m3a")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(NearestEnemyOfType([PC]),WEAPON)
	!CheckStatGT(NearestEnemyOfType([PC]),0,SANCTUARY)
	!StateCheck(NearestEnemyOfType([PC]),STATE_REALLY_DEAD)
	See(NearestEnemyOfType([PC]))
	Range(LastSeenBy(Myself),6)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m3a",LastSeenBy(Myself))
END

IF
	HaveSpellRES("jas0m3a")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(SecondNearestEnemyOfType([PC]),WEAPON)
	!CheckStatGT(SecondNearestEnemyOfType([PC]),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOfType([PC]),STATE_REALLY_DEAD)
	See(SecondNearestEnemyOfType([PC]))
	Range(LastSeenBy(Myself),6)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m3a",LastSeenBy(Myself))
END

IF
	HaveSpellRES("jas0m3a")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(ThirdNearestEnemyOfType([PC]),WEAPON)
	!CheckStatGT(ThirdNearestEnemyOfType([PC]),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOfType([PC]),STATE_REALLY_DEAD)
	See(ThirdNearestEnemyOfType([PC]))
	Range(LastSeenBy(Myself),6)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m3a",LastSeenBy(Myself))
END

IF
	HaveSpellRES("jas0m3a")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(FourthNearestEnemyOfType([PC]),WEAPON)
	!CheckStatGT(FourthNearestEnemyOfType([PC]),0,SANCTUARY)
	!StateCheck(FourthNearestEnemyOfType([PC]),STATE_REALLY_DEAD)
	See(FourthNearestEnemyOfType([PC]))
	Range(LastSeenBy(Myself),6)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m3a",LastSeenBy(Myself))
END

IF
	HaveSpellRES("jas0m3a")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(FifthNearestEnemyOfType([PC]),WEAPON)
	!CheckStatGT(FifthNearestEnemyOfType([PC]),0,SANCTUARY)
	!StateCheck(FifthNearestEnemyOfType([PC]),STATE_REALLY_DEAD)
	See(FifthNearestEnemyOfType([PC]))
	Range(LastSeenBy(Myself),6)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m3a",LastSeenBy(Myself))
END

IF
	HaveSpellRES("jas0m3a")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(SixthNearestEnemyOfType([PC]),WEAPON)
	!CheckStatGT(SixthNearestEnemyOfType([PC]),0,SANCTUARY)
	!StateCheck(SixthNearestEnemyOfType([PC]),STATE_REALLY_DEAD)
	See(SixthNearestEnemyOfType([PC]))
	Range(LastSeenBy(Myself),6)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m3a",LastSeenBy(Myself))
END

// Attack HeldAndNotPoisoned enemy
IF
	OR(6)
		!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
		StateCheck(NearestEnemyOf(Myself),STATE_POISONED)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(6)
		!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_POISONED)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(6)
		!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_POISONED)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(6)
		!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_POISONED)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(6)
		!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_POISONED)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(6)
		!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_POISONED)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(6)
		!CheckStatGT(SeventhNearestEnemyOf(Myself),0,HELD)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_POISONED)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(6)
		!CheckStatGT(EighthNearestEnemyOf(Myself),0,HELD)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_POISONED)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(6)
		!CheckStatGT(NinthNearestEnemyOf(Myself),0,HELD)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_POISONED)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(6)
		!CheckStatGT(TenthNearestEnemyOf(Myself),0,HELD)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_POISONED)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON0,0)
		Continue()
END

IF
	CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON1,0)
		Continue()
END

IF
	CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Slowed enemy
IF
	OR(12)
		!StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(NearestEnemyOf(Myself),0,HELD)
		StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(12)
		!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(SeventhNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,HELD)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(EighthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,HELD)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(NinthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,HELD)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(TenthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,HELD)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON0,0)
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON1,0)
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Able enemy
IF
	OR(11)
		CheckStatGT(NearestEnemyOf(Myself),0,HELD)
		StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,HELD)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,HELD)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,HELD)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,HELD)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON0,0)
		Continue()
END

IF
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON1,0)
		Continue()
END

IF
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Held enemy
IF
	OR(5)
		!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(SeventhNearestEnemyOf(Myself),0,HELD)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(EighthNearestEnemyOf(Myself),0,HELD)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(NinthNearestEnemyOf(Myself),0,HELD)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(TenthNearestEnemyOf(Myself),0,HELD)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	CheckStatGT(LastSeenBy(Myself),0,HELD)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON0,0)
		Continue()
END

IF
	CheckStatGT(LastSeenBy(Myself),0,HELD)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON1,0)
		Continue()
END

IF
	CheckStatGT(LastSeenBy(Myself),0,HELD)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Stunned enemy
IF
	OR(5)
		!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(5)
		!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(SeventhNearestEnemyOf(Myself),STATE_STUNNED)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(EighthNearestEnemyOf(Myself),STATE_STUNNED)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(NinthNearestEnemyOf(Myself),STATE_STUNNED)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(TenthNearestEnemyOf(Myself),STATE_STUNNED)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON0,0)
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON1,0)
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack NoCheck enemy
IF
	OR(4)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(4)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(4)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(4)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(4)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(4)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(4)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(4)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(4)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(4)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON0,0)
		Continue()
END

IF
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON1,0)
		Continue()
END

IF
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Sleep enemy
IF
	OR(4)
		!StateCheck(Player1,STATE_SLEEPING)
		CheckStatGT(Player1,0,SANCTUARY)
		StateCheck(Player1,STATE_REALLY_DEAD)
		!See(Player1)
	OR(4)
		!StateCheck(Player2,STATE_SLEEPING)
		CheckStatGT(Player2,0,SANCTUARY)
		StateCheck(Player2,STATE_REALLY_DEAD)
		!See(Player2)
	OR(4)
		!StateCheck(Player3,STATE_SLEEPING)
		CheckStatGT(Player3,0,SANCTUARY)
		StateCheck(Player3,STATE_REALLY_DEAD)
		!See(Player3)
	OR(4)
		!StateCheck(Player4,STATE_SLEEPING)
		CheckStatGT(Player4,0,SANCTUARY)
		StateCheck(Player4,STATE_REALLY_DEAD)
		!See(Player4)
	OR(4)
		!StateCheck(Player5,STATE_SLEEPING)
		CheckStatGT(Player5,0,SANCTUARY)
		StateCheck(Player5,STATE_REALLY_DEAD)
		!See(Player5)
	OR(4)
		!StateCheck(Player6,STATE_SLEEPING)
		CheckStatGT(Player6,0,SANCTUARY)
		StateCheck(Player6,STATE_REALLY_DEAD)
		!See(Player6)
THEN
	RESPONSE #100
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON0,0)
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_WEAPON1,0)
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Random walking (in combat) 
IF
	Global("JA_COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

