/**
 * Development tools
 */

DEFINE_ACTION_MACRO makeCreatureList BEGIN
    COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
        PATCH_IF (%SOURCE_SIZE% > 0x2d3) BEGIN
            READ_BYTE 0x272 race
            READ_BYTE 0x273 class
            READ_LONG 0x28 animation
            READ_STRREF 0x08 name
            // PATCH_IF class = 199 BEGIN
            // PATCH_IF race = 119 BEGIN
            PATCH_IF race = 133 OR class = 171 BEGIN
                // PATCH_IF class = 135 OR animation = 0xeb10 BEGIN
                // PATCH_IF race = 133 OR class = 171 OR animation = 0x6403 BEGIN
                // PATCH_IF animation = 0xE080 BEGIN
                PATCH_PRINT ~"%SOURCE_RES%",  // %name%~
            END
        END
    BUT_ONLY
END

DEFINE_ACTION_MACRO checkSpells BEGIN
    ACTION_FOR_EACH ~file~ IN dvbanish.spl dvgasfrm.spl BEGIN
        ACTION_IF FILE_EXISTS_IN_GAME ~%file%~ BEGIN
            COPY_EXISTING ~%file%~ ~override~
                PATCH_IF ("%version%" STRING_COMPARE_CASE "V2.0" = 0) BEGIN  // iwd2, spl 2.0
                    SET min_size = 0x82
                END ELSE BEGIN
                    SET min_size = 0x72
                END
                READ_LONG 0x6a fx_off ELSE 0
                SET counter_offset = 0x70
                SET abil_length = 0x28
                SET fx_type = 0
                READ_LONG 0x64 abil_off ELSE 0
                READ_SHORT 0x68 abil_num ELSE 0
                PATCH_IF (BUFFER_LENGTH >= min_size) BEGIN  // sanity check
                    READ_LONG 0x0c strref
                    PATCH_IF ((strref > 0) AND (strref < 200000)) BEGIN
                        READ_STRREF 0x0c name
                    END ELSE BEGIN
                        READ_STRREF 0x08 name
                    END
                    FOR (index = "-1"; index < abil_num; ++index) BEGIN  // we start at -1 for global effects
                        PATCH_IF (index < 0) BEGIN  // if loop through globals needed
                            SET abil_fx_idx = 0  // start with effect 0 since we're in the global loop
                            SET abil_type = "-1"  // basically, ignore header type checks for global loop
                        END ELSE BEGIN  // otherwise normal ability

                            READ_BYTE (abil_off + (abil_length * index)) abil_type
                            SET counter_offset = (abil_off + 0x1e + (abil_length * index))
                            READ_SHORT (abil_off + 0x20 + (abil_length * index)) abil_fx_idx
                        END
                        READ_SHORT counter_offset counter  // fx_num on global loop, otherwise abil_fx_num
                        FOR (index2 = 0; index2 < counter; ++index2) BEGIN
                            READ_SHORT (fx_off + (0x08 * fx_type) + ((abil_fx_idx + index2) * (0x30 + (0xd8 * fx_type)))) o_opcode
                            READ_LONG (fx_off + 0x04 + (0x10 * fx_type) + ((abil_fx_idx + index2) * (0x30 + (0xd8 * fx_type)))) o_parameter1
                            PATCH_IF o_opcode = 139 BEGIN
                                READ_STRREF (fx_off + 0x04 + (0x10 * fx_type) + ((abil_fx_idx + index2) * (0x30 + (0xd8 * fx_type)))) str
                                PATCH_PRINT ~%SOURCE_FILE% (%name%): %o_parameter1% -> %str%~
                            END  // end patch_if for a matched effect
                        END
                        // end of the for loop through effects
                    END
                    // end loop through effects on ability
                END
                // end ability loop
            BUT_ONLY_IF_IT_CHANGES
        END
    END
END
