/**
 * Converts any decimal number into a hexadecimal number
 */
DEFINE_ACTION_FUNCTION TO_HEX_NUMBER
INT_VAR
  value     = 0   // the decimal number
  minDigits = 1   // min. number of digits in return value (not counting sign)
  prefix    = 0   // whether to return number with "0x" prefix
RET
  hexNumber       // returned as string without prefix
BEGIN
  ACTION_IF (minDigits < 1) BEGIN OUTER_SET minDigits = 1 END
  ACTION_IF (minDigits > 8) BEGIN OUTER_SET minDigits = 8 END
  OUTER_TEXT_SPRINT hexNumber ~~
  ACTION_DEFINE_ARRAY digit BEGIN ~0~ ~1~ ~2~ ~3~ ~4~ ~5~ ~6~ ~7~ ~8~ ~9~ ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ END

  ACTION_IF (value < 0) BEGIN
    OUTER_SET signed = 1
    OUTER_SET value = 0 - value
  END ELSE BEGIN
    OUTER_SET signed = 0
  END

  OUTER_WHILE (value != 0) BEGIN
    OUTER_SET curDigit = value BAND 0xf
    OUTER_SET value = value BLSR 4
    OUTER_TEXT_SPRINT hexDigit $EVAL digit(~%curDigit%~)
    OUTER_TEXT_SPRINT hexNumber ~%hexDigit%%hexNumber%~
  END

  OUTER_WHILE (STRING_LENGTH ~%hexNumber%~ < minDigits) BEGIN
    OUTER_TEXT_SPRINT hexNumber ~0%hexNumber%~
  END

  ACTION_IF (prefix) BEGIN
    OUTER_TEXT_SPRINT hexNumber ~0x%hexNumber%~
  END

  ACTION_IF (signed) BEGIN
    OUTER_TEXT_SPRINT hexNumber ~-%hexNumber%~
  END
END

DEFINE_PATCH_FUNCTION STRING_TO_ARRAY
STR_VAR
  string = ""     // string with space separator
RET_ARRAY array
BEGIN
  CLEAR_ARRAY array
  SET i=0
  INNER_PATCH ~%string%~ BEGIN
    REPLACE_EVALUATE ~[^ %TAB%]+~ BEGIN
      SPRINT $array("%i%") "%MATCH0%"
      i+=1
    END ~%MATCH0%~
  END    
END

DEFINE_ACTION_FUNCTION MERGE_ARRAYS
STR_VAR
  array1 = ""
  array2 = ""
  array3 = ""
  array4 = ""
  array5 = ""
  array6 = ""
  array7 = ""
  array8 = ""
  array9 = ""
RET_ARRAY array
BEGIN
  ACTION_CLEAR_ARRAY array
  OUTER_SET i=0
  ACTION_PHP_EACH array1 AS _ => item BEGIN
    OUTER_SPRINT $array("%i%") EVAL ~%item%~
    OUTER_SET i=i+1
  END
  ACTION_PHP_EACH array2 AS _ => item BEGIN
    OUTER_SPRINT $array("%i%") EVAL ~%item%~
    OUTER_SET i=i+1
  END
  ACTION_PHP_EACH array3 AS _ => item BEGIN
    OUTER_SPRINT $array("%i%") EVAL ~%item%~
    OUTER_SET i=i+1
  END
  ACTION_PHP_EACH array4 AS _ => item BEGIN
    OUTER_SPRINT $array("%i%") EVAL ~%item%~
    OUTER_SET i=i+1
  END
  ACTION_PHP_EACH array5 AS _ => item BEGIN
    OUTER_SPRINT $array("%i%") EVAL ~%item%~
    OUTER_SET i=i+1
  END
  ACTION_PHP_EACH array6 AS _ => item BEGIN
    OUTER_SPRINT $array("%i%") EVAL ~%item%~
    OUTER_SET i=i+1
  END
  ACTION_PHP_EACH array7 AS _ => item BEGIN
    OUTER_SPRINT $array("%i%") EVAL ~%item%~
    OUTER_SET i=i+1
  END
  ACTION_PHP_EACH array8 AS _ => item BEGIN
    OUTER_SPRINT $array("%i%") EVAL ~%item%~
    OUTER_SET i=i+1
  END
  ACTION_PHP_EACH array9 AS _ => item BEGIN
    OUTER_SPRINT $array("%i%") EVAL ~%item%~
    OUTER_SET i=i+1
  END
END
