// Wild Cat

IF
	Allegiance(Myself,NEUTRAL)
	Class(Myself,HUNTER_CREATURE)
	Detect([PC])
	See([0.0.0.FOOD_CREATURE])
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Init
IF
	Global("JA#INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",0)
		SetGlobal("JA#PRECAST_LONG","LOCALS",0)
		SetGlobal("JA#PRECAST_MID","LOCALS",0)
		SetGlobalTimer("JA#REST","LOCALS",2400)
		SetGlobal("JA#INIT","LOCALS",1)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA#INIT","LOCALS",1)
	GlobalTimerExpired("JA#REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#INIT","LOCALS",0)
		Rest()
END

// Precast Stoneskin
IF
	Global("JA#PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPWI408")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPWI408",Myself)
		RemoveSpellRES("SPWI408")
		Continue()
END

// Precast Ironskin
IF
	Global("JA#PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPPR506")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPPR506",Myself)
		RemoveSpellRES("SPPR506")
		Continue()
END

IF
	Global("JA#PRECAST_LONG","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#PRECAST_LONG","LOCALS",1)
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.CAT],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA#COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA#HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA#HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.CAT],99)
	InMyArea([EVILCUTOFF.0.CAT])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA#COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.CAT],99)
	InMyArea([EVILCUTOFF.0.CAT])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA#COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Handle Panic state
IF
	StateCheck(Myself,STATE_PANIC)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),15)
END

IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Run away from enemies
IF
	Range(NearestEnemyOf(Myself),20)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Random walking (in combat) 
IF
	Global("JA#COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

// Random facing
IF
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		RandomTurn()
END

