
// COPY ~%MOD_FOLDER%/lib/pnp-spell/color_spray/spwi105.spl~ ~override~                                          // Color Spray
//   SAY NAME1 @1000000 SAY NAME2 #-1
//   SAY UNIDENTIFIED_DESC @1890 SAY DESC @1890
//   PATCH_IF GAME_IS ~iwdee~ BEGIN
//     LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 target = 2 opcode = 324 duration = 1 parameter2 = 23 END // do not affect blinded creatures
//   END
LAF create_spell_ColorSpray END

// TODO:
// COPY ~%MOD_FOLDER%/spl/mephits/rr#mracs.spl~ ~override/spin937.spl~                     // Color Spray (Radiant Mephit version)
//   SAY NAME1 @1000000 SAY NAME2 #-1
//   SAY UNIDENTIFIED_DESC @1890 SAY DESC @1890
//   PATCH_IF GAME_IS ~iwdee~ BEGIN
//     LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 target = 2 opcode = 324 duration = 1 parameter2 = 23 END // do not affect blinded creatures
//   END

// Patch immunity to both Color Spray versions into spells and items that cause blindness
// Note: Color Spray should not protect the target from its own effects. It's clunky and can often cause more harm than good. The drawbacks outweigh the benefits in this case.
ACTION_IF !GAME_IS ~iwdee~ BEGIN // not needed on IWD:EE
  LAF get_blindness_resources RET_ARRAY resources END
  ACTION_PHP_EACH resources AS _ => file BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%file%~ BEGIN
      COPY_EXISTING ~%file%~ ~override~
        PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN
          LPF add_conditional_immunity INT_VAR opcode = 74 STR_VAR spell = spwi105 END
          LPF add_conditional_immunity INT_VAR opcode = 74 STR_VAR spell = spin937 END
        END
      BUT_ONLY_IF_IT_CHANGES
    END
  END
END
