// Summons are destroyed on death
IF
	Die()
THEN
	RESPONSE #100
		DestroySelf()
END

// Precast Stoneskin
IF
	Global("JA#PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPWI408")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPWI408",Myself)
		RemoveSpellRES("SPWI408")
		Continue()
END

// Precast Ironskin
IF
	Global("JA#PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPPR506")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPPR506",Myself)
		RemoveSpellRES("SPPR506")
		Continue()
END

IF
	Global("JA#PRECAST_LONG","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA#PRECAST_LONG","LOCALS",1)
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA#COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA#COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA#HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(98)
		SetGlobalTimer("JA#HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA#COMBAT","LOCALS",0)
	Heard(LastSummonerOf(Myself),98)
	InMyArea(LastSummonerOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("JA#COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA#COMBAT","LOCALS",1)
	Heard(LastSummonerOf(Myself),98)
	InMyArea(LastSummonerOf(Myself))
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Summon follow summoner
IF
	Global("JA#COMBAT","LOCALS",0)
	!StateCheck(Myself,STATE_BLIND)
	ActionListEmpty()
	!See(NearestEnemyOf(Myself))
	!See(LastSummonerOf(Myself))
	HPGT(LastSummonerOf(Myself),0)
	Range(LastSummonerOf(Myself),150)
THEN
	RESPONSE #100
		MoveToObject(LastSummonerOf(Myself))
END

// Do nothing if...
IF
	ActionListEmpty()
	OR(4)
		Global("JA#COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	ActionListEmpty()
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Vocalize
IF
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	ActionListEmpty()
	HaveSpell(WIZARD_VOCALIZE)
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(Myself,WIZARD_VOCALIZE)
END

// Mirror Images
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	ActionListEmpty()
	HaveSpell(WIZARD_MIRROR_IMAGE)
	!StateCheck(Myself,STATE_MIRRORIMAGE)
	RandomNumGT(800,240)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(Myself,WIZARD_MIRROR_IMAGE)
END

// Greater Malison
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

// Emotion
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

// Minor Spell Deflection
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	ActionListEmpty()
	HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
	OR(4)
		See([PC.0.0.MAGE_ALL])
		See([PC.0.0.CLERIC_ALL])
		See([PC.0.0.DRUID_ALL])
		See([PC.0.0.BARD])
	RandomNumGT(803,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
END

// Shield
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	ActionListEmpty()
	HaveSpell(WIZARD_SHIELD)
	CheckStat(Myself,2,SCRIPTINGSTATE5)
	RandomNumGT(804,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SHIELD)
END

// Haste
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	ActionListEmpty()
	HaveSpell(WIZARD_HASTE)
	!StateCheck(Myself,STATE_HASTED)
	RandomNumGT(805,242)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(Myself,WIZARD_HASTE)
END

// Slow
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOfType([PC.0.0.RANGER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

// Slow
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

// Spell Thrust
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(806,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(806,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(806,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(806,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

// Spook
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

// Stinking Cloud
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

// Melf Acid Arrow
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

// Melf Acid Arrow
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

// Magic Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// Magic Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// Magic Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// Chromatic Orb
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

// Glitterdust
IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	ActionListEmpty()
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA#ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA#ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

// Try to reposition to use ranged attack
IF
	ActionListEmpty()
	CanEquipRanged()
	Range(NearestEnemyOf(Myself),4)
THEN
	RESPONSE #50
		SetInterrupt(FALSE)
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)
		SetInterrupt(TRUE)
	RESPONSE #50
		Continue()
END

// Attack NoCheck enemy
IF
	ActionListEmpty()
	OR(4)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(4)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(4)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(4)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(4)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(4)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(4)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(4)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(4)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(4)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	ActionListEmpty()
	CanEquipRanged()
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		Continue()
END

IF
	ActionListEmpty()
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		Continue()
END

IF
	ActionListEmpty()
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Sleep enemy
IF
	ActionListEmpty()
	OR(4)
		!StateCheck(Player1,STATE_SLEEPING)
		CheckStatGT(Player1,0,SANCTUARY)
		StateCheck(Player1,STATE_REALLY_DEAD)
		!See(Player1)
	OR(4)
		!StateCheck(Player2,STATE_SLEEPING)
		CheckStatGT(Player2,0,SANCTUARY)
		StateCheck(Player2,STATE_REALLY_DEAD)
		!See(Player2)
	OR(4)
		!StateCheck(Player3,STATE_SLEEPING)
		CheckStatGT(Player3,0,SANCTUARY)
		StateCheck(Player3,STATE_REALLY_DEAD)
		!See(Player3)
	OR(4)
		!StateCheck(Player4,STATE_SLEEPING)
		CheckStatGT(Player4,0,SANCTUARY)
		StateCheck(Player4,STATE_REALLY_DEAD)
		!See(Player4)
	OR(4)
		!StateCheck(Player5,STATE_SLEEPING)
		CheckStatGT(Player5,0,SANCTUARY)
		StateCheck(Player5,STATE_REALLY_DEAD)
		!See(Player5)
	OR(4)
		!StateCheck(Player6,STATE_SLEEPING)
		CheckStatGT(Player6,0,SANCTUARY)
		StateCheck(Player6,STATE_REALLY_DEAD)
		!See(Player6)
THEN
	RESPONSE #100
		Continue()
END

IF
	ActionListEmpty()
	CanEquipRanged()
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		Continue()
END

IF
	ActionListEmpty()
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		Continue()
END

IF
	ActionListEmpty()
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

