// Ghost

// Initiate dialog
IF
	Global("JA_DIALOG","LOCALS",0)
	Name("daitel",Myself)
	NumTimesTalkedTo(0)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("JA_DIALOG","LOCALS",1)
		FaceObject([PC])
		StartDialogueNoSet([PC])
END

// Init
IF
	Global("JA_INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",0)
		SetGlobal("JA_PRECAST_LONG","LOCALS",0)
		SetGlobal("JA_PRECAST_MID","LOCALS",0)
		SetGlobalTimer("JA_REST","LOCALS",2400)
		SetGlobal("JA_INIT","LOCALS",1)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA_INIT","LOCALS",1)
	GlobalTimerExpired("JA_REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_INIT","LOCALS",0)
		Rest()
END

// Precast Stoneskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPWI408")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPWI408",Myself)
		RemoveSpellRES("SPWI408")
		Continue()
END

// Precast Ironskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPPR506")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPPR506",Myself)
		RemoveSpellRES("SPPR506")
		Continue()
END

IF
	Global("JA_PRECAST_LONG","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_PRECAST_LONG","LOCALS",1)
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.SPECTRE],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA_COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA_HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA_HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA_COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.SPECTRE],99)
	InMyArea([EVILCUTOFF.0.SPECTRE])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA_COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.SPECTRE],99)
	InMyArea([EVILCUTOFF.0.SPECTRE])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA_COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Fear Aura
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas0m5d")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m5d",Myself)
		RemoveSpellRES("jas0m5d")
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas0m5d")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m5d",Myself)
		RemoveSpellRES("jas0m5d")
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas0m5d")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m5d",Myself)
		RemoveSpellRES("jas0m5d")
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas0m5d")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m5d",Myself)
		RemoveSpellRES("jas0m5d")
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas0m5d")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m5d",Myself)
		RemoveSpellRES("jas0m5d")
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas0m5d")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m5d",Myself)
		RemoveSpellRES("jas0m5d")
END

// Vocalize
IF
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_VOCALIZE)
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_VOCALIZE)
END

// Shadow Door
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_SHADOW_DOOR)
	Detect(NearestEnemyOf(Myself))
	HPLT(Myself,75)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	RandomNumGT(801,240)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SHADOW_DOOR)
END

// Protection From Magical Weapons
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	RandomNumGT(802,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
END

// Stoneskin
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_STONE_SKIN)
	CheckStatLT(Myself,2,STONESKINS)
	RandomNumGT(803,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_STONE_SKIN)
END

// Minor Globe Of Invulnerability
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
	RandomNumGT(804,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
END

// Protection From Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
	!CheckSpellState(Myself,PROTECTION_FROM_NORMAL_MISSILES)
	RandomNumGT(805,242)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
END

// Minor Spell Deflection
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
	OR(4)
		See([PC.0.0.MAGE_ALL])
		See([PC.0.0.CLERIC_ALL])
		See([PC.0.0.DRUID_ALL])
		See([PC.0.0.BARD])
	RandomNumGT(806,242)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
END

// Mirror Images
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_MIRROR_IMAGE)
	!StateCheck(Myself,STATE_MIRRORIMAGE)
	RandomNumGT(807,242)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_MIRROR_IMAGE)
END

// Shield
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_SHIELD)
	CheckStat(Myself,2,SCRIPTINGSTATE5)
	RandomNumGT(808,242)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SHIELD)
END

// Fire Shield
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_FIRE_SHIELD_RED)
	!CheckStatGT(Myself,0,WIZARD_FIRE_SHIELD)
	RandomNumGT(809,243)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_FIRE_SHIELD_RED)
END

// Breach
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BREACH)
	!StateCheck([PC.0.0.MAGE_ALL],STATE_DISABLED)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	OR(2)
		HasBounceEffects(LastSeenBy(Myself))
		HasImmunityEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BREACH)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BREACH)
	!StateCheck([PC.0.0.CLERIC_ALL],STATE_DISABLED)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	OR(2)
		HasBounceEffects(LastSeenBy(Myself))
		HasImmunityEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BREACH)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BREACH)
	!StateCheck([PC.0.0.DRUID_ALL],STATE_DISABLED)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	OR(2)
		HasBounceEffects(LastSeenBy(Myself))
		HasImmunityEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BREACH)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BREACH)
	!StateCheck([PC.0.0.BARD],STATE_DISABLED)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	OR(2)
		HasBounceEffects(LastSeenBy(Myself))
		HasImmunityEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BREACH)
END

// Spell Thrust
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

// Dispel Magic
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	!StateCheck(Player1,STATE_DISABLED)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	!StateCheck(Player2,STATE_DISABLED)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	!StateCheck(Player3,STATE_DISABLED)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	!StateCheck(Player4,STATE_DISABLED)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	!StateCheck(Player5,STATE_DISABLED)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TRUE_DISPEL_MAGIC)
	!StateCheck(Player6,STATE_DISABLED)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TRUE_DISPEL_MAGIC)
END

// Dispel Magic
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_REMOVE_MAGIC)
	!StateCheck(Player1,STATE_DISABLED)
	RandomNumGT(813,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_REMOVE_MAGIC)
	!StateCheck(Player2,STATE_DISABLED)
	RandomNumGT(813,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_REMOVE_MAGIC)
	!StateCheck(Player3,STATE_DISABLED)
	RandomNumGT(813,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_REMOVE_MAGIC)
	!StateCheck(Player4,STATE_DISABLED)
	RandomNumGT(813,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_REMOVE_MAGIC)
	!StateCheck(Player5,STATE_DISABLED)
	RandomNumGT(813,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_REMOVE_MAGIC)
	!StateCheck(Player6,STATE_DISABLED)
	RandomNumGT(813,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	OR(9)
		CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),49,RESISTFIRE)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
END

// Chain Lightning
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	RandomNumGT(814,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	RandomNumGT(814,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	RandomNumGT(814,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	RandomNumGT(814,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	RandomNumGT(814,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	RandomNumGT(814,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	RandomNumGT(814,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	RandomNumGT(814,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	RandomNumGT(814,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	RandomNumGT(814,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

// Cloudkill
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CLOUDKILL)
	RandomNumGT(815,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CLOUDKILL)
	RandomNumGT(815,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CLOUDKILL)
	RandomNumGT(815,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CLOUDKILL)
	RandomNumGT(815,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CLOUDKILL)
	RandomNumGT(815,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CLOUDKILL)
	RandomNumGT(815,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CLOUDKILL)
	RandomNumGT(815,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CLOUDKILL)
	RandomNumGT(815,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CLOUDKILL)
	RandomNumGT(815,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CLOUDKILL)
	RandomNumGT(815,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END

// Fireburst
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SUN_FIRE)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SUN_FIRE)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SUN_FIRE)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SUN_FIRE)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SUN_FIRE)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SUN_FIRE)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SUN_FIRE)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SUN_FIRE)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SUN_FIRE)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SUN_FIRE)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END

// Cone of Cold
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONE_OF_COLD)
	RandomNumGT(817,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONE_OF_COLD)
	RandomNumGT(817,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONE_OF_COLD)
	RandomNumGT(817,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONE_OF_COLD)
	RandomNumGT(817,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONE_OF_COLD)
	RandomNumGT(817,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONE_OF_COLD)
	RandomNumGT(817,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONE_OF_COLD)
	RandomNumGT(817,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONE_OF_COLD)
	RandomNumGT(817,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONE_OF_COLD)
	RandomNumGT(817,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONE_OF_COLD)
	RandomNumGT(817,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END

// Greater Malison
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(818,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(818,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(818,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(818,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(818,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(818,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

// Confusion
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONFUSION)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONFUSION)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONFUSION)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONFUSION)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONFUSION)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONFUSION)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONFUSION)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONFUSION)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONFUSION)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CONFUSION)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONFUSION)
END

// Teleport Field
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TELEPORT_FIELD)
	RandomNumGT(820,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TELEPORT_FIELD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TELEPORT_FIELD)
	RandomNumGT(820,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TELEPORT_FIELD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TELEPORT_FIELD)
	RandomNumGT(820,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TELEPORT_FIELD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TELEPORT_FIELD)
	RandomNumGT(820,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TELEPORT_FIELD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TELEPORT_FIELD)
	RandomNumGT(820,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TELEPORT_FIELD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_TELEPORT_FIELD)
	RandomNumGT(820,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TELEPORT_FIELD)
END

// Vitriolic Sphere
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_VITRIOLIC_SPHERE)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FarthestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_VITRIOLIC_SPHERE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_VITRIOLIC_SPHERE)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondFarthestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_VITRIOLIC_SPHERE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_VITRIOLIC_SPHERE)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdFarthestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_VITRIOLIC_SPHERE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_VITRIOLIC_SPHERE)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthFarthestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_VITRIOLIC_SPHERE)
END

// Mordenkainen's Force Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

// Mordenkainen's Force Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

// Mordenkainen's Force Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MORDENKAINENS_FORCE_MISSILES)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_FORCE_MISSILES)
END

// Slow
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOfType([PC.0.0.RANGER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

// Slow
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

// Flame Arrow
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_FLAME_ARROW)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_FLAME_ARROW)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_FLAME_ARROW)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_FLAME_ARROW)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_FLAME_ARROW)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_FLAME_ARROW)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

// Lightning Bolt
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_LIGHTNING_BOLT)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_LIGHTNING_BOLT)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_LIGHTNING_BOLT)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_LIGHTNING_BOLT)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_LIGHTNING_BOLT)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_LIGHTNING_BOLT)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END

// Hold Person
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_HOLD_PERSON)
	RandomNumGT(825,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_HOLD_PERSON)
	RandomNumGT(825,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_HOLD_PERSON)
	RandomNumGT(825,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_HOLD_PERSON)
	RandomNumGT(825,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_HOLD_PERSON)
	RandomNumGT(825,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_HOLD_PERSON)
	RandomNumGT(825,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
END

// Minor Sequencer
IF
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	!StateCheck(Myself,STATE_MIRRORIMAGE)
	RandomNumGT(826,248)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(Myself,WIZARD_MIRROR_IMAGE)
		ForceSpell(Myself,WIZARD_BLUR)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

// Minor Sequencer
IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

// Minor Sequencer
IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

IF
	Global("JA_MINOR_SEQUENCER","LOCALS",0)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),WIZARD_WEB)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMBUST)
		SetGlobal("JA_MINOR_SEQUENCER","LOCALS",1)
END

// Combust
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_COMBUST)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COMBUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_COMBUST)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COMBUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_COMBUST)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COMBUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_COMBUST)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COMBUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_COMBUST)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COMBUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_COMBUST)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COMBUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_COMBUST)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COMBUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_COMBUST)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COMBUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_COMBUST)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COMBUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_COMBUST)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COMBUST)
END

// Melf Acid Arrow
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

// Melf Acid Arrow
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

// Agannazar's Scorcher
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	RandomNumGT(830,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	RandomNumGT(830,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	RandomNumGT(830,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	RandomNumGT(830,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	RandomNumGT(830,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	RandomNumGT(830,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
END

// Obscuring Mist
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_OBSCURING_MIST)
	RandomNumGT(831,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_OBSCURING_MIST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_OBSCURING_MIST)
	RandomNumGT(831,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_OBSCURING_MIST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_OBSCURING_MIST)
	RandomNumGT(831,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_OBSCURING_MIST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_OBSCURING_MIST)
	RandomNumGT(831,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_OBSCURING_MIST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_OBSCURING_MIST)
	RandomNumGT(831,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_OBSCURING_MIST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_OBSCURING_MIST)
	RandomNumGT(831,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_OBSCURING_MIST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_OBSCURING_MIST)
	RandomNumGT(831,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_OBSCURING_MIST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_OBSCURING_MIST)
	RandomNumGT(831,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_OBSCURING_MIST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_OBSCURING_MIST)
	RandomNumGT(831,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_OBSCURING_MIST)
END

// Spook
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(832,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(832,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(832,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(832,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(832,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(832,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

// Magic Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// Magic Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// Magic Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(833,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// Burning Hands
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BURNING_HANDS)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BURNING_HANDS)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BURNING_HANDS)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BURNING_HANDS)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BURNING_HANDS)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BURNING_HANDS)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BURNING_HANDS)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BURNING_HANDS)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BURNING_HANDS)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_BURNING_HANDS)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END

// Attack Slowed enemy
IF
	OR(12)
		!StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(NearestEnemyOf(Myself),0,HELD)
		StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(12)
		!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(SeventhNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,HELD)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(EighthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,HELD)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(NinthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,HELD)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(12)
		!StateCheck(TenthNearestEnemyOf(Myself),STATE_SLOWED)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,HELD)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Able enemy
IF
	OR(11)
		CheckStatGT(NearestEnemyOf(Myself),0,HELD)
		StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,HELD)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_HELPLESS)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,HELD)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,HELD)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(11)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,HELD)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_STUNNED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_CONFUSED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_SLEEPING)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_HELPLESS)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Held enemy
IF
	OR(5)
		!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(SeventhNearestEnemyOf(Myself),0,HELD)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(EighthNearestEnemyOf(Myself),0,HELD)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(NinthNearestEnemyOf(Myself),0,HELD)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(5)
		!CheckStatGT(TenthNearestEnemyOf(Myself),0,HELD)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	CheckStatGT(LastSeenBy(Myself),0,HELD)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Stunned enemy
IF
	OR(5)
		!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(5)
		!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(SeventhNearestEnemyOf(Myself),STATE_STUNNED)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(EighthNearestEnemyOf(Myself),STATE_STUNNED)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(NinthNearestEnemyOf(Myself),STATE_STUNNED)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(5)
		!StateCheck(TenthNearestEnemyOf(Myself),STATE_STUNNED)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack NoCheck enemy
IF
	OR(4)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(4)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(4)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(4)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(4)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(4)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(4)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(4)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(4)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(4)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Sleep enemy
IF
	OR(4)
		!StateCheck(Player1,STATE_SLEEPING)
		CheckStatGT(Player1,0,SANCTUARY)
		StateCheck(Player1,STATE_REALLY_DEAD)
		!See(Player1)
	OR(4)
		!StateCheck(Player2,STATE_SLEEPING)
		CheckStatGT(Player2,0,SANCTUARY)
		StateCheck(Player2,STATE_REALLY_DEAD)
		!See(Player2)
	OR(4)
		!StateCheck(Player3,STATE_SLEEPING)
		CheckStatGT(Player3,0,SANCTUARY)
		StateCheck(Player3,STATE_REALLY_DEAD)
		!See(Player3)
	OR(4)
		!StateCheck(Player4,STATE_SLEEPING)
		CheckStatGT(Player4,0,SANCTUARY)
		StateCheck(Player4,STATE_REALLY_DEAD)
		!See(Player4)
	OR(4)
		!StateCheck(Player5,STATE_SLEEPING)
		CheckStatGT(Player5,0,SANCTUARY)
		StateCheck(Player5,STATE_REALLY_DEAD)
		!See(Player5)
	OR(4)
		!StateCheck(Player6,STATE_SLEEPING)
		CheckStatGT(Player6,0,SANCTUARY)
		StateCheck(Player6,STATE_REALLY_DEAD)
		!See(Player6)
THEN
	RESPONSE #100
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Open door
IF
	Global("RR#NOPND","GLOBAL",0)
	Allegiance(Myself,EVILCUTOFF)
	!AreaType(OUTDOOR)
	!Range(NearestEnemyOf(Myself),30)
	Range(NearestDoor,15)
	OpenState(NearestDoor,FALSE)
THEN
	RESPONSE #100
		MoveToObject(NearestDoor)
		OpenDoor(NearestDoor)
END

// Random walking (in combat) 
IF
	Global("JA_COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

