// Skeleton Monster

// Init
IF
	Global("JA_INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",0)
		SetGlobal("JA_PRECAST_LONG","LOCALS",0)
		SetGlobal("JA_PRECAST_MID","LOCALS",0)
		SetGlobalTimer("JA_REST","LOCALS",2400)
		SetGlobal("JA_INIT","LOCALS",1)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA_INIT","LOCALS",1)
	GlobalTimerExpired("JA_REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_INIT","LOCALS",0)
		Rest()
		ApplySpell(Myself,RESTORE_FULL_HEALTH)
END

// Precast Stoneskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPWI408")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPWI408",Myself)
		RemoveSpellRES("SPWI408")
		Continue()
END

// Precast AnimateDead
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPPR301")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPPR301",Myself)
		RemoveSpellRES("SPPR301")
		Continue()
END

// Precast AnimateSkeletonWarrior
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPPR619")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPPR619",Myself)
		RemoveSpellRES("SPPR619")
		Continue()
END

// Precast Ironskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPPR506")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPPR506",Myself)
		RemoveSpellRES("SPPR506")
		Continue()
END

IF
	Global("JA_PRECAST_LONG","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_PRECAST_LONG","LOCALS",1)
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.SKELETON],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA_COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA_HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA_HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA_COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.SKELETON],99)
	InMyArea([EVILCUTOFF.0.SKELETON])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA_COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.SKELETON],99)
	InMyArea([EVILCUTOFF.0.SKELETON])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA_COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Vocalize
IF
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_VOCALIZE)
	StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_VOCALIZE)
END

// Glitterdust
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GLITTERDUST)
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END

// Haste
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_HASTE)
	!StateCheck(Myself,STATE_HASTED)
	RandomNumGT(801,240)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_HASTE)
END

// Minor Spell Deflection
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
	OR(4)
		See([PC.0.0.MAGE_ALL])
		See([PC.0.0.CLERIC_ALL])
		See([PC.0.0.DRUID_ALL])
		See([PC.0.0.BARD])
	RandomNumGT(802,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
END

// Mirror Images
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_MIRROR_IMAGE)
	!StateCheck(Myself,STATE_MIRRORIMAGE)
	RandomNumGT(803,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_MIRROR_IMAGE)
END

// Shield
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(WIZARD_SHIELD)
	CheckStat(Myself,2,SCRIPTINGSTATE5)
	RandomNumGT(804,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,WIZARD_SHIELD)
END

// Spell Thrust
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(805,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(805,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(805,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPELL_THRUST)
	RandomNumGT(805,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	CheckSpellState(LastSeenBy(Myself),BUFF_PRO_SPELLS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)
END

// Greater Malison
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(806,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(806,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(806,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(806,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(806,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_GREATER_MALISON)
	RandomNumGT(806,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

// Emotion
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	RandomNumGT(807,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

// Slow
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOfType([PC.0.0.RANGER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

// Slow
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SLOW)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END

// Stinking Cloud
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_STINKING_CLOUD)
	RandomNumGT(808,242)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END

// Chromatic Orb
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_CHROMATIC_ORB)
	RandomNumGT(809,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END

// Spook
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_SPOOK)
	RandomNumGT(810,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END

// Melf Acid Arrow
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

// Melf Acid Arrow
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	RandomNumGT(811,243)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_NORMAL_MISSILES)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

// Magic Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// Magic Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// Magic Missiles
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	RandomNumGT(812,244)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

// True Seeing
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_TRUE_SIGHT)
	!CheckStatGT(Myself,0,TRUE_SIGHT)
	RandomNumGT(800,240)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_TRUE_SIGHT)
END

// Entropy Shield
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_ENTROPY_SHIELD)
	RandomNumGT(801,240)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_ENTROPY_SHIELD)
END

// Free Action
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_FREE_ACTION)
	RandomNumGT(802,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_FREE_ACTION)
END

// Physical Mirror
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_PHYSICAL_MIRROR)
	RandomNumGT(803,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_PHYSICAL_MIRROR)
END

// Unholy Word
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_UNHOLY_WORD)
	RandomNumGT(804,241)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_UNHOLY_WORD)
END

// SummonDeathKnight
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_SUMMON_DEATH_KNIGHT)
	RandomNumGT(805,242)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SUMMON_DEATH_KNIGHT)
END

// Bolt Of Glory
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_BOLT_OF_GLORY)
	RandomNumGT(806,242)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

// Animate Skeleton Warrior
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_ANIMATE_SKELETON_WARRIOR)
	RandomNumGT(807,242)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_ANIMATE_SKELETON_WARRIOR)
END

// Magic Resistance
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_MAGIC_RESISTANCE)
	RandomNumGT(808,242)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_MAGIC_RESISTANCE)
END

// Blade Barrier
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_BLADE_BARRIER)
	!CheckStatGT(Myself,0,CLERIC_BLADE_BARRIER)
	RandomNumGT(809,243)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_BLADE_BARRIER)
END

// Protection From Good
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_PROTECT_FROM_GOOD)
	RandomNumGT(810,243)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_PROTECT_FROM_GOOD)
END

// Protection From Good 10 Radius
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_PROTECTION_FROM_GOOD_10_FOOT)
	RandomNumGT(811,243)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_PROTECTION_FROM_GOOD_10_FOOT)
END

// Animate Dead
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!GlobalTimerNotExpired("Summoning","LOCALS")
	HaveSpell(CLERIC_ANIMATE_DEAD)
	!HaveSpellRES("D5PP422")
	!HaveSpellRES("D5P2632")
	RandomNumGT(812,244)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_ANIMATE_DEAD)
		SetGlobalTimer("Summoning","LOCALS",12)
END

// Armor Of Faith
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_ARMOR_OF_FAITH)
	RandomNumGT(813,244)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_ARMOR_OF_FAITH)
END

// Sanctuary
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_SANCTUARY)
	Detect(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	RandomNumGT(814,244)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_SANCTUARY)
END

// Chant
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_CHANT)
	RandomNumGT(815,245)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_CHANT)
END

// Dolorous Decay
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

// Dolorous Decay
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOLOROUS_DECAY)
	RandomNumGT(816,245)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOLOROUS_DECAY)
END

// Slay Living
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_SLAY_LIVING)
	!HasItem("LIGHT",Myself)
	!HasItem("SERIOUS",Myself)
	!HasItem("CRITICAL",Myself)
	!HasItem("HARM",Myself)
	!HasItem("SLAYLIVE",Myself)
	RandomNumGT(817,245)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_SLAY_LIVING)
END

// Holy Power
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_HOLY_POWER)
	CheckStatLT(Myself,100,STR)
	RandomNumGT(818,245)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_HOLY_POWER)
END

// Silence
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_SILENCE_15_FOOT)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!Range(LastSeenBy(Myself),20)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_SILENCE_15_FOOT)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!Range(LastSeenBy(Myself),20)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_SILENCE_15_FOOT)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!Range(LastSeenBy(Myself),20)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_SILENCE_15_FOOT)
	RandomNumGT(819,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!Range(LastSeenBy(Myself),20)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
END

// Miscast Magic
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MISCAST_MAGIC)
	RandomNumGT(820,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MISCAST_MAGIC)
	RandomNumGT(820,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MISCAST_MAGIC)
	RandomNumGT(820,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MISCAST_MAGIC)
	RandomNumGT(820,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([PC.0.0.BARD])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)
END

// Mental Domination
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

// Mental Domination
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

// Mental Domination
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

// Mental Domination
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	RandomNumGT(821,246)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END

// Flame Strike
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_FLAME_STRIKE)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_FLAME_STRIKE)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_FLAME_STRIKE)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_FLAME_STRIKE)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_FLAME_STRIKE)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_FLAME_STRIKE)
	RandomNumGT(822,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

// Poison
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_POISON)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_POISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_POISON)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_POISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_POISON)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_POISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_POISON)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_POISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_POISON)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_POISON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_POISON)
	RandomNumGT(823,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_POISON)
END

// Cloud of Pestilence
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOUD_OF_PESTILENCE)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOUD_OF_PESTILENCE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOUD_OF_PESTILENCE)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOUD_OF_PESTILENCE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOUD_OF_PESTILENCE)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOUD_OF_PESTILENCE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOUD_OF_PESTILENCE)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOUD_OF_PESTILENCE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOUD_OF_PESTILENCE)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOUD_OF_PESTILENCE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOUD_OF_PESTILENCE)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOUD_OF_PESTILENCE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOUD_OF_PESTILENCE)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOUD_OF_PESTILENCE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOUD_OF_PESTILENCE)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOUD_OF_PESTILENCE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOUD_OF_PESTILENCE)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOUD_OF_PESTILENCE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOUD_OF_PESTILENCE)
	RandomNumGT(824,247)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOUD_OF_PESTILENCE)
END

// Glyph of Warding
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_GLYPH_OF_WARDING)
	RandomNumGT(825,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FarthestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_GLYPH_OF_WARDING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_GLYPH_OF_WARDING)
	RandomNumGT(825,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondFarthestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_GLYPH_OF_WARDING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_GLYPH_OF_WARDING)
	RandomNumGT(825,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdFarthestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_GLYPH_OF_WARDING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_GLYPH_OF_WARDING)
	RandomNumGT(825,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthFarthestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_GLYPH_OF_WARDING)
END

// HolySmite
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_HOLY_SMITE)
	RandomNumGT(826,248)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLY_SMITE)
END

// Greater Command
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_GREATER_COMMAND)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_GREATER_COMMAND)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_GREATER_COMMAND)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_GREATER_COMMAND)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_GREATER_COMMAND)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_GREATER_COMMAND)
	RandomNumGT(827,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

// Rigid Thinking
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_RIGID_THINKING)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_RIGID_THINKING)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_RIGID_THINKING)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_RIGID_THINKING)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_RIGID_THINKING)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_RIGID_THINKING)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_RIGID_THINKING)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_RIGID_THINKING)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_RIGID_THINKING)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_RIGID_THINKING)
	RandomNumGT(828,248)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

// Cloak of Fear
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOAK_OF_FEAR)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_CLOAK_OF_FEAR)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOAK_OF_FEAR)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_CLOAK_OF_FEAR)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOAK_OF_FEAR)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_CLOAK_OF_FEAR)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOAK_OF_FEAR)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_CLOAK_OF_FEAR)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOAK_OF_FEAR)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_CLOAK_OF_FEAR)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_CLOAK_OF_FEAR)
	RandomNumGT(829,249)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_CLOAK_OF_FEAR)
END

// Mass Cause Light Wounds
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_MASS_CAUSE_LIGHT_WOUNDS)
	!HasItem("LIGHT",Myself)
	!HasItem("SERIOUS",Myself)
	!HasItem("CRITICAL",Myself)
	!HasItem("HARM",Myself)
	!HasItem("SLAYLIVE",Myself)
	RandomNumGT(830,249)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_MASS_CAUSE_LIGHT_WOUNDS)
END

// Cause Moderate Wounds
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_CAUSE_MODERATE_WOUNDS)
	RandomNumGT(831,249)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CAUSE_MODERATE_WOUNDS)
END

// Contagion
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_CONTAGION)
	RandomNumGT(832,250)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CONTAGION)
END

// Cause Disease
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_CAUSE_DISEASE)
	RandomNumGT(833,250)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CAUSE_DISEASE)
END

// Hold Person
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_HOLD_PERSON)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_HOLD_PERSON)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_HOLD_PERSON)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_HOLD_PERSON)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_HOLD_PERSON)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_HOLD_PERSON)
	RandomNumGT(834,250)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

// Cause Serious Wounds
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_CAUSE_SERIOUS_WOUNDS)
	!HasItem("LIGHT",Myself)
	!HasItem("SERIOUS",Myself)
	!HasItem("CRITICAL",Myself)
	!HasItem("HARM",Myself)
	!HasItem("SLAYLIVE",Myself)
	!HaveSpellRES("D5F1608")
	!HaveSpellRES("SPPR511")
	RandomNumGT(835,251)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_CAUSE_SERIOUS_WOUNDS)
END

// Doom
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOOM)
	RandomNumGT(836,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player1)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckSpellState(LastSeenBy(Myself),DOOM)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOOM)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOOM)
	RandomNumGT(836,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player2)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckSpellState(LastSeenBy(Myself),DOOM)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOOM)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOOM)
	RandomNumGT(836,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player3)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckSpellState(LastSeenBy(Myself),DOOM)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOOM)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOOM)
	RandomNumGT(836,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player4)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckSpellState(LastSeenBy(Myself),DOOM)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOOM)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOOM)
	RandomNumGT(836,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player5)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckSpellState(LastSeenBy(Myself),DOOM)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOOM)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_DOOM)
	RandomNumGT(836,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(Player6)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckSpellState(LastSeenBy(Myself),DOOM)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_DOOM)
END

// Command
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_COMMAND)
	RandomNumGT(837,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_COMMAND)
	RandomNumGT(837,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_COMMAND)
	RandomNumGT(837,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_COMMAND)
	RandomNumGT(837,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_COMMAND)
	RandomNumGT(837,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpell(CLERIC_COMMAND)
	RandomNumGT(837,251)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)
END

// Draw Upon Holy Might
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)
	!CheckStat(Myself,4,SCRIPTINGSTATE6)
	RandomNumGT(838,251)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)
END

// Cause Light Wounds
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_CAUSE_LIGHT_WOUNDS)
	!HasItem("LIGHT",Myself)
	!HasItem("SERIOUS",Myself)
	!HasItem("CRITICAL",Myself)
	!HasItem("HARM",Myself)
	!HasItem("SLAYLIVE",Myself)
	!HaveSpellRES("SPPR414")
	!HaveSpellRES("D5F1608")
	!HaveSpellRES("SPPR511")
	RandomNumGT(839,252)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,CLERIC_CAUSE_LIGHT_WOUNDS)
END

// Aid
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_AID)
	RandomNumGT(840,252)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_AID)
END

// Curse
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_CURSE)
	RandomNumGT(841,252)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CURSE)
END

// Spiritual Hammer
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpell(CLERIC_SPIRITUAL_HAMMER)
	RandomNumGT(842,253)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SPIRITUAL_HAMMER)
END

// Try to reposition to use ranged attack
IF
	CanEquipRanged()
	Range(NearestEnemyOf(Myself),4)
THEN
	RESPONSE #50
		SetInterrupt(FALSE)
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)
		SetInterrupt(TRUE)
	RESPONSE #50
		Continue()
END

// Attack NoCheck enemy
IF
	OR(4)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(4)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(4)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(4)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(4)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(4)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(4)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(4)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(4)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(4)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	CanEquipRanged()
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		Continue()
END

IF
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		Continue()
END

IF
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Sleep enemy
IF
	OR(4)
		!StateCheck(Player1,STATE_SLEEPING)
		CheckStatGT(Player1,0,SANCTUARY)
		StateCheck(Player1,STATE_REALLY_DEAD)
		!See(Player1)
	OR(4)
		!StateCheck(Player2,STATE_SLEEPING)
		CheckStatGT(Player2,0,SANCTUARY)
		StateCheck(Player2,STATE_REALLY_DEAD)
		!See(Player2)
	OR(4)
		!StateCheck(Player3,STATE_SLEEPING)
		CheckStatGT(Player3,0,SANCTUARY)
		StateCheck(Player3,STATE_REALLY_DEAD)
		!See(Player3)
	OR(4)
		!StateCheck(Player4,STATE_SLEEPING)
		CheckStatGT(Player4,0,SANCTUARY)
		StateCheck(Player4,STATE_REALLY_DEAD)
		!See(Player4)
	OR(4)
		!StateCheck(Player5,STATE_SLEEPING)
		CheckStatGT(Player5,0,SANCTUARY)
		StateCheck(Player5,STATE_REALLY_DEAD)
		!See(Player5)
	OR(4)
		!StateCheck(Player6,STATE_SLEEPING)
		CheckStatGT(Player6,0,SANCTUARY)
		StateCheck(Player6,STATE_REALLY_DEAD)
		!See(Player6)
THEN
	RESPONSE #100
		Continue()
END

IF
	CanEquipRanged()
	!Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipRanged()
		Continue()
END

IF
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		Continue()
END

IF
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Random walking (in combat) 
IF
	Global("JA_COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

