LAM load_secondary_types
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/common.tpa"
ACTION_IF FILE_EXISTS_IN_GAME ~BDGHOST.BCS~ BEGIN
	COMPILE ~%MOD_FOLDER%/lib/pnp-monster/undead/assets/BDGHOST.BAF~
END
ACTION_IF FILE_EXISTS_IN_GAME ~CB3579DK.BCS~ BEGIN
	COMPILE ~%MOD_FOLDER%/lib/pnp-monster/undead/assets/CB3579DK.BAF~
END
ACTION_IF FILE_EXISTS_IN_GAME ~DVDEATHK.BCS~ BEGIN
	COMPILE ~%MOD_FOLDER%/lib/pnp-monster/undead/assets/dvdeathk.BAF~
END
ACTION_IF FILE_EXISTS_IN_GAME ~DW#DEATH.BCS~ BEGIN
	COMPILE ~%MOD_FOLDER%/lib/pnp-monster/undead/assets/dw#death.BAF~
END
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/49.tpa" // Banshee
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4c.tpa" // Ghoul
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4b.tpa" // Ghast
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4d.tpa" // Ghoul Lord
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4e.tpa" // Mummy
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4f.tpa" // Greater Mummy
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/50.tpa" // Shadow
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/59.tpa" // Greater Shadow
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/5a.tpa" // Baneguard
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/5b.tpa" // Bonebat
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/51.tpa" // Skeleton
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/94.tpa" // Archer Skeleton
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/98.tpa" // Skeleton Monster
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/52.tpa" // Skeleton Warrior
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4a.tpa" // Death Knight
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/53.tpa" // Spectre
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/5d.tpa" // Ghost
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/54.tpa" // Wight
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/55.tpa" // Wraith
