///////////////////////////////////////////////////////////////////////
// Petrified NPC
// Fully healed if someone cast stone to flesh on it
///////////////////////////////////////////////////////////////////////
IF
  Global("stonetoflesh","LOCALS",0)
  !StateCheck(Myself,STATE_STONE_DEATH)
  HPGT(Myself,0)
THEN
  RESPONSE #100
    ApplySpellRES("JA#HEAL",Myself)
    SetGlobal("stonetoflesh","LOCALS",1)
END
