LAM load_secondary_types
// Flaming Greatsword
CREATE ITM "ja#i0f6"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10157)
	WRITE_LONG 0xc RESOLVE_STR_REF(@10157)
	WRITE_LONG 0x18 66
	WRITE_SHORT 0x1c 57
	WRITE_ASCII 0x22 ~S2~ #2
	WRITE_BYTE 0x31 93
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10640)
	WRITE_LONG 0x60 1
COPY_EXISTING ~ja#i0f6.itm~ ~override~
	READ_SHORT 0x68 abicount
	PATCH_IF (%abicount% > 0) BEGIN
		WRITE_BYTE 0x74 1
		WRITE_BYTE 0x7e 1
		WRITE_SHORT 0x80 2
		WRITE_BYTE 0x84 10
		WRITE_BYTE 0x88 6
		WRITE_BYTE 0x8a 2
		WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 40
	WRITE_SHORT 0xa0 40
	WRITE_SHORT 0xa2 20
	WRITE_LONG 0x98 1
	LPF ADD_EFFECT INT_VAR opcode=12 target=2 parameter2=524288 probability1=100 dicesize=6 dicenumber=1 END
	END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=67 parameter2=21 timing=2 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=67 parameter2=20 timing=2 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=12 parameter2=16 timing=2 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=8 target=1 global=1 parameter1=16384 parameter2=16 timing=2 duration=3 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=8 target=1 global=1 parameter1=16384 parameter2=21 timing=2 duration=3 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=8 target=1 global=1 parameter2=20 timing=2 duration=3 probability1=100 END

// Long Sword
CREATE ITM "ja#i1f6"
	WRITE_LONG 0x64 0x72
	INSERT_BYTES 0x72 0x38
	WRITE_SHORT 0x68 1
	WRITE_SHORT 0x72 1
	WRITE_LONG 0x6a 0xaa
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10158)
	WRITE_LONG 0xc RESOLVE_STR_REF(@10158)
	WRITE_LONG 0x18 64
	WRITE_SHORT 0x1c 20
	WRITE_ASCII 0x22 ~S1~ #2
	WRITE_BYTE 0x31 90
	WRITE_ASCII 0x3a ~ISW1H04~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10641)
	WRITE_LONG 0x60 1
COPY_EXISTING ~ja#i1f6.itm~ ~override~
	READ_SHORT 0x68 abicount
	PATCH_IF (%abicount% > 0) BEGIN
		WRITE_BYTE 0x74 1
		WRITE_ASCII 0x76 ~ISW1H04~ #8
		WRITE_BYTE 0x7e 1
		WRITE_SHORT 0x80 1
		WRITE_BYTE 0x84 5
		WRITE_BYTE 0x88 8
		WRITE_BYTE 0x8a 1
		WRITE_SHORT 0x8e 3
	WRITE_SHORT 0x9e 50
	WRITE_SHORT 0xa0 50
	WRITE_LONG 0x98 1
	END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=27 parameter2=21 timing=2 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=94 parameter2=20 timing=2 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=6 parameter2=16 timing=2 probability1=100 END

// Plate Mail
CREATE ITM "ja#i2f6"
	WRITE_LONG 0x64 0x72
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10159)
	WRITE_LONG 0xc RESOLVE_STR_REF(@10159)
	WRITE_SHORT 0x1c 2
	WRITE_ASCII 0x22 ~4A~ #2
	WRITE_ASCII 0x3a ~IPLAT01~ #8
COPY_EXISTING ~ja#i2f6.itm~ ~override~
	READ_SHORT 0x68 abicount
	PATCH_IF (%abicount% > 0) BEGIN
	END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=98 parameter2=5 timing=2 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=29 parameter2=4 timing=2 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=87 timing=2 probability1=100 END

// Helmet
CREATE ITM "ja#i3f6"
	WRITE_LONG 0x64 0x72
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10160)
	WRITE_LONG 0xc RESOLVE_STR_REF(@10160)
	WRITE_SHORT 0x1c 7
	WRITE_ASCII 0x22 ~H5~ #2
	WRITE_ASCII 0x3a ~ihelm10~ #8
COPY_EXISTING ~ja#i3f6.itm~ ~override~
	READ_SHORT 0x68 abicount
	PATCH_IF (%abicount% > 0) BEGIN
	END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=27 parameter2=53 timing=2 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=27 parameter2=52 timing=2 probability1=100 END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode=7 target=1 global=1 parameter1=27 parameter2=48 timing=2 probability1=100 END

INCLUDE "%MOD_FOLDER%/lib/pnp-monster/construct/f.tpa" // Helmed Horror
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/construct/8.tpa" // Battle Horror
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/construct/42.tpa" // Doom Sayer
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/construct/10.tpa" // Doom Guard
