IF
	Global("TrueForm","GLOBAL",0)
	AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		Polymorph(IC_CORNUGONSKI)
		SetGlobal("TrueForm","GLOBAL",1)
		Enemy()
		SetInterrupt(TRUE)
END

IF
	See([PC])
	NumTimesTalkedTo(0)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Dialogue([PC])
END

IF
	See([PC])
	Global("Rufie","GLOBAL",2)
	Range("rufie",3)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		Dialogue([PC])
		SetInterrupt(TRUE)
END

IF
	See([PC])
	Dead("rufie")
	!Global("Rufie","GLOBAL",3)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Dialogue([PC])
END

