///////////////////////////////////////////////////////////////////////
// Initialization script
// - sleep
// - initialization
// - cast long protection spells
///////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Just after resting, everything is reset and creature is healed
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("ja#PrepTimer","LOCALS")
	!Global("ja#initialize","LOCALS",0)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Rest()
		ForceSpellRES("spin124",Myself) // Shapeshifts Natural Form
		SelectWeaponAbility(SLOT_WEAPON,0)
		ApplySpellRES("JA#HEAL",Myself)
		SetGlobal("ja#initialize","LOCALS",0)
END


///////////////////////////////////////////////////////////////////////
// Initialize variables & timers
///////////////////////////////////////////////////////////////////////
IF
	Global("ja#initialize","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#initialize","LOCALS",1)
		SetGlobal("ja#disable_spellcasting","LOCALS",0)
		SetGlobal("ja#prepspells","LOCALS",0)
		SetGlobal("ja#nohealspells","LOCALS",0)
		SetGlobal("ja#buffdone","LOCALS",0)
		SetGlobal("ja#castsilence","LOCALS",0)
		SetGlobal("ja#polymorph","LOCALS",0)
		SetGlobal("ja#startcombat","LOCALS",0)
		SetGlobalTimer("ja#holymight","LOCALS",0)
		SetGlobalTimer("ja#chant","LOCALS",0)
		SetGlobalTimer("ja#PrepTimer","LOCALS",2400)
END


/////////////////////////////////////////////////////////////////////
// Priests always cast their long protection spells before combat
// (long = 1 turn per level, and in general more than 5 turns)
// Also some long duration weapons & summons
////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Ironskin
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpell(CLERIC_IRONSKIN)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,CLERIC_IRONSKIN)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Protection from evil 3 meters
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpell(CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,CLERIC_PROTECTION_FROM_EVIL_10_FOOT)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Protection from good 3 meters
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpellRES("CDPRGD10")
THEN
	RESPONSE #100
		ReallyForceSpellRES("CDPRGD10", Myself)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Chaotic commands
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpell(CLERIC_CHAOTIC_COMMANDS)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,CLERIC_CHAOTIC_COMMANDS)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Death ward
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpell(CLERIC_DEATH_WARD)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,CLERIC_DEATH_WARD)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Resist fear
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpell(CLERIC_REMOVE_FEAR)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,CLERIC_REMOVE_FEAR)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Aerial servant
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpell(CLERIC_AERIAL_SERVANT)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,CLERIC_AERIAL_SERVANT)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Earth elemental
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpellRES("sppr702")
THEN
	RESPONSE #100
		ReallyForceSpellRES("sppr702", Myself)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Fire elemental
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpell(CLERIC_CONJURE_FIRE_ELEMENTAL)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,CLERIC_CONJURE_FIRE_ELEMENTAL)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Air elemental
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpellRES("NMCONAIR")
THEN
	RESPONSE #100
		ReallyForceSpellRES("NMCONAIR", Myself)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Animate dead
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
	HaveSpell(CLERIC_ANIMATE_DEAD)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,CLERIC_ANIMATE_DEAD)
		Continue()
END


/////////////////////////////////////////////////////////////////////
// End of long protection spells 
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#prepspells","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#prepspells","LOCALS",1)
END


