///////////////////////////////////////////////////////////////////////
// Add kit special abilities (not added for npc)
///////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Cavalier
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#kitabilities","LOCALS",0)
	Kit(Myself,CAVALIER)
THEN
	RESPONSE #100
		SetGlobal("ja#kitabilities","LOCALS",1)
		ReallyForceSpellRES("spcl221",Myself)
END


/////////////////////////////////////////////////////////////////////
// Inquisitor
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#kitabilities","LOCALS",0)
	Kit(Myself,INQUISITOR)
THEN
	RESPONSE #100
		SetGlobal("ja#kitabilities","LOCALS",1)
		ReallyForceSpellRES("spcl233b",Myself)
END


/////////////////////////////////////////////////////////////////////
// Xvim
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#kitabilities","LOCALS",0)
	Kit(Myself,CDXvim)
THEN
	RESPONSE #100
		SetGlobal("ja#kitabilities","LOCALS",1)
		ReallyForceSpellRES("cdxvfear",Myself)
END


/////////////////////////////////////////////////////////////////////
// Deathbringer
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#kitabilities","LOCALS",0)
	Kit(Myself,IK_DEATHBRINGER)
THEN
	RESPONSE #100
		SetGlobal("ja#kitabilities","LOCALS",1)
		ReallyForceSpellRES("ikdb1",Myself)
END


/////////////////////////////////////////////////////////////////////
// Monk
/////////////////////////////////////////////////////////////////////

// Level 5 Immunity to all diseases, and cannot be Slowed or Hasted.
IF
	Global("ja#kitabilities","LOCALS",0)
	Class(Myself,20)
	CheckStatGT(Myself,4,LEVEL)
THEN
	RESPONSE #100
		SetGlobal("ja#kitabilities","LOCALS",1)
		ReallyForceSpellRES("SPCL814",Myself)
		Continue()
END

// Level 9 Immune to charm.
IF
	Global("ja#kitabilities","LOCALS",0)
	Class(Myself,20)
	CheckStatGT(Myself,8,LEVEL)
THEN
	RESPONSE #100
		SetGlobal("ja#kitabilities","LOCALS",1)
		ReallyForceSpellRES("SPCL817",Myself)
		Continue()
END

// Level 11 Immune to poison.
IF
	Global("ja#kitabilities","LOCALS",0)
	Class(Myself,20)
	CheckStatGT(Myself,10,LEVEL)
THEN
	RESPONSE #100
		SetGlobal("ja#kitabilities","LOCALS",1)
		ReallyForceSpellRES("SPCL818",Myself)
		Continue()
END

// Level 20 Immune to non-magical weapons
IF
	Global("ja#kitabilities","LOCALS",0)
	Class(Myself,20)
	CheckStatGT(Myself,19,LEVEL)
THEN
	RESPONSE #100
		SetGlobal("ja#kitabilities","LOCALS",1)
		ReallyForceSpellRES("SPCL821",Myself)
		Continue()
END
