/////////////////////////////////////////////////////////////////////
// If all buffing spells are done, combat can start
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#buffdone","LOCALS",0)
	!GlobalTimerNotExpired("ja#confirm","LOCALS")
	!GlobalTimerNotExpired("ja#cast","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#confirm","LOCALS",2)
END

IF
	Global("ja#buffdone","LOCALS",0)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	GlobalTimerNotExpired("ja#confirm","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("ja#buffdone","LOCALS",1)
END

IF
	Global("ja#buffdone","LOCALS",0)
	OR(2)
		!StateCheck(Myself,STATE_INVISIBLE)
		!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!HaveSpell(WIZARD_INVISIBILITY)
	!HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
	!HaveSpell(WIZARD_SHADOW_DOOR)
	!HaveSpell(WIZARD_MISLEAD)
	!HaveSpell(WIZARD_MASS_INVISIBILITY)
THEN
	RESPONSE #100
		SetGlobal("ja#buffdone","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Not ready to attack, wait
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#buffdone","LOCALS",0)
THEN
	RESPONSE #100
		NoAction()
END
	

/////////////////////////////////////////////////////////////////////
// Now, it's time to kill things
// Priorities are:
//   Remove magic on buffed people
//   Power word
//   Charm/dominate the best fighter
//   Destroy mage's defense
//   Disable spells
//   Damage spells
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Find a target that has something to dispel
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(SixthNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(SixthNearestEnemyOf(Myself))
		CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(FifthNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(FifthNearestEnemyOf(Myself))
		CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)	
		CheckStatGT(FourthNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(FourthNearestEnemyOf(Myself))
		CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(ThirdNearestEnemyOf(Myself),18,STR)	
		HasImmunityEffects(ThirdNearestEnemyOf(Myself))	
		CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(SecondNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(SecondNearestEnemyOf(Myself))
		CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)	
		CheckStatGT(NearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(NearestEnemyOf(Myself))
		CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Remove magic
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_DISPEL_MAGIC)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(LastSeenBy(Myself),18,STR)
		HasImmunityEffects(LastSeenBy(Myself))
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END


/////////////////////////////////////////////////////////////////////
// Breach
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_BREACH)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(4)
		HasImmunityEffects(LastSeenBy(Myself))
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BREACH)
END


/////////////////////////////////////////////////////////////////////
// Lower resistances
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_LOWER_RESISTANCE)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END


/////////////////////////////////////////////////////////////////////
// Begin of block:
// Power word kill
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	HPLT(SixthNearestEnemyOf(Myself),60)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	HPLT(FifthNearestEnemyOf(Myself),60)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	HPLT(FourthNearestEnemyOf(Myself),60)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	HPLT(ThirdNearestEnemyOf(Myself),60)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	HPLT(SecondNearestEnemyOf(Myself),60)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	HPLT(NearestEnemyOf(Myself),60)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_POWER_WORD_KILL)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	HPLT(LastSeenBy(Myself),60)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
END
/////////////////////////////////////////////////////////////////////
// End of block:
// Power word kill
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Begin of block:
// Power word blind
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(SixthNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(SixthNearestEnemyOf(Myself),PALADIN_ALL)
		Class(SixthNearestEnemyOf(Myself),RANGER_ALL)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(FifthNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(FifthNearestEnemyOf(Myself),PALADIN_ALL)
		Class(FifthNearestEnemyOf(Myself),RANGER_ALL)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(FourthNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(FourthNearestEnemyOf(Myself),PALADIN_ALL)
		Class(FourthNearestEnemyOf(Myself),RANGER_ALL)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(ThirdNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(ThirdNearestEnemyOf(Myself),PALADIN_ALL)
		Class(ThirdNearestEnemyOf(Myself),RANGER_ALL)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(SecondNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(SecondNearestEnemyOf(Myself),PALADIN_ALL)
		Class(SecondNearestEnemyOf(Myself),RANGER_ALL)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(NearestEnemyOf(Myself),FIGHTER_ALL)
		Class(NearestEnemyOf(Myself),PALADIN_ALL)
		Class(NearestEnemyOf(Myself),RANGER_ALL)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_POWER_WORD_BLIND)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	OR(3)
		Class(LastSeenBy(Myself),FIGHTER_ALL)
		Class(LastSeenBy(Myself),PALADIN_ALL)
		Class(LastSeenBy(Myself),RANGER_ALL)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
END
/////////////////////////////////////////////////////////////////////
// End of block:
// Power word blind
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Begin of block:
// Power word stun
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(SixthNearestEnemyOf(Myself),30)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(FifthNearestEnemyOf(Myself),30)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(FourthNearestEnemyOf(Myself),30)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(ThirdNearestEnemyOf(Myself),30)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(SecondNearestEnemyOf(Myself),30)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(NearestEnemyOf(Myself),30)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_POWER_WORD_STUN)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage	
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(LastSeenBy(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
END
/////////////////////////////////////////////////////////////////////
// End of block:
// Power word stun
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Begin of block:
// Power word silence
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(SixthNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(SixthNearestEnemyOf(Myself),DRUID_ALL)
		Class(SixthNearestEnemyOf(Myself),BARD_ALL)
		Class(SixthNearestEnemyOf(Myself),CLERIC_ALL)
		Class(SixthNearestEnemyOf(Myself),MAGE_ALL)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(FifthNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(FifthNearestEnemyOf(Myself),DRUID_ALL)
		Class(FifthNearestEnemyOf(Myself),BARD_ALL)
		Class(FifthNearestEnemyOf(Myself),CLERIC_ALL)
		Class(FifthNearestEnemyOf(Myself),MAGE_ALL)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(FourthNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(FourthNearestEnemyOf(Myself),DRUID_ALL)
		Class(FourthNearestEnemyOf(Myself),BARD_ALL)
		Class(FourthNearestEnemyOf(Myself),CLERIC_ALL)
		Class(FourthNearestEnemyOf(Myself),MAGE_ALL)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(ThirdNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(ThirdNearestEnemyOf(Myself),DRUID_ALL)
		Class(ThirdNearestEnemyOf(Myself),BARD_ALL)
		Class(ThirdNearestEnemyOf(Myself),CLERIC_ALL)
		Class(ThirdNearestEnemyOf(Myself),MAGE_ALL)	
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(SecondNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(SecondNearestEnemyOf(Myself),DRUID_ALL)
		Class(SecondNearestEnemyOf(Myself),BARD_ALL)
		Class(SecondNearestEnemyOf(Myself),CLERIC_ALL)
		Class(SecondNearestEnemyOf(Myself),MAGE_ALL)	
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(NearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(NearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(NearestEnemyOf(Myself),DRUID_ALL)
		Class(NearestEnemyOf(Myself),BARD_ALL)
		Class(NearestEnemyOf(Myself),CLERIC_ALL)
		Class(NearestEnemyOf(Myself),MAGE_ALL)	
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_POWER_WORD_SILENCE)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	OR(4)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),MAGE_ALL)	
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)
END
/////////////////////////////////////////////////////////////////////
// End of block:
// Power word silence
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Begin of block:
// Power word sleep
/////////////////////////////////////////////////////////////////////
IF
	!Race(SixthNearestEnemyOf(Myself),ELF)
	!CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(SixthNearestEnemyOf(Myself),21)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(FifthNearestEnemyOf(Myself),ELF)
	!CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(FifthNearestEnemyOf(Myself),21)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(FourthNearestEnemyOf(Myself),ELF)
	!CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(FourthNearestEnemyOf(Myself),21)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(ThirdNearestEnemyOf(Myself),ELF)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(ThirdNearestEnemyOf(Myself),21)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(SecondNearestEnemyOf(Myself),ELF)
	!CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(SecondNearestEnemyOf(Myself),21)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(NearestEnemyOf(Myself),ELF)
	!CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(NearestEnemyOf(Myself),21)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_POWER_WORD_SLEEP)
	!Race(LastSeenBy(Myself),ELF)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	HPLT(LastSeenBy(Myself),21)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SLEEP)
END
/////////////////////////////////////////////////////////////////////
// End of block:
// Power word sleep
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Find a fighter to charm/dominate
/////////////////////////////////////////////////////////////////////
IF
	!Race(SixthNearestEnemyOf(Myself),ELF)
	!CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(SixthNearestEnemyOf(Myself),30)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(SixthNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(SixthNearestEnemyOf(Myself),PALADIN_ALL)
		Class(SixthNearestEnemyOf(Myself),RANGER_ALL)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(FifthNearestEnemyOf(Myself),ELF)
	!CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(FifthNearestEnemyOf(Myself),30)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(FifthNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(FifthNearestEnemyOf(Myself),PALADIN_ALL)
		Class(FifthNearestEnemyOf(Myself),RANGER_ALL)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(FourthNearestEnemyOf(Myself),ELF)
	!CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(FourthNearestEnemyOf(Myself),30)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(FourthNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(FourthNearestEnemyOf(Myself),PALADIN_ALL)
		Class(FourthNearestEnemyOf(Myself),RANGER_ALL)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(ThirdNearestEnemyOf(Myself),ELF)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(ThirdNearestEnemyOf(Myself),30)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(ThirdNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(ThirdNearestEnemyOf(Myself),PALADIN_ALL)
		Class(ThirdNearestEnemyOf(Myself),RANGER_ALL)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(SecondNearestEnemyOf(Myself),ELF)
	!CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(SecondNearestEnemyOf(Myself),30)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(SecondNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(SecondNearestEnemyOf(Myself),PALADIN_ALL)
		Class(SecondNearestEnemyOf(Myself),RANGER_ALL)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(NearestEnemyOf(Myself),ELF)
	!CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(NearestEnemyOf(Myself),30)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(NearestEnemyOf(Myself),FIGHTER_ALL)
		Class(NearestEnemyOf(Myself),PALADIN_ALL)
		Class(NearestEnemyOf(Myself),RANGER_ALL)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Great Malison before trying a charm spell
/////////////////////////////////////////////////////////////////////	
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_GREATER_MALISON)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_GREATER_MALISON)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END


/////////////////////////////////////////////////////////////////////
// Domination
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_DOMINATION)
	!Race(LastSeenBy(Myself),ELF)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	HPPercentGT(LastSeenBy(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	OR(3)
		Class(LastSeenBy(Myself),FIGHTER_ALL)
		Class(LastSeenBy(Myself),PALADIN_ALL)
		Class(LastSeenBy(Myself),RANGER_ALL)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_DOMINATION)
END


IF
	!Race(SixthNearestEnemyOf(Myself),ELF)
	!CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(SixthNearestEnemyOf(Myself),30)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(SixthNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(SixthNearestEnemyOf(Myself),PALADIN_ALL)
		Class(SixthNearestEnemyOf(Myself),RANGER_ALL)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(FifthNearestEnemyOf(Myself),ELF)
	!CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(FifthNearestEnemyOf(Myself),30)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(FifthNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(FifthNearestEnemyOf(Myself),PALADIN_ALL)
		Class(FifthNearestEnemyOf(Myself),RANGER_ALL)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(FourthNearestEnemyOf(Myself),ELF)
	!CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(FourthNearestEnemyOf(Myself),30)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(FourthNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(FourthNearestEnemyOf(Myself),PALADIN_ALL)
		Class(FourthNearestEnemyOf(Myself),RANGER_ALL)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(ThirdNearestEnemyOf(Myself),ELF)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(ThirdNearestEnemyOf(Myself),30)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(ThirdNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(ThirdNearestEnemyOf(Myself),PALADIN_ALL)
		Class(ThirdNearestEnemyOf(Myself),RANGER_ALL)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(SecondNearestEnemyOf(Myself),ELF)
	!CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(SecondNearestEnemyOf(Myself),30)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(SecondNearestEnemyOf(Myself),FIGHTER_ALL)
		Class(SecondNearestEnemyOf(Myself),PALADIN_ALL)
		Class(SecondNearestEnemyOf(Myself),RANGER_ALL)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(NearestEnemyOf(Myself),ELF)
	!CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(NearestEnemyOf(Myself),30)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		Class(NearestEnemyOf(Myself),FIGHTER_ALL)
		Class(NearestEnemyOf(Myself),PALADIN_ALL)
		Class(NearestEnemyOf(Myself),RANGER_ALL)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Dire charm
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_DIRE_CHARM)
	!Race(LastSeenBy(Myself),ELF)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	HPPercentGT(LastSeenBy(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	OR(3)
		Class(LastSeenBy(Myself),FIGHTER_ALL)
		Class(LastSeenBy(Myself),PALADIN_ALL)
		Class(LastSeenBy(Myself),RANGER_ALL)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_DIRE_CHARM)
END


/////////////////////////////////////////////////////////////////////
// Charm person
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_CHARM_PERSON)	
	!Race(LastSeenBy(Myself),ELF)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	HPPercentGT(LastSeenBy(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	OR(3)
		Class(LastSeenBy(Myself),FIGHTER_ALL)
		Class(LastSeenBy(Myself),PALADIN_ALL)
		Class(LastSeenBy(Myself),RANGER_ALL)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHARM_PERSON)
END


/////////////////////////////////////////////////////////////////////
// *********************  Disabling spells *********************** //
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Level 6+ spells
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Symbol fear
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SYMBOL_FEAR)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)
END


/////////////////////////////////////////////////////////////////////
// Bigbys Clenched Fist
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)
END


/////////////////////////////////////////////////////////////////////
// Primastic Spray
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_PRISMATIC_SPRAY)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_PRISMATIC_SPRAY)
END


/////////////////////////////////////////////////////////////////////
// Sphere of chaos
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SPHERE_OF_CHAOS)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPHERE_OF_CHAOS)
END


/////////////////////////////////////////////////////////////////////
// Finger of death
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_FINGER_OF_DEATH)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
END


/////////////////////////////////////////////////////////////////////
// Death spells
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_DEATH_SPELL)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
END


/////////////////////////////////////////////////////////////////////
// Disintegrate
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_DISINTEGRATE)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_DISINTEGRATE)
END


/////////////////////////////////////////////////////////////////////
// Flesh to stone
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_FLESH_TO_STONE)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FLESH_TO_STONE)
END


/////////////////////////////////////////////////////////////////////
// Death fog
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_DEATH_FOG)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_DEATH_FOG)
END


/////////////////////////////////////////////////////////////////////
// Level 4-5 spells
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Great Malison before trying anything else
/////////////////////////////////////////////////////////////////////	
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_GREATER_MALISON)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_GREATER_MALISON)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END


/////////////////////////////////////////////////////////////////////
// Cloud kill
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_CLOUDKILL)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
END


/////////////////////////////////////////////////////////////////////
// Chaos
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_CHAOS)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)
END


/////////////////////////////////////////////////////////////////////
// Feeblemind
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_FEEBLEMIND)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)
END


/////////////////////////////////////////////////////////////////////
// Hold monsters
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_HOLD_MONSTER)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_HOLD_MONSTER)
END


/////////////////////////////////////////////////////////////////////
// Emotion
/////////////////////////////////////////////////////////////////////	
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_EMOTION_HOPELESSNESS)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END


/////////////////////////////////////////////////////////////////////
// Teleport field
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_TELEPORT_FIELD)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_TELEPORT_FIELD)
END


/////////////////////////////////////////////////////////////////////
// Level 3- spells
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Hold person
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_HOLD_PERSON)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_HOLD_PERSON)
END


/////////////////////////////////////////////////////////////////////
// Web
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_WEB)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	OR(2)
		CheckStat(Myself,1,MINORGLOBE)
		HasItemEquiped("_RING09",Myself) // Ring of Free Action
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_WEB)
END


/////////////////////////////////////////////////////////////////////
// Slow
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SLOW)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)
END


/////////////////////////////////////////////////////////////////////
// Stinking cloud
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_STINKING_CLOUD)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	OR(2)
		CheckStat(Myself,1,MINORGLOBE)
		CheckStatGT(Myself,99,RESISTPOISON)
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)
END


/////////////////////////////////////////////////////////////////////
// Horror
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_HORROR)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_HORROR)
END


/////////////////////////////////////////////////////////////////////
// Glitterdust
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_GLITTERDUST)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_GLITTERDUST)
END


/////////////////////////////////////////////////////////////////////
// Sleep
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SLEEP)
	!Race(LastSeenBy(Myself),ELF)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SLEEP)
END


/////////////////////////////////////////////////////////////////////
// Spook
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SPOOK)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SPOOK)
END


/////////////////////////////////////////////////////////////////////
// Color spray
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_COLOR_SPRAY)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_COLOR_SPRAY)
END


/////////////////////////////////////////////////////////////////////
// Wand of paralyzation
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HasItemEquiped("_WAND04",Myself) // Wand of Paralyzation
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	RandomNum(4,1) // 25% to use
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		UseItem("_WAND04",LastSeenBy(Myself)) // Wand of Paralyzation
END


/////////////////////////////////////////////////////////////////////
// Wand of fear
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HasItemEquiped("_WAND02",Myself) // Wand of Fear
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4) // Rage
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	RandomNum(4,1) // 25% to use
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		UseItem("_WAND02",LastSeenBy(Myself)) // Wand of Fear
END


/////////////////////////////////////////////////////////////////////
// Ray of enfeeblement
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_RAY_OF_ENFEEBLEMENT)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	OR(3)
		Class(LastSeenBy(Myself),FIGHTER_ALL)
		Class(LastSeenBy(Myself),PALADIN_ALL)
		Class(LastSeenBy(Myself),RANGER_ALL)	
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_RAY_OF_ENFEEBLEMENT)
END


/////////////////////////////////////////////////////////////////////
// Blindness
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_BLINDNESS)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BLINDNESS)
END


/////////////////////////////////////////////////////////////////////
// *********************  Summoning spells *********************** //
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Planatar
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SUMMON_PLANATAR_GOOD)
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_SUMMON_PLANATAR_GOOD)
END


/////////////////////////////////////////////////////////////////////
// Mordenkainen sword
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MORDENKAINENS_SWORD)
	RandomNum(4,1) // 25% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_MORDENKAINENS_SWORD)
END


/////////////////////////////////////////////////////////////////////
// Hakeashar
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SUMMON_HAKEASHAR)
	RandomNum(4,1) // 25% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_SUMMON_HAKEASHAR)
END


/////////////////////////////////////////////////////////////////////
// Djinni
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SUMMON_DJINNI)
	RandomNum(4,1) // 25% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_SUMMON_DJINNI)
END


/////////////////////////////////////////////////////////////////////
// Efreeti
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SUMMON_EFREET)
	RandomNum(4,1) // 25% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_SUMMON_EFREET)
END


/////////////////////////////////////////////////////////////////////
// Wyvern
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_WYVERN_CALL)
	RandomNum(4,1) // 25% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_WYVERN_CALL)
END


/////////////////////////////////////////////////////////////////////
// Squeleton
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_ANIMATE_DEAD)
	RandomNum(4,1) // 25% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_ANIMATE_DEAD)
END


/////////////////////////////////////////////////////////////////////
// Monsters (3)
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MONSTER_SUMMONING_3)
	RandomNum(4,1) // 25% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_MONSTER_SUMMONING_3)
END


/////////////////////////////////////////////////////////////////////
// Spider
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SPIDER_SPAWN)
	RandomNum(4,1) // 25% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_SPIDER_SPAWN)
END


/////////////////////////////////////////////////////////////////////
// Monsters (2)
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MONSTER_SUMMONING_2)
	RandomNum(4,1) // 25% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_MONSTER_SUMMONING_2)
END


/////////////////////////////////////////////////////////////////////
// Monsters (1)
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MONSTER_SUMMONING_1)
	RandomNum(4,1) // 25% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(NearestEnemyOf(Myself),WIZARD_MONSTER_SUMMONING_1)
END


/////////////////////////////////////////////////////////////////////
// Summoning weapons
/////////////////////////////////////////////////////////////////////	


/////////////////////////////////////////////////////////////////////
// Energy Blade
/////////////////////////////////////////////////////////////////////	
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("spwi920")
	!HasItem("chillt",Myself) // Chill touch
	!HasItem("ghoult",Myself) // Ghoul touch
	!HasItem("melfmet",Myself) // Melf's Minute Meteor
	!HasItem("phanblad",Myself) // Phantom Blade
	!HasItem("eneblade",Myself) // Energy Blade
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("spwi920", Myself)
END


/////////////////////////////////////////////////////////////////////
// Melf meteor
/////////////////////////////////////////////////////////////////////	
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MELF_METEOR)
	!HasItem("chillt",Myself) // Chill touch
	!HasItem("ghoult",Myself) // Ghoul touch
	!HasItem("melfmet",Myself) // Melf's Minute Meteor
	!HasItem("phanblad",Myself) // Phantom Blade
	!HasItem("eneblade",Myself) // Energy Blade
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_MELF_METEOR)
END


/////////////////////////////////////////////////////////////////////
// Phantom blade
/////////////////////////////////////////////////////////////////////	
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_PHANTOM_BLADE)
	!HasItem("chillt",Myself) // Chill touch
	!HasItem("ghoult",Myself) // Ghoul touch
	!HasItem("melfmet",Myself) // Melf's Minute Meteor
	!HasItem("phanblad",Myself) // Phantom Blade
	!HasItem("eneblade",Myself) // Energy Blade
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_PHANTOM_BLADE)
END


/////////////////////////////////////////////////////////////////////
// Ghoul touch
/////////////////////////////////////////////////////////////////////	
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_GHOUL_TOUCH)
	!HasItem("chillt",Myself) // Chill touch
	!HasItem("ghoult",Myself) // Ghoul touch
	!HasItem("melfmet",Myself) // Melf's Minute Meteor
	!HasItem("phanblad",Myself) // Phantom Blade
	!HasItem("eneblade",Myself) // Energy Blade
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_GHOUL_TOUCH)
END


/////////////////////////////////////////////////////////////////////
// Chill touch
/////////////////////////////////////////////////////////////////////	
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_CHILL_TOUCH)
	!HasItem("chillt",Myself) // Chill touch
	!HasItem("ghoult",Myself) // Ghoul touch
	!HasItem("melfmet",Myself) // Melf's Minute Meteor
	!HasItem("phanblad",Myself) // Phantom Blade
	!HasItem("eneblade",Myself) // Energy Blade
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_CHILL_TOUCH)
END


/////////////////////////////////////////////////////////////////////
// *********************  Damaging spells ************************ //
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Level 6+ spells
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Dragon breath
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_DRAGONS_BREATH)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(5,1) // 80% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END


/////////////////////////////////////////////////////////////////////
// Abi dalzims horrid wilting
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END


/////////////////////////////////////////////////////////////////////
// Incendiary cloud
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_INCENDIARY_CLOUD)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_INCENDIARY_CLOUD)
END


/////////////////////////////////////////////////////////////////////
// Delayed blast fireball
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_DELAYED_BLAST_FIREBALL)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_DELAYED_BLAST_FIREBALL)
END


/////////////////////////////////////////////////////////////////////
// Chain Lightning
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_CHAIN_LIGHTNING)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END


/////////////////////////////////////////////////////////////////////
// Wand of frost
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HasItemEquiped("_WAND06",Myself) // Wand of Frost
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	RandomNum(4,1) // 25% to use
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		UseItem("_WAND06",LastSeenBy(Myself)) // Wand of Frost
END


/////////////////////////////////////////////////////////////////////
// Level 4-5 spells
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Sunfire
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SUN_FIRE)
	Range(LastSeenBy(Myself),10)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_SUN_FIRE)
END


/////////////////////////////////////////////////////////////////////
// Cone of cold
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_CONE_OF_COLD)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONE_OF_COLD)
END


/////////////////////////////////////////////////////////////////////
// Ice storm
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_ICE_STORM)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	OR(2)
		CheckStatGT(Myself,99,RESISTCOLD)
		CheckStat(Myself,6,SCRIPTINGSTATE6)	// Immunity evocation
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_ICE_STORM)
END


/////////////////////////////////////////////////////////////////////
// Polymorph other
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_POLYMORPH_OTHER)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_POLYMORPH_OTHER)
END


/////////////////////////////////////////////////////////////////////
// Contagion
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_CONTAGION)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CONTAGION)
END


/////////////////////////////////////////////////////////////////////
// Level 3- spells
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Skull trap
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SKULL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	OR(2)
		CheckStatGT(Myself,50,MAGICDAMAGERESISTANCE)
		CheckStat(Myself,1,MINORGLOBE)
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SKULL_TRAP)
END


/////////////////////////////////////////////////////////////////////
// Fireball
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_FIREBALL)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	OR(2)
		CheckStatGT(Myself,70,RESISTFIRE)
		CheckStat(Myself,1,MINORGLOBE)
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FIREBALL)
END


/////////////////////////////////////////////////////////////////////
// Lightning bolt
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_LIGHTNING_BOLT)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	OR(2)
		CheckStatGT(Myself,99,RESISTELECTRICITY)
		CheckStat(Myself,1,MINORGLOBE)
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)
END


/////////////////////////////////////////////////////////////////////
// Vampiric touch
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_VAMPIRIC_TOUCH)
	Range(LastSeenBy(Myself),10)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)
END


/////////////////////////////////////////////////////////////////////
// Flame arrow
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_FLAME_ARROW)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END


/////////////////////////////////////////////////////////////////////
// Agannazar scorcher
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_AGANNAZAR_SCORCHER)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_AGANNAZAR_SCORCHER)
		Wait(6)
END


/////////////////////////////////////////////////////////////////////
// Magic missile
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MAGIC_MISSILE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3) // Wizard shield
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END


/////////////////////////////////////////////////////////////////////
// Melf acid arrow
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MELF_ACID_ARROW)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END


/////////////////////////////////////////////////////////////////////
// Chromatic orb
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_CHROMATIC_ORB)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1)  // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)
END


/////////////////////////////////////////////////////////////////////
// Burning hands
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_BURNING_HANDS)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_BURNING_HANDS)
END


/////////////////////////////////////////////////////////////////////
// Shocking grasp
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SHOCKING_GRASP)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_SHOCKING_GRASP)
END


/////////////////////////////////////////////////////////////////////
// Larloch minor drain
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
END


/////////////////////////////////////////////////////////////////////
// Polymorph self
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#polymorph","LOCALS",0)
	!GlobalTimerNotExpired("ja#confirm","LOCALS")
	!GlobalTimerNotExpired("ja#cast","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#confirm","LOCALS",6)
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	GlobalTimerNotExpired("ja#confirm","LOCALS")
	CheckStat(Myself,0,POLYMORPH_SELF) 
	HaveSpell(WIZARD_POLYMORPH_SELF)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_POLYMORPH_SELF)
		SetGlobal("ja#polymorph","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Polymorph forms
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	!GlobalTimerNotExpired("ja#polyform","LOCALS")
	CheckStat(Myself,1,POLYMORPH_SELF)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#polyform","LOCALS",24)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spwi495",Myself)  // Sword spider
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
	RESPONSE #100
		SetGlobalTimer("ja#polyform","LOCALS",24)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spwi494",Myself)  // Ogre
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
	RESPONSE #100
		SetGlobalTimer("ja#polyform","LOCALS",24)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spwi497",Myself)  // Brown bear
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
	RESPONSE #100
		SetGlobalTimer("ja#polyform","LOCALS",24)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spwi496",Myself)  // Mustard jelly
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
	RESPONSE #100
		SetGlobalTimer("ja#polyform","LOCALS",24)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spwi499",Myself)  // Dread Wolf
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
	RESPONSE #0 // Disable
		SetGlobalTimer("ja#polyform","LOCALS",24)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spwi490",Myself)  // Natural form
		SetGlobal("ja#disable_spellcasting","LOCALS",0)
END

