LAM load_secondary_types
// Improved stream of frost
COPY_EXISTING "CONECOLD.pro" ~override/jas0f3.pro~
	READ_SHORT 0x08 type
	PATCH_IF (%type% = 1) BEGIN
		INSERT_BYTES 0x100 0x100
	END
	WRITE_LONG 0x200 80
	WRITE_SHORT 0x204 180
	WRITE_SHORT 0x206 180
ADD_PROJECTILE ~override/jas0f3.pro~ ~Improved stream of frost~

CREATE SPL "jas0f3"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~jas0f3.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10142)
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 10
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPWI523C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10143)
	LPF ADD_SPELL_HEADER INT_VAR type=2 location=4 target=4 range=10 projectile=(IDS_OF_SYMBOL (~projectl~ ~jas0f3~)) + 1 STR_VAR icon="SPWI523B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=12 target=2 power=1 parameter2=131072 timing=1 probability1=100 dicesize=4 dicenumber=6 savingthrow=2 special=256 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=175 target=2 power=1 parameter1=IDS_OF_SYMBOL (~EA~ ~ANYONE~) parameter2=2 duration=60 probability1=100 savingthrow=4 savebonus="-2" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=142 target=2 power=1 parameter2=13 duration=60 probability1=100 savingthrow=4 savebonus="-2" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=50 target=2 power=1 parameter1="-2786560" parameter2=1310720 timing=1 probability1=100 savingthrow=4 savebonus="-2" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=141 target=2 power=1 parameter2=6 timing=1 probability1=100 savingthrow=4 savebonus="-2" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=174 target=2 power=1 timing=1 probability1=100 savingthrow=4 savebonus="-2" STR_VAR resource="MISC_04A" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=174 target=2 power=1 timing=4 duration=60 probability1=100 savingthrow=4 savebonus="-2" STR_VAR resource="EFF_E03" END
	LPF CHANGE_SPELL INT_VAR    renew=3 END
	
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/bear/4.tpa" // Black Bear
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/bear/5.tpa" // Brown Bear
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/bear/6.tpa" // Cave Bear
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/bear/60.tpa" // Grizzly Bear
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/bear/7.tpa" // Polar Bear
