
// The Major and Minor Globes of Invulnerability should be dispellable by Dispel Magic, as per the spell's description and per PnP rules
LAF get_minorGlobeOfInvulnerability_resources RET_ARRAY array1=resources END
LAF get_globeOfInvulnerability_resources RET_ARRAY array2=resources END
LAF MERGE_ARRAYS STR_VAR array1 array2 RET_ARRAY array END
ACTION_PHP_EACH array AS _ => file BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%file%.spl~ BEGIN
    COPY_EXISTING ~%file%.spl~ ~override~
      PATCH_IF (%SOURCE_SIZE% > 0x71) THEN BEGIN
        READ_LONG  0x64 "abil_off"
        READ_SHORT 0x68 "abil_num"
        READ_LONG  0x6a "fx_off"
        FOR (index = 0 ; index < abil_num ; index = index + 1 ) BEGIN              // cycle through abilities
          READ_SHORT  ("%abil_off%" + 0x1e + (0x28 * "%index%")) "abil_fx_num"
          READ_SHORT  ("%abil_off%" + 0x20 + (0x28 * "%index%")) "abil_fx_idx"
          FOR (index2 = 0 ; index2 < abil_fx_num ; index2 = index2 + 1) BEGIN
            READ_BYTE ("%fx_off%" + 0x0d + (0x30 * ("%index2%" + "%abil_fx_idx%"))) "dispel"
            PATCH_IF NOT ("%dispel%" = 3) BEGIN
              WRITE_BYTE ("%fx_off%" + 0x0d + (0x30 * ("%index2%" + "%abil_fx_idx%"))) 3 // make each effect dispellable and let it bypasses magic resistance
            END      
          END
        END
        LPF FJ_SPL_ITM_REINDEX END
      END
    BUT_ONLY_IF_IT_CHANGES
  END
END
