export interface SpellCount {
  level: number;
  count: number;
}

export const ClericSpellTable: { level: number; spells: SpellCount[] }[] = [
  { level: 1, spells: [{ level: 1, count: 1 }] },
  { level: 2, spells: [{ level: 1, count: 2 }] },
  { level: 3, spells: [{ level: 1, count: 2 }, { level: 2, count: 1 }] },
  { level: 4, spells: [{ level: 1, count: 3 }, { level: 2, count: 2 }] },
  { level: 5, spells: [{ level: 1, count: 3 }, { level: 2, count: 3 }, { level: 3, count: 1 }] },
  { level: 6, spells: [{ level: 1, count: 3 }, { level: 2, count: 3 }, { level: 3, count: 2 }] },
  { level: 7, spells: [{ level: 1, count: 3 }, { level: 2, count: 3 }, { level: 3, count: 2 }, { level: 4, count: 1 }] },
  { level: 8, spells: [{ level: 1, count: 3 }, { level: 2, count: 3 }, { level: 3, count: 3 }, { level: 4, count: 2 }] },
  { level: 9, spells: [{ level: 1, count: 4 }, { level: 2, count: 4 }, { level: 3, count: 3 }, { level: 4, count: 2 }, { level: 5, count: 1 }] },
  { level: 10, spells: [{ level: 1, count: 4 }, { level: 2, count: 4 }, { level: 3, count: 3 }, { level: 4, count: 3 }, { level: 5, count: 2 }] },
  { level: 11, spells: [{ level: 1, count: 5 }, { level: 2, count: 4 }, { level: 3, count: 4 }, { level: 4, count: 3 }, { level: 5, count: 2 }, { level: 6, count: 1 }] },
  { level: 12, spells: [{ level: 1, count: 6 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 3 }, { level: 5, count: 2 }, { level: 6, count: 2 }] },
  { level: 13, spells: [{ level: 1, count: 6 }, { level: 2, count: 6 }, { level: 3, count: 6 }, { level: 4, count: 4 }, { level: 5, count: 2 }, { level: 6, count: 2 }] },
  { level: 14, spells: [{ level: 1, count: 6 }, { level: 2, count: 6 }, { level: 3, count: 6 }, { level: 4, count: 5 }, { level: 5, count: 3 }, { level: 6, count: 2 }, { level: 7, count: 1 }] },
  { level: 15, spells: [{ level: 1, count: 6 }, { level: 2, count: 6 }, { level: 3, count: 6 }, { level: 4, count: 6 }, { level: 5, count: 4 }, { level: 6, count: 2 }, { level: 7, count: 1 }] },
  { level: 16, spells: [{ level: 1, count: 7 }, { level: 2, count: 7 }, { level: 3, count: 7 }, { level: 4, count: 6 }, { level: 5, count: 4 }, { level: 6, count: 3 }, { level: 7, count: 1 }] },
  { level: 17, spells: [{ level: 1, count: 7 }, { level: 2, count: 7 }, { level: 3, count: 7 }, { level: 4, count: 7 }, { level: 5, count: 5 }, { level: 6, count: 3 }, { level: 7, count: 2 }] },
  { level: 18, spells: [{ level: 1, count: 8 }, { level: 2, count: 8 }, { level: 3, count: 8 }, { level: 4, count: 8 }, { level: 5, count: 6 }, { level: 6, count: 4 }, { level: 7, count: 2 }] },
  { level: 19, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 8 }, { level: 4, count: 8 }, { level: 5, count: 6 }, { level: 6, count: 4 }, { level: 7, count: 2 }] },
  { level: 20, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 8 }, { level: 5, count: 7 }, { level: 6, count: 5 }, { level: 7, count: 2 }] },
  { level: 21, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 8 }, { level: 6, count: 6 }, { level: 7, count: 2 }] },
  { level: 22, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 6 }, { level: 7, count: 3 }] },
  { level: 23, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 7 }, { level: 7, count: 3 }] },
  { level: 24, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 8 }, { level: 7, count: 3 }] },
  { level: 25, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 8 }, { level: 7, count: 4 }] },
  { level: 26, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 4 }] },
  { level: 27, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 5 }] },
  { level: 28, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 6 }] },
  { level: 29, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 7 }] },
  { level: 30, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 8 }] },
  { level: 31, spells: [{ level: 1, count: 10 }, { level: 2, count: 10 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 8 }] },
  { level: 32, spells: [{ level: 1, count: 10 }, { level: 2, count: 10 }, { level: 3, count: 10 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 8 }] },
  { level: 33, spells: [{ level: 1, count: 10 }, { level: 2, count: 10 }, { level: 3, count: 10 }, { level: 4, count: 10 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }] },
  { level: 34, spells: [{ level: 1, count: 11 }, { level: 2, count: 11 }, { level: 3, count: 10 }, { level: 4, count: 10 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }] },
  { level: 35, spells: [{ level: 1, count: 11 }, { level: 2, count: 11 }, { level: 3, count: 10 }, { level: 4, count: 10 }, { level: 5, count: 10 }, { level: 6, count: 10 }, { level: 7, count: 9 }] },
  { level: 36, spells: [{ level: 1, count: 11 }, { level: 2, count: 11 }, { level: 3, count: 11 }, { level: 4, count: 11 }, { level: 5, count: 10 }, { level: 6, count: 10 }, { level: 7, count: 10 }] },
  { level: 37, spells: [{ level: 1, count: 12 }, { level: 2, count: 12 }, { level: 3, count: 11 }, { level: 4, count: 11 }, { level: 5, count: 10 }, { level: 6, count: 10 }, { level: 7, count: 10 }] },
  { level: 38, spells: [{ level: 1, count: 12 }, { level: 2, count: 12 }, { level: 3, count: 11 }, { level: 4, count: 11 }, { level: 5, count: 11 }, { level: 6, count: 11 }, { level: 7, count: 10 }] },
  { level: 39, spells: [{ level: 1, count: 12 }, { level: 2, count: 12 }, { level: 3, count: 12 }, { level: 4, count: 12 }, { level: 5, count: 11 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 40, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 41, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 42, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 43, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 44, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 45, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 46, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 47, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 48, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 49, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
  { level: 50, spells: [{ level: 1, count: 13 }, { level: 2, count: 13 }, { level: 3, count: 13 }, { level: 4, count: 12 }, { level: 5, count: 12 }, { level: 6, count: 11 }, { level: 7, count: 11 }] },
];

export const MageSpellTable: { level: number; spells: SpellCount[] }[] = [
  { level: 1, spells: [{ level: 1, count: 1 }] },
  { level: 2, spells: [{ level: 1, count: 2 }] },
  { level: 3, spells: [{ level: 1, count: 2 }, { level: 2, count: 1 }] },
  { level: 4, spells: [{ level: 1, count: 3 }, { level: 2, count: 2 }] },
  { level: 5, spells: [{ level: 1, count: 4 }, { level: 2, count: 2 }, { level: 3, count: 1 }] },
  { level: 6, spells: [{ level: 1, count: 4 }, { level: 2, count: 2 }, { level: 3, count: 2 }] },
  { level: 7, spells: [{ level: 1, count: 4 }, { level: 2, count: 3 }, { level: 3, count: 2 }, { level: 4, count: 1 }] },
  { level: 8, spells: [{ level: 1, count: 4 }, { level: 2, count: 3 }, { level: 3, count: 3 }, { level: 4, count: 2 }] },
  { level: 9, spells: [{ level: 1, count: 4 }, { level: 2, count: 3 }, { level: 3, count: 3 }, { level: 4, count: 2 }, { level: 5, count: 1 }] },
  { level: 10, spells: [{ level: 1, count: 4 }, { level: 2, count: 4 }, { level: 3, count: 3 }, { level: 4, count: 2 }, { level: 5, count: 2 }] },
  { level: 11, spells: [{ level: 1, count: 4 }, { level: 2, count: 4 }, { level: 3, count: 4 }, { level: 4, count: 3 }, { level: 5, count: 3 }] },
  { level: 12, spells: [{ level: 1, count: 4 }, { level: 2, count: 4 }, { level: 3, count: 4 }, { level: 4, count: 4 }, { level: 5, count: 4 }, { level: 6, count: 1 }] },
  { level: 13, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 4 }, { level: 5, count: 4 }, { level: 6, count: 2 }] },
  { level: 14, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 4 }, { level: 5, count: 4 }, { level: 6, count: 2 }, { level: 7, count: 1 }] },
  { level: 15, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 2 }, { level: 7, count: 1 }] },
  { level: 16, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 3 }, { level: 7, count: 2 }, { level: 8, count: 1 }] },
  { level: 17, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 3 }, { level: 7, count: 3 }, { level: 8, count: 2 }] },
  { level: 18, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 3 }, { level: 7, count: 3 }, { level: 8, count: 2 }, { level: 9, count: 1 }] },
  { level: 19, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 3 }, { level: 7, count: 3 }, { level: 8, count: 3 }, { level: 9, count: 1 }] },
  { level: 20, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 4 }, { level: 7, count: 3 }, { level: 8, count: 3 }, { level: 9, count: 2 }] },
  { level: 21, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 4 }, { level: 7, count: 4 }, { level: 8, count: 4 }, { level: 9, count: 2 }] },
  { level: 22, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 5 }, { level: 7, count: 4 }, { level: 8, count: 4 }, { level: 9, count: 3 }] },
  { level: 23, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 5 }, { level: 7, count: 5 }, { level: 8, count: 5 }, { level: 9, count: 3 }] },
  { level: 24, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 5 }, { level: 7, count: 5 }, { level: 8, count: 5 }, { level: 9, count: 4 }] },
  { level: 25, spells: [{ level: 1, count: 5 }, { level: 2, count: 5 }, { level: 3, count: 5 }, { level: 4, count: 5 }, { level: 5, count: 5 }, { level: 6, count: 5 }, { level: 7, count: 5 }, { level: 8, count: 5 }, { level: 9, count: 4 }] },
  { level: 26, spells: [{ level: 1, count: 6 }, { level: 2, count: 6 }, { level: 3, count: 6 }, { level: 4, count: 6 }, { level: 5, count: 6 }, { level: 6, count: 5 }, { level: 7, count: 5 }, { level: 8, count: 5 }, { level: 9, count: 5 }] },
  { level: 27, spells: [{ level: 1, count: 6 }, { level: 2, count: 6 }, { level: 3, count: 6 }, { level: 4, count: 6 }, { level: 5, count: 6 }, { level: 6, count: 6 }, { level: 7, count: 6 }, { level: 8, count: 5 }, { level: 9, count: 5 }] },
  { level: 28, spells: [{ level: 1, count: 6 }, { level: 2, count: 6 }, { level: 3, count: 6 }, { level: 4, count: 6 }, { level: 5, count: 6 }, { level: 6, count: 6 }, { level: 7, count: 6 }, { level: 8, count: 6 }, { level: 9, count: 6 }] },
  { level: 29, spells: [{ level: 1, count: 7 }, { level: 2, count: 7 }, { level: 3, count: 7 }, { level: 4, count: 7 }, { level: 5, count: 7 }, { level: 6, count: 6 }, { level: 7, count: 6 }, { level: 8, count: 6 }, { level: 9, count: 6 }] },
  { level: 30, spells: [{ level: 1, count: 7 }, { level: 2, count: 7 }, { level: 3, count: 7 }, { level: 4, count: 7 }, { level: 5, count: 7 }, { level: 6, count: 7 }, { level: 7, count: 7 }, { level: 8, count: 6 }, { level: 9, count: 6 }] },
  { level: 31, spells: [{ level: 1, count: 7 }, { level: 2, count: 7 }, { level: 3, count: 7 }, { level: 4, count: 7 }, { level: 5, count: 7 }, { level: 6, count: 7 }, { level: 7, count: 7 }, { level: 8, count: 7 }, { level: 9, count: 7 }] },
  { level: 32, spells: [{ level: 1, count: 7 }, { level: 2, count: 7 }, { level: 3, count: 7 }, { level: 4, count: 7 }, { level: 5, count: 7 }, { level: 6, count: 7 }, { level: 7, count: 7 }, { level: 8, count: 7 }, { level: 9, count: 7 }] },
  { level: 33, spells: [{ level: 1, count: 7 }, { level: 2, count: 7 }, { level: 3, count: 7 }, { level: 4, count: 7 }, { level: 5, count: 7 }, { level: 6, count: 7 }, { level: 7, count: 7 }, { level: 8, count: 7 }, { level: 9, count: 7 }] },
  { level: 34, spells: [{ level: 1, count: 8 }, { level: 2, count: 8 }, { level: 3, count: 8 }, { level: 4, count: 8 }, { level: 5, count: 8 }, { level: 6, count: 7 }, { level: 7, count: 7 }, { level: 8, count: 7 }, { level: 9, count: 7 }] },
  { level: 35, spells: [{ level: 1, count: 8 }, { level: 2, count: 8 }, { level: 3, count: 8 }, { level: 4, count: 8 }, { level: 5, count: 8 }, { level: 6, count: 8 }, { level: 7, count: 8 }, { level: 8, count: 7 }, { level: 9, count: 7 }] },
  { level: 36, spells: [{ level: 1, count: 8 }, { level: 2, count: 8 }, { level: 3, count: 8 }, { level: 4, count: 8 }, { level: 5, count: 8 }, { level: 6, count: 8 }, { level: 7, count: 8 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 37, spells: [{ level: 1, count: 8 }, { level: 2, count: 8 }, { level: 3, count: 8 }, { level: 4, count: 8 }, { level: 5, count: 8 }, { level: 6, count: 8 }, { level: 7, count: 8 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 38, spells: [{ level: 1, count: 8 }, { level: 2, count: 8 }, { level: 3, count: 8 }, { level: 4, count: 8 }, { level: 5, count: 8 }, { level: 6, count: 8 }, { level: 7, count: 8 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 39, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 8 }, { level: 7, count: 8 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 40, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 41, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 42, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 43, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 44, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 45, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 46, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 47, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 48, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 49, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
  { level: 50, spells: [{ level: 1, count: 9 }, { level: 2, count: 9 }, { level: 3, count: 9 }, { level: 4, count: 9 }, { level: 5, count: 9 }, { level: 6, count: 9 }, { level: 7, count: 9 }, { level: 8, count: 8 }, { level: 9, count: 8 }] },
];

export const WisdomBonusSpellTable: { wisdom: number; bonusSpells: SpellCount[] }[] = [
  { wisdom: 13, bonusSpells: [{ level: 1, count: 1 }] },
  { wisdom: 14, bonusSpells: [{ level: 1, count: 2 }] },
  { wisdom: 15, bonusSpells: [{ level: 1, count: 2 }, { level: 2, count: 1 }] },
  { wisdom: 16, bonusSpells: [{ level: 1, count: 2 }, { level: 2, count: 2 }] },
  { wisdom: 17, bonusSpells: [{ level: 1, count: 2 }, { level: 2, count: 2 }, { level: 3, count: 1 }] },
  { wisdom: 18, bonusSpells: [{ level: 1, count: 2 }, { level: 2, count: 2 }, { level: 3, count: 1 }, { level: 4, count: 1 }] },
  { wisdom: 19, bonusSpells: [{ level: 1, count: 3 }, { level: 2, count: 2 }, { level: 3, count: 2 }, { level: 4, count: 1 }] },
  { wisdom: 20, bonusSpells: [{ level: 1, count: 3 }, { level: 2, count: 3 }, { level: 3, count: 2 }, { level: 4, count: 2 }] },
  { wisdom: 21, bonusSpells: [{ level: 1, count: 3 }, { level: 2, count: 3 }, { level: 3, count: 3 }, { level: 4, count: 2 }, { level: 5, count: 1 }] },
  { wisdom: 22, bonusSpells: [{ level: 1, count: 3 }, { level: 2, count: 3 }, { level: 3, count: 3 }, { level: 4, count: 3 }, { level: 5, count: 2 }] },
  { wisdom: 23, bonusSpells: [{ level: 1, count: 4 }, { level: 2, count: 3 }, { level: 3, count: 3 }, { level: 4, count: 3 }, { level: 5, count: 2 }, { level: 6, count: 1 }] },
  { wisdom: 24, bonusSpells: [{ level: 1, count: 4 }, { level: 2, count: 3 }, { level: 3, count: 3 }, { level: 4, count: 3 }, { level: 5, count: 3 }, { level: 6, count: 2 }] },
  { wisdom: 25, bonusSpells: [{ level: 1, count: 4 }, { level: 2, count: 3 }, { level: 3, count: 3 }, { level: 4, count: 3 }, { level: 5, count: 3 }, { level: 6, count: 3 }, { level: 7, count: 1 }] },
];
