LAM load_secondary_types
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/common.tpa"
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/49.tpa" // Banshee
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4c.tpa" // Ghoul
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4b.tpa" // Ghast
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4d.tpa" // Ghoul Lord
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4e.tpa" // Mummy
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/4f.tpa" // Greater Mummy
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/50.tpa" // Shadow
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/59.tpa" // Greater Shadow
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/5a.tpa" // Baneguard
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/5b.tpa" // Bonebat
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/51.tpa" // Skeleton
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/52.tpa" // Skeleton Warrior
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/53.tpa" // Spectre
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/undead/5d.tpa" // Ghost
