export const ITEMS = {
  CloudSpells: "jai1",
  Construct: "jai2",
  CriticalHitImmunity: "jai3",
  EntangleImmunity: "jai4",
  Fey: "jai5",
  GhostVisuals1: "ja6",
  GhostVisuals2: "ja7",
  GhostVisuals3: "ja8",
  Giant: "jai9",
  Hover: "jai10",
  Incorporeal: "jai11",
  MagicalBeast: "jai12",
  Ooze: "jai13",
  Plant: "jai14",
  Sketetal: "jai15",
  Spider: "jai16",
  Undead: "jai17",
  Vermin: "jai18",
  Cat: "jai19",
};

export enum MonsterItemIconEnum {
  Traits = "IRING15",
  ISQUIRL = "ISQUIRL",
  MindFlayer = "ISHAPE02",
  Golem = "ISHAPE03",
  Troll = "ISHAPE04",
  Wolfwere = "ISHAPE05",
  EarthElemental = "ISHAPE06",
  FireElemental = "ISHAPE07",
  Ghoul = "IGHOUL",
  Fist = "IFIST",
  Wolf = "IWOLF",
  Jelly = "IJELLY",
  Jaws = "SPPR416B", // not great, until a better icon is found or created
}
