// Summons are destroyed on death
IF
	Die()
THEN
	RESPONSE #100
		DestroySelf()
END

// Precast Stoneskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPWI408")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPWI408",Myself)
		RemoveSpellRES("SPWI408")
		Continue()
END

// Precast Ironskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPPR506")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPPR506",Myself)
		RemoveSpellRES("SPPR506")
		Continue()
END

IF
	Global("JA_PRECAST_LONG","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_PRECAST_LONG","LOCALS",1)
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA_COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA_HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(98)
		SetGlobalTimer("JA_HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA_COMBAT","LOCALS",0)
	Heard(LastSummonerOf(Myself),98)
	InMyArea(LastSummonerOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA_COMBAT","LOCALS",1)
	Heard(LastSummonerOf(Myself),98)
	InMyArea(LastSummonerOf(Myself))
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Summon follow summoner
IF
	Global("JA_COMBAT","LOCALS",0)
	!StateCheck(Myself,STATE_BLIND)
	ActionListEmpty()
	!See(NearestEnemyOf(Myself))
	!See(LastSummonerOf(Myself))
	HPGT(LastSummonerOf(Myself),0)
	Range(LastSummonerOf(Myself),150)
THEN
	RESPONSE #100
		MoveToObject(LastSummonerOf(Myself))
END

// Do nothing if...
IF
	ActionListEmpty()
	OR(4)
		Global("JA_COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	ActionListEmpty()
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Handle Panic state
IF
	StateCheck(Myself,STATE_PANIC)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),15)
END

IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Charge
IF
	ActionListEmpty()
	HaveSpellRES("jas0m44")
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!General(FarthestEnemyOf(Myself),WEAPON)
	!CheckStatGT(FarthestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FarthestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(FarthestEnemyOf(Myself))
	Range(LastSeenBy(Myself),50)
	!Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m44",LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	HaveSpellRES("jas0m44")
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!General(SecondFarthestEnemyOf(Myself),WEAPON)
	!CheckStatGT(SecondFarthestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondFarthestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(SecondFarthestEnemyOf(Myself))
	Range(LastSeenBy(Myself),50)
	!Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m44",LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	HaveSpellRES("jas0m44")
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!General(ThirdFarthestEnemyOf(Myself),WEAPON)
	!CheckStatGT(ThirdFarthestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdFarthestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(ThirdFarthestEnemyOf(Myself))
	Range(LastSeenBy(Myself),50)
	!Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m44",LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	ActionListEmpty()
	HaveSpellRES("jas0m44")
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!General(FourthFarthestEnemyOf(Myself),WEAPON)
	!CheckStatGT(FourthFarthestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthFarthestEnemyOf(Myself),STATE_REALLY_DEAD)
	See(FourthFarthestEnemyOf(Myself))
	Range(LastSeenBy(Myself),50)
	!Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas0m44",LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Barbarian Rage
IF
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	ActionListEmpty()
	HaveSpell(BARBARIAN_RAGE)
	See(NearestEnemyOf(Myself))
	!CheckSpellState(Myself,BARBARIAN_RAGE)
	RandomNumGT(800,80)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		Spell(Myself,BARBARIAN_RAGE)
END

// Potion of superior healing (40hp)
IF
	ActionListEmpty()
	HasItem("POTN55",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!General(Myself,UNDEAD)
	HPPercentLT(Myself,30)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN55",Myself)
END

// Potion of extra healing (30hp)
IF
	ActionListEmpty()
	HasItem("POTN52",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!General(Myself,UNDEAD)
	HPPercentLT(Myself,40)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN52",Myself)
END

// Potion of regeneration
IF
	ActionListEmpty()
	HasItem("POTN42",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HPPercentLT(Myself,90)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN42",Myself)
END

// Exilir of health (10hp)
IF
	ActionListEmpty()
	HasItem("POTN17",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!General(Myself,UNDEAD)
	OR(2)
		HPPercentLT(Myself,75)
		StateCheck(Myself,STATE_POISONED)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN17",Myself)
END

// Antidote
IF
	ActionListEmpty()
	HasItem("POTN20",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	StateCheck(Myself,STATE_POISONED)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN20",Myself)
END

// Potion of healing (10hp)
IF
	ActionListEmpty()
	HasItem("POTN08",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!General(Myself,UNDEAD)
	HPPercentLT(Myself,75)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN08",Myself)
END

// Potion of speed
IF
	ActionListEmpty()
	HasItem("POTN14",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!StateCheck(Myself,STATE_HASTED)
	RandomNumGT(200,40)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN14",Myself)
END

// Potion of invisibility
IF
	ActionListEmpty()
	HasItem("POTN10",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!StateCheck(Myself,STATE_INVISIBLE)
	RandomNumGT(201,40)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN10",Myself)
END

// Potion of invulnerability
IF
	ActionListEmpty()
	HasItem("POTN11",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	RandomNumGT(202,40)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN11",Myself)
END

// Potion of defense
IF
	ActionListEmpty()
	HasItem("POTN24",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	RandomNumGT(203,41)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN24",Myself)
END

// Potion of fire resistance
IF
	ActionListEmpty()
	HasItem("POTN02",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	CheckStatLT(Myself,100,RESISTFIRE)
	RandomNumGT(204,41)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN02",Myself)
END

// Potion of magic resistance
IF
	ActionListEmpty()
	HasItem("POTN34",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	CheckStatLT(Myself,20,RESISTMAGIC)
	RandomNumGT(205,41)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN34",Myself)
END

// Potion of magic shielding
IF
	ActionListEmpty()
	HasItem("POTN35",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	CheckStatLT(Myself,50,MAGICDAMAGERESISTANCE)
	RandomNumGT(206,41)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN35",Myself)
END

// Potion of freedom
IF
	ActionListEmpty()
	HasItem("POTN45",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!CheckStatGT(Myself,0,CLERIC_FREE_ACTION)
	RandomNumGT(207,41)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN45",Myself)
END

// Potion of storm giant strength
IF
	ActionListEmpty()
	HasItem("POTN07",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	CheckStatLT(Myself,24,STR)
	RandomNumGT(208,42)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN07",Myself)
END

// Potion of cloud giant strength
IF
	ActionListEmpty()
	HasItem("POTN06",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	CheckStatLT(Myself,23,STR)
	RandomNumGT(209,42)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN06",Myself)
END

// Potion of fire giant strength
IF
	ActionListEmpty()
	HasItem("POTN05",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	CheckStatLT(Myself,22,STR)
	RandomNumGT(210,42)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN05",Myself)
END

// Potion of frost giant strength
IF
	ActionListEmpty()
	HasItem("POTN04",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	CheckStatLT(Myself,21,STR)
	RandomNumGT(211,42)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN04",Myself)
END

// Potion of hill giant strength
IF
	ActionListEmpty()
	HasItem("POTN03",Myself)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	CheckStatLT(Myself,19,STR)
	RandomNumGT(212,42)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@10113)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		UseItem("POTN03",Myself)
END

// Attack NoCheck enemy
IF
	ActionListEmpty()
	OR(4)
		General(NearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NearestEnemyOf(Myself))
	OR(4)
		General(SecondNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SecondNearestEnemyOf(Myself))
	OR(4)
		General(ThirdNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(ThirdNearestEnemyOf(Myself))
	OR(4)
		General(FourthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FourthNearestEnemyOf(Myself))
	OR(4)
		General(FifthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(FifthNearestEnemyOf(Myself))
	OR(4)
		General(SixthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SixthNearestEnemyOf(Myself))
	OR(4)
		General(SeventhNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(SeventhNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(SeventhNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(SeventhNearestEnemyOf(Myself))
	OR(4)
		General(EighthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(EighthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(EighthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(EighthNearestEnemyOf(Myself))
	OR(4)
		General(NinthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(NinthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(NinthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(NinthNearestEnemyOf(Myself))
	OR(4)
		General(TenthNearestEnemyOf(Myself),WEAPON)
		CheckStatGT(TenthNearestEnemyOf(Myself),0,SANCTUARY)
		StateCheck(TenthNearestEnemyOf(Myself),STATE_REALLY_DEAD)
		!See(TenthNearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	ActionListEmpty()
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Attack Sleep enemy
IF
	ActionListEmpty()
	OR(4)
		!StateCheck(Player1,STATE_SLEEPING)
		CheckStatGT(Player1,0,SANCTUARY)
		StateCheck(Player1,STATE_REALLY_DEAD)
		!See(Player1)
	OR(4)
		!StateCheck(Player2,STATE_SLEEPING)
		CheckStatGT(Player2,0,SANCTUARY)
		StateCheck(Player2,STATE_REALLY_DEAD)
		!See(Player2)
	OR(4)
		!StateCheck(Player3,STATE_SLEEPING)
		CheckStatGT(Player3,0,SANCTUARY)
		StateCheck(Player3,STATE_REALLY_DEAD)
		!See(Player3)
	OR(4)
		!StateCheck(Player4,STATE_SLEEPING)
		CheckStatGT(Player4,0,SANCTUARY)
		StateCheck(Player4,STATE_REALLY_DEAD)
		!See(Player4)
	OR(4)
		!StateCheck(Player5,STATE_SLEEPING)
		CheckStatGT(Player5,0,SANCTUARY)
		StateCheck(Player5,STATE_REALLY_DEAD)
		!See(Player5)
	OR(4)
		!StateCheck(Player6,STATE_SLEEPING)
		CheckStatGT(Player6,0,SANCTUARY)
		StateCheck(Player6,STATE_REALLY_DEAD)
		!See(Player6)
THEN
	RESPONSE #100
		Continue()
END

IF
	ActionListEmpty()
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	ActionListEmpty()
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

