LAM load_secondary_types
COPY_EXISTING "gaze.pro" ~override/jap0f2.pro~
	READ_SHORT 0x08 type
	PATCH_IF (%type% = 1) BEGIN
		INSERT_BYTES 0x100 0x100
	END
	PATCH_IF (%type% != 3) BEGIN
		INSERT_BYTES 0x200 0x100
	END
	WRITE_SHORT 0x8 3
	WRITE_LONG 0x200 2112
	WRITE_SHORT 0x204 255
	WRITE_SHORT 0x206 255
	WRITE_SHORT 0x212 0x4001
	WRITE_BYTE 0x217 255
	WRITE_SHORT 0x224 60
ADD_PROJECTILE ~override/jap0f2.pro~ ~Basilisk petrifying gaze~

// Petrifying Gaze
CREATE SPL "jas0f2"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~jas0f2.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10125)
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 11
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPWI604C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10126)
	LPF ADD_SPELL_HEADER INT_VAR type=2 location=4 target=1 range=30 projectile=(IDS_OF_SYMBOL (~projectl~ ~jap0f2~)) + 1 STR_VAR icon="SPWI604B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=134 target=2 power=1 probability1=100 savingthrow=16 savebonus="-4" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=139 target=2 power=1 parameter1=RESOLVE_STR_REF(@10128) probability1=100 savingthrow=16 savebonus="-4" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=174 target=2 power=1 probability1=100 savingthrow=16 savebonus="-4" STR_VAR resource="MISC_06B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=215 target=2 power=1 probability1=100 savingthrow=16 savebonus="-4" STR_VAR resource="SPFLESHS.VVC" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=61 target=2 power=1 parameter1=2021160960 parameter2=1638400 probability1=100 savingthrow=16 savebonus="-4" END
	LPF CHANGE_SPELL INT_VAR    renew=1 END
	
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/basilisk/2.tpa" // Lesser Basilisk
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/basilisk/3.tpa" // Greater Basilisk
