IF
    Detect([PC])
    NumberOfTimesTalkedTo(0)
THEN
    RESPONSE #100
        StartDialogueNoSet(LastSeenBy(Myself))
END

IF
    Detect([PC])
    OpenState("Mirror",FALSE)
    NumberOfTimesTalkedTo(1)
THEN
    RESPONSE #100
        StartDialogueNoSet(LastSeenBy(Myself))
END

IF
    Allegiance(Myself,ENEMY)
    Range(Player1,30)
    !GlobalTimerNotExpired("thief_detection","LOCALS")
    CheckStatGT(Player1,65,DETECTILLUSIONS)
    ModalStateObject(Player1,DETECTTRAPS)
THEN
    RESPONSE #100
        SetGlobalTimer("thief_detection","LOCALS",ONE_MINUTE)
        Continue()
END

IF
    Allegiance(Myself,ENEMY)
    Range(Player2,30)
    !GlobalTimerNotExpired("thief_detection","LOCALS")
    CheckStatGT(Player2,65,DETECTILLUSIONS)
    ModalStateObject(Player2,DETECTTRAPS)
THEN
    RESPONSE #100
        SetGlobalTimer("thief_detection","LOCALS",ONE_MINUTE)
        Continue()
END

IF
    Allegiance(Myself,ENEMY)
    Range(Player3,30)
    !GlobalTimerNotExpired("thief_detection","LOCALS")
    CheckStatGT(Player3,65,DETECTILLUSIONS)
    ModalStateObject(Player3,DETECTTRAPS)
THEN
    RESPONSE #100
        SetGlobalTimer("thief_detection","LOCALS",ONE_MINUTE)
        Continue()
END

IF
    Allegiance(Myself,ENEMY)
    Range(Player4,30)
    !GlobalTimerNotExpired("thief_detection","LOCALS")
    CheckStatGT(Player4,65,DETECTILLUSIONS)
    ModalStateObject(Player4,DETECTTRAPS)
THEN
    RESPONSE #100
        SetGlobalTimer("thief_detection","LOCALS",ONE_MINUTE)
        Continue()
END

IF
    Allegiance(Myself,ENEMY)
    Range(Player5,30)
    !GlobalTimerNotExpired("thief_detection","LOCALS")
    CheckStatGT(Player5,65,DETECTILLUSIONS)
    ModalStateObject(Player5,DETECTTRAPS)
THEN
    RESPONSE #100
        SetGlobalTimer("thief_detection","LOCALS",ONE_MINUTE)
        Continue()
END

IF
    Allegiance(Myself,ENEMY)
    Range(Player6,30)
    !GlobalTimerNotExpired("thief_detection","LOCALS")
    CheckStatGT(Player6,65,DETECTILLUSIONS)
    ModalStateObject(Player6,DETECTTRAPS)
THEN
    RESPONSE #100
        SetGlobalTimer("thief_detection","LOCALS",ONE_MINUTE)
        Continue()
END

IF
    !Global("inafight","LOCALS",1)
    OR(6)
        AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
        AttackedBy([PC],DEFAULT)
        AttackedBy([FAMILIAR],DEFAULT)
        AttackedBy([ALLY],DEFAULT)
        AttackedBy([CONTROLLED],DEFAULT)
        AttackedBy([CHARMED],DEFAULT)
THEN
    RESPONSE #100
        Enemy()
        SetGlobal("inafight","LOCALS",1)
        SetGlobalTimer("stayontarget","LOCALS",TWO_ROUNDS)
        SetGlobalTimer("seedefences","LOCALS",ONE_ROUND)
        Continue()
END

IF
    !Global("inafight","LOCALS",1)
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        SetGlobal("inafight","LOCALS",1)
        SetGlobalTimer("stayontarget","LOCALS",TWO_ROUNDS)
        SetGlobalTimer("seedefences","LOCALS",ONE_ROUND)
        Continue()
END

IF
    Global("rest_state","LOCALS",0)
    Detect(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        SetGlobal("rest_state","LOCALS",1)
        Continue()
END

IF
    Global("rest_state","LOCALS",1)
    !Detect(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        SetGlobal("rest_state","LOCALS",2)
        SetGlobalTimer("rest_timer","LOCALS",EIGHT_HOURS)
        Continue()
END

IF
    Global("rest_state","LOCALS",2)
    Detect(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        SetGlobal("rest_state","LOCALS",1)
        Continue()
END

IF
    Global("rest_state","LOCALS",2)
    GlobalTimerExpired("rest_timer","LOCALS")
THEN
    RESPONSE #100
        SetGlobal("rest_state","LOCALS",0)
        ApplySpell(Myself,RESTORE_FULL_HEALTH)  // SPIN746.SPL (No such index)
        Rest()
END

IF
    Allegiance(Myself,ENEMY)
    OR(12)
        AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
        AttackedBy([PC],DEFAULT)
        AttackedBy([FAMILIAR],DEFAULT)
        AttackedBy([ALLY],DEFAULT)
        AttackedBy([CONTROLLED],DEFAULT)
        AttackedBy([CHARMED],DEFAULT)
        SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
        SpellCastOnMe([PC],0)
        SpellCastOnMe([FAMILIAR],0)
        SpellCastOnMe([ALLY],0)
        SpellCastOnMe([CONTROLLED],0)
        SpellCastOnMe([CHARMED],0)
    !GlobalTimerNotExpired("whatthe","LOCALS")
    !See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        SetGlobalTimer("whatthe","LOCALS",TWO_ROUNDS)
        Continue()
END

IF
    !See(NearestEnemyOf(Myself))
    GlobalTimerNotExpired("whatthe","LOCALS")
THEN
    RESPONSE #100
        RandomWalkContinuous()
END

IF
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    Heard([ANYONE],404)
    Range(LastHeardBy(Myself),20)
    !General(Myself,UNDEAD)
    !Race(Myself,DEMONIC)
    OR(2)
        !CheckStatGT(Myself,80,RESISTMAGIC)
        !See(NearestEnemyOf(Myself))
    !See([PC])
THEN
    RESPONSE #100
        SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
        RunAwayFromNoLeaveArea(LastHeardBy(Myself),30)
END

IF
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    Heard([ANYONE],411)
    Range(LastHeardBy(Myself),15)
    !CheckStatGT(Myself,0,MINORGLOBE)
    !General(Myself,UNDEAD)
    !Race(Myself,DEMONIC)
    OR(2)
        !CheckStatGT(Myself,80,RESISTMAGIC)
        !See(NearestEnemyOf(Myself))
    !See([PC])
THEN
    RESPONSE #100
        SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
        RunAwayFromNoLeaveArea(LastHeardBy(Myself),30)
END

IF
    See(Myself)
    !Kit(Myself,UNDEADHUNTER)
    !Kit(Myself,INQUISITOR)
    !CheckStatGT(Myself,0,CLERIC_FREE_ACTION)
    OR(2)
        !CheckSpellState(Myself,HOLD_IMMUNITY_SEEN)
        !CheckSpellState(Myself,HOLD_IMMUNITY)
    OR(2)
        !CheckSpellState(Myself,ITEM_ANTIWEB_SEEN)
        !CheckSpellState(Myself,ITEM_ANTIWEB)
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    !CheckStatGT(Myself,0,MINORGLOBE)
    Heard([ANYONE],410)
    Range(LastHeardBy(Myself),15)
    OR(2)
        !CheckStatGT(Myself,80,RESISTMAGIC)
        !See(NearestEnemyOf(Myself))
    !See([PC])
THEN
    RESPONSE #100
        SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
        RunAwayFromNoLeaveArea(LastHeardBy(Myself),30)
END

IF
    See(Myself)
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    Heard([ANYONE],412)
    Range(LastHeardBy(Myself),20)
    !CheckStatGT(Myself,99,RESISTCOLD)
    OR(2)
        !CheckStatGT(Myself,80,RESISTMAGIC)
        !See(NearestEnemyOf(Myself))
    OR(2)
        !CheckStatGT(Myself,59,RESISTCOLD)
        !See(NearestEnemyOf(Myself))
    !See([PC])
THEN
    RESPONSE #100
        SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
        RunAwayFromNoLeaveArea(LastHeardBy(Myself),30)
END

IF
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    Heard([ANYONE],404)
    Range(LastHeardBy(Myself),20)
    !General(Myself,UNDEAD)
    !Race(Myself,DEMONIC)
    OR(2)
        !CheckStatGT(Myself,80,RESISTMAGIC)
        !See(NearestEnemyOf(Myself))
    See([PC])
    !Range([PC],8)
THEN
    RESPONSE #100
        SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
        MoveToObject([PC])
END

IF
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    Heard([ANYONE],411)
    Range(LastHeardBy(Myself),15)
    !CheckStatGT(Myself,0,MINORGLOBE)
    !General(Myself,UNDEAD)
    !Race(Myself,DEMONIC)
    OR(2)
        !CheckStatGT(Myself,80,RESISTMAGIC)
        !See(NearestEnemyOf(Myself))
    See([PC])
    !Range([PC],8)
THEN
    RESPONSE #100
        SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
        MoveToObject([PC])
END

IF
    See(Myself)
    !Kit(Myself,UNDEADHUNTER)
    !Kit(Myself,INQUISITOR)
    !CheckStatGT(Myself,0,CLERIC_FREE_ACTION)
    OR(2)
        !CheckSpellState(Myself,HOLD_IMMUNITY_SEEN)
        !CheckSpellState(Myself,HOLD_IMMUNITY)
    OR(2)
        !CheckSpellState(Myself,ITEM_ANTIWEB_SEEN)
        !CheckSpellState(Myself,ITEM_ANTIWEB)
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    !CheckStatGT(Myself,0,MINORGLOBE)
    Heard([ANYONE],410)
    Range(LastHeardBy(Myself),15)
    OR(2)
        !CheckStatGT(Myself,80,RESISTMAGIC)
        !See(NearestEnemyOf(Myself))
    See([PC])
    !Range([PC],8)
THEN
    RESPONSE #100
        SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
        MoveToObject([PC])
END

IF
    See(Myself)
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    Heard([ANYONE],412)
    Range(LastHeardBy(Myself),20)
    !CheckStatGT(Myself,99,RESISTCOLD)
    OR(2)
        !CheckStatGT(Myself,80,RESISTMAGIC)
        !See(NearestEnemyOf(Myself))
    OR(2)
        !CheckStatGT(Myself,59,RESISTCOLD)
        !See(NearestEnemyOf(Myself))
    See([PC])
    !Range([PC],8)
THEN
    RESPONSE #100
        SetGlobalTimer("seencloud","LOCALS",FOUR_MINUTES)
        MoveToObject([PC])
END

IF
    !See(NearestEnemyOf(Myself))
    OR(8)
        Heard([ANYONE],404)
        Heard([ANYONE],405)
        Heard([ANYONE],406)
        Heard([ANYONE],407)
        Heard([ANYONE],408)
        Heard([ANYONE],409)
        Heard([ANYONE],410)
        Heard([ANYONE],411)
THEN
    RESPONSE #100
        NoAction()
END

IF
    !Detect(NearestEnemyOf(Myself))
    !Gender(Myself,SUMMONED_DEMON)
    !Global("inafight","LOCALS",1)
    !Allegiance(Myself,GOODCUTOFF)
    ActionListEmpty()
THEN
    RESPONSE #100
        NoAction()
END

IF
    See(NearestEnemyOf(Myself))
    !Global("chasing","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("chasing","LOCALS",0)
        ClearActions(Myself)
END

IF
    !GlobalTimerNotExpired("chasetarget","LOCALS")
    Allegiance(Myself,ENEMY)
    See(Player1)
THEN
    RESPONSE #100
        SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
        SetGlobal("chasePC","LOCALS",1)
        Continue()
END

IF
    !GlobalTimerNotExpired("chasetarget","LOCALS")
    Allegiance(Myself,ENEMY)
    !See(Player1)
    See(Player2)
THEN
    RESPONSE #100
        SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
        SetGlobal("chasePC","LOCALS",2)
        Continue()
END

IF
    !GlobalTimerNotExpired("chasetarget","LOCALS")
    Allegiance(Myself,ENEMY)
    !See(Player1)
    !See(Player2)
    See(Player3)
THEN
    RESPONSE #100
        SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
        SetGlobal("chasePC","LOCALS",3)
        Continue()
END

IF
    !GlobalTimerNotExpired("chasetarget","LOCALS")
    Allegiance(Myself,ENEMY)
    !See(Player1)
    !See(Player2)
    !See(Player3)
    See(Player4)
THEN
    RESPONSE #100
        SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
        SetGlobal("chasePC","LOCALS",4)
        Continue()
END

IF
    !GlobalTimerNotExpired("chasetarget","LOCALS")
    Allegiance(Myself,ENEMY)
    !See(Player1)
    !See(Player2)
    !See(Player3)
    !See(Player4)
    See(Player5)
THEN
    RESPONSE #100
        SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
        SetGlobal("chasePC","LOCALS",5)
        Continue()
END

IF
    !GlobalTimerNotExpired("chasetarget","LOCALS")
    Allegiance(Myself,ENEMY)
    !See(Player1)
    !See(Player2)
    !See(Player3)
    !See(Player4)
    !See(Player5)
    See(Player6)
THEN
    RESPONSE #100
        SetGlobalTimer("chasetarget","LOCALS",ONE_HOUR)
        SetGlobal("chasePC","LOCALS",6)
        Continue()
END

IF
    Global("chasePC","LOCALS",1)
    StateCheck(Player1,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetGlobal("chasePC","LOCALS",0)
        Continue()
END

IF
    Global("chasePC","LOCALS",2)
    StateCheck(Player2,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetGlobal("chasePC","LOCALS",0)
        Continue()
END

IF
    Global("chasePC","LOCALS",3)
    StateCheck(Player3,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetGlobal("chasePC","LOCALS",0)
        Continue()
END

IF
    Global("chasePC","LOCALS",4)
    StateCheck(Player4,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetGlobal("chasePC","LOCALS",0)
        Continue()
END

IF
    Global("chasePC","LOCALS",5)
    StateCheck(Player5,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetGlobal("chasePC","LOCALS",0)
        Continue()
END

IF
    Global("chasePC","LOCALS",6)
    StateCheck(Player6,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetGlobal("chasePC","LOCALS",0)
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)  // SPWI899.SPL (Symbol, Fear)
    !CheckSpellState(SixthNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
    !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
    !Kit(SixthNearestEnemyOf(Myself),CAVALIER)
    !CheckSpellState(SixthNearestEnemyOf(Myself),RESIST_FEAR)
    !General(SixthNearestEnemyOf(Myself),UNDEAD)
    !Kit(SixthNearestEnemyOf(Myself),Blackguard)
    !CheckSpellState(SixthNearestEnemyOf(Myself),EXALTATION)
    OR(2)
        !CheckSpellState(SixthNearestEnemyOf(Myself),PANIC_IMMUNITY_SEEN)
        !CheckSpellState(SixthNearestEnemyOf(Myself),PANIC_IMMUNITY)
    !CheckStatGT(SixthNearestEnemyOf(Myself),99,RESISTMAGIC)
    Allegiance(Myself,ENEMY)
    !Allegiance(SixthNearestEnemyOf(Myself),ENEMY)
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
    OR(3)
        TriggerOverride(SixthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        !TriggerOverride(SixthNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        !TriggerOverride(SixthNearestEnemyOf(Myself),StateCheck(SecondNearestAllyOf(Myself),STATE_HELPLESS))
    OR(2)
        !TriggerOverride(SixthNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        TriggerOverride(SixthNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
    See(SixthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)  // SPWI899.SPL (Symbol, Fear)
    !CheckSpellState(FifthNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
    !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
    !Kit(FifthNearestEnemyOf(Myself),CAVALIER)
    !CheckSpellState(FifthNearestEnemyOf(Myself),RESIST_FEAR)
    !General(FifthNearestEnemyOf(Myself),UNDEAD)
    !Kit(FifthNearestEnemyOf(Myself),Blackguard)
    !CheckSpellState(FifthNearestEnemyOf(Myself),EXALTATION)
    OR(2)
        !CheckSpellState(FifthNearestEnemyOf(Myself),PANIC_IMMUNITY_SEEN)
        !CheckSpellState(FifthNearestEnemyOf(Myself),PANIC_IMMUNITY)
    !CheckStatGT(FifthNearestEnemyOf(Myself),99,RESISTMAGIC)
    Allegiance(Myself,ENEMY)
    !Allegiance(FifthNearestEnemyOf(Myself),ENEMY)
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
    OR(3)
        TriggerOverride(FifthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        !TriggerOverride(FifthNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        !TriggerOverride(FifthNearestEnemyOf(Myself),StateCheck(SecondNearestAllyOf(Myself),STATE_HELPLESS))
    OR(2)
        !TriggerOverride(FifthNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        TriggerOverride(FifthNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
    See(FifthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)  // SPWI899.SPL (Symbol, Fear)
    !CheckSpellState(FourthNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
    !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
    !Kit(FourthNearestEnemyOf(Myself),CAVALIER)
    !CheckSpellState(FourthNearestEnemyOf(Myself),RESIST_FEAR)
    !General(FourthNearestEnemyOf(Myself),UNDEAD)
    !Kit(FourthNearestEnemyOf(Myself),Blackguard)
    !CheckSpellState(FourthNearestEnemyOf(Myself),EXALTATION)
    OR(2)
        !CheckSpellState(FourthNearestEnemyOf(Myself),PANIC_IMMUNITY_SEEN)
        !CheckSpellState(FourthNearestEnemyOf(Myself),PANIC_IMMUNITY)
    !CheckStatGT(FourthNearestEnemyOf(Myself),99,RESISTMAGIC)
    Allegiance(Myself,ENEMY)
    !Allegiance(FourthNearestEnemyOf(Myself),ENEMY)
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
    OR(3)
        TriggerOverride(FourthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        !TriggerOverride(FourthNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        !TriggerOverride(FourthNearestEnemyOf(Myself),StateCheck(SecondNearestAllyOf(Myself),STATE_HELPLESS))
    OR(2)
        !TriggerOverride(FourthNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        TriggerOverride(FourthNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
    See(FourthNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)  // SPWI899.SPL (Symbol, Fear)
    !CheckSpellState(ThirdNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
    !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
    !Kit(ThirdNearestEnemyOf(Myself),CAVALIER)
    !CheckSpellState(ThirdNearestEnemyOf(Myself),RESIST_FEAR)
    !General(ThirdNearestEnemyOf(Myself),UNDEAD)
    !Kit(ThirdNearestEnemyOf(Myself),Blackguard)
    !CheckSpellState(ThirdNearestEnemyOf(Myself),EXALTATION)
    OR(2)
        !CheckSpellState(ThirdNearestEnemyOf(Myself),PANIC_IMMUNITY_SEEN)
        !CheckSpellState(ThirdNearestEnemyOf(Myself),PANIC_IMMUNITY)
    !CheckStatGT(ThirdNearestEnemyOf(Myself),99,RESISTMAGIC)
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
    OR(3)
        TriggerOverride(ThirdNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        !TriggerOverride(ThirdNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        !TriggerOverride(ThirdNearestEnemyOf(Myself),StateCheck(SecondNearestAllyOf(Myself),STATE_HELPLESS))
    OR(2)
        !TriggerOverride(ThirdNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        TriggerOverride(ThirdNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
    See(ThirdNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)  // SPWI899.SPL (Symbol, Fear)
    !CheckSpellState(SecondNearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
    !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
    !Kit(SecondNearestEnemyOf(Myself),CAVALIER)
    !CheckSpellState(SecondNearestEnemyOf(Myself),RESIST_FEAR)
    !General(SecondNearestEnemyOf(Myself),UNDEAD)
    !Kit(SecondNearestEnemyOf(Myself),Blackguard)
    !CheckSpellState(SecondNearestEnemyOf(Myself),EXALTATION)
    OR(2)
        !CheckSpellState(SecondNearestEnemyOf(Myself),PANIC_IMMUNITY_SEEN)
        !CheckSpellState(SecondNearestEnemyOf(Myself),PANIC_IMMUNITY)
    !CheckStatGT(SecondNearestEnemyOf(Myself),99,RESISTMAGIC)
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
    OR(3)
        TriggerOverride(SecondNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        !TriggerOverride(SecondNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        !TriggerOverride(SecondNearestEnemyOf(Myself),StateCheck(SecondNearestAllyOf(Myself),STATE_HELPLESS))
    OR(2)
        !TriggerOverride(SecondNearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        TriggerOverride(SecondNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
    See(SecondNearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)  // SPWI899.SPL (Symbol, Fear)
    !CheckSpellState(NearestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
    !Gender(NearestEnemyOf(Myself),SUMMONED)
    !Kit(NearestEnemyOf(Myself),CAVALIER)
    !CheckSpellState(NearestEnemyOf(Myself),RESIST_FEAR)
    !General(NearestEnemyOf(Myself),UNDEAD)
    !Kit(NearestEnemyOf(Myself),Blackguard)
    !CheckSpellState(NearestEnemyOf(Myself),EXALTATION)
    OR(2)
        !CheckSpellState(NearestEnemyOf(Myself),PANIC_IMMUNITY_SEEN)
        !CheckSpellState(NearestEnemyOf(Myself),PANIC_IMMUNITY)
    !CheckStatGT(NearestEnemyOf(Myself),99,RESISTMAGIC)
    Allegiance(Myself,ENEMY)
    !Allegiance(NearestEnemyOf(Myself),ENEMY)
    !StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
    !StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
    OR(3)
        TriggerOverride(NearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        !TriggerOverride(NearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        !TriggerOverride(NearestEnemyOf(Myself),StateCheck(SecondNearestAllyOf(Myself),STATE_HELPLESS))
    OR(2)
        !TriggerOverride(NearestEnemyOf(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        TriggerOverride(NearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
    See(NearestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_NPC_SYMBOL_FEAR)  // SPWI899.SPL (Symbol, Fear)
    !CheckSpellState(LastSeenBy(Myself),DO_NOT_TARGET_SPELLS)
    !Gender(LastSeenBy(Myself),SUMMONED)
    !Kit(LastSeenBy(Myself),CAVALIER)
    !CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
    !General(LastSeenBy(Myself),UNDEAD)
    !Kit(LastSeenBy(Myself),Blackguard)
    !CheckSpellState(LastSeenBy(Myself),EXALTATION)
    OR(2)
        !CheckSpellState(LastSeenBy(Myself),PANIC_IMMUNITY_SEEN)
        !CheckSpellState(LastSeenBy(Myself),PANIC_IMMUNITY)
    !CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
    Allegiance(Myself,ENEMY)
    !Allegiance(LastSeenBy(Myself),ENEMY)
    !StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
    !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(LastSeenBy(Myself),0,HELD)
    !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
    OR(3)
        TriggerOverride(LastSeenBy(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        !TriggerOverride(LastSeenBy(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        !TriggerOverride(LastSeenBy(Myself),StateCheck(SecondNearestAllyOf(Myself),STATE_HELPLESS))
    OR(2)
        !TriggerOverride(LastSeenBy(Myself),StateCheck(NearestAllyOf(Myself),STATE_HELPLESS))
        TriggerOverride(LastSeenBy(Myself),Range(SecondNearestAllyOf(Myself),15))
    See(LastSeenBy(Myself))
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_FEAR)  // SPWI899.SPL (Symbol, Fear)
    RESPONSE #200
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Unholy Fireball)
    !CheckSpellState(ThirdFarthestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
    !CheckStatGT(ThirdFarthestEnemyOf(Myself),99,RESISTMAGIC)
    !CheckStatGT(ThirdFarthestEnemyOf(Myself),50,RESISTFIRE)
    !CheckStatGT(ThirdFarthestEnemyOf(Myself),0,MINORGLOBE)
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdFarthestEnemyOf(Myself),ENEMY)
    OR(3)
        TriggerOverride(ThirdFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(6)
        !TriggerOverride(ThirdFarthestEnemyOf(Myself),Range(NearestEnemyOfType([0.HUMANOID]),22))
        TriggerOverride(ThirdFarthestEnemyOf(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),59,RESISTFIRE))
        TriggerOverride(ThirdFarthestEnemyOf(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),59,RESISTMAGIC))
        TriggerOverride(ThirdFarthestEnemyOf(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),0,MINORGLOBE))
        TriggerOverride(ThirdFarthestEnemyOf(Myself),Race(NearestEnemyOfType([0.HUMANOID]),RAKSHASA))
        TriggerOverride(ThirdFarthestEnemyOf(Myself),Race(NearestEnemyOfType([0.HUMANOID]),LICH))
    See(ThirdFarthestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Unholy Fireball)
    !CheckSpellState(SecondFarthestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
    !CheckStatGT(SecondFarthestEnemyOf(Myself),99,RESISTMAGIC)
    !CheckStatGT(SecondFarthestEnemyOf(Myself),50,RESISTFIRE)
    !CheckStatGT(SecondFarthestEnemyOf(Myself),0,MINORGLOBE)
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondFarthestEnemyOf(Myself),ENEMY)
    OR(3)
        TriggerOverride(SecondFarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(6)
        !TriggerOverride(SecondFarthestEnemyOf(Myself),Range(NearestEnemyOfType([0.HUMANOID]),22))
        TriggerOverride(SecondFarthestEnemyOf(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),59,RESISTFIRE))
        TriggerOverride(SecondFarthestEnemyOf(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),59,RESISTMAGIC))
        TriggerOverride(SecondFarthestEnemyOf(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),0,MINORGLOBE))
        TriggerOverride(SecondFarthestEnemyOf(Myself),Race(NearestEnemyOfType([0.HUMANOID]),RAKSHASA))
        TriggerOverride(SecondFarthestEnemyOf(Myself),Race(NearestEnemyOfType([0.HUMANOID]),LICH))
    See(SecondFarthestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Unholy Fireball)
    !CheckSpellState(FarthestEnemyOf(Myself),DO_NOT_TARGET_SPELLS)
    !CheckStatGT(FarthestEnemyOf(Myself),99,RESISTMAGIC)
    !CheckStatGT(FarthestEnemyOf(Myself),50,RESISTFIRE)
    !CheckStatGT(FarthestEnemyOf(Myself),0,MINORGLOBE)
    Allegiance(Myself,ENEMY)
    !Allegiance(FarthestEnemyOf(Myself),ENEMY)
    OR(3)
        TriggerOverride(FarthestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(6)
        !TriggerOverride(FarthestEnemyOf(Myself),Range(NearestEnemyOfType([0.HUMANOID]),22))
        TriggerOverride(FarthestEnemyOf(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),59,RESISTFIRE))
        TriggerOverride(FarthestEnemyOf(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),59,RESISTMAGIC))
        TriggerOverride(FarthestEnemyOf(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),0,MINORGLOBE))
        TriggerOverride(FarthestEnemyOf(Myself),Race(NearestEnemyOfType([0.HUMANOID]),RAKSHASA))
        TriggerOverride(FarthestEnemyOf(Myself),Race(NearestEnemyOfType([0.HUMANOID]),LICH))
    See(FarthestEnemyOf(Myself))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Unholy Fireball)
    !CheckSpellState(LastSeenBy(Myself),DO_NOT_TARGET_SPELLS)
    !CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
    !CheckStatGT(LastSeenBy(Myself),50,RESISTFIRE)
    !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
    Allegiance(Myself,ENEMY)
    !Allegiance(LastSeenBy(Myself),ENEMY)
    OR(3)
        TriggerOverride(LastSeenBy(Myself),Range(NearestAllyOf(Myself),15))
        NumInParty(1)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(6)
        !TriggerOverride(LastSeenBy(Myself),Range(NearestEnemyOfType([0.HUMANOID]),22))
        TriggerOverride(LastSeenBy(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),59,RESISTFIRE))
        TriggerOverride(LastSeenBy(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),59,RESISTMAGIC))
        TriggerOverride(LastSeenBy(Myself),CheckStatGT(NearestEnemyOfType([0.HUMANOID]),0,MINORGLOBE))
        TriggerOverride(LastSeenBy(Myself),Race(NearestEnemyOfType([0.HUMANOID]),RAKSHASA))
        TriggerOverride(LastSeenBy(Myself),Race(NearestEnemyOfType([0.HUMANOID]),LICH))
    See(LastSeenBy(Myself))
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),DEATHKNIGHT_FIREBALL)  // SPIN701.SPL (Unholy Fireball)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    !CheckSpellState(ThirdNearest([PC]),DO_NOT_TARGET_SPELLS)
    !Gender(ThirdNearest([PC]),SUMMONED)
    !CheckStatGT(ThirdNearest([PC]),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(ThirdNearest([PC]),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(ThirdNearest([PC]),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(ThirdNearest([PC]),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    OR(2)
        !CheckStatGT(ThirdNearest([PC]),50,RESISTMAGIC)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !CheckSpellState(ThirdNearest([PC]),MIND_BLANK)
    See(ThirdNearest([PC]))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    !CheckSpellState(SecondNearest([PC]),DO_NOT_TARGET_SPELLS)
    !Gender(SecondNearest([PC]),SUMMONED)
    !CheckStatGT(SecondNearest([PC]),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(SecondNearest([PC]),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(SecondNearest([PC]),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(SecondNearest([PC]),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    OR(2)
        !CheckStatGT(SecondNearest([PC]),50,RESISTMAGIC)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !CheckSpellState(SecondNearest([PC]),MIND_BLANK)
    See(SecondNearest([PC]))
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    !CheckSpellState([PC],DO_NOT_TARGET_SPELLS)
    !Gender([PC],SUMMONED)
    !CheckStatGT([PC],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC],0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT([PC],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    OR(2)
        !CheckStatGT([PC],50,RESISTMAGIC)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !CheckSpellState([PC],MIND_BLANK)
    See([PC])
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    !CheckSpellState([PC.0.0.THIEF],DO_NOT_TARGET_SPELLS)
    !Gender([PC.0.0.THIEF],SUMMONED)
    !CheckStatGT([PC.0.0.THIEF],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.THIEF],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.THIEF],0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT([PC.0.0.THIEF],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    OR(2)
        !CheckStatGT([PC.0.0.THIEF],50,RESISTMAGIC)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !CheckSpellState([PC.0.0.THIEF],MIND_BLANK)
    See([PC.0.0.THIEF])
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    !CheckSpellState([PC.0.0.BARD],DO_NOT_TARGET_SPELLS)
    !Gender([PC.0.0.BARD],SUMMONED)
    !CheckStatGT([PC.0.0.BARD],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.BARD],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.BARD],0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT([PC.0.0.BARD],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    OR(2)
        !CheckStatGT([PC.0.0.BARD],50,RESISTMAGIC)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !CheckSpellState([PC.0.0.BARD],MIND_BLANK)
    See([PC.0.0.BARD])
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    !CheckSpellState([PC.0.0.FIGHTER_THIEF],DO_NOT_TARGET_SPELLS)
    !Gender([PC.0.0.FIGHTER_THIEF],SUMMONED)
    !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT([PC.0.0.FIGHTER_THIEF],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    OR(2)
        !CheckStatGT([PC.0.0.FIGHTER_THIEF],50,RESISTMAGIC)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.FIGHTER_THIEF],ENEMY)
    !CheckSpellState([PC.0.0.FIGHTER_THIEF],MIND_BLANK)
    See([PC.0.0.FIGHTER_THIEF])
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    !CheckSpellState([PC.0.0.PALADIN],DO_NOT_TARGET_SPELLS)
    !Gender([PC.0.0.PALADIN],SUMMONED)
    !CheckStatGT([PC.0.0.PALADIN],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.PALADIN],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.PALADIN],0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT([PC.0.0.PALADIN],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    OR(2)
        !CheckStatGT([PC.0.0.PALADIN],50,RESISTMAGIC)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.PALADIN],ENEMY)
    !CheckSpellState([PC.0.0.PALADIN],MIND_BLANK)
    See([PC.0.0.PALADIN])
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    !CheckSpellState([PC.0.0.RANGER],DO_NOT_TARGET_SPELLS)
    !Gender([PC.0.0.RANGER],SUMMONED)
    !CheckStatGT([PC.0.0.RANGER],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.RANGER],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.RANGER],0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT([PC.0.0.RANGER],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    OR(2)
        !CheckStatGT([PC.0.0.RANGER],50,RESISTMAGIC)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.RANGER],ENEMY)
    !CheckSpellState([PC.0.0.RANGER],MIND_BLANK)
    See([PC.0.0.RANGER])
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    !CheckSpellState([PC.0.0.FIGHTER],DO_NOT_TARGET_SPELLS)
    !Gender([PC.0.0.FIGHTER],SUMMONED)
    !CheckStatGT([PC.0.0.FIGHTER],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.FIGHTER],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.FIGHTER],0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT([PC.0.0.FIGHTER],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    OR(2)
        !CheckStatGT([PC.0.0.FIGHTER],50,RESISTMAGIC)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.FIGHTER],ENEMY)
    !CheckSpellState([PC.0.0.FIGHTER],MIND_BLANK)
    See([PC.0.0.FIGHTER])
    False()
THEN
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    !CheckSpellState(LastSeenBy(Myself),DO_NOT_TARGET_SPELLS)
    !Gender(LastSeenBy(Myself),SUMMONED)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    OR(2)
        !CheckStatGT(LastSeenBy(Myself),50,RESISTMAGIC)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Allegiance(Myself,ENEMY)
    !Allegiance(LastSeenBy(Myself),ENEMY)
    !CheckSpellState(LastSeenBy(Myself),MIND_BLANK)
    See(LastSeenBy(Myself))
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)  // SPWI815.SPL (Power Word Blind)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState([PC.0.0.MAGE],DO_NOT_TARGET_SPELLS)
    See([PC.0.0.MAGE])
    !CheckStatGT([PC.0.0.MAGE],99,RESISTMAGIC)
    !CheckStatGT([PC.0.0.MAGE],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.MAGE],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.MAGE],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState([PC.0.0.MAGE],CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState([PC.0.0.MAGE],STUN_IMMUNITY_SEEN)
        !CheckSpellState([PC.0.0.MAGE],STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    !CheckSpellState([PC.0.0.MAGE],MIND_BLANK)
    OR(3)
        HPPercentLT([PC.0.0.MAGE],60)
        Class([PC.0.0.MAGE],MAGE)
        Class([PC.0.0.MAGE],MAGE_THIEF)
    !CheckStatGT([PC.0.0.MAGE],50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell([PC.0.0.MAGE],WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState([PC.0.0.MAGE_THIEF],DO_NOT_TARGET_SPELLS)
    See([PC.0.0.MAGE_THIEF])
    !CheckStatGT([PC.0.0.MAGE_THIEF],99,RESISTMAGIC)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState([PC.0.0.MAGE_THIEF],CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState([PC.0.0.MAGE_THIEF],STUN_IMMUNITY_SEEN)
        !CheckSpellState([PC.0.0.MAGE_THIEF],STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    !CheckSpellState([PC.0.0.MAGE_THIEF],MIND_BLANK)
    OR(3)
        HPPercentLT([PC.0.0.MAGE_THIEF],60)
        Class([PC.0.0.MAGE_THIEF],MAGE)
        Class([PC.0.0.MAGE_THIEF],MAGE_THIEF)
    !CheckStatGT([PC.0.0.MAGE_THIEF],50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell([PC.0.0.MAGE_THIEF],WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState([PC.0.0.MAGE_ALL],DO_NOT_TARGET_SPELLS)
    See([PC.0.0.MAGE_ALL])
    !CheckStatGT([PC.0.0.MAGE_ALL],99,RESISTMAGIC)
    !CheckStatGT([PC.0.0.MAGE_ALL],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.MAGE_ALL],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.MAGE_ALL],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState([PC.0.0.MAGE_ALL],CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState([PC.0.0.MAGE_ALL],STUN_IMMUNITY_SEEN)
        !CheckSpellState([PC.0.0.MAGE_ALL],STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_ALL],ENEMY)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
    !CheckSpellState([PC.0.0.MAGE_ALL],MIND_BLANK)
    OR(3)
        HPPercentLT([PC.0.0.MAGE_ALL],60)
        Class([PC.0.0.MAGE_ALL],MAGE)
        Class([PC.0.0.MAGE_ALL],MAGE_THIEF)
    !CheckStatGT([PC.0.0.MAGE_ALL],50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell([PC.0.0.MAGE_ALL],WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState([PC.0.0.THIEF],DO_NOT_TARGET_SPELLS)
    See([PC.0.0.THIEF])
    !CheckStatGT([PC.0.0.THIEF],99,RESISTMAGIC)
    !CheckStatGT([PC.0.0.THIEF],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.THIEF],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.THIEF],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState([PC.0.0.THIEF],CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState([PC.0.0.THIEF],STUN_IMMUNITY_SEEN)
        !CheckSpellState([PC.0.0.THIEF],STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    !CheckSpellState([PC.0.0.THIEF],MIND_BLANK)
    OR(3)
        HPPercentLT([PC.0.0.THIEF],60)
        Class([PC.0.0.THIEF],MAGE)
        Class([PC.0.0.THIEF],MAGE_THIEF)
    !CheckStatGT([PC.0.0.THIEF],50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell([PC.0.0.THIEF],WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState([PC.0.0.BARD],DO_NOT_TARGET_SPELLS)
    See([PC.0.0.BARD])
    !CheckStatGT([PC.0.0.BARD],99,RESISTMAGIC)
    !CheckStatGT([PC.0.0.BARD],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.BARD],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.BARD],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState([PC.0.0.BARD],CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState([PC.0.0.BARD],STUN_IMMUNITY_SEEN)
        !CheckSpellState([PC.0.0.BARD],STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
    !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    !CheckSpellState([PC.0.0.BARD],MIND_BLANK)
    OR(3)
        HPPercentLT([PC.0.0.BARD],60)
        Class([PC.0.0.BARD],MAGE)
        Class([PC.0.0.BARD],MAGE_THIEF)
    !CheckStatGT([PC.0.0.BARD],50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell([PC.0.0.BARD],WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState([PC.0.0.THIEF_ALL],DO_NOT_TARGET_SPELLS)
    See([PC.0.0.THIEF_ALL])
    !CheckStatGT([PC.0.0.THIEF_ALL],99,RESISTMAGIC)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState([PC.0.0.THIEF_ALL],CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState([PC.0.0.THIEF_ALL],STUN_IMMUNITY_SEEN)
        !CheckSpellState([PC.0.0.THIEF_ALL],STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    !CheckSpellState([PC.0.0.THIEF_ALL],MIND_BLANK)
    OR(3)
        HPPercentLT([PC.0.0.THIEF_ALL],60)
        Class([PC.0.0.THIEF_ALL],MAGE)
        Class([PC.0.0.THIEF_ALL],MAGE_THIEF)
    !CheckStatGT([PC.0.0.THIEF_ALL],50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell([PC.0.0.THIEF_ALL],WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState([PC.0.0.CLERIC],DO_NOT_TARGET_SPELLS)
    See([PC.0.0.CLERIC])
    !CheckStatGT([PC.0.0.CLERIC],99,RESISTMAGIC)
    !CheckStatGT([PC.0.0.CLERIC],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC.0.0.CLERIC],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC.0.0.CLERIC],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState([PC.0.0.CLERIC],CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState([PC.0.0.CLERIC],STUN_IMMUNITY_SEEN)
        !CheckSpellState([PC.0.0.CLERIC],STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
    !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    !CheckSpellState([PC.0.0.CLERIC],MIND_BLANK)
    OR(3)
        HPPercentLT([PC.0.0.CLERIC],60)
        Class([PC.0.0.CLERIC],MAGE)
        Class([PC.0.0.CLERIC],MAGE_THIEF)
    !CheckStatGT([PC.0.0.CLERIC],50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell([PC.0.0.CLERIC],WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState([PC],DO_NOT_TARGET_SPELLS)
    See([PC])
    !CheckStatGT([PC],99,RESISTMAGIC)
    !CheckStatGT([PC],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState([PC],CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState([PC],STUN_IMMUNITY_SEEN)
        !CheckSpellState([PC],STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    !CheckSpellState([PC],MIND_BLANK)
    OR(3)
        HPPercentLT([PC],60)
        Class([PC],MAGE)
        Class([PC],MAGE_THIEF)
    !CheckStatGT([PC],50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell([PC],WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState(SecondNearest([PC]),DO_NOT_TARGET_SPELLS)
    See(SecondNearest([PC]))
    !CheckStatGT(SecondNearest([PC]),99,RESISTMAGIC)
    !CheckStatGT(SecondNearest([PC]),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(SecondNearest([PC]),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(SecondNearest([PC]),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState(SecondNearest([PC]),CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState(SecondNearest([PC]),STUN_IMMUNITY_SEEN)
        !CheckSpellState(SecondNearest([PC]),STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    !CheckSpellState(SecondNearest([PC]),MIND_BLANK)
    OR(3)
        HPPercentLT(SecondNearest([PC]),60)
        Class(SecondNearest([PC]),MAGE)
        Class(SecondNearest([PC]),MAGE_THIEF)
    !CheckStatGT(SecondNearest([PC]),50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell(SecondNearest([PC]),WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState(ThirdNearest([PC]),DO_NOT_TARGET_SPELLS)
    See(ThirdNearest([PC]))
    !CheckStatGT(ThirdNearest([PC]),99,RESISTMAGIC)
    !CheckStatGT(ThirdNearest([PC]),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(ThirdNearest([PC]),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(ThirdNearest([PC]),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState(ThirdNearest([PC]),CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState(ThirdNearest([PC]),STUN_IMMUNITY_SEEN)
        !CheckSpellState(ThirdNearest([PC]),STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    !CheckSpellState(ThirdNearest([PC]),MIND_BLANK)
    OR(3)
        HPPercentLT(ThirdNearest([PC]),60)
        Class(ThirdNearest([PC]),MAGE)
        Class(ThirdNearest([PC]),MAGE_THIEF)
    !CheckStatGT(ThirdNearest([PC]),50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell(ThirdNearest([PC]),WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState([PC],DO_NOT_TARGET_SPELLS)
    See([PC])
    !CheckStatGT([PC],99,RESISTMAGIC)
    !CheckStatGT([PC],0,WIZARD_SPELL_TURNING)
    !CheckStatGT([PC],0,WIZARD_SPELL_TRAP)
    !CheckStatGT([PC],0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState([PC],CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState([PC],STUN_IMMUNITY_SEEN)
        !CheckSpellState([PC],STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    !CheckSpellState([PC],MIND_BLANK)
    OR(3)
        HPPercentLT([PC],60)
        Class([PC],MAGE)
        Class([PC],MAGE_THIEF)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell([PC],WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState(SecondNearest([PC]),DO_NOT_TARGET_SPELLS)
    See(SecondNearest([PC]))
    !CheckStatGT(SecondNearest([PC]),99,RESISTMAGIC)
    !CheckStatGT(SecondNearest([PC]),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(SecondNearest([PC]),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(SecondNearest([PC]),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState(SecondNearest([PC]),CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState(SecondNearest([PC]),STUN_IMMUNITY_SEEN)
        !CheckSpellState(SecondNearest([PC]),STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    !CheckSpellState(SecondNearest([PC]),MIND_BLANK)
    OR(3)
        HPPercentLT(SecondNearest([PC]),60)
        Class(SecondNearest([PC]),MAGE)
        Class(SecondNearest([PC]),MAGE_THIEF)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell(SecondNearest([PC]),WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    !AreaCheck("ar3004")
    !GlobalTimerNotExpired("castspell","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    !CheckSpellState(ThirdNearest([PC]),DO_NOT_TARGET_SPELLS)
    See(ThirdNearest([PC]))
    !CheckStatGT(ThirdNearest([PC]),99,RESISTMAGIC)
    !CheckStatGT(ThirdNearest([PC]),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(ThirdNearest([PC]),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(ThirdNearest([PC]),0,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckSpellState(ThirdNearest([PC]),CHAOTIC_COMMANDS)
    OR(2)
        !CheckSpellState(ThirdNearest([PC]),STUN_IMMUNITY_SEEN)
        !CheckSpellState(ThirdNearest([PC]),STUN_IMMUNITY)
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    !CheckSpellState(ThirdNearest([PC]),MIND_BLANK)
    OR(3)
        HPPercentLT(ThirdNearest([PC]),60)
        Class(ThirdNearest([PC]),MAGE)
        Class(ThirdNearest([PC]),MAGE_THIEF)
THEN
    RESPONSE #100
        SetGlobalTimer("castspell","LOCALS",ONE_ROUND)
        Spell(ThirdNearest([PC]),WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word Stun)
    RESPONSE #100
        Continue()
END

IF
    See(LastTargetedBy(Myself))
    Global("validtarget","LOCALS",1)
    OR(2)
        !WeaponEffectiveVs(LastTargetedBy(Myself),MAINHAND)
        !WeaponCanDamage(LastTargetedBy(Myself),MAINHAND)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",0)
        ClearActions(Myself)
END

IF
    See([PC.0.0.MAGE])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    !StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.MAGE],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
    !HPPercentGT([PC.0.0.MAGE],20)
    Range([PC.0.0.MAGE],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE])
END

IF
    See([PC.0.0.MAGE_THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
    !HPPercentGT([PC.0.0.MAGE_THIEF],20)
    Range([PC.0.0.MAGE_THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
    See([PC.0.0.MAGE_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_ALL],ENEMY)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.MAGE_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
    !HPPercentGT([PC.0.0.MAGE_ALL],20)
    Range([PC.0.0.MAGE_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_ALL])
END

IF
    See([PC.0.0.THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    !StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
    !HPPercentGT([PC.0.0.THIEF],20)
    Range([PC.0.0.THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF])
END

IF
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
    !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    !StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.BARD],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.BARD],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.BARD],0,STONESKINS)
    !HPPercentGT([PC.0.0.BARD],20)
    Range([PC.0.0.BARD],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.BARD])
END

IF
    See([PC.0.0.THIEF_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
    !HPPercentGT([PC.0.0.THIEF_ALL],20)
    Range([PC.0.0.THIEF_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
    See([PC.0.0.CLERIC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
    !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    !StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.CLERIC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.CLERIC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
    !HPPercentGT([PC.0.0.CLERIC],20)
    Range([PC.0.0.CLERIC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.CLERIC])
END

IF
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    !StateCheck([PC],STATE_MIRRORIMAGE)
    CheckStatLT([PC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC],0,STONESKINS)
    !HPPercentGT([PC],20)
    Range([PC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC])
END

IF
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    !StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
    CheckStatLT(SecondNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT(SecondNearest([PC]),0,STONESKINS)
    !HPPercentGT(SecondNearest([PC]),20)
    Range(SecondNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearest([PC]))
END

IF
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    !StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
    CheckStatLT(ThirdNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
    !HPPercentGT(ThirdNearest([PC]),20)
    Range(ThirdNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearest([PC]))
END

IF
    See([PC.0.0.MAGE])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    !StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.MAGE],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
    !HPPercentGT([PC.0.0.MAGE],50)
    Range([PC.0.0.MAGE],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE])
END

IF
    See([PC.0.0.MAGE_THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
    !HPPercentGT([PC.0.0.MAGE_THIEF],50)
    Range([PC.0.0.MAGE_THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
    See([PC.0.0.MAGE_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_ALL],ENEMY)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.MAGE_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
    !HPPercentGT([PC.0.0.MAGE_ALL],50)
    Range([PC.0.0.MAGE_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_ALL])
END

IF
    See([PC.0.0.THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    !StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
    !HPPercentGT([PC.0.0.THIEF],50)
    Range([PC.0.0.THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF])
END

IF
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
    !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    !StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.BARD],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.BARD],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.BARD],0,STONESKINS)
    !HPPercentGT([PC.0.0.BARD],50)
    Range([PC.0.0.BARD],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.BARD])
END

IF
    See([PC.0.0.THIEF_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
    !HPPercentGT([PC.0.0.THIEF_ALL],50)
    Range([PC.0.0.THIEF_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
    See([PC.0.0.CLERIC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
    !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    !StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.CLERIC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.CLERIC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
    !HPPercentGT([PC.0.0.CLERIC],50)
    Range([PC.0.0.CLERIC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.CLERIC])
END

IF
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    !StateCheck([PC],STATE_MIRRORIMAGE)
    CheckStatLT([PC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC],0,STONESKINS)
    !HPPercentGT([PC],50)
    Range([PC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC])
END

IF
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    !StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
    CheckStatLT(SecondNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT(SecondNearest([PC]),0,STONESKINS)
    !HPPercentGT(SecondNearest([PC]),50)
    Range(SecondNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearest([PC]))
END

IF
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    !StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
    CheckStatLT(ThirdNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
    !HPPercentGT(ThirdNearest([PC]),50)
    Range(ThirdNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearest([PC]))
END

IF
    See([PC.0.0.MAGE])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    !StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.MAGE],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
    Range([PC.0.0.MAGE],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE])
END

IF
    See([PC.0.0.MAGE_THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
    Range([PC.0.0.MAGE_THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
    See([PC.0.0.MAGE_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_ALL],ENEMY)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.MAGE_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.MAGE_ALL],0,STONESKINS)
    Range([PC.0.0.MAGE_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_ALL])
END

IF
    See([PC.0.0.THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    !StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
    Range([PC.0.0.THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF])
END

IF
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
    !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    !StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.BARD],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.BARD],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.BARD],0,STONESKINS)
    Range([PC.0.0.BARD],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.BARD])
END

IF
    See([PC.0.0.THIEF_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.THIEF_ALL],0,STONESKINS)
    Range([PC.0.0.THIEF_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
    See([PC.0.0.CLERIC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
    !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    !StateCheck([PC.0.0.CLERIC],STATE_MIRRORIMAGE)
    CheckStatLT([PC.0.0.CLERIC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.CLERIC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC.0.0.CLERIC],0,STONESKINS)
    Range([PC.0.0.CLERIC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.CLERIC])
END

IF
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    !StateCheck([PC],STATE_MIRRORIMAGE)
    CheckStatLT([PC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT([PC],0,STONESKINS)
    Range([PC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC])
END

IF
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    !StateCheck(SecondNearest([PC]),STATE_MIRRORIMAGE)
    CheckStatLT(SecondNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT(SecondNearest([PC]),0,STONESKINS)
    Range(SecondNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearest([PC]))
END

IF
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    !StateCheck(ThirdNearest([PC]),STATE_MIRRORIMAGE)
    CheckStatLT(ThirdNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !CheckStatGT(ThirdNearest([PC]),0,STONESKINS)
    Range(ThirdNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearest([PC]))
END

IF
    See([PC.0.0.MAGE])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    CheckStatLT([PC.0.0.MAGE],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range([PC.0.0.MAGE],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE])
END

IF
    See([PC.0.0.MAGE_THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range([PC.0.0.MAGE_THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_THIEF])
END

IF
    See([PC.0.0.MAGE_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_ALL],ENEMY)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
    CheckStatLT([PC.0.0.MAGE_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range([PC.0.0.MAGE_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.MAGE_ALL])
END

IF
    See([PC.0.0.THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    CheckStatLT([PC.0.0.THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range([PC.0.0.THIEF],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF])
END

IF
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_IMMOBILE)
    !StateCheck([PC.0.0.BARD],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    CheckStatLT([PC.0.0.BARD],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.BARD],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range([PC.0.0.BARD],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.BARD])
END

IF
    See([PC.0.0.THIEF_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_IMMOBILE)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range([PC.0.0.THIEF_ALL],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.THIEF_ALL])
END

IF
    See([PC.0.0.CLERIC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_IMMOBILE)
    !StateCheck([PC.0.0.CLERIC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    CheckStatLT([PC.0.0.CLERIC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.CLERIC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range([PC.0.0.CLERIC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC.0.0.CLERIC])
END

IF
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_IMMOBILE)
    !StateCheck([PC],STATE_FEEBLEMINDED)
    !CheckStatGT([PC],0,HELD)
    CheckStatLT([PC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range([PC],4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound([PC])
END

IF
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_IMMOBILE)
    !StateCheck(SecondNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    CheckStatLT(SecondNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range(SecondNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearest([PC]))
END

IF
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_IMMOBILE)
    !StateCheck(ThirdNearest([PC]),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    CheckStatLT(ThirdNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range(ThirdNearest([PC]),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearest([PC]))
END

IF
    See(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(NearestEnemyOf(Myself),ENEMY)
    !StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
    CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(NearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range(NearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(NearestEnemyOf(Myself))
END

IF
    See(SecondNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
    CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range(SecondNearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearestEnemyOf(Myself))
END

IF
    See(ThirdNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
    !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
    CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range(ThirdNearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearestEnemyOf(Myself))
END

IF
    See(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(NearestEnemyOf(Myself),ENEMY)
    CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(NearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range(NearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(NearestEnemyOf(Myself))
END

IF
    See(SecondNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
    CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range(SecondNearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(SecondNearestEnemyOf(Myself))
END

IF
    See(ThirdNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
    CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    Range(ThirdNearestEnemyOf(Myself),4)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(ThirdNearestEnemyOf(Myself))
END

IF
    !CanEquipRanged()
    ActionListEmpty()
    Allegiance(Myself,ENEMY)
    !GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("targetcompromise","LOCALS",FOUR_ROUNDS)
END

IF
    HasItem("dw#move0",Myself)  // Mirror
THEN
    RESPONSE #100
        NoAction()
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(NearestEnemyOf(Myself),ENEMY)
    CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(NearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
        StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
    Range(NearestEnemyOf(Myself),10)
THEN
    RESPONSE #100
        MoveToObject(NearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See(SecondNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
    CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
        StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
    Range(SecondNearestEnemyOf(Myself),10)
THEN
    RESPONSE #100
        MoveToObject(SecondNearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See(ThirdNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
    CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
        StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
    Range(ThirdNearestEnemyOf(Myself),10)
THEN
    RESPONSE #100
        MoveToObject(ThirdNearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See(FourthNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(FourthNearestEnemyOf(Myself),ENEMY)
    CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
        StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
    Range(FourthNearestEnemyOf(Myself),10)
THEN
    RESPONSE #100
        MoveToObject(FourthNearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See(FifthNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(FifthNearestEnemyOf(Myself),ENEMY)
    CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
        StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
    Range(FifthNearestEnemyOf(Myself),10)
THEN
    RESPONSE #100
        MoveToObject(FifthNearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See(SixthNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(SixthNearestEnemyOf(Myself),ENEMY)
    CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    OR(2)
        StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
        StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
    Range(SixthNearestEnemyOf(Myself),10)
THEN
    RESPONSE #100
        MoveToObject(SixthNearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See([PC.0.0.MAGE])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_DISABLED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    CheckStatLT([PC.0.0.MAGE],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !HPPercentGT([PC.0.0.MAGE],40)
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.MAGE])
END

IF
    ActionListEmpty()
    See([PC.0.0.MAGE_THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !HPPercentGT([PC.0.0.MAGE_THIEF],40)
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.MAGE_THIEF])
END

IF
    ActionListEmpty()
    See([PC.0.0.MAGE_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_ALL],ENEMY)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_DISABLED)
    !CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
    CheckStatLT([PC.0.0.MAGE_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !HPPercentGT([PC.0.0.MAGE_ALL],40)
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.MAGE_ALL])
END

IF
    ActionListEmpty()
    See([PC.0.0.THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_DISABLED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    CheckStatLT([PC.0.0.THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !HPPercentGT([PC.0.0.THIEF],40)
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.THIEF])
END

IF
    ActionListEmpty()
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_DISABLED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    CheckStatLT([PC.0.0.BARD],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.BARD],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !HPPercentGT([PC.0.0.BARD],40)
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.BARD])
END

IF
    ActionListEmpty()
    See([PC.0.0.THIEF_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !HPPercentGT([PC.0.0.THIEF_ALL],40)
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.THIEF_ALL])
END

IF
    ActionListEmpty()
    See([PC.0.0.CLERIC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    CheckStatLT([PC.0.0.CLERIC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.CLERIC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !HPPercentGT([PC.0.0.CLERIC],40)
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.CLERIC])
END

IF
    ActionListEmpty()
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_DISABLED)
    !CheckStatGT([PC],0,HELD)
    CheckStatLT([PC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !HPPercentGT([PC],40)
THEN
    RESPONSE #100
        MoveToObject([PC])
END

IF
    ActionListEmpty()
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_DISABLED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    CheckStatLT(SecondNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !HPPercentGT(SecondNearest([PC]),40)
THEN
    RESPONSE #100
        MoveToObject(SecondNearest([PC]))
END

IF
    ActionListEmpty()
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_DISABLED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    CheckStatLT(ThirdNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
    !HPPercentGT(ThirdNearest([PC]),40)
THEN
    RESPONSE #100
        MoveToObject(ThirdNearest([PC]))
END

IF
    ActionListEmpty()
    See([PC.0.0.MAGE])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE],ENEMY)
    !StateCheck([PC.0.0.MAGE],STATE_DISABLED)
    !CheckStatGT([PC.0.0.MAGE],0,HELD)
    CheckStatLT([PC.0.0.MAGE],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.MAGE])
END

IF
    ActionListEmpty()
    See([PC.0.0.MAGE_THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_THIEF],ENEMY)
    !StateCheck([PC.0.0.MAGE_THIEF],STATE_DISABLED)
    !CheckStatGT([PC.0.0.MAGE_THIEF],0,HELD)
    CheckStatLT([PC.0.0.MAGE_THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.MAGE_THIEF])
END

IF
    ActionListEmpty()
    See([PC.0.0.MAGE_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.MAGE_ALL],ENEMY)
    !StateCheck([PC.0.0.MAGE_ALL],STATE_DISABLED)
    !CheckStatGT([PC.0.0.MAGE_ALL],0,HELD)
    CheckStatLT([PC.0.0.MAGE_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.MAGE_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.MAGE_ALL])
END

IF
    ActionListEmpty()
    See([PC.0.0.THIEF])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF],ENEMY)
    !StateCheck([PC.0.0.THIEF],STATE_DISABLED)
    !CheckStatGT([PC.0.0.THIEF],0,HELD)
    CheckStatLT([PC.0.0.THIEF],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.THIEF])
END

IF
    ActionListEmpty()
    See([PC.0.0.BARD])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.BARD],ENEMY)
    !StateCheck([PC.0.0.BARD],STATE_DISABLED)
    !CheckStatGT([PC.0.0.BARD],0,HELD)
    CheckStatLT([PC.0.0.BARD],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.BARD],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.BARD])
END

IF
    ActionListEmpty()
    See([PC.0.0.THIEF_ALL])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.THIEF_ALL],ENEMY)
    !StateCheck([PC.0.0.THIEF_ALL],STATE_DISABLED)
    !CheckStatGT([PC.0.0.THIEF_ALL],0,HELD)
    CheckStatLT([PC.0.0.THIEF_ALL],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.THIEF_ALL],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.THIEF_ALL])
END

IF
    ActionListEmpty()
    See([PC.0.0.CLERIC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC.0.0.CLERIC],ENEMY)
    !StateCheck([PC.0.0.CLERIC],STATE_DISABLED)
    !CheckStatGT([PC.0.0.CLERIC],0,HELD)
    CheckStatLT([PC.0.0.CLERIC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC.0.0.CLERIC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject([PC.0.0.CLERIC])
END

IF
    ActionListEmpty()
    See([PC])
    Allegiance(Myself,ENEMY)
    !Allegiance([PC],ENEMY)
    !StateCheck([PC],STATE_DISABLED)
    !CheckStatGT([PC],0,HELD)
    CheckStatLT([PC],100,RESISTSLASHING)
    OR(2)
        CheckStatLT([PC],75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject([PC])
END

IF
    ActionListEmpty()
    See(SecondNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearest([PC]),ENEMY)
    !StateCheck(SecondNearest([PC]),STATE_DISABLED)
    !CheckStatGT(SecondNearest([PC]),0,HELD)
    CheckStatLT(SecondNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SecondNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject(SecondNearest([PC]))
END

IF
    ActionListEmpty()
    See(ThirdNearest([PC]))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearest([PC]),ENEMY)
    !StateCheck(ThirdNearest([PC]),STATE_DISABLED)
    !CheckStatGT(ThirdNearest([PC]),0,HELD)
    CheckStatLT(ThirdNearest([PC]),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(ThirdNearest([PC]),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject(ThirdNearest([PC]))
END

IF
    ActionListEmpty()
    See(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(NearestEnemyOf(Myself),ENEMY)
    !StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
    !CheckStatGT(NearestEnemyOf(Myself),0,HELD)
    CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(NearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject(NearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See(SecondNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(SecondNearestEnemyOf(Myself),ENEMY)
    !StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
    !CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
    CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SecondNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject(SecondNearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See(ThirdNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(ThirdNearestEnemyOf(Myself),ENEMY)
    !StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
    !CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
    CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(ThirdNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject(ThirdNearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See(FourthNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(FourthNearestEnemyOf(Myself),ENEMY)
    !StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
    !CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
    CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(FourthNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject(FourthNearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See(FifthNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(FifthNearestEnemyOf(Myself),ENEMY)
    !StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
    !CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
    CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(FifthNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject(FifthNearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    See(SixthNearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
    !Allegiance(SixthNearestEnemyOf(Myself),ENEMY)
    !StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
    !CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
    CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTSLASHING)
    OR(2)
        CheckStatLT(SixthNearestEnemyOf(Myself),75,RESISTSLASHING)
        GlobalTimerNotExpired("targetcompromise","LOCALS")
THEN
    RESPONSE #100
        MoveToObject(SixthNearestEnemyOf(Myself))
END

IF
    See(Player4)
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(Player4)
END

IF
    See(Player5)
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(Player5)
END

IF
    See(Player6)
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(Player6)
END

IF
    See(Player3)
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(Player3)
END

IF
    See(Player2)
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(Player2)
END

IF
    See(Player1)
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(Player1)
END

IF
    See(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(NearestEnemyOf(Myself))
END

IF
    See(NearestEnemyOf(Myself))
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
        SetGlobal("validtarget","LOCALS",1)
        EquipMostDamagingMelee()
        AttackOneRound(NearestEnemyOf(Myself))
END

IF
    ActionListEmpty()
    Global("inafight","LOCALS",1)
    Allegiance(Myself,ENEMY)
    !See(NearestEnemyOf(Myself))
    Global("chasing","LOCALS",0)
    !Global("chasePC","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobalTimer("chasetimer","LOCALS",8)
        SetGlobal("chasing","LOCALS",1)
END

IF
    !Global("DMWWNoFiendTeleport","GLOBAL",1)
    ActionListEmpty()
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",1)
    Global("inafight","LOCALS",1)
    Allegiance(Myself,ENEMY)
    InMyArea(Player1)
    !AreaCheck("ar3004")
    !AreaCheck("ar2202")
    !CheckStatGT(Player1,0,SANCTUARY)
THEN
    RESPONSE #100
        ReallyForceSpellRES("dw#fitel",Player1)  // Teleport Without Error
END

IF
    !Global("DMWWNoFiendTeleport","GLOBAL",1)
    ActionListEmpty()
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",2)
    Global("inafight","LOCALS",1)
    Allegiance(Myself,ENEMY)
    InMyArea(Player2)
    !AreaCheck("ar3004")
    !AreaCheck("ar2202")
    !CheckStatGT(Player2,0,SANCTUARY)
THEN
    RESPONSE #100
        ReallyForceSpellRES("dw#fitel",Player2)  // Teleport Without Error
END

IF
    !Global("DMWWNoFiendTeleport","GLOBAL",1)
    ActionListEmpty()
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",3)
    Global("inafight","LOCALS",1)
    Allegiance(Myself,ENEMY)
    InMyArea(Player3)
    !AreaCheck("ar3004")
    !AreaCheck("ar2202")
    !CheckStatGT(Player3,0,SANCTUARY)
THEN
    RESPONSE #100
        ReallyForceSpellRES("dw#fitel",Player3)  // Teleport Without Error
END

IF
    !Global("DMWWNoFiendTeleport","GLOBAL",1)
    ActionListEmpty()
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",4)
    Global("inafight","LOCALS",1)
    Allegiance(Myself,ENEMY)
    InMyArea(Player4)
    !AreaCheck("ar3004")
    !AreaCheck("ar2202")
    !CheckStatGT(Player4,0,SANCTUARY)
THEN
    RESPONSE #100
        ReallyForceSpellRES("dw#fitel",Player4)  // Teleport Without Error
END

IF
    !Global("DMWWNoFiendTeleport","GLOBAL",1)
    ActionListEmpty()
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",5)
    Global("inafight","LOCALS",1)
    Allegiance(Myself,ENEMY)
    InMyArea(Player5)
    !AreaCheck("ar3004")
    !AreaCheck("ar2202")
    !CheckStatGT(Player5,0,SANCTUARY)
THEN
    RESPONSE #100
        ReallyForceSpellRES("dw#fitel",Player5)  // Teleport Without Error
END

IF
    !Global("DMWWNoFiendTeleport","GLOBAL",1)
    ActionListEmpty()
    !INI("DMWW_durlag_difficulty",1)
    OR(2)
        DifficultyGT(EASIEST)
        !INI("DMWW_durlag_difficulty",0)
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",6)
    Global("inafight","LOCALS",1)
    Allegiance(Myself,ENEMY)
    InMyArea(Player6)
    !AreaCheck("ar3004")
    !AreaCheck("ar2202")
    !CheckStatGT(Player6,0,SANCTUARY)
THEN
    RESPONSE #100
        ReallyForceSpellRES("dw#fitel",Player6)  // Teleport Without Error
END

IF
    !See(NearestEnemyOf(Myself))
    !Detect(Player1)
    !StateCheck(Player1,STATE_INVISIBLE)
    !CheckStatGT(Player1,0,SANCTUARY)
    ActionListEmpty()
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",1)
THEN
    RESPONSE #100
        MoveToObject(Player1)
END

IF
    !See(NearestEnemyOf(Myself))
    !Detect(Player2)
    !StateCheck(Player2,STATE_INVISIBLE)
    !CheckStatGT(Player2,0,SANCTUARY)
    ActionListEmpty()
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",2)
THEN
    RESPONSE #100
        MoveToObject(Player2)
END

IF
    !See(NearestEnemyOf(Myself))
    !Detect(Player3)
    !StateCheck(Player3,STATE_INVISIBLE)
    !CheckStatGT(Player3,0,SANCTUARY)
    ActionListEmpty()
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",3)
THEN
    RESPONSE #100
        MoveToObject(Player3)
END

IF
    !See(NearestEnemyOf(Myself))
    !Detect(Player4)
    !StateCheck(Player4,STATE_INVISIBLE)
    !CheckStatGT(Player4,0,SANCTUARY)
    ActionListEmpty()
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",4)
THEN
    RESPONSE #100
        MoveToObject(Player4)
END

IF
    !See(NearestEnemyOf(Myself))
    !Detect(Player5)
    !StateCheck(Player5,STATE_INVISIBLE)
    !CheckStatGT(Player5,0,SANCTUARY)
    ActionListEmpty()
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",5)
THEN
    RESPONSE #100
        MoveToObject(Player5)
END

IF
    !See(NearestEnemyOf(Myself))
    !Detect(Player6)
    !StateCheck(Player6,STATE_INVISIBLE)
    !CheckStatGT(Player6,0,SANCTUARY)
    ActionListEmpty()
    GlobalTimerNotExpired("chasetimer","LOCALS")
    Global("chasePC","LOCALS",6)
THEN
    RESPONSE #100
        MoveToObject(Player6)
END

