LAM load_secondary_types
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/17.tpa" // Flesh Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/19.tpa" // Stone Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/1a.tpa" // Iron Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/1b.tpa" // Bone Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/21.tpa" // Juggernaut Golem
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/golem/43.tpa" // Snow Golem
