import { describe, expect, it } from "vitest";
import { Creature } from "../../model/creature/creature";
import { CreatureData } from "../../model/creature/data";
import adjustmentService from "./adjustment.service";

function fakeCreature(p: {
  data?: Partial<CreatureData>;
  dualWielding?: boolean;
  adjustments?: {
    files: string[];
    noWeapon?: boolean;
    data: Partial<CreatureData>;
  }[];
}): Creature {
  const data: CreatureData = {
    level1: { pnpValue: 5, type: "none", value: 5 },
    movement: { pnpValue: 12 },
    strength: 10,
    dexterity: 12,
    constitution: 12,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
    hp: 40,
    ac: 5,
    thac0: 15,
    apr: 2,
    doubleApr: false,
    xpv: 500,
    alignment: "NEUTRAL",
    morale: 10,
    size: "Large",
    script: { remove: [] },
    proficiencies: [],
    immunities: [],
    items: { equipped: [], remove: [] },
    spells: { memorized: [] },
    effects: { list: [] },
    ...p.data,
  } as unknown as CreatureData;

  return {
    data,
    id: 1,
    attack: { dualWielding: p.dualWielding ?? false },
    adjustments: (p.adjustments ?? []).map((a) => ({
      files: a.files,
      noWeapon: a.noWeapon ?? false,
      summon: false,
      scriptName: false,
      data: {
        script: { remove: [] },
        proficiencies: [],
        immunities: [],
        items: { equipped: [], remove: [] },
        spells: { memorized: [] },
        effects: { list: [] },
        ...a.data,
      },
    })),
  } as unknown as Creature;
}

describe("adjustmentService.getEffectiveAdjustments", () => {
  it("returns an empty array when the creature has no adjustments", () => {
    expect(adjustmentService.getEffectiveAdjustments(fakeCreature({}))).toEqual([]);
  });

  it("folds cumulative adjustments per file (later entry wins) and groups files with an identical result", () => {
    // Reproduces the real Ogre chieftain case (lib/creatures/ogres.ts:463-493): three separate
    // adjustment entries touch BDSOGR1/BDSOGR2, one of which (the weapon swap) also covers
    // AC#FP2OT, and one file (AC#WRIM1) is only ever touched by the first entry.
    const creature = fakeCreature({
      adjustments: [
        {
          files: ["AC#WRIM1", "BDSOGR1", "BDSOGR2"],
          data: { level1: { pnpValue: 7, type: "none", value: 7 }, ac: 2, xpv: 975 },
        },
        {
          files: ["AC#FP2OT", "BDSOGR1", "BDSOGR2"],
          noWeapon: true,
          data: {},
        },
        {
          files: ["BDSOGR1", "BDSOGR2"],
          data: { xpv: 1000 },
        },
      ],
    });

    const effectives = adjustmentService.getEffectiveAdjustments(creature);

    const bdsogr = effectives.find((e) => e.files.includes("BDSOGR1"));
    expect(bdsogr?.files).toEqual(["BDSOGR1", "BDSOGR2"]);
    expect(bdsogr?.level).toEqual({ value: 7, changed: true });
    expect(bdsogr?.ac).toEqual({ value: 2, changed: true });
    expect(bdsogr?.xpv).toEqual({ value: 1000, changed: true }); // third entry's xpv wins over the first's
    expect(bdsogr?.noWeapon).toBe(true);

    const acWrim = effectives.find((e) => e.files.includes("AC#WRIM1"));
    expect(acWrim?.files).toEqual(["AC#WRIM1"]);
    expect(acWrim?.xpv).toEqual({ value: 975, changed: true });
    expect(acWrim?.noWeapon).toBe(false);

    const acFp2ot = effectives.find((e) => e.files.includes("AC#FP2OT"));
    expect(acFp2ot?.files).toEqual(["AC#FP2OT"]);
    expect(acFp2ot?.noWeapon).toBe(true);
    expect(acFp2ot?.level).toEqual({ value: 5, changed: false }); // inherited from the base
    expect(acFp2ot?.xpv).toEqual({ value: 500, changed: false });
  });

  it("excludes a file whose only authored change is to a field with no doc presence (e.g. class)", () => {
    const creature = fakeCreature({
      adjustments: [{ files: ["WELT"], data: { class: "INNOCENT" } }],
    });

    expect(adjustmentService.getEffectiveAdjustments(creature)).toEqual([]);
  });

  it("still produces an entry for a file whose only change is noWeapon", () => {
    const creature = fakeCreature({
      adjustments: [{ files: ["KAHRK"], noWeapon: true, data: {} }],
    });

    const effectives = adjustmentService.getEffectiveAdjustments(creature);

    expect(effectives).toEqual([expect.objectContaining({ files: ["KAHRK"], noWeapon: true })]);
  });

  // creatureService.checkData autogenerates hp/thac0 for every adjustment (from bonusHp,
  // constitution, etc.) even when the adjustment never touches hp/thac0 directly - so by the time
  // this runs, an adjustment driven purely by bonusHp already has its own final hp/thac0 baked
  // into `.data`. changed must reflect whether that final value actually differs from the base's
  // own - not merely that hp/thac0 are always present.
  it("flags hp/thac0 changed only when the autogenerated final value actually differs from the base", () => {
    const creature = fakeCreature({
      data: { hp: 40, thac0: 15 },
      adjustments: [
        { files: ["SAME"], data: { hp: 40, thac0: 15 } },
        { files: ["DIFFERENT"], data: { hp: 52, thac0: 14 } },
      ],
    });

    const effectives = adjustmentService.getEffectiveAdjustments(creature);

    expect(effectives.find((e) => e.files.includes("SAME"))).toBeUndefined();
    const different = effectives.find((e) => e.files.includes("DIFFERENT"));
    expect(different?.hp).toEqual({ value: 52, changed: true });
    expect(different?.thac0).toEqual({ value: 14, changed: true });
  });

  it("compares AC against the base creature's own final (dexterity-adjusted) armor class", () => {
    const creature = fakeCreature({
      data: { ac: 10, dexterity: 18 }, // final AC = 10 + (-4) = 6, see creature.service.test.ts
      adjustments: [
        { files: ["SAME_FINAL"], data: { ac: 6 } },
        { files: ["DIFFERENT"], data: { ac: 2 } },
      ],
    });

    const effectives = adjustmentService.getEffectiveAdjustments(creature);

    expect(effectives.find((e) => e.files.includes("SAME_FINAL"))).toBeUndefined();
    expect(effectives.find((e) => e.files.includes("DIFFERENT"))?.ac).toEqual({
      value: 2,
      changed: true,
    });
  });

  it("falls back to the base's own final AC when the adjustment never sets ac", () => {
    const creature = fakeCreature({
      data: { ac: 10, dexterity: 18 },
      adjustments: [{ files: ["NOAC"], data: { xpv: 999 } }],
    });

    const effective = adjustmentService
      .getEffectiveAdjustments(creature)
      .find((e) => e.files.includes("NOAC"));

    expect(effective?.ac).toEqual({ value: 6, changed: false });
  });

  // Mirrors documentationService.getEffectiveApr's own apr*doubleApr(+dual-wielding) formula so an
  // adjustment card's APR number and its "changed" flag agree with what the main block would show
  // for the same raw apr/doubleApr - duplicated here (not imported) because documentation.service
  // already imports this file, and importing it back would be circular.
  it("combines apr, doubleApr, and the base creature's own dual-wielding bonus consistently", () => {
    const creature = fakeCreature({
      data: { apr: 2, doubleApr: false },
      dualWielding: true, // base's own effective apr = 2 + 1 = 3
      adjustments: [
        { files: ["SAME"], data: { apr: 2 } }, // 2 + 1 = 3, same as base
        { files: ["DOUBLED"], data: { apr: 2, doubleApr: true } }, // 2*2 + 1 = 5
      ],
    });

    const effectives = adjustmentService.getEffectiveAdjustments(creature);

    expect(effectives.find((e) => e.files.includes("SAME"))).toBeUndefined();
    expect(effectives.find((e) => e.files.includes("DOUBLED"))?.apr).toEqual({
      value: 5,
      changed: true,
    });
  });

  it("shows the full effective equipped set, flagging only the slot that changed", () => {
    const creature = fakeCreature({
      data: {
        items: {
          equipped: [
            { file: "BASEWEAP", slot: "WEAPON1" },
            { file: "BASERING", slot: "LRING" },
          ],
          remove: [],
        },
      },
      adjustments: [
        {
          files: ["SWAP"],
          data: {
            items: {
              equipped: [{ file: "NEWWEAP", slot: "WEAPON1" }],
              remove: [],
            },
          },
        },
      ],
    });

    const swap = adjustmentService
      .getEffectiveAdjustments(creature)
      .find((e) => e.files.includes("SWAP"));

    expect(swap?.equipped).toEqual(
      expect.arrayContaining([
        { item: { file: "NEWWEAP", slot: "WEAPON1" }, changed: true },
        { item: { file: "BASERING", slot: "LRING" }, changed: false },
      ]),
    );
    expect(swap?.equipped).toHaveLength(2);
  });

  it("shows the full effective immunities set, flagging only newly granted ones", () => {
    const creature = fakeCreature({
      data: { immunities: ["giant"] },
      adjustments: [{ files: ["IMMUNE"], data: { immunities: ["giant", "undead"] } }],
    });

    const effective = adjustmentService
      .getEffectiveAdjustments(creature)
      .find((e) => e.files.includes("IMMUNE"));

    expect(effective?.immunities).toEqual(
      expect.arrayContaining([
        { name: "giant", changed: false },
        { name: "undead", changed: true },
      ]),
    );
    expect(effective?.immunities).toHaveLength(2);
  });

  it("shows the full effective memorized spellbook, flagging only entries whose count changed", () => {
    const creature = fakeCreature({
      data: {
        spells: {
          memorized: [
            { file: "SPPR101", memorizedCount: 1 },
            { file: "SPPR201", memorizedCount: 2 },
          ],
        },
      },
      adjustments: [
        {
          files: ["CASTER"],
          data: {
            spells: {
              memorized: [{ file: "SPPR101", memorizedCount: 3 }],
            },
          },
        },
      ],
    });

    const effective = adjustmentService
      .getEffectiveAdjustments(creature)
      .find((e) => e.files.includes("CASTER"));

    expect(effective?.memorized).toEqual(
      expect.arrayContaining([
        { spell: { file: "SPPR101", memorizedCount: 3 }, changed: true },
        { spell: { file: "SPPR201", memorizedCount: 2 }, changed: false },
      ]),
    );
    expect(effective?.memorized).toHaveLength(2);
  });
});
