IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    Allegiance(Myself,NEUTRAL)
THEN
    RESPONSE #100
        SetGlobal("P#EMMAWolf","GLOBAL",1)
        ActionOverride("P#WOLF01",MoveToObject("P#IMANEL"))  // Imanel Silversword
        ActionOverride("P#WOLF02",MoveToObject("P#IMANEL"))  // Imanel Silversword
        ActionOverride("P#WOLF03",MoveToObject("P#IMANEL"))  // Imanel Silversword
        ActionOverride("P#WOLF04",MoveToObject("P#IMANEL"))  // Imanel Silversword
        ActionOverride("P#WOLF05",MoveToObject("P#IMANEL"))  // Imanel Silversword
END
