// Hamadryad

// Initiate dialog
IF
	Global("JA_DIALOG","LOCALS",0)
	Name("VAELASA",Myself)
	NumTimesTalkedTo(0)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("JA_DIALOG","LOCALS",1)
		FaceObject([PC])
		StartDialogueNoSet([PC])
END

// Can use dimension door and detect traps
IF
	Global("ja_wilderness","LOCALS",0)
	AreaType(OUTDOOR)
	!AreaType(CITY)
	!AreaType(DUNGEON)
THEN
	RESPONSE #100
		SetGlobal("ja_wilderness","LOCALS",1)
END

IF
	Global("ja_wilderness","LOCALS",0)
	OR(2)
		HaveSpellRES("jas0f8")
		HaveSpellRES("jas6f8")
THEN
	RESPONSE #100
		RemoveSpellRES("jas0f8")
		RemoveSpellRES("jas6f8")
		SetGlobal("ja_wilderness","LOCALS",2)
END

// Vaelasa, the Fairy Queen
IF
	Name("VAELASA",Myself)
	AreaCheck("AR1200")
	Global("SummonDryads","AR1200",1)
THEN
	RESPONSE #100
		SetGlobal("SummonDryads","AR1200",2)
		StartCutSceneMode()
		StartCutScene("Cut23a")
END

IF
	Name("VAELASA",Myself)
	AreaCheck("AR0602")
	AttackedBy([GOODCUTOFF],DEFAULT)
	Global("VaelasaHostile","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("VaelasaHostile","GLOBAL",1)
		Enemy()
END

// Cloakwood Hamadryad
IF
	Global("rr#chama","MYAREA",1)
	Global("rr#hamat","LOCALS",0)
	See([PC])
THEN
	RESPONSE #100
		SetGlobal("rr#hamat","LOCALS",1)
		FaceObject([PC])
		DisplayStringHead(Myself,5184)
END

// Init
IF
	Global("JA_INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",0)
		SetGlobal("JA_PRECAST_LONG","LOCALS",0)
		SetGlobal("JA_PRECAST_MID","LOCALS",0)
		SetGlobalTimer("JA_REST","LOCALS",2400)
		SetGlobal("JA_INIT","LOCALS",1)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA_INIT","LOCALS",1)
	GlobalTimerExpired("JA_REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_INIT","LOCALS",0)
		Rest()
		ApplySpell(Myself,RESTORE_FULL_HEALTH)
END

// Precast Stoneskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPWI408")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPWI408",Myself)
		RemoveSpellRES("SPWI408")
		Continue()
END

// Precast Ironskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPPR506")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPPR506",Myself)
		RemoveSpellRES("SPPR506")
		Continue()
END

IF
	Global("JA_PRECAST_LONG","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_PRECAST_LONG","LOCALS",1)
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.FAIRY],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA_COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA_HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA_HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA_COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA_COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA_COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Handle Panic state
IF
	StateCheck(Myself,STATE_PANIC)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),15)
END

IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Dimension Door
IF
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpellRES("jas0f8")
	OR(2)
		Range(NearestEnemyOf(Myself),15)
		AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		CreateCreatureOffscreen("RR#TRAT",0)
		ForceSpellRES("jas0f8","RR#TRAT")
		RemoveSpellRES("jas0f8")
		Wait(1)
		SetInterrupt(TRUE)
END

// Speak With Plants
IF
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	!GlobalTimerNotExpired("speakWithPlants","LOCALS")
	HaveSpellRES("jas3f8")
	CheckStatGT(Myself,0,ENTANGLE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3f8",LastSeenBy(Myself))
		SetGlobalTimer("speakWithPlants","LOCALS",60)
		SetInterrupt(TRUE)
END

// Entangle
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas4f8")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,ENTANGLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas4f8",LastSeenBy(Myself))
		RemoveSpellRES("jas4f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas4f8")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,ENTANGLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas4f8",LastSeenBy(Myself))
		RemoveSpellRES("jas4f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas4f8")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,ENTANGLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas4f8",LastSeenBy(Myself))
		RemoveSpellRES("jas4f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas4f8")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,ENTANGLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas4f8",LastSeenBy(Myself))
		RemoveSpellRES("jas4f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas4f8")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,ENTANGLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas4f8",LastSeenBy(Myself))
		RemoveSpellRES("jas4f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas4f8")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,ENTANGLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas4f8",LastSeenBy(Myself))
		RemoveSpellRES("jas4f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas4f8")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,ENTANGLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas4f8",LastSeenBy(Myself))
		RemoveSpellRES("jas4f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas4f8")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,ENTANGLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas4f8",LastSeenBy(Myself))
		RemoveSpellRES("jas4f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas4f8")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,ENTANGLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas4f8",LastSeenBy(Myself))
		RemoveSpellRES("jas4f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas4f8")
	RandomNumGT(800,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,ENTANGLE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas4f8",LastSeenBy(Myself))
		RemoveSpellRES("jas4f8")
		SetInterrupt(TRUE)
END

// Dryad Charm
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

// Dryad Charm
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	Race(LastSeenBy(Myself),HALF_ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

// Dryad Charm
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.FIGHTER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.RANGER_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Race(LastSeenBy(Myself),ELF)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

// Dryad Charm
IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

IF
	!StateCheck(Myself,STATE_SILENCED)
	HaveSpellRES("jas2f8")
	!HaveSpellRES("SPWI506")
	!HaveSpellRES("SPPR405")
	RandomNumGT(801,240)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOfType([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas2f8",LastSeenBy(Myself))
		RemoveSpellRES("jas2f8")
		SetInterrupt(TRUE)
END

// Animal Friendship
IF
	HaveSpellRES("jas5f8")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOfType([0.ANIMAL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5f8",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("jas5f8")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOfType([0.ANIMAL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5f8",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("jas5f8")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOfType([0.ANIMAL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5f8",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("jas5f8")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([NEUTRAL.ANIMAL])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5f8",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("jas5f8")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearest([NEUTRAL.ANIMAL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5f8",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	HaveSpellRES("jas5f8")
	RandomNumGT(802,241)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearest([NEUTRAL.ANIMAL]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5f8",LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

// Detect snares and pits
IF
	!StateCheck(Myself,STATE_SILENCED)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	HaveSpellRES("jas6f8")
	False()
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas6f8",Myself)
END

// Run away from enemies
IF
	Range(NearestEnemyOf(Myself),20)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	HaveSpellRES("jas2f8")
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	HaveSpellRES("jas2f8")
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	HaveSpellRES("jas2f8")
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	HaveSpellRES("jas2f8")
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	HaveSpellRES("jas2f8")
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	HaveSpellRES("jas2f8")
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	HaveSpellRES("jas2f8")
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Open door
IF
	Global("RR#NOPND","GLOBAL",0)
	Allegiance(Myself,EVILCUTOFF)
	!AreaType(OUTDOOR)
	!Range(NearestEnemyOf(Myself),30)
	Range(NearestDoor,15)
	OpenState(NearestDoor,FALSE)
THEN
	RESPONSE #100
		MoveToObject(NearestDoor)
		OpenDoor(NearestDoor)
END

// Random walking (in combat) 
IF
	Global("JA_COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

// Random facing
IF
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		RandomTurn()
END

