// Nereid

// Init
IF
	Global("JA_INIT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",0)
		SetGlobal("JA_PRECAST_LONG","LOCALS",0)
		SetGlobal("JA_PRECAST_MID","LOCALS",0)
		SetGlobalTimer("JA_REST","LOCALS",2400)
		SetGlobal("JA_INIT","LOCALS",1)
END

// Rest (reset everything and heal if applicable)
IF
	Global("JA_INIT","LOCALS",1)
	GlobalTimerExpired("JA_REST","LOCALS")
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_INIT","LOCALS",0)
		Rest()
		ApplySpell(Myself,RESTORE_FULL_HEALTH)
END

// Precast Stoneskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPWI408")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPWI408",Myself)
		RemoveSpellRES("SPWI408")
		Continue()
END

// Precast Ironskin
IF
	Global("JA_PRECAST_LONG","LOCALS",0)
	HaveSpellRES("SPPR506")
THEN
	RESPONSE #100
		ReallyForceSpellRES("SPPR506",Myself)
		RemoveSpellRES("SPPR506")
		Continue()
END

IF
	Global("JA_PRECAST_LONG","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("JA_PRECAST_LONG","LOCALS",1)
END

// Turn hostile if attacked
IF
	Allegiance(Myself,NEUTRAL)
	OR(4)
		AttackedBy([GOODCUTOFF],DEFAULT)
		SpellCastOnMe([GOODCUTOFF],0)
		TookDamage()
		Heard([EVILCUTOFF.0.FAIRY],99)
THEN
	RESPONSE #100
		Enemy()
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Detect combat
IF
	Global("JA_COMBAT","LOCALS",0)
	Allegiance(Myself,GOODCUTOFF)
	See([EVILCUTOFF])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
END

// Shouts every 3 rounds
IF
	Global("JA_COMBAT","LOCALS",1)
	!GlobalTimerNotExpired("JA_HELP","LOCALS")
THEN
	RESPONSE #100
		Shout(99)
		SetGlobalTimer("JA_HELP","LOCALS",18)
END

// React to shouts
IF
	Global("JA_COMBAT","LOCALS",0)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
THEN
	RESPONSE #100
		SetGlobal("JA_COMBAT","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("JA_COMBAT","LOCALS",1)
	Heard([EVILCUTOFF.0.FAIRY],99)
	InMyArea([EVILCUTOFF.0.FAIRY])
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

// Do nothing if...
IF
	OR(4)
		Global("JA_COMBAT","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!InActiveArea(Myself)
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

// Handle Panic state
IF
	StateCheck(Myself,STATE_PANIC)
	Range(NearestEnemyOf(Myself),10)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),15)
END

IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

// Beguiling Aura
IF
	!GlobalTimerNotExpired("BeguilingAura","LOCALS")
	HaveSpellRES("jas1m72")
	!StateCheck(NearestEnemyOf(Myself),STATE_INVISIBLE)
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("BeguilingAura","LOCALS",6)
		ReallyForceSpellRES("jas1m72",Myself)
END

IF
	!GlobalTimerNotExpired("BeguilingAura","LOCALS")
	HaveSpellRES("jas1m72")
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_INVISIBLE)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("BeguilingAura","LOCALS",6)
		ReallyForceSpellRES("jas1m72",Myself)
END

IF
	!GlobalTimerNotExpired("BeguilingAura","LOCALS")
	HaveSpellRES("jas1m72")
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_INVISIBLE)
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("BeguilingAura","LOCALS",6)
		ReallyForceSpellRES("jas1m72",Myself)
END

// Summon Giant Poisonous Snake
IF
	HaveSpellRES("jas4m72")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		ForceSpellRES("jas4m72",Myself)
		RemoveSpellRES("jas4m72")
END

// Venom Spit
IF
	HaveSpellRES("jas3m72")
	!StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
	RandomNumGT(800,400)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3m72",LastSeenBy(Myself))
		RemoveSpellRES("jas3m72")
END

IF
	HaveSpellRES("jas3m72")
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
	RandomNumGT(800,400)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3m72",LastSeenBy(Myself))
		RemoveSpellRES("jas3m72")
END

IF
	HaveSpellRES("jas3m72")
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
	RandomNumGT(800,400)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3m72",LastSeenBy(Myself))
		RemoveSpellRES("jas3m72")
END

IF
	HaveSpellRES("jas3m72")
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
	RandomNumGT(800,400)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3m72",LastSeenBy(Myself))
		RemoveSpellRES("jas3m72")
END

IF
	HaveSpellRES("jas3m72")
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
	RandomNumGT(800,400)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3m72",LastSeenBy(Myself))
		RemoveSpellRES("jas3m72")
END

IF
	HaveSpellRES("jas3m72")
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
	RandomNumGT(800,400)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3m72",LastSeenBy(Myself))
		RemoveSpellRES("jas3m72")
END

IF
	HaveSpellRES("jas3m72")
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_BLIND)
	RandomNumGT(800,400)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3m72",LastSeenBy(Myself))
		RemoveSpellRES("jas3m72")
END

IF
	HaveSpellRES("jas3m72")
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_BLIND)
	RandomNumGT(800,400)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3m72",LastSeenBy(Myself))
		RemoveSpellRES("jas3m72")
END

IF
	HaveSpellRES("jas3m72")
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_BLIND)
	RandomNumGT(800,400)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3m72",LastSeenBy(Myself))
		RemoveSpellRES("jas3m72")
END

IF
	HaveSpellRES("jas3m72")
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_BLIND)
	RandomNumGT(800,400)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas3m72",LastSeenBy(Myself))
		RemoveSpellRES("jas3m72")
END

// Drowning Kiss
IF
	HaveSpellRES("jas2m72")
	StateCheck([EVILCUTOFF.HUMANOID.0.0.0.MALE],STATE_CHARMED)
	!StateCheck([EVILCUTOFF.HUMANOID.0.0.0.MALE],STATE_HELPLESS)
	RandomNumGT(801,200)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See([EVILCUTOFF.HUMANOID.0.0.0.MALE])
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		FaceObject(LastSeenBy(Myself))
		ActionOverride(LastSeenBy(Myself),FaceObject([EVILCUTOFF.0.FAIRY.FAIRY_NEREID.0.FEMALE.CHAOTIC_NEUTRAL]))
		ForceSpellRES("jas2m72",LastSeenBy(Myself))
		RemoveSpellRES("jas2m72")
END

IF
	HaveSpellRES("jas2m72")
	StateCheck(SecondNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]),STATE_CHARMED)
	!StateCheck(SecondNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]),STATE_HELPLESS)
	RandomNumGT(801,200)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		FaceObject(LastSeenBy(Myself))
		ActionOverride(LastSeenBy(Myself),FaceObject([EVILCUTOFF.0.FAIRY.FAIRY_NEREID.0.FEMALE.CHAOTIC_NEUTRAL]))
		ForceSpellRES("jas2m72",LastSeenBy(Myself))
		RemoveSpellRES("jas2m72")
END

IF
	HaveSpellRES("jas2m72")
	StateCheck(ThirdNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]),STATE_CHARMED)
	!StateCheck(ThirdNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]),STATE_HELPLESS)
	RandomNumGT(801,200)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		FaceObject(LastSeenBy(Myself))
		ActionOverride(LastSeenBy(Myself),FaceObject([EVILCUTOFF.0.FAIRY.FAIRY_NEREID.0.FEMALE.CHAOTIC_NEUTRAL]))
		ForceSpellRES("jas2m72",LastSeenBy(Myself))
		RemoveSpellRES("jas2m72")
END

IF
	HaveSpellRES("jas2m72")
	StateCheck(FourthNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]),STATE_CHARMED)
	!StateCheck(FourthNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]),STATE_HELPLESS)
	RandomNumGT(801,200)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		FaceObject(LastSeenBy(Myself))
		ActionOverride(LastSeenBy(Myself),FaceObject([EVILCUTOFF.0.FAIRY.FAIRY_NEREID.0.FEMALE.CHAOTIC_NEUTRAL]))
		ForceSpellRES("jas2m72",LastSeenBy(Myself))
		RemoveSpellRES("jas2m72")
END

IF
	HaveSpellRES("jas2m72")
	StateCheck(FifthNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]),STATE_CHARMED)
	!StateCheck(FifthNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]),STATE_HELPLESS)
	RandomNumGT(801,200)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		FaceObject(LastSeenBy(Myself))
		ActionOverride(LastSeenBy(Myself),FaceObject([EVILCUTOFF.0.FAIRY.FAIRY_NEREID.0.FEMALE.CHAOTIC_NEUTRAL]))
		ForceSpellRES("jas2m72",LastSeenBy(Myself))
		RemoveSpellRES("jas2m72")
END

IF
	HaveSpellRES("jas2m72")
	StateCheck(SixthNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]),STATE_CHARMED)
	!StateCheck(SixthNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]),STATE_HELPLESS)
	RandomNumGT(801,200)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearest([EVILCUTOFF.HUMANOID.0.0.0.MALE]))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		MoveToObjectNoInterrupt(LastSeenBy(Myself))
		FaceObject(LastSeenBy(Myself))
		ActionOverride(LastSeenBy(Myself),FaceObject([EVILCUTOFF.0.FAIRY.FAIRY_NEREID.0.FEMALE.CHAOTIC_NEUTRAL]))
		ForceSpellRES("jas2m72",LastSeenBy(Myself))
		RemoveSpellRES("jas2m72")
END

// Watery Fist
IF
	HaveSpellRES("jas5m72")
	RandomNumGT(802,401)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5m72",LastSeenBy(Myself))
		RemoveSpellRES("jas5m72")
END

IF
	HaveSpellRES("jas5m72")
	RandomNumGT(802,401)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5m72",LastSeenBy(Myself))
		RemoveSpellRES("jas5m72")
END

IF
	HaveSpellRES("jas5m72")
	RandomNumGT(802,401)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5m72",LastSeenBy(Myself))
		RemoveSpellRES("jas5m72")
END

IF
	HaveSpellRES("jas5m72")
	RandomNumGT(802,401)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5m72",LastSeenBy(Myself))
		RemoveSpellRES("jas5m72")
END

IF
	HaveSpellRES("jas5m72")
	RandomNumGT(802,401)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5m72",LastSeenBy(Myself))
		RemoveSpellRES("jas5m72")
END

IF
	HaveSpellRES("jas5m72")
	RandomNumGT(802,401)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5m72",LastSeenBy(Myself))
		RemoveSpellRES("jas5m72")
END

IF
	HaveSpellRES("jas5m72")
	RandomNumGT(802,401)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5m72",LastSeenBy(Myself))
		RemoveSpellRES("jas5m72")
END

IF
	HaveSpellRES("jas5m72")
	RandomNumGT(802,401)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5m72",LastSeenBy(Myself))
		RemoveSpellRES("jas5m72")
END

IF
	HaveSpellRES("jas5m72")
	RandomNumGT(802,401)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5m72",LastSeenBy(Myself))
		RemoveSpellRES("jas5m72")
END

IF
	HaveSpellRES("jas5m72")
	RandomNumGT(802,401)
	!GlobalTimerNotExpired("JA_ROUND","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!General(LastSeenBy(Myself),WEAPON)
	Range(LastSeenBy(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("JA_ROUND","LOCALS",6)
		ForceSpellRES("jas5m72",LastSeenBy(Myself))
		RemoveSpellRES("jas5m72")
END

// Run away from enemies
IF
	Range(NearestEnemyOf(Myself),20)
THEN
	RESPONSE #100
		RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),45)
END

// Track players if allegiance is not GOODCUTOFF
IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player1)
	Range(Player1,150)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStatGT(Player1,0,SANCTUARY)
	!StateCheck(Player1,STATE_CHARMED)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player2)
	Range(Player2,150)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStatGT(Player2,0,SANCTUARY)
	!StateCheck(Player2,STATE_CHARMED)
	!StateCheck(Player2,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player3)
	Range(Player3,150)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStatGT(Player3,0,SANCTUARY)
	!StateCheck(Player3,STATE_CHARMED)
	!StateCheck(Player3,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player4)
	Range(Player4,150)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStatGT(Player4,0,SANCTUARY)
	!StateCheck(Player4,STATE_CHARMED)
	!StateCheck(Player4,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player5)
	Range(Player5,150)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStatGT(Player5,0,SANCTUARY)
	!StateCheck(Player5,STATE_CHARMED)
	!StateCheck(Player5,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	!Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(Player6)
	Range(Player6,150)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStatGT(Player6,0,SANCTUARY)
	!StateCheck(Player6,STATE_CHARMED)
	!StateCheck(Player6,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Track last seen enemy if allegiance is GOODCUTOFF
IF
	Allegiance(Myself,GOODCUTOFF)
	!StateCheck(Myself,STATE_BLIND)
	InMyArea(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),150)
	!General(LastSeenBy(Myself),WEAPON)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

// Open door
IF
	Global("RR#NOPND","GLOBAL",0)
	Allegiance(Myself,EVILCUTOFF)
	!AreaType(OUTDOOR)
	!Range(NearestEnemyOf(Myself),30)
	Range(NearestDoor,15)
	OpenState(NearestDoor,FALSE)
THEN
	RESPONSE #100
		MoveToObject(NearestDoor)
		OpenDoor(NearestDoor)
END

// Random walking (in combat) 
IF
	Global("JA_COMBAT","LOCALS",1)
	ActionListEmpty()
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalk()
		Wait(2)
END

// Random facing
IF
	!Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		RandomTurn()
END

