LAM load_secondary_types
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/fey/common.tpa"
// Dimension Door
CREATE SPL "ja#s0f8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#s0f8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10379)
	WRITE_ASCII 0x10 ~CAS_M08~ #8
	WRITE_LONG 0x18 2048
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x1e 64
	WRITE_SHORT 0x22 10
	WRITE_BYTE 0x25 8
	WRITE_BYTE 0x27 13
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPWI402C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10380)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=4 range=900 speed=1 STR_VAR icon="SPWI402B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=141 target=1 power=1 parameter2=38 timing=1 resist_dispel=1 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=174 target=1 power=1 timing=1 resist_dispel=1 probability1=100 STR_VAR resource="EFF_M09" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=215 target=1 power=1 parameter2=2 resist_dispel=1 duration=1 probability1=100 STR_VAR resource="SPDIMNDR" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=124 target=1 power=1 timing=4 resist_dispel=1 duration=1 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=20 target=1 power=1 resist_dispel=1 duration=1 probability1=100 END
	LPF CHANGE_SPELL INT_VAR    renew=1 END
	
	// Dimension Door
CREATE SPL "ja#s1f8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#s1f8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10379)
	WRITE_ASCII 0x10 ~CAS_M08~ #8
	WRITE_LONG 0x18 2048
	WRITE_SHORT 0x1c 2
	WRITE_LONG 0x1e 64
	WRITE_SHORT 0x22 10
	WRITE_BYTE 0x25 8
	WRITE_BYTE 0x27 13
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPWI402C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10380)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=2 target=4 range=900 speed=1 STR_VAR icon="SPWI402B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=141 target=1 power=1 parameter2=38 timing=1 resist_dispel=1 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=174 target=1 power=1 timing=1 resist_dispel=1 probability1=100 STR_VAR resource="EFF_M09" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=215 target=1 power=1 parameter2=2 resist_dispel=1 duration=1 probability1=100 STR_VAR resource="SPDIMNDR" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=124 target=1 power=1 timing=4 resist_dispel=1 duration=1 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=20 target=1 power=1 resist_dispel=1 duration=1 probability1=100 END
	LPF CHANGE_SPELL INT_VAR     END
	
	// Dryad Charm
CREATE EFF "ja#s2f8"
	WRITE_LONG 0x10 206
	WRITE_LONG 0x14 2
	WRITE_LONG 0x24 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#s2f8~ #8

CREATE SPL "ja#s2f8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#s2f8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10180)
	WRITE_ASCII 0x10 ~CAS_M05~ #8
	WRITE_LONG 0x18 512
	WRITE_SHORT 0x1c 4
	WRITE_SHORT 0x22 11
	WRITE_BYTE 0x25 4
	WRITE_BYTE 0x27 11
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPWI316C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10684)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=1 range=30 speed=1 projectile=(IDS_OF_SYMBOL (~projectl~ ~SPARKLGO~)) + 1 STR_VAR icon="SPWI316B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~ELF~) parameter2=4 duration=1 probability1=90 STR_VAR resource="ja#s2f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~HALF_ELF~) parameter2=4 duration=1 probability1=30 STR_VAR resource="ja#s2f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=5 target=2 power=1 parameter1=IDS_OF_SYMBOL (~GENERAL~ ~HUMANOID~) parameter2=2 resist_dispel=1 duration=180 probability1=100 savingthrow=1 savebonus="-3" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=139 target=2 power=1 parameter1=14780 timing=1 resist_dispel=1 probability1=100 savingthrow=1 savebonus="-3" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=50 target=2 power=1 parameter1="-1819214080" parameter2=1966080 resist_dispel=1 duration=1 probability1=100 savingthrow=1 savebonus="-3" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=215 target=2 power=1 parameter2=1 resist_dispel=1 duration=3 probability1=100 savingthrow=1 savebonus="-3" STR_VAR resource="SPNWCHRM" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=174 target=2 power=1 timing=3 resist_dispel=1 duration=180 probability1=100 savingthrow=1 savebonus="-3" STR_VAR resource="EFF_E07" END
	
	// Speak With Plants
CREATE SPL "ja#s3f8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#s3f8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10183)
	WRITE_ASCII 0x10 ~CAS_P02~ #8
	WRITE_SHORT 0x1c 4
	WRITE_SHORT 0x22 10
	WRITE_BYTE 0x25 8
	WRITE_BYTE 0x27 13
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~RR#FSPKP~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10184)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=5 range=30 speed=1 STR_VAR icon="RR#FSPKP" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=143 target=2 power=1 parameter1=IDS_OF_SYMBOL (~slots~ ~SLOT_AMULET~) resist_dispel=3 duration=60 probability1=100 STR_VAR resource="ja#i4" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=50 target=2 power=1 parameter1=1727219712 parameter2=1966080 resist_dispel=3 duration=1 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=215 target=2 power=1 parameter2=1 resist_dispel=3 duration=2 probability1=100 STR_VAR resource="SPRMCURS" END
	LPF CHANGE_SPELL INT_VAR    renew=1 END
	
	// Entangle
CREATE EFF "ja#s4f8"
	WRITE_LONG 0x10 206
	WRITE_LONG 0x14 2
	WRITE_LONG 0x24 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#s4f8~ #8

COPY_EXISTING "ENTANG2.pro" ~override/ja#s4f8.pro~
	READ_SHORT 0x08 type
	PATCH_IF (%type% = 1) BEGIN
		INSERT_BYTES 0x100 0x100
	END
	WRITE_LONG 0x200 64
ADD_PROJECTILE ~override/ja#s4f8.pro~ ~Hamadryad Entangle~

CREATE SPL "ja#s4f8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#s4f8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10181)
	WRITE_ASCII 0x10 ~CAS_P08~ #8
	WRITE_SHORT 0x1c 4
	WRITE_SHORT 0x22 10
	WRITE_BYTE 0x25 8
	WRITE_BYTE 0x27 11
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPPR105C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10182)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=4 range=30 speed=1 projectile=(IDS_OF_SYMBOL (~projectl~ ~ja#s4f8~)) + 1 STR_VAR icon="SPPR105B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~DRAGON~) parameter2=4 duration=6 probability1=100 STR_VAR resource="ja#s4f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~CLASS~ ~NEOTHELID~) parameter2=5 duration=6 probability1=100 STR_VAR resource="ja#s4f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~MIST~) parameter2=4 duration=6 probability1=100 STR_VAR resource="ja#s4f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~SHADOW~) parameter2=4 duration=6 probability1=100 STR_VAR resource="ja#s4f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~SPECTRAL_UNDEAD~) parameter2=4 duration=6 probability1=100 STR_VAR resource="ja#s4f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~SPECTRE~) parameter2=4 duration=6 probability1=100 STR_VAR resource="ja#s4f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~WILL-O-WISP~) parameter2=4 duration=6 probability1=100 STR_VAR resource="ja#s4f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~WRAITH~) parameter2=4 duration=6 probability1=100 STR_VAR resource="ja#s4f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~CLASS~ ~SPECTRAL_TROLL~) parameter2=5 duration=6 probability1=100 STR_VAR resource="ja#s4f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~CLASS~ ~SPIDER_WRAITH~) parameter2=5 duration=6 probability1=100 STR_VAR resource="ja#s4f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=126 target=2 power=1 parameter1=50 parameter2=2 resist_dispel=1 duration=6 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=126 target=2 power=1 parameter2=1 resist_dispel=1 duration=6 probability1=100 savingthrow=1 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=278 target=2 power=1 parameter1="-2" resist_dispel=1 duration=6 probability1=100 savingthrow=1 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=0 target=2 power=1 parameter1="-2" resist_dispel=1 duration=6 probability1=100 savingthrow=1 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=174 target=2 power=1 resist_dispel=1 duration=1 probability1=100 savingthrow=1 STR_VAR resource="CRE_P01" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=174 target=2 power=1 timing=4 resist_dispel=1 duration=6 probability1=100 savingthrow=1 STR_VAR resource="EFF_M22A" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=154 target=2 power=1 resist_dispel=1 duration=6 probability1=100 savingthrow=1 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=142 target=2 power=1 parameter2=144 resist_dispel=1 duration=6 probability1=100 savingthrow=1 END
	LPF CHANGE_SPELL INT_VAR    renew=3 END
	
	// Animal Friendship
CREATE EFF "ja#s5f8"
	WRITE_LONG 0x10 206
	WRITE_LONG 0x14 2
	WRITE_LONG 0x24 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#s5f8~ #8

CREATE SPL "ja#s5f8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#s5f8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10185)
	WRITE_ASCII 0x10 ~CORAN03~ #8
	WRITE_LONG 0x18 33554432
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x25 4
	WRITE_BYTE 0x27 11
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPPR204C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10186)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=1 range=30 speed=1 STR_VAR icon="SPPR204B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~ELF~) parameter2=4 duration=1 probability1=90 STR_VAR resource="ja#s5f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~HALF_ELF~) parameter2=4 duration=1 probability1=30 STR_VAR resource="ja#s5f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=324 target=2 power=1 parameter1=IDS_OF_SYMBOL (~general~ ~ANIMAL~) parameter2=113 resist_dispel=1 duration=120 probability1=100 savingthrow=1 STR_VAR resource="ja#s5f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=5 target=2 power=1 parameter1=IDS_OF_SYMBOL (~GENERAL~ ~ANIMAL~) resist_dispel=1 duration=120 probability1=100 savingthrow=1 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=50 target=2 power=1 parameter1=509245440 parameter2=1638400 resist_dispel=1 duration=1 probability1=100 savingthrow=1 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=215 target=2 power=1 parameter2=1 resist_dispel=1 duration=3 probability1=100 savingthrow=1 STR_VAR resource="SPNWCHRM" END
	LPF CHANGE_SPELL INT_VAR    renew=1 END
	
	// Detect snares and pits
CREATE SPL "ja#s6f8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#s6f8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10187)
	WRITE_ASCII 0x10 ~CAS_P04~ #8
	WRITE_LONG 0x18 8192
	WRITE_SHORT 0x1c 4
	WRITE_SHORT 0x22 16
	WRITE_BYTE 0x25 3
	WRITE_BYTE 0x27 13
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPPR205C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10188)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=5 speed=1 projectile=(IDS_OF_SYMBOL (~projectl~ ~INAREANS~)) + 1 STR_VAR icon="SPPR205B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=150 target=1 power=1 duration=120 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=142 target=1 power=1 parameter2=109 duration=120 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=141 target=1 power=1 parameter2=30 timing=1 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=50 target=2 power=1 parameter1=1226851840 parameter2=1310720 duration=2 probability1=100 END
	LPF CHANGE_SPELL INT_VAR    renew=16 END
	
	// Blinding Beauty
CREATE SPL "ja#s7f8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#s7f8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10189)
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPPR704C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10685)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=5 STR_VAR icon="SPPR704B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=206 target=2 power=1 resist_dispel=3 duration=7200 probability1=100 STR_VAR resource="SPWI105" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=206 target=2 power=1 resist_dispel=3 duration=7200 probability1=100 STR_VAR resource="SPIN937" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=74 target=2 power=1 resist_dispel=3 duration=7200 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=142 target=2 power=1 parameter2=8 resist_dispel=3 duration=7200 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=139 target=2 power=1 parameter1=14674 timing=1 resist_dispel=3 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=174 target=2 power=1 timing=1 resist_dispel=3 duration=7200 probability1=100 savingthrow=1 STR_VAR resource="EFF_P71B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=215 target=2 power=1 parameter2=1 resist_dispel=3 duration=3 probability1=100 savingthrow=1 STR_VAR resource="SPH1HI01" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=206 target=2 power=1 resist_dispel=3 duration=7200 probability1=100 savingthrow=1 STR_VAR resource="ja#s7f8" END
	
	// Blinding Beauty
CREATE EFF "ja#s8f8"
	WRITE_LONG 0x10 146
	WRITE_LONG 0x14 2
	WRITE_LONG 0x1c 0
	WRITE_LONG 0x24 1
	WRITE_LONG 0x20 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#s7f8~ #8

CREATE SPL "ja#s8f8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#s8f8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10189)
	WRITE_SHORT 0x1c 4
	WRITE_BYTE 0x27 11
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPPR704C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10190)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=5 projectile=(IDS_OF_SYMBOL (~projectl~ ~ja#sight~)) + 1 STR_VAR icon="SPPR704B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=215 target=1 power=1 parameter2=1 duration=2 probability1=100 STR_VAR resource="ICCLKFR2" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~GENERAL~ ~HUMANOID~) parameter2=3 timing=1 probability1=100 STR_VAR resource="ja#s8f8" END
	LPF CHANGE_SPELL INT_VAR    renew=1 END
	
	// Charm Song
CREATE EFF "ja#s9f8"
	WRITE_LONG 0x10 206
	WRITE_LONG 0x14 2
	WRITE_LONG 0x24 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#s9f8~ #8

CREATE SPL "ja#s9f8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#s9f8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10191)
	WRITE_ASCII 0x10 ~SIRIN05~ #8
	WRITE_LONG 0x18 512
	WRITE_SHORT 0x1c 4
	WRITE_SHORT 0x22 11
	WRITE_BYTE 0x25 4
	WRITE_BYTE 0x27 11
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPWI316C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10686)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=1 range=30 speed=1 STR_VAR icon="SPWI316B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~ELF~) parameter2=4 duration=1 probability1=90 STR_VAR resource="ja#s9f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~RACE~ ~HALF_ELF~) parameter2=4 duration=1 probability1=30 STR_VAR resource="ja#s9f8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=5 target=2 power=1 parameter1=IDS_OF_SYMBOL (~GENERAL~ ~HUMANOID~) parameter2=2 resist_dispel=1 duration=180 probability1=100 savingthrow=1 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=139 target=2 power=1 parameter1=14780 timing=1 resist_dispel=1 probability1=100 savingthrow=1 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=50 target=2 power=1 parameter1="-1819214080" parameter2=1966080 resist_dispel=1 duration=1 probability1=100 savingthrow=1 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=215 target=2 power=1 parameter2=1 resist_dispel=1 duration=3 probability1=100 savingthrow=1 STR_VAR resource="SPNWCHRM" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=174 target=2 power=1 timing=3 resist_dispel=1 duration=180 probability1=100 savingthrow=1 STR_VAR resource="EFF_E07" END
	
	// Charm Song
CREATE EFF "ja#saf8"
	WRITE_LONG 0x10 146
	WRITE_LONG 0x14 2
	WRITE_LONG 0x1c 0
	WRITE_LONG 0x24 1
	WRITE_LONG 0x20 1
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~ja#s9f8~ #8

CREATE SPL "ja#saf8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#saf8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10191)
	WRITE_ASCII 0x10 ~SIRIN05~ #8
	WRITE_LONG 0x18 16896
	WRITE_SHORT 0x1c 4
	WRITE_SHORT 0x22 11
	WRITE_BYTE 0x25 4
	WRITE_BYTE 0x27 11
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPWI316C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10192)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=1 range=30 speed=1 projectile=(IDS_OF_SYMBOL (~projectl~ ~ja#sight~)) + 1 STR_VAR icon="SPWI316B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=177 target=2 power=1 parameter1=IDS_OF_SYMBOL (~GENERAL~ ~HUMANOID~) parameter2=3 probability1=100 STR_VAR resource="ja#saf8" END
	LPF CHANGE_SPELL INT_VAR   rinvs=1  END
	
	// Fog Cloud
CREATE SPL "ja#sbf8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#sbf8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10193)
	WRITE_ASCII 0x10 ~CAS_M08~ #8
	WRITE_SHORT 0x1c 4
	WRITE_SHORT 0x22 10
	WRITE_BYTE 0x25 8
	WRITE_BYTE 0x27 9
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPWI204C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10194)
	LPF ADD_SPELL_HEADER INT_VAR type=2 location=4 target=4 range=30 speed=1 projectile=(IDS_OF_SYMBOL (~projectl~ ~CLOUD~)) + 1 STR_VAR icon="SPWI204B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=206 target=2 power=1 resist_dispel=1 duration=7 probability1=100 STR_VAR resource="SPWI105" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=206 target=2 power=1 resist_dispel=1 duration=7 probability1=100 STR_VAR resource="SPIN937" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=74 target=2 power=1 resist_dispel=1 duration=7 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=142 target=2 power=1 parameter2=8 resist_dispel=1 duration=7 probability1=100 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=139 target=2 power=1 parameter1=14674 timing=1 resist_dispel=1 probability1=100 END
	LPF CHANGE_SPELL INT_VAR   rinvs=1  END
	
	// Touch of Tranquility
CREATE SPL "ja#scf8"
	WRITE_LONG 0x64 0x72
COPY_EXISTING ~ja#scf8.SPL~  ~override~
	WRITE_LONG 0x8 RESOLVE_STR_REF(@10195)
	WRITE_ASCII 0x10 ~EFF_P11~ #8
	WRITE_LONG 0x18 17408
	WRITE_SHORT 0x1c 4
	WRITE_SHORT 0x22 10
	WRITE_BYTE 0x25 8
	WRITE_BYTE 0x27 9
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~SPWI509C~ #8
	WRITE_LONG 0x50 RESOLVE_STR_REF(@10196)
	LPF ADD_SPELL_HEADER INT_VAR type=1 location=4 target=1 STR_VAR icon="SPWI509B" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=324 target=2 power=1 parameter1=IDS_OF_SYMBOL (~splstate~ ~CHAOTIC_COMMANDS~) parameter2=76 duration=1 probability1=100 STR_VAR resource="ja#scf8" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=76 target=2 power=1 duration=300 probability1=100 savingthrow=4 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=142 target=2 power=1 parameter2=48 duration=300 probability1=100 savingthrow=4 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=215 target=2 power=1 parameter2=1 duration=2 probability1=100 savingthrow=4 STR_VAR resource="SPMINDAT" END
	LPF ADD_EFFECT INT_VAR header=1 opcode=50 target=2 power=1 parameter1=4812032 parameter2=1310720 duration=1 probability1=100 savingthrow=4 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=139 target=2 power=1 parameter1=23744 timing=1 duration=300 probability1=100 savingthrow=4 END
	LPF ADD_EFFECT INT_VAR header=1 opcode=206 target=2 power=1 duration=300 probability1=100 savingthrow=4 STR_VAR resource="ja#scf8" END
	
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/fey/29.tpa" // Dryad
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/fey/2a.tpa" // Hamadryad
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/fey/2c.tpa" // Nymph
INCLUDE "%MOD_FOLDER%/lib/pnp-monster/fey/2b.tpa" // Sirine
