export const GLOBAL_CONFIG = {
  files: {
    coreMonsters: "lib/pnp-monster/common/core.tpa",
    spellResources: "lib/common/spell-resources.tpa",
    spellFunctions: "lib/common/spell-functions.tpa",
    immunities: "lib/common/immunities.tpa",
  },
  constitutionAffectHitPoint: true,
  spellcasterPrecastMidDurationSpells: false,
  /**
   * Keep disabled during development: shuffling target order on every
   * regeneration would churn the committed .baf files with no real
   * config change behind it. Enable once, right before a release build,
   * to bake in the intended non-nearest-first target variety.
   */
  enableRandomTargetOrder: false,
  /**
   * Keep disabled during development because it increases installation time.
   * Enable once, right before a release build.
   */
  enableSecondaryTypes: false,
  bafConstants: {
    combatStarted: "JA#COMBAT",
    disableSpellcasting: "JA#DISABLE_SPELLCASTING",
    initGlobal: "JA#INIT",
    precastLongDurationSpells: "JA#PRECAST_LONG",
    precastMidDurationSpells: "JA#PRECAST_MID",
    minorSequencer: "JA#MINOR_SEQUENCER",
    sequencer: "JA#SEQUENCER",
    restTimer: "JA#REST",
    helpTimer: "JA#HELP",
    roundTimer: "JA#ROUND",
    noOpenDoor: "RR#NOPND",
    dialog: "JA#DIALOG",
    monsterShoutId: 99,
    summonerShoutId: 98,
    trackingRange: 150,
    meleeRange: 4,
  },
  tpaConstants: {
    genericScriptsToRemove: [
      "BDANIMN",
      "BDARCHNI",
      "BDENRAGE",
      "BDENSHTV",
      "BDFIG00",
      "BDFIGH01",
      "BDFIGH42",
      "BDFIGH43",
      "BDFMAG01",
      "BDFMAG23",
      "BPWTSIGT",
      "BPWTRSGT",
      "BPWDRSGT",
      "BPWDASGT",
      "BDGRSHTV",
      "BDNONIN",
      "BDSHM00",
      // "BDSHOUT",
      "BDSUM00",
      "BPASIGHT",
      "BPSIGHT",
      "DVMELEE",
      "DW#MG29",
      "DW#MG47",
      "DW#MG56",
      "DW#MG78",
      "DW#MG84",
      "DW#MG99",
      "DW#MG101",
      "DW#MG102",
      "DW#MG103",
      "DW#MG104",
      "DW#MG105",
      "DW#MG106",
      "DW#MG107",
      "DW#MG108",
      "DW#MG131",
      "DW#MG132",
      "DW#MG137",
      "DW#MG139",
      "DW#GPSHM",
      "DW#GPSHT",
      "dw1melbe",
      "DW1MELGE",
      "DW2RS0MO",
      "DW#PRSHT",
      "DW1RANGE",
      "DW2MC3MO",
      "dw1ranmo",
      "DW2MC1GE",
      "dw1melmo",
      "DW2MS1GE",
      "DW2MC0MO",
      "DW2MC1MO",
      "DW2RC0MO",
      "DW2MS0MO",
      "DW2MC0GE",
      "DW2MC0GW",
      "DW2MC2GE",
      "DW2MP2GW",
      "DW2MM0GE",
      "DW2MP0GE",
      "DW2MP0GW",
      "DW2MP1GE",
      "DW2MP2GE",
      "DW2MS0GE",
      "DW2RC2MO",
      "GENSHT01",
      "HUNTER",
      "initdlg",
      "SHOUT",
      "SUMSHT02",
      "TUTU_SCR",
      "WTASIGHT",
      "WDASIGHT",
      "wtrunsgt",
    ],
  },
};
