import { SPELLS } from "./spells/spell-names";
import { FNP_SPELLS } from "./spells/fnp-spell-names";
import { PRESET_NAMES } from "./common";

/**
 * Spell cast-priority order (earlier entry = cast sooner) for AbilityOrderService - see
 * `docs/superpowers/specs/2026-08-10-spell-priority-order-emulti-design.md`.
 */

// Ordered by the line of each spell's first cast in assets/emulti.baf.
export const SPELL_PRIORITY_ORDER: string[] = [
  SPELLS.Wizard.Vocalize.file,
  SPELLS.Priest.CureLightWounds.file,
  SPELLS.Priest.ResistFear.file,
  SPELLS.Wizard.DispelMagic.file,
  SPELLS.Wizard.RemoveMagic.file,
  SPELLS.Wizard.DetectInvisibility.file,
  SPELLS.Wizard.Glitterdust.file,
  SPELLS.Wizard.ShadowDoor.file,
  SPELLS.Wizard.Stoneskin.file,
  SPELLS.Priest.TrueSeeing.file,
  SPELLS.Priest.DispelMagic.file,
  SPELLS.Priest.Ironskin.file,
  SPELLS.Wizard.ProtectionFromMagicalWeapons.file,
  SPELLS.Wizard.TeleportField.file,
  SPELLS.Priest.AerialServant.file,
  SPELLS.Wizard.MinorGlobeOfInvulnerability.file,
  SPELLS.Wizard.FireShield.file,
  SPELLS.Priest.MagicResistance.file,
  SPELLS.Wizard.ProtectionFromMissiles.file,
  SPELLS.Priest.BladeBarrier.file,
  SPELLS.Priest.CallWoodlandBeeings.file,
  SPELLS.Priest.AnimateDead.file,
  FNP_SPELLS.Priest.AnimateDead.file,
  SPELLS.Wizard.Haste.file,
  SPELLS.Wizard.MinorSpellDeflection.file,
  SPELLS.Wizard.Blur.file,
  SPELLS.Wizard.MirrorImages.file,
  SPELLS.Priest.Sanctuary.file,
  SPELLS.Wizard.ImprovedInvisibility.file,
  SPELLS.Wizard.Shield.file,
  FNP_SPELLS.Priest.Shield.file,
  SPELLS.Priest.Barkskin.file,
  SPELLS.Wizard.Invisibility.file,
  SPELLS.Priest.ProtectionFromLightning.file,
  SPELLS.Priest.Chant.file,
  SPELLS.Priest.Bless.file,
  SPELLS.Wizard.SpellThrust.file,
  SPELLS.Wizard.Breach.file,
  SPELLS.Wizard.ConeOfCold.file,
  SPELLS.Wizard.ChainLightning.file,
  SPELLS.Priest.DolorousDecay.file,
  SPELLS.Wizard.WailOfTheBanshee.file,
  SPELLS.Wizard.PowerWordKill.file,
  SPELLS.Wizard.Fireburst.file,
  SPELLS.Priest.SymbolDeath.file,
  SPELLS.Priest.FingerOfDeath.file,
  SPELLS.Wizard.PowerWordStun.file,
  SPELLS.Wizard.PowerWordBlind.file,
  SPELLS.Priest.Wither.file,
  SPELLS.Priest.Harm.file,
  SPELLS.Priest.SlayLiving.file,
  SPELLS.Priest.WavesOfAgony.file,
  SPELLS.Priest.RighteousMagic.file,
  SPELLS.Priest.HolyPower.file,
  SPELLS.Priest.Silence.file,
  SPELLS.Priest.MiscastMagic.file,
  FNP_SPELLS.Priest.MiscastMagic.file,
  SPELLS.Wizard.Domination.file,
  SPELLS.Priest.MentalDomination.file,
  SPELLS.Wizard.VitriolicSphere.file,
  SPELLS.Wizard.LightningBolt.file,
  SPELLS.Wizard.IceStorm.file,
  SPELLS.Priest.FlameStrike.file,
  SPELLS.Priest.Poison.file,
  SPELLS.Wizard.MordenkainenForceMissiles.file,
  SPELLS.Wizard.Cloudkill.file,
  SPELLS.Priest.UnholyBlight.file,
  SPELLS.Priest.CloudOfPestilence.file,
  SPELLS.Priest.GlyphOfWarding.file,
  SPELLS.Wizard.GreaterMalison.file,
  SPELLS.Wizard.Emotion.file,
  FNP_SPELLS.Priest.GreaterMalison.file,
  SPELLS.Priest.GreaterCommand.file,
  FNP_SPELLS.Priest.Emotion.file,
  SPELLS.Priest.Chaos.file,
  SPELLS.Priest.RigidThinking.file,
  FNP_SPELLS.Priest.Chaos.file,
  SPELLS.Priest.CloakOfFear.file,
  FNP_SPELLS.Priest.RigidThinking.file,
  SPELLS.Priest.SummonInsects.file,
  FNP_SPELLS.Priest.CloakOfFear.file,
  SPELLS.Wizard.DireCharm.file,
  SPELLS.Wizard.FlameArrow.file,
  SPELLS.Priest.MassCauseLightWounds.file,
  SPELLS.Wizard.AgannazarScorcher.file,
  SPELLS.Wizard.Combust.file,
  SPELLS.Priest.CallLightning.file,
  SPELLS.Wizard.PowerWordSleep.file,
  SPELLS.Wizard.Slow.file,
  SPELLS.Wizard.Confusion.file,
  SPELLS.Wizard.Web.file,
  SPELLS.Wizard.StinkingCloud.file,
  SPELLS.Wizard.Darkness15Radius.file,
  SPELLS.Wizard.ObscuringMist.file,
  SPELLS.Wizard.ChromaticOrb.file,
  SPELLS.Wizard.HoldPerson.file,
  SPELLS.Wizard.Spook.file,
  SPELLS.Wizard.Horror.file,
  SPELLS.Priest.Entangle.file,
  SPELLS.Priest.HoldPersonOrAnimal.file,
  SPELLS.Priest.HoldPerson.file,
  FNP_SPELLS.Priest.CauseCriticalWounds.file,
  SPELLS.Wizard.CharmPerson.file,
  SPELLS.Priest.CharmPersonOrAnimal.file,
  SPELLS.Wizard.MelfAcidArrow.file,
  SPELLS.Wizard.BurningHands.file,
  SPELLS.Wizard.MagicMissiles.file,
  SPELLS.Wizard.Sleep.file,
  FNP_SPELLS.Priest.Doom.file,
  SPELLS.Priest.Command.file,
  SPELLS.Priest.DrawUponHolyMight.file,
];

// No direct cast evidence in assets/emulti.baf (not cast anywhere in the script, at
// least not through a cast syntax this derivation understands - see the design doc).
// Order here is not derived from anything - reorder by hand as you develop a
// considered opinion on where an entry belongs, then move it into the array above.
// Regenerated every run: an entry only leaves this list once it gains real evidence.
export const SPELL_PRIORITY_ORDER_UNVETTED: string[] = [
  FNP_SPELLS.Priest.SummonShadows.file,
  FNP_SPELLS.Priest.CloudOfPestilence.file,
  FNP_SPELLS.Priest.Shades.file,
  FNP_SPELLS.Priest.WavesOfFatigue.file,
  FNP_SPELLS.Priest.DemiShadowMonsters.file,
  FNP_SPELLS.Priest.CircleOfBones.file,
  FNP_SPELLS.Priest.ShadowMonsters.file,
  FNP_SPELLS.Priest.CauseSeriousWounds.file,
  FNP_SPELLS.Priest.Forbiddance.file,
  FNP_SPELLS.Priest.Shatter.file,
  FNP_SPELLS.Priest.CauseDisease.file,
  SPELLS.Wizard.DimensionDoor.file,
  PRESET_NAMES.DimensionDoorOffscreen,
  FNP_SPELLS.Priest.CauseLightWounds.file,
  FNP_SPELLS.Priest.FrostFingers.file,
  SPELLS.Priest.FindTraps.file,
  SPELLS.Priest.AnimalSummoning4.file,
];
