///////////////////////////////////////////////////////////////////////
// Greater doppelganger
///////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Just after resting, everything is reset and creature is healed
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("ja#PrepTimer","LOCALS")
	!Global("ja#initialize","LOCALS",0)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Rest()
		ApplySpellRES("JA#HEAL",Myself)
		SetGlobal("ja#initialize","LOCALS",0)
END


///////////////////////////////////////////////////////////////////////
// Initialize variables & timers
///////////////////////////////////////////////////////////////////////
IF
	Global("ja#initialize","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#initialize","LOCALS",1)
		SetGlobal("ja#mirrorimage","LOCALS",0)
		SetGlobal("ja#haste","LOCALS",0)
		SetGlobal("ja#buffdone","LOCALS",0)
		SetGlobal("ja#startcombat","LOCALS",0)
		SetGlobalTimer("ja#PrepTimer","LOCALS",2400)
END


IF
	Heard([ANYONE],95)
	Allegiance(Myself,NEUTRAL)
	Range(LastHeardBy(Myself),20)
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("ja#startcombat","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Heard([ANYONE],95)
	!See(NearestEnemyOf(Myself))	
	Range(LastHeardBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobal("ja#startcombat","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// See an enemy
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOf(Myself))
	Global("ja#startcombat","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#startcombat","LOCALS",1)
		Shout(95)
END


/////////////////////////////////////////////////////////////////////
// Mirror image
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOf(Myself))
	Global("ja#mirrorimage","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#mirrorimage","LOCALS",1)
		ForceSpell(Myself,WIZARD_MIRROR_IMAGE)
END


/////////////////////////////////////////////////////////////////////
// Haste
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOf(Myself))
	Global("ja#haste","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#haste","LOCALS",1)
		ForceSpell(Myself,WIZARD_HASTE)
END