///////////////////////////////////////////////////////////////////////
// Spellcasting for clerics
// - protection/buff spells
///////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Unable to cast a spell
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#disable_spellcasting","LOCALS",0)
	OR(2)
		StateCheck(Myself,STATE_SILENCED)
		CheckStatGT(Myself,69,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Able to cast a spell
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#disable_spellcasting","LOCALS",1)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,70,SPELLFAILUREPRIEST)
	!CheckStat(Myself,1,SCRIPTINGSTATE3) // Tenser's tranformation
	!CheckStat(Myself,1,POLYMORPH_SELF)
	!CheckStat(Myself,1,WIZARD_MISLEAD)
	!Global("ja#polymorph","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("ja#disable_spellcasting","LOCALS",0)
END


/////////////////////////////////////////////////////////////////////
// Neutralize poison
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("cdilnps")
	StateCheck(Myself,STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("cdilnps",Myself)
END


/////////////////////////////////////////////////////////////////////
// Slow poison
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_SLOW_POISON)
	StateCheck(Myself,STATE_POISONED)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_SLOW_POISON)
END


/////////////////////////////////////////////////////////////////////
// Mantle
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("cdhmmnt")
	CheckStat(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	HitBy([ANYONE],CRUSHING)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("cdhmmnt",Myself)
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("cdxvmtl")
	CheckStat(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	HitBy([ANYONE],CRUSHING)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("cdxvmtl",Myself)
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("nmsun14")
	CheckStat(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	HitBy([ANYONE],CRUSHING)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("nmsun14",Myself)
END


/////////////////////////////////////////////////////////////////////
// Shapeshift
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#polymorph","LOCALS",0)
	Kit(Myself,SHAPESHIFTER)
	OR(2)
		HPPercentLT(Myself,70)
		Global("ja#disable_spellcasting","LOCALS",1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("ja#polymorph","LOCALS",1)
		SetGlobalTimer("ja#cast","LOCALS",6)
		SelectWeaponAbility(SLOT_WEAPON1,0)  // (Greater)Wolfwere
		Wait(6) // Morphing time
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#polymorph","LOCALS",0)
	Kit(Myself,BEASTFRIEND)
	CheckStatGT(Myself,6,LEVEL)
	OR(2)
		HPPercentLT(Myself,70)
		Global("ja#disable_spellcasting","LOCALS",1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("ja#polymorph","LOCALS",1)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spcl633",Myself)  // Baby wyvern
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
		SetInterrupt(TRUE)
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("ja#polymorph","LOCALS",1)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spcl632",Myself)  // Sword spider
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
		SetInterrupt(TRUE)
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("ja#polymorph","LOCALS",1)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spcl634",Myself)  // Fire salamander
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
		SetInterrupt(TRUE)
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("ja#polymorph","LOCALS",1)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spcl611",Myself)  // Brown bear
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
		SetInterrupt(TRUE)
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("ja#polymorph","LOCALS",1)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spcl612",Myself)  // Dread Wolf
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#polymorph","LOCALS",0)
	!Kit(Myself,TOTEMIC)
	!Kit(Myself,BEASTFRIEND)
	!Kit(Myself,SHAPESHIFTER)
	CheckStatGT(Myself,6,LEVEL)
	OR(2)
		HPPercentLT(Myself,70)
		Global("ja#disable_spellcasting","LOCALS",1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("ja#polymorph","LOCALS",1)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spcl611",Myself)  // Brown bear
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
		SetInterrupt(TRUE)
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("ja#polymorph","LOCALS",1)
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpellRES("spcl612",Myself)  // Dread Wolf
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
		SetInterrupt(TRUE)
END


/////////////////////////////////////////////////////////////////////
// Priests have weak defenses (comparing to mage)
// So try a disabling spell before buffing
// Silence 15' radius
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_SILENCE_15_FOOT)
	See(NearestEnemyOf(Myself))
	!Range(NearestEnemyOf(Myself),13)
	Global("ja#castsilence","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
		SetGlobal("ja#castsilence","LOCALS",1)
		RunAwayFromNoInterrupt(LastSeenBy(Myself),45)
		Spell(Myself,CLERIC_SANCTUARY)
END


/////////////////////////////////////////////////////////////////////
// Check if priest have some heal spells
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#nohealspells","LOCALS",0)
	!HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	!HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	!HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
	!HaveSpell(CLERIC_HEAL)
THEN
	RESPONSE #100
		SetGlobal("ja#nohealspells","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Mislead
/////////////////////////////////////////////////////////////////////
IF
	False()
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!StateCheck(Myself,STATE_INVISIBLE)
	HaveSpellRES("nmsun11")
	OR(2)
		Global("ja#buffdone","LOCALS",0)
		!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("nmsun11",Myself)
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Sanctuary if priest need to heal himself
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#disable_spellcasting","LOCALS",0)
	HPPercentLT(Myself,30)
	Global("nohealspell","LOCALS",0)
	CheckStat(Myself,0,SANCTUARY)
	HaveSpell(CLERIC_SANCTUARY)
THEN
	RESPONSE #100
		RunAwayFromNoInterrupt(LastSeenBy(Myself),15)
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_SANCTUARY)
END


/////////////////////////////////////////////////////////////////////
// Sanctuary during the initial buffing phase
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#disable_spellcasting","LOCALS",0)
	Global("ja#buffdone","LOCALS",0)
	CheckStat(Myself,0,SANCTUARY)
	HaveSpell(CLERIC_SANCTUARY)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_SANCTUARY)
END


/////////////////////////////////////////////////////////////////////
// Potion of invisibility
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	!StateCheck(Myself,STATE_INVISIBLE)	
	HasItem("_POTN10",Myself) // Potion of Invisibility
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		UseItem("_POTN10",Myself) // Potion of Invisibility
END


/////////////////////////////////////////////////////////////////////
// Greater restoration
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("cdltgrs")
	HPPercentLT(Myself,50)
	OR(2)
		CheckStat(Myself,1,SANCTUARY)
		!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("cdltgrs",Myself)
END


/////////////////////////////////////////////////////////////////////
// Heal
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_HEAL)
	HPPercentLT(Myself,50)
	OR(2)
		CheckStat(Myself,1,SANCTUARY)
		!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_HEAL)
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("cdlthel")
	HPPercentLT(Myself,50)
	OR(2)
		CheckStat(Myself,1,SANCTUARY)
		!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("cdlthel",Myself)
END


/////////////////////////////////////////////////////////////////////
// Cure serious wounds
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_CURE_SERIOUS_WOUNDS)
	HPPercentLT(Myself,70)
	OR(2)
		CheckStat(Myself,1,SANCTUARY)
		!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_CURE_SERIOUS_WOUNDS)
END


/////////////////////////////////////////////////////////////////////
// Cure medium wounds
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	HPPercentLT(Myself,80)
	OR(2)
		CheckStat(Myself,1,SANCTUARY)
		!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_CURE_MEDIUM_WOUNDS)
END

/////////////////////////////////////////////////////////////////////
// Cure light wounds
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	HPPercentLT(Myself,100)
	OR(2)
		CheckStat(Myself,1,SANCTUARY)
		!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
END


/////////////////////////////////////////////////////////////////////
// Shield of the archons
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_SHIELD_OF_THE_ARCHONS)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)
END


/////////////////////////////////////////////////////////////////////
// Protection from the elements
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("cdslpfe")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("cdslpfe",Myself)
END


/////////////////////////////////////////////////////////////////////
// Protection from normal weapons
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("cdhmpnw")
	CheckStat(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("cdhmpnw",Myself)
END


/////////////////////////////////////////////////////////////////////
// Ironskin (recast when have less than 2 stoneskins)
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_IRONSKIN)
	CheckStatLT(Myself,2,STONESKINS)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_IRONSKIN)
END


/////////////////////////////////////////////////////////////////////
// Impregnable mind
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("nmimpreg")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("nmimpreg",Myself)
END


/////////////////////////////////////////////////////////////////////
// Fire shield : red
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("a#kos07")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("a#kos07",Myself)
END


/////////////////////////////////////////////////////////////////////
// Magical resistance
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("sppr509")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("sppr509",Myself)
END


/////////////////////////////////////////////////////////////////////
// Defensive harmony
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_DEFENSIVE_HARMONY)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_DEFENSIVE_HARMONY)
END


/////////////////////////////////////////////////////////////////////
// Protection from lightning
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("SPPR407")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("SPPR407", Myself)
END


/////////////////////////////////////////////////////////////////////
// Protection from fire
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_PROTECTION_FROM_FIRE)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_PROTECTION_FROM_FIRE)
END


/////////////////////////////////////////////////////////////////////
// Chant
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_CHANT)
	GlobalTimerExpired("ja#chant","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_CHANT)
		SetGlobalTimer("ja#chant","LOCALS",60)
END


/////////////////////////////////////////////////////////////////////
// Free action
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_FREE_ACTION)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_FREE_ACTION)
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("cdslfre")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("cdslfre",Myself)
END


/////////////////////////////////////////////////////////////////////
// Holy power
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!CheckStat(Myself,3,SCRIPTINGSTATE5)
	HaveSpell(CLERIC_HOLY_POWER)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_HOLY_POWER)
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!CheckStat(Myself,3,SCRIPTINGSTATE5)
	HaveSpellRES("a#tem07")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("a#tem07",Myself)
END


/////////////////////////////////////////////////////////////////////
// Strenght of Stone
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("NMSTRSTN")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("NMSTRSTN",Myself)
END


/////////////////////////////////////////////////////////////////////
// Draw upon holy might
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)
	!GlobalTimerNotExpired("ja#holymight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)
		SetGlobalTimer("ja#holymight","LOCALS",60)
END


/////////////////////////////////////////////////////////////////////
// Righteous magic
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!CheckStat(Myself,6,SCRIPTINGSTATE5)
	HaveSpell(CLERIC_RIGHTEOUS_MAGIC)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_RIGHTEOUS_MAGIC)
END


/////////////////////////////////////////////////////////////////////
// True sight
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_TRUE_SIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_TRUE_SIGHT)
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("spcl232")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("spcl232",Myself)
END


/////////////////////////////////////////////////////////////////////
// Blade barrier
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_BLADE_BARRIER)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_BLADE_BARRIER)
END


/////////////////////////////////////////////////////////////////////
// Regeneration
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_REGENERATE)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_REGENERATE)
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("cdilrgn")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("cdilrgn",Myself)
END


/////////////////////////////////////////////////////////////////////
// Barkskin
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("SPPR202")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("SPPR202", Myself)
END


/////////////////////////////////////////////////////////////////////
// Armor of faith
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(CLERIC_ARMOR_OF_FAITH)
	!CheckStat(Myself,1,CLERIC_ARMOR_OF_FAITH)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,CLERIC_ARMOR_OF_FAITH)
END


/////////////////////////////////////////////////////////////////////
// Protection from Evil
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("sppr107")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("sppr107", Myself)
END


/////////////////////////////////////////////////////////////////////
// Protection from Good
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("CDPRGOOD")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("CDPRGOOD", Myself)
END


/////////////////////////////////////////////////////////////////////
// Divine shell
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("cddshel")
	!GlobalTimerNotExpired("ja#divineshell","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("cddshel",Myself)
		SetGlobalTimer("ja#divineshell","LOCALS",48)
END

