///////////////////////////////////////////////////////////////////////
// Greater Nabassu
///////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Just after resting, everything is reset and creature is healed
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("ja#PrepTimer","LOCALS")
	Global("ja#initialize","LOCALS",1)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Rest()
		ApplySpellRES("ja#HEAL",Myself)
		SetGlobal("ja#initialize","LOCALS",0)
END


///////////////////////////////////////////////////////////////////////
// Initialize variables & timers
///////////////////////////////////////////////////////////////////////
IF
	Global("ja#initialize","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#initialize","LOCALS",1)
		SetGlobal("ja#startcombat","LOCALS",0)
		SetGlobal("ja#deathgaze","LOCALS",0) // 20 death gazes per day
		SetGlobalTimer("ja#cast","LOCALS",0)
		SetGlobalTimer("ja#PrepTimer","LOCALS",2400)
END


/////////////////////////////////////////////////////////////////////
// See an enemy
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOf(Myself))
	Global("ja#startcombat","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#startcombat","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Do nothing if no enemy is detected and no combat started
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#startcombat","LOCALS",0)
	!Detect(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		NoAction()
END


/////////////////////////////////////////////////////////////////////
// Become ethereal (2x per day) or hide in shadows
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	!Detect(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpell(Myself,SUCCUBUS_ETHEREAL)
END


IF
	OR(2)
		Class(Myself,THIEF)
		Class(Myself,THIEF_ALL)
	!See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!GlobalTimerNotExpired("ja#stealth","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#stealth","LOCALS",9)
		Hide()
END


/////////////////////////////////////////////////////////////////////
// Are there any enemies that try to escape? follow them
/////////////////////////////////////////////////////////////////////
IF
	!Detect(NearestEnemyOf(Myself))
	Range(LastAttackerOf(Myself),70)
	HPGT(LastAttackerOf(Myself),0)
	StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		MoveToObject(LastAttackerOf(Myself))
END

IF
	!Detect(NearestEnemyOf(Myself))
	Range(PLAYER1,70)
	HPGT(PLAYER1,0)
	StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		MoveToObject(PLAYER1)
END

IF
	!Detect(NearestEnemyOf(Myself))
	Range(PLAYER2,70)
	HPGT(PLAYER2,0)
	StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		MoveToObject(PLAYER2)
END

IF
	!Detect(NearestEnemyOf(Myself))
	Range(PLAYER3,70)
	HPGT(PLAYER3,0)
	StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		MoveToObject(PLAYER3)
END

IF
	!Detect(NearestEnemyOf(Myself))
	Range(PLAYER4,70)
	HPGT(PLAYER4,0)
	StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		MoveToObject(PLAYER4)
END

IF
	!Detect(NearestEnemyOf(Myself))
	Range(PLAYER5,70)
	HPGT(PLAYER5,0)
	StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		MoveToObject(PLAYER5)
END

IF
	!Detect(NearestEnemyOf(Myself))
	Range(PLAYER6,70)
	HPGT(PLAYER6,0)
	StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		MoveToObject(PLAYER6)
END

IF
	!Detect(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		NoAction()
END


/////////////////////////////////////////////////////////////////////
// Backstab
/////////////////////////////////////////////////////////////////////
IF
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	OR(2)
		StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	StateCheck(Myself,STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
END

IF
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	StateCheck(Myself,STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_SLOWED)
		StateCheck(LastSeenBy(Myself),STATE_BLIND)
		StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
END

IF
  RandomNum(2,1)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(MostDamagedOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(2,2)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(WorstAC(Myself))
  False()
THEN
  RESPONSE #100
END

IF
	StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
		AttackOneRound(LastSeenBy(Myself))
END

IF
	StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		NoAction()
END


/////////////////////////////////////////////////////////////////////
// Paralyzation aura
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	!GlobalTimerNotExpired("ja#paralyze","LOCALS")
THEN
	RESPONSE #100
		ReallyForceSpellRES("ja#NABPA",LastSeenBy(Myself))
		SetGlobalTimer("ja#paralyze","LOCALS",6)
END


/////////////////////////////////////////////////////////////////////
// Death gaze
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Global("ja#deathgaze","LOCALS",20)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	RandomNum(4,1)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		IncrementGlobal("ja#deathgaze","LOCALS",1)		
		//ForceSpell(LastSeenBy(Myself),TANARI_DEATH_GAZE)
END


/////////////////////////////////////////////////////////////////////
// Silence 15' radius
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SILENCED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(SixthNearestEnemyOf(Myself),DRUID_ALL)
		Class(SixthNearestEnemyOf(Myself),BARD_ALL)
		Class(SixthNearestEnemyOf(Myself),CLERIC_ALL)
		Class(SixthNearestEnemyOf(Myself),MAGE_ALL)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SILENCED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(FifthNearestEnemyOf(Myself),DRUID_ALL)
		Class(FifthNearestEnemyOf(Myself),BARD_ALL)
		Class(FifthNearestEnemyOf(Myself),CLERIC_ALL)
		Class(FifthNearestEnemyOf(Myself),MAGE_ALL)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SILENCED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(FourthNearestEnemyOf(Myself),DRUID_ALL)
		Class(FourthNearestEnemyOf(Myself),BARD_ALL)
		Class(FourthNearestEnemyOf(Myself),CLERIC_ALL)
		Class(FourthNearestEnemyOf(Myself),MAGE_ALL)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SILENCED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(ThirdNearestEnemyOf(Myself),DRUID_ALL)
		Class(ThirdNearestEnemyOf(Myself),BARD_ALL)
		Class(ThirdNearestEnemyOf(Myself),CLERIC_ALL)
		Class(ThirdNearestEnemyOf(Myself),MAGE_ALL)	
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SILENCED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(SecondNearestEnemyOf(Myself),DRUID_ALL)
		Class(SecondNearestEnemyOf(Myself),BARD_ALL)
		Class(SecondNearestEnemyOf(Myself),CLERIC_ALL)
		Class(SecondNearestEnemyOf(Myself),MAGE_ALL)	
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(NearestEnemyOf(Myself),STATE_SILENCED)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(NearestEnemyOf(Myself),DRUID_ALL)
		Class(NearestEnemyOf(Myself),BARD_ALL)
		Class(NearestEnemyOf(Myself),CLERIC_ALL)
		Class(NearestEnemyOf(Myself),MAGE_ALL)	
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	OR(4)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),MAGE_ALL)	
	See(LastSeenBy(Myself))	
	RandomNum(4,2)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#_cast","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),TANARI_SILENCE)
		//ForceSpell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
END


/////////////////////////////////////////////////////////////////////
// Energy Drain
/////////////////////////////////////////////////////////////////////
IF
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	GlobalTimerExpired("ja#cast","LOCALS")
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	RandomNum(4,3)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		//ForceSpellRES("SPWI914",LastSeenBy(Myself))
		ForceSpell(LastSeenBy(Myself),WIZARD_ENERGY_DRAIN)
END


/////////////////////////////////////////////////////////////////////
// Vampiric touch
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	Range(SixthNearestEnemyOf(Myself),5)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	Range(FifthNearestEnemyOf(Myself),5)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	Range(FourthNearestEnemyOf(Myself),5)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	Range(ThirdNearestEnemyOf(Myself),5)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	Range(SecondNearestEnemyOf(Myself),5)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	Range(NearestEnemyOf(Myself),5)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	Range(LastSeenBy(Myself),5)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		ForceSpell(LastSeenBy(Myself),TANARI_VAMPIRIC_TOUCH)
		//ForceSpell(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)
END


/////////////////////////////////////////////////////////////////////
// Find a helpless target to attack
/////////////////////////////////////////////////////////////////////
IF
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	OR(2)
		StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Find something to attack, which has bonus on to hit
/////////////////////////////////////////////////////////////////////
IF
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_SLOWED)
		StateCheck(LastSeenBy(Myself),STATE_BLIND)
		StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Find something to attack, which has control of itself
/////////////////////////////////////////////////////////////////////
IF
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Random attack (priority on melee range target)
/////////////////////////////////////////////////////////////////////

// three melee target
IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,1)
  OR(3)
  	See(NearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,2)
  OR(3)
  	See(SecondNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,3)
  OR(3)
  	See(NearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,4)
  OR(3)
  	See(ThirdNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,5)
  OR(3)
  	See(SecondNearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,6)
  OR(3)
  	See(ThirdNearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

// two melee target
IF
  !Range(ThirdNearestEnemyOf(Myself),8)
  Range(SecondNearestEnemyOf(Myself),8)
  RandomNum(2,1)
  OR(2)
  	See(NearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Range(ThirdNearestEnemyOf(Myself),8)
  Range(SecondNearestEnemyOf(Myself),8)
  RandomNum(2,2)
  OR(2)
  	See(SecondNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

// one melee target
IF
  !Range(SecondNearestEnemyOf(Myself),8)
  Range(NearestEnemyOf(Myself),8)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
	See(LastSeenBy(Myself))
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END


// No target in melee range, pick a random one
IF
  RandomNum(8,1)
  See(NearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,2)
  See(FourthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,3)
  See(SixthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,4)
  See(FourthNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,5)
  See(SixthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,6)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,7)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(WeakestOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,8)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(MostDamagedOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

