///////////////////////////////////////////////////////////////////////
// Mage : diviner
// - contingency and chain contingencies
// - minor sequencer, spell sequencer, spell trigger
///////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Contingency, level 12-14
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#contigency","LOCALS",0)
	CheckStatGT(Myself,11,LEVEL)
	CheckStatLT(Myself,15,LEVEL)
THEN
	RESPONSE #100
		SetGlobal("ja#contigency","LOCALS",1)
		DisplayString(Myself,84763) // Contingency Released
		ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
END


/////////////////////////////////////////////////////////////////////
// Contingency, level 15-17
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#contigency","LOCALS",0)
	CheckStatGT(Myself,14,LEVEL)
	CheckStatLT(Myself,18,LEVEL)
THEN
	RESPONSE #100
		SetGlobal("ja#contigency","LOCALS",1)
		DisplayString(Myself,84763) // Contingency Released
		ReallyForceSpell(Myself,WIZARD_MINOR_SPELL_TURNING)
END


/////////////////////////////////////////////////////////////////////
// Chain contingencies, level 18+
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#contigency","LOCALS",0)
	CheckStatGT(Myself,17,LEVEL)
	!RandomNum(4,1)
THEN
	RESPONSE #100
		SetGlobal("ja#contigency","LOCALS",1)
		DisplayString(Myself,26328) // Chain Contingency
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_DISPEL_MAGIC)
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_PRISMATIC_SPRAY)
END

IF
	Global("ja#contigency","LOCALS",0)
	CheckStatGT(Myself,17,LEVEL)
THEN
	RESPONSE #100
		SetGlobal("ja#contigency","LOCALS",1)
		DisplayString(Myself,26328) // Chain Contingency
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)
		ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)
		ReallyForceSpell(Myself,WIZARD_TRUE_SIGHT)
END


/////////////////////////////////////////////////////////////////////
// Minor sequencer, level 7-13
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),2,SCRIPTINGSTATE3) // Wizard shield
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),2,SCRIPTINGSTATE3) // Wizard shield
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),2,SCRIPTINGSTATE3) // Wizard shield
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),2,SCRIPTINGSTATE3) // Wizard shield
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),2,SCRIPTINGSTATE3) // Wizard shield
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),2,SCRIPTINGSTATE3) // Wizard shield
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	Global("ja#sequencer","LOCALS",0)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStatGT(Myself,6,LEVEL)
	CheckStatLT(Myself,14,LEVEL)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3) // Wizard shield
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		DisplayString(Myself,8635) // Minor Sequencer Activated
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_HORROR)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
		SetGlobal("ja#sequencer","LOCALS",1)
END

IF
	Global("ja#sequencer","LOCALS",0)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStatGT(Myself,6,LEVEL)
	CheckStatLT(Myself,14,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		DisplayString(Myself,8635) // Minor Sequencer Activated
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_EVIL)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
		SetGlobal("ja#sequencer","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Spell sequencer, level 14
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(SixthNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(SixthNearestEnemyOf(Myself))
		CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(FifthNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(FifthNearestEnemyOf(Myself))
		CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)	
		CheckStatGT(FourthNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(FourthNearestEnemyOf(Myself))
		CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(ThirdNearestEnemyOf(Myself),18,STR)	
		HasImmunityEffects(ThirdNearestEnemyOf(Myself))	
		CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(SecondNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(SecondNearestEnemyOf(Myself))
		CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)	
		CheckStatGT(NearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(NearestEnemyOf(Myself))
		CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	Global("ja#sequencer","LOCALS",0)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStat(Myself,14,LEVEL)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)	
		CheckStatGT(LastSeenBy(Myself),18,STR)
		HasImmunityEffects(LastSeenBy(Myself))
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(LastSeenBy(Myself))
	!RandomNum(4,1)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		DisplayString(Myself,25951) // Spell Sequencer
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SECRET_WORD)		
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
		SetGlobal("ja#sequencer","LOCALS",1)
END

IF
	Global("ja#sequencer","LOCALS",0)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStat(Myself,14,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		DisplayString(Myself,25951) // Spell Sequencer
		ReallyForceSpell(Myself,WIZARD_SPIRIT_ARMOR)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)
		ReallyForceSpell(Myself,WIZARD_SPIDER_SPAWN)
		SetGlobal("ja#sequencer","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Spell sequencer, level 15
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#sequencer","LOCALS",0)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStat(Myself,15,LEVEL)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)	
		CheckStatGT(LastSeenBy(Myself),18,STR)
		HasImmunityEffects(LastSeenBy(Myself))
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(LastSeenBy(Myself))
	!RandomNum(4,1)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		DisplayString(Myself,25951) // Spell Sequencer
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SECRET_WORD)		
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
		SetGlobal("ja#sequencer","LOCALS",1)
END

IF
	Global("ja#sequencer","LOCALS",0)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStat(Myself,15,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		DisplayString(Myself,25951) // Spell Sequencer
		ReallyForceSpell(Myself,WIZARD_SPIRIT_ARMOR)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)
		ReallyForceSpell(Myself,WIZARD_SPIDER_SPAWN)
		SetGlobal("ja#sequencer","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Spell trigger, level 16-17
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(SixthNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(SixthNearestEnemyOf(Myself))
		CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(FifthNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(FifthNearestEnemyOf(Myself))
		CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)	
		CheckStatGT(FourthNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(FourthNearestEnemyOf(Myself))
		CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(ThirdNearestEnemyOf(Myself),18,STR)	
		HasImmunityEffects(ThirdNearestEnemyOf(Myself))	
		CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)
		CheckStatGT(SecondNearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(SecondNearestEnemyOf(Myself))
		CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,PROTECTION_FROM_MAGIC) 
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	OR(5)	
		CheckStatGT(NearestEnemyOf(Myself),18,STR)
		HasImmunityEffects(NearestEnemyOf(Myself))
		CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
		CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
		CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	Global("ja#sequencer","LOCALS",0)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStatGT(Myself,15,LEVEL)
	CheckStatLT(Myself,18,LEVEL)
	!CheckStat(LastSeenBy(Myself),1,PROTECTION_FROM_MAGIC) 
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		DisplayString(Myself,26243) // Spell Trigger
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_BREACH)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
		SetGlobal("ja#sequencer","LOCALS",1)
END

IF
	Global("ja#sequencer","LOCALS",0)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStatGT(Myself,15,LEVEL)
	CheckStatLT(Myself,18,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		DisplayString(Myself,26243) // Spell Trigger
		ReallyForceSpell(Myself,WIZARD_WYVERN_CALL)		
		ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		SetGlobal("ja#sequencer","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Spell trigger, level 18+
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#sequencer","LOCALS",0)
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStatGT(Myself,17,LEVEL)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		DisplayString(Myself,26243) // Spell Trigger
		ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
		ReallyForceSpell(Myself,WIZARD_SPELL_DEFLECTION)		
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		SetGlobal("ja#sequencer","LOCALS",1)
END


