///////////////////////////////////////////////////////////////////////
// Fighting with a weapon, for intelligent monsters
///////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Find a slept target. this only work for PC's enemies            //
// because sleeping creatures are not considered as enemies        //
/////////////////////////////////////////////////////////////////////
IF
	!StateCheck(Player6,STATE_CHARMED)
	CheckStat(Player6,0,SANCTUARY)
	StateCheck(Player6,STATE_SLEEPING)
	See(Player6)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player5,STATE_CHARMED)
	CheckStat(Player5,0,SANCTUARY)
	StateCheck(Player5,STATE_SLEEPING)
	See(Player5)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player4,STATE_CHARMED)
	CheckStat(Player4,0,SANCTUARY)
	StateCheck(Player4,STATE_SLEEPING)
	See(Player4)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player3,STATE_CHARMED)
	CheckStat(Player3,0,SANCTUARY)
	StateCheck(Player3,STATE_SLEEPING)
	See(Player3)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player2,STATE_CHARMED)
	CheckStat(Player2,0,SANCTUARY)
	StateCheck(Player2,STATE_SLEEPING)
	See(Player2)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player1,STATE_CHARMED)
	CheckStat(Player1,0,SANCTUARY)
	StateCheck(Player1,STATE_SLEEPING)
	See(Player1)
	False()
THEN
	RESPONSE #100
END

IF
	Allegiance(Myself,Enemy)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	See(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END	

IF
	Allegiance(Myself,Enemy)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	See(LastSeenBy(Myself))
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END	


/////////////////////////////////////////////////////////////////////
// Do nothing if no enemies are seen
/////////////////////////////////////////////////////////////////////
IF
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		NoAction()
END


/////////////////////////////////////////////////////////////////////
// Find a helpless target to attack
/////////////////////////////////////////////////////////////////////
IF
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	OR(2)
		StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	See(LastSeenBy(Myself))	
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	See(LastSeenBy(Myself))	
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////////////////
// Find something to attack, which has bonus on to hit
/////////////////////////////////////////////////////////////////////
IF
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_SLOWED)
		StateCheck(LastSeenBy(Myself),STATE_BLIND)
		StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	See(LastSeenBy(Myself))	
	Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_SLOWED)
		StateCheck(LastSeenBy(Myself),STATE_BLIND)
		StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	See(LastSeenBy(Myself))	
	!Range(LastSeenBy(Myself),5)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////////////////
// Find something to attack, which has control of itself
/////////////////////////////////////////////////////////////////////
IF
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	Range(LastSeenBy(Myself),5)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!Range(LastSeenBy(Myself),5)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

/////////////////////////////////////////////////////////////////////
// Random attack (priority on melee range target)
/////////////////////////////////////////////////////////////////////

// three melee target
IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,1)
  OR(3)
  	See(NearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,2)
  OR(3)
  	See(SecondNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,3)
  OR(3)
  	See(NearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,4)
  OR(3)
  	See(ThirdNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,5)
  OR(3)
  	See(SecondNearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,6)
  OR(3)
  	See(ThirdNearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

// two melee target
IF
  !Range(ThirdNearestEnemyOf(Myself),8)
  Range(SecondNearestEnemyOf(Myself),8)
  RandomNum(2,1)
  OR(2)
  	See(NearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Range(ThirdNearestEnemyOf(Myself),8)
  Range(SecondNearestEnemyOf(Myself),8)
  RandomNum(2,2)
  OR(2)
  	See(SecondNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

// one melee target
IF
  !Range(SecondNearestEnemyOf(Myself),8)
  Range(NearestEnemyOf(Myself),8)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
	Range(LastSeenBy(Myself),5)
	See(LastSeenBy(Myself))
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END


// No target in melee range, pick a random one
IF
  RandomNum(8,1)
  See(NearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,2)
  See(FourthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,3)
  See(SixthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,4)
  See(FourthNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,5)
  See(SixthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,6)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,7)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(WeakestOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,8)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(MostDamagedOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
	!Range(LastSeenBy(Myself),5)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
THEN
	RESPONSE #100
		EquipRanged()
		AttackOneRound(LastSeenBy(Myself))
END

IF
	Range(LastSeenBy(Myself),5)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackOneRound(LastSeenBy(Myself))
END

