///////////////////////////////////////////////////////////////////////
// Threat Detection for NORMAL monsters
// This script has many purposes:
// - turn hostile if attacked
// - alert nearby monsters, requesting help
// - entering/leaving combat
// - sleep
///////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Rest - everything is reset
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("ja#PrepTimer","LOCALS")
	!Global("ja#initialize","LOCALS",0)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Rest()
		ApplySpellRES("ja#HEAL",Myself) // it can be considered as a cheat, but it prevents many exploits
		SetGlobal("ja#initialize","LOCALS",0)
END


///////////////////////////////////////////////////////////////////////
// Initialize variables & timers
///////////////////////////////////////////////////////////////////////
IF
	Global("ja#initialize","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#initialize","LOCALS",1)
		SetGlobal("ja#startcombat","LOCALS",0)
		SetGlobalTimer("ja#PrepTimer","LOCALS",2400)
END


///////////////////////////////////////////////////////////////////////
// Attacked? Spell cast on me? Someone shouted a warning?
///////////////////////////////////////////////////////////////////////
IF
	!Allegiance(Myself,ENEMY)
	OR(12)
		AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
		AttackedBy([PC],DEFAULT)
		AttackedBy([FAMILIAR],DEFAULT)
		AttackedBy([ALLY],DEFAULT)
		AttackedBy([CONTROLLED],DEFAULT)
		AttackedBy([CHARMED],DEFAULT)
		SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
		SpellCastOnMe([PC],0)
		SpellCastOnMe([FAMILIAR],0)
		SpellCastOnMe([ALLY],0)
		SpellCastOnMe([CONTROLLED],0)
		SpellCastOnMe([CHARMED],0)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Heard([ANYONE],95)
	Allegiance(Myself,NEUTRAL)
	Range(LastHeardBy(Myself),20)
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("ja#startcombat","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Heard([ANYONE],95)
	!See(NearestEnemyOf(Myself))	
	Range(LastHeardBy(Myself),20)
THEN
	RESPONSE #100
		SetGlobal("ja#startcombat","LOCALS",1)
		MoveToObject(LastHeardBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// See an enemy
/////////////////////////////////////////////////////////////////////
IF
	See(NearestEnemyOf(Myself))
	Global("ja#startcombat","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#startcombat","LOCALS",1)
		Shout(95)
END///////////////////////////////////////////////////////////////////////
// Movement and Tracking:
// Not in combat : do nothing
// In combat : random walk or track the target
///////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Are there any enemies that try to escape, follow them
// It's not about sight but memory (I saw that enemy going in that dir.)
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#startcombat","LOCALS",1)
	!See(NearestEnemyOf(Myself))
	!StateCheck(LastAttackerOf(Myself),STATE_INVISIBLE)
	Range(LastAttackerOf(Myself),70)
THEN
	RESPONSE #100
		MoveToObject(LastAttackerOf(Myself))
END

IF
	Global("ja#startcombat","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!See(NearestEnemyOf(Myself))
	!StateCheck(Player1,STATE_INVISIBLE)
	Range(Player1,70)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Global("ja#startcombat","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!See(NearestEnemyOf(Myself))
	!StateCheck(Player2,STATE_INVISIBLE)
	Range(Player2,70)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	Global("ja#startcombat","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!See(NearestEnemyOf(Myself))
	!StateCheck(Player3,STATE_INVISIBLE)
	Range(Player3,70)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	Global("ja#startcombat","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!See(NearestEnemyOf(Myself))
	!StateCheck(Player4,STATE_INVISIBLE)
	Range(Player4,70)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	Global("ja#startcombat","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!See(NearestEnemyOf(Myself))
	!StateCheck(Player5,STATE_INVISIBLE)
	Range(Player5,70)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	Global("ja#startcombat","LOCALS",1)
	Allegiance(Myself,ENEMY)
	!See(NearestEnemyOf(Myself))
	!StateCheck(Player6,STATE_INVISIBLE)
	Range(Player6,70)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END

///////////////////////////////////////////////////////////////////////
// Ankheg
///////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Acid once per day
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	See(NearestEnemyOf(Myself))
	HaveSpellRES("ja#ANKH")
	HPPercentLT(Myself,30)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("ja#ANKH",LastSeenBy(Myself))
END///////////////////////////////////////////////////////////////////////
// Fighting with a weapon, for non-intelligent monsters
///////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Do nothing if no enemies are seen
/////////////////////////////////////////////////////////////////////
IF
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		NoAction()
END


/////////////////////////////////////////////////////////////////////
// Find a slept target. this only work for PC's enemies            //
// because sleeping creatures are not considered as enemies        //
/////////////////////////////////////////////////////////////////////
IF
	!StateCheck(Player6,STATE_CHARMED)
	CheckStat(Player6,0,SANCTUARY)
	StateCheck(Player6,STATE_SLEEPING)
	See(Player6)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player5,STATE_CHARMED)
	CheckStat(Player5,0,SANCTUARY)
	StateCheck(Player5,STATE_SLEEPING)
	See(Player5)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player4,STATE_CHARMED)
	CheckStat(Player4,0,SANCTUARY)
	StateCheck(Player4,STATE_SLEEPING)
	See(Player4)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player3,STATE_CHARMED)
	CheckStat(Player3,0,SANCTUARY)
	StateCheck(Player3,STATE_SLEEPING)
	See(Player3)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player2,STATE_CHARMED)
	CheckStat(Player2,0,SANCTUARY)
	StateCheck(Player2,STATE_SLEEPING)
	See(Player2)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player1,STATE_CHARMED)
	CheckStat(Player1,0,SANCTUARY)
	StateCheck(Player1,STATE_SLEEPING)
	See(Player1)
	False()
THEN
	RESPONSE #100
END

IF
	Allegiance(Myself,Enemy)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),15)
		//AttackOneRound(LastSeenBy(Myself))
END	


/////////////////////////////////////////////////////////////////////
// Random attack (priority on melee range target)
/////////////////////////////////////////////////////////////////////

// three melee target
IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,1)
  OR(3)
  	See(NearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,2)
  OR(3)
  	See(SecondNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,3)
  OR(3)
  	See(NearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,4)
  OR(3)
  	See(ThirdNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,5)
  OR(3)
  	See(SecondNearestEnemyOf(Myself))
  	See(ThirdNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  Range(ThirdNearestEnemyOf(Myself),8)
  RandomNum(6,6)
  OR(3)
  	See(ThirdNearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

// two melee target
IF
  !Range(ThirdNearestEnemyOf(Myself),8)
  Range(SecondNearestEnemyOf(Myself),8)
  RandomNum(2,1)
  OR(2)
  	See(NearestEnemyOf(Myself))
  	See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !Range(ThirdNearestEnemyOf(Myself),8)
  Range(SecondNearestEnemyOf(Myself),8)
  RandomNum(2,2)
  OR(2)
  	See(SecondNearestEnemyOf(Myself))
  	See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

// one melee target
IF
  !Range(SecondNearestEnemyOf(Myself),8)
  Range(NearestEnemyOf(Myself),8)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
	Range(LastSeenBy(Myself),8)
	See(LastSeenBy(Myself))
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	//!GlobalTimerNotExpired("ja#attack","LOCALS")
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),15)
		//AttackOneRound(LastSeenBy(Myself))
END


// No target in melee range, pick a random one
IF
  RandomNum(8,1)
  See(NearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,2)
  See(FourthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,3)
  See(SixthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,4)
  See(FourthNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(SixthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,5)
  See(SixthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,6)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,7)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(WeakestOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(8,8)
  See(SixthNearestEnemyOf(Myself))
  See(FifthNearestEnemyOf(Myself))
  See(FourthNearestEnemyOf(Myself))
  See(ThirdNearestEnemyOf(Myself))
  See(SecondNearestEnemyOf(Myself))
  See(NearestEnemyOf(Myself))
  See(MostDamagedOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
	See(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),5)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	//!GlobalTimerNotExpired("ja#attack","LOCALS")
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),15)
		//AttackOneRound(LastSeenBy(Myself))
END
