///////////////////////////////////////////////////////////////////////
// Spellcasting for mages
// - protection/buff spells
///////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Counter silence
/////////////////////////////////////////////////////////////////////
IF
	StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_VOCALIZE)	
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_VOCALIZE)
END


/////////////////////////////////////////////////////////////////////
// Back to human form
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#polymorph","LOCALS",1)	
	CheckStat(Myself,0,POLYMORPH_SELF) 
	!Race(Myself,LYCANTHROPE)
THEN
	RESPONSE #100
		SetGlobal("ja#polymorph","LOCALS",0)
		SetGlobal("ja#disable_spellcasting","LOCALS",0)
END


/////////////////////////////////////////////////////////////////////
// Unable to cast a spell
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#disable_spellcasting","LOCALS",0)
	OR(2)
		StateCheck(Myself,STATE_SILENCED)
		CheckStatGT(Myself,69,SPELLFAILUREPRIEST)
THEN
	RESPONSE #100
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Able to cast a spell
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#disable_spellcasting","LOCALS",1)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,70,SPELLFAILUREPRIEST)
	!CheckStat(Myself,1,SCRIPTINGSTATE3) // Tenser's tranformation
	!CheckStat(Myself,1,POLYMORPH_SELF)
	!CheckStat(Myself,1,WIZARD_MISLEAD)
	!Global("ja#polymorph","LOCALS",1)	
THEN
	RESPONSE #100
		SetGlobal("ja#disable_spellcasting","LOCALS",0)
END


/////////////////////////////////////////////////////////////////////
// Improved chaos shield
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("spwi723")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("spwi723",Myself)
END


/////////////////////////////////////////////////////////////////////
// Chaos shield
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpellRES("spwi222")
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		SpellRES("spwi222",Myself)
END


/////////////////////////////////////////////////////////////////////
// Timestop
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_TIME_STOP)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_TIME_STOP)
END


/////////////////////////////////////////////////////////////////////
// Improved mantle
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_IMPROVED_MANTLE)
	CheckStat(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)	
	HitBy([ANYONE],CRUSHING)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_IMPROVED_MANTLE)
END


/////////////////////////////////////////////////////////////////////
// Mantle
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MANTLE)
	CheckStat(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	HitBy([ANYONE],CRUSHING)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_MANTLE)
END


/////////////////////////////////////////////////////////////////////
// Protection from magical weapons
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	CheckStat(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	HitBy([ANYONE],CRUSHING)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
END


/////////////////////////////////////////////////////////////////////
// Stoneskin (recast when have less than 2 stoneskins)
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_STONE_SKIN)
	CheckStatLT(Myself,2,STONESKINS)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_STONE_SKIN)
END


/////////////////////////////////////////////////////////////////////
// Tenser Transformation when no more weapon protections
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_TENSERS_TRANSFORMATION)	
	!HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!HaveSpell(WIZARD_STONE_SKIN)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_TENSERS_TRANSFORMATION)
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Mass invisibility
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!StateCheck(Myself,STATE_INVISIBLE)
	HaveSpell(WIZARD_MASS_INVISIBILITY)
	OR(2)
		Global("ja#buffdone","LOCALS",0)
		!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_MASS_INVISIBILITY)
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Mislead
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!StateCheck(Myself,STATE_INVISIBLE)
	HaveSpell(WIZARD_MISLEAD)
	OR(2)
		Global("ja#buffdone","LOCALS",0)
		!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_MISLEAD)
		SetGlobal("ja#disable_spellcasting","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Shadow door
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!StateCheck(Myself,STATE_INVISIBLE)
	HaveSpell(WIZARD_SHADOW_DOOR)
	OR(2)
		Global("ja#buffdone","LOCALS",0)
		!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_SHADOW_DOOR)
END


/////////////////////////////////////////////////////////////////////
// Improved invisibilty
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!StateCheck(Myself,STATE_INVISIBLE)
	HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
	OR(2)
		Global("ja#buffdone","LOCALS",0)
		!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)
END


/////////////////////////////////////////////////////////////////////
// Invisibility
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!StateCheck(Myself,STATE_INVISIBLE)
	HaveSpell(WIZARD_INVISIBILITY)
	Global("ja#buffdone","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_INVISIBILITY)
END


/////////////////////////////////////////////////////////////////////
// Potion of invisibility
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	!StateCheck(Myself,STATE_INVISIBLE)	
	HasItem("_POTN10",Myself) // Potion of Invisibility
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		UseItem("_POTN10",Myself) // Potion of Invisibility
END


/////////////////////////////////////////////////////////////////////
// Invisibility on 3 meters
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!StateCheck(Myself,STATE_INVISIBLE)
	HaveSpell(WIZARD_INVISIBILITY_10_FOOT)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_INVISIBILITY_10_FOOT)
END


/////////////////////////////////////////////////////////////////////
// Protection from the elements
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_PROTECTION_FROM_THE_ELEMENTS)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
END


/////////////////////////////////////////////////////////////////////
// Protection from normal weapons
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStat(Myself,0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
	HaveSpell(WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
END


/////////////////////////////////////////////////////////////////////
// Globe of invulnerability
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_GLOBE_OF_INVULNERABILITY)	
	CheckStat(Myself,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
END


/////////////////////////////////////////////////////////////////////
// Minor globe of invulnerability
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
	CheckStat(Myself,0,MINORGLOBE)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
END


/////////////////////////////////////////////////////////////////////
// Spell immunity
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SPELL_IMMUNITY)	
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_SPELL_IMMUNITY_INVOCATION)
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_SPELL_IMMUNITY_ENCHANTMENT)
	RESPONSE #80
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_SPELL_IMMUNITY_NECROMANCY)
	RESPONSE #80
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_SPELL_IMMUNITY_ALTERATION)
	RESPONSE #60
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_SPELL_IMMUNITY_CONJURATION)						
END


/////////////////////////////////////////////////////////////////////
// Spell turning
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_SPELL_TURNING)
END


/////////////////////////////////////////////////////////////////////
// Spell deflection
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_SPELL_DEFLECTION)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_SPELL_DEFLECTION)
END


/////////////////////////////////////////////////////////////////////
// Minor spell turning
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MINOR_SPELL_TURNING)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_MINOR_SPELL_TURNING)
END


/////////////////////////////////////////////////////////////////////
// Minor spell deflection
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MINOR_SPELL_DEFLECTION)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)
END


/////////////////////////////////////////////////////////////////////
// Blur
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_BLUR)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_BLUR)
END


/////////////////////////////////////////////////////////////////////
// Fire shield red
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!CheckStat(Myself,1,WIZARD_FIRE_SHIELD)
	HaveSpell(WIZARD_FIRE_SHIELD_RED)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_FIRE_SHIELD_RED)
END


/////////////////////////////////////////////////////////////////////
// Fire shield blue
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!CheckStat(Myself,2,WIZARD_FIRE_SHIELD)
	HaveSpell(WIZARD_FIRE_SHIELD_BLUE)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_FIRE_SHIELD_BLUE)
END


/////////////////////////////////////////////////////////////////////
// Mirror image
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_MIRROR_IMAGE)	
	!StateCheck(Myself,STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_MIRROR_IMAGE)
END


/////////////////////////////////////////////////////////////////////
// Reflected image
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_REFLECTED_IMAGE)	
	!StateCheck(Myself,STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_REFLECTED_IMAGE)
END


/////////////////////////////////////////////////////////////////////
// True sight
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	CheckStat(Myself,0,TRUE_SIGHT)
	HaveSpell(WIZARD_TRUE_SIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_TRUE_SIGHT)
END


/////////////////////////////////////////////////////////////////////
// Protection from evil
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_PROTECTION_FROM_EVIL)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_PROTECTION_FROM_EVIL)
END


/////////////////////////////////////////////////////////////////////
// Improved haste
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_IMPROVED_HASTE)
	!StateCheck(Myself,STATE_HASTED)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_IMPROVED_HASTE)
END


/////////////////////////////////////////////////////////////////////
// Haste
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_HASTE)
	!StateCheck(Myself,STATE_HASTED)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_HASTE)
END


/////////////////////////////////////////////////////////////////////
// Shield
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	!CheckStat(Myself,2,SCRIPTINGSTATE3) // Shield
	HaveSpell(WIZARD_SHIELD)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_SHIELD)
END


/////////////////////////////////////////////////////////////////////
// Wraith form
/////////////////////////////////////////////////////////////////////
IF
	!GlobalTimerNotExpired("ja#cast","LOCALS")
	Global("ja#disable_spellcasting","LOCALS",0)
	HaveSpell(WIZARD_WRAITH_FORM)
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(Myself,WIZARD_WRAITH_FORM)
END


