///////////////////////////////////////////////////////////////////////
// Nymph                                                             //
///////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////
// Threat Detection
//
// Attacked? Spell cast on me? Someone shouted a warning?
///////////////////////////////////////////////////////////////////////
IF
	!Allegiance(Myself,ENEMY)
	OR(13)
		AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
		AttackedBy([PC],DEFAULT)
		AttackedBy([FAMILIAR],DEFAULT)
		AttackedBy([ALLY],DEFAULT)
		AttackedBy([CONTROLLED],DEFAULT)
		AttackedBy([CHARMED],DEFAULT)
		SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
		SpellCastOnMe([PC],0)
		SpellCastOnMe([FAMILIAR],0)
		SpellCastOnMe([ALLY],0)
		SpellCastOnMe([CONTROLLED],0)
		SpellCastOnMe([CHARMED],0)
		Allegiance(LastSummonerOf(Myself),Enemy)
THEN
	RESPONSE #100
		Enemy()
		Continue()
END


///////////////////////////////////////////////////////////////////////
// Initialize variables & timers
///////////////////////////////////////////////////////////////////////
IF
	Global("ja#initialize","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#initialize","LOCALS",1)
		SetGlobal("ja#teleport","LOCALS",0)
		SetGlobalTimer("ja#cast","LOCALS",0)
END


/////////////////////////////////////////////////////////////////////
// if no enemy, follow summoner
/////////////////////////////////////////////////////////////////////
IF
	InMyArea(LastSummonerOf(Myself))
	HPGT(LastSummonerOf(Myself),0)
	!See(LastSummonerOf(Myself))
	!See(NearestEnemyOf(Myself))
	Global("ja#teleport","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ja#teleport","LOCALS",1)
		ForceSpellRES("SPWI931",LastSummonerOf(Myself))
END

IF
	ActionListEmpty()
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastSummonerOf(Myself))
		Continue()
END


/////////////////////////////////////////////////////////////////////
// Do nothing if no enemy is detected
/////////////////////////////////////////////////////////////////////
IF
	!Detect(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		NoAction()
END


/////////////////////////////////////////////////////////////////////
// Nymph nature beauty
/////////////////////////////////////////////////////////////////////
IF
	Global("ja#nature","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		ForceSpell(LastSeenBy(Myself),CLERIC_NATURE_BEAUTY)
		SetGlobal("ja#nature","LOCALS",1)
END


/////////////////////////////////////////////////////////////////////
// Now, it's time to kill things
// Priorities are:
//   Charm/dominate the best fighter
//   Disable spells
//   Damage spells
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Find someone to charm
/////////////////////////////////////////////////////////////////////
IF
	!Race(SixthNearestEnemyOf(Myself),ELF)
	!CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(SixthNearestEnemyOf(Myself),30)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)	
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(FifthNearestEnemyOf(Myself),ELF)
	!CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(FifthNearestEnemyOf(Myself),30)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(FourthNearestEnemyOf(Myself),ELF)
	!CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(FourthNearestEnemyOf(Myself),30)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(ThirdNearestEnemyOf(Myself),ELF)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(ThirdNearestEnemyOf(Myself),30)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)	
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(SecondNearestEnemyOf(Myself),ELF)
	!CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(SecondNearestEnemyOf(Myself),30)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)		
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!Race(NearestEnemyOf(Myself),ELF)
	!CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	HPPercentGT(NearestEnemyOf(Myself),30)
	!StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)		
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Domination
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("ja#cast","LOCALS")
	HaveSpell(CLERIC_MENTAL_DOMINATION)
	!Race(LastSeenBy(Myself),ELF)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	HPPercentGT(LastSeenBy(Myself),30)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)		
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	OR(3)
		Class(LastSeenBy(Myself),FIGHTER_ALL)
		Class(LastSeenBy(Myself),PALADIN_ALL)
		Class(LastSeenBy(Myself),RANGER_ALL)
	See(LastSeenBy(Myself))
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_DOOM)
		SmallWait(1)
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
END


/////////////////////////////////////////////////////////////////////
// Begin of block:
// miscast magic, summon insects
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(SixthNearestEnemyOf(Myself),0,CLERIC_INSECT_PLAGUE)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(SixthNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(SixthNearestEnemyOf(Myself),DRUID_ALL)
		Class(SixthNearestEnemyOf(Myself),BARD_ALL)
		Class(SixthNearestEnemyOf(Myself),CLERIC_ALL)
		Class(SixthNearestEnemyOf(Myself),MAGE_ALL)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(FifthNearestEnemyOf(Myself),0,CLERIC_INSECT_PLAGUE)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(FifthNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(FifthNearestEnemyOf(Myself),DRUID_ALL)
		Class(FifthNearestEnemyOf(Myself),BARD_ALL)
		Class(FifthNearestEnemyOf(Myself),CLERIC_ALL)
		Class(FifthNearestEnemyOf(Myself),MAGE_ALL)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(FourthNearestEnemyOf(Myself),0,CLERIC_INSECT_PLAGUE)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(FourthNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(FourthNearestEnemyOf(Myself),DRUID_ALL)
		Class(FourthNearestEnemyOf(Myself),BARD_ALL)
		Class(FourthNearestEnemyOf(Myself),CLERIC_ALL)
		Class(FourthNearestEnemyOf(Myself),MAGE_ALL)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(ThirdNearestEnemyOf(Myself),0,CLERIC_INSECT_PLAGUE)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(ThirdNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(ThirdNearestEnemyOf(Myself),DRUID_ALL)
		Class(ThirdNearestEnemyOf(Myself),BARD_ALL)
		Class(ThirdNearestEnemyOf(Myself),CLERIC_ALL)
		Class(ThirdNearestEnemyOf(Myself),MAGE_ALL)	
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(SecondNearestEnemyOf(Myself),0,CLERIC_INSECT_PLAGUE)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(SecondNearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(SecondNearestEnemyOf(Myself),DRUID_ALL)
		Class(SecondNearestEnemyOf(Myself),BARD_ALL)
		Class(SecondNearestEnemyOf(Myself),CLERIC_ALL)
		Class(SecondNearestEnemyOf(Myself),MAGE_ALL)	
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	CheckStat(NearestEnemyOf(Myself),0,CLERIC_INSECT_PLAGUE)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(NearestEnemyOf(Myself),STATE_SILENCED)
	CheckStatLT(NearestEnemyOf(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	OR(4)
		Class(NearestEnemyOf(Myself),DRUID_ALL)
		Class(NearestEnemyOf(Myself),BARD_ALL)
		Class(NearestEnemyOf(Myself),CLERIC_ALL)
		Class(NearestEnemyOf(Myself),MAGE_ALL)	
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Summon insects
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("ja#cast","LOCALS")
	HaveSpell(CLERIC_SUMMON_INSECTS)
	CheckStat(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	OR(4)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),MAGE_ALL)	
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_SUMMON_INSECTS)
END


/////////////////////////////////////////////////////////////////////
// Mistcast magic
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("ja#cast","LOCALS")
	HaveSpell(CLERIC_MISCAST_MAGIC)
	CheckStat(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),49,SPELLFAILUREPRIEST)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	OR(4)
		Class(LastSeenBy(Myself),DRUID_ALL)
		Class(LastSeenBy(Myself),BARD_ALL)
		Class(LastSeenBy(Myself),CLERIC_ALL)
		Class(LastSeenBy(Myself),MAGE_ALL)	
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)
END


/////////////////////////////////////////////////////////////////////
// End of block:
// miscast magic, summon insects
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// *********************  Disabling spells *********************** //
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Level 4- spells
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(NearestEnemyOf(Myself),STATE_SLEEPING)
	!StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	!StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
	!StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
	!CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	!StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	!StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	!StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Cloak of fear
/////////////////////////////////////////////////////////////////////	
IF
	GlobalTimerExpired("ja#cast","LOCALS")
	HaveSpell(CLERIC_CLOAK_OF_FEAR)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CLOAK_OF_FEAR)
END


/////////////////////////////////////////////////////////////////////
// Command
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("ja#cast","LOCALS")
	HaveSpell(CLERIC_COMMAND)
	!Race(LastSeenBy(Myself),ELF)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
	!StateCheck(LastSeenBy(Myself),STATE_BLIND)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(4,1) // 75% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_COMMAND)
END


/////////////////////////////////////////////////////////////////////
// *********************  Damaging spells ************************ //
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////
// Level 4- spells
/////////////////////////////////////////////////////////////////////
IF
	!CheckStat(SixthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SixthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FifthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FifthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(FourthNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(FourthNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(ThirdNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(ThirdNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(SecondNearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(SecondNearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!CheckStat(NearestEnemyOf(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(NearestEnemyOf(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
	!StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
	!StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Call lightning
/////////////////////////////////////////////////////////////////////
IF
	GlobalTimerExpired("ja#cast","LOCALS")
	HaveSpell(CLERIC_CALL_LIGHTNING)
	AreaType(OUTDOOR)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE3) // Protection from magic
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_PROTECTION)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_SHIELDING)
	!CheckStat(LastSeenBy(Myself),1,POTION_OF_MAGIC_BLOCKING)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	See(LastSeenBy(Myself))
	!RandomNum(2,1) // 50% to cast
THEN
	RESPONSE #100
		SetGlobalTimer("ja#cast","LOCALS",6)
		Spell(LastSeenBy(Myself),CLERIC_CALL_LIGHTNING)
END


/////////////////////////////////////////////////////////////////////
// Find a slept target. this only work for PC's enemies            //
// because sleeping creatures are not considered as enemies        //
/////////////////////////////////////////////////////////////////////
IF
	!StateCheck(Player6,STATE_CHARMED)
	CheckStat(Player6,0,SANCTUARY)
	StateCheck(Player6,STATE_SLEEPING)
	See(Player6)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player5,STATE_CHARMED)
	CheckStat(Player5,0,SANCTUARY)
	StateCheck(Player5,STATE_SLEEPING)
	See(Player5)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player4,STATE_CHARMED)
	CheckStat(Player4,0,SANCTUARY)
	StateCheck(Player4,STATE_SLEEPING)
	See(Player4)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player3,STATE_CHARMED)
	CheckStat(Player3,0,SANCTUARY)
	StateCheck(Player3,STATE_SLEEPING)
	See(Player3)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player2,STATE_CHARMED)
	CheckStat(Player2,0,SANCTUARY)
	StateCheck(Player2,STATE_SLEEPING)
	See(Player2)
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(Player1,STATE_CHARMED)
	CheckStat(Player1,0,SANCTUARY)
	StateCheck(Player1,STATE_SLEEPING)
	See(Player1)
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Safe attack, target is sleeping
/////////////////////////////////////////////////////////////////////
IF
	Allegiance(Myself,Enemy)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	StateCheck(LastSeenBy(Myself),STATE_SLEEPING)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		//AttackReevaluate(LastSeenBy(Myself),15)
		AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Find a helpless target to attack
/////////////////////////////////////////////////////////////////////
IF
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(SixthNearestEnemyOf(Myself),0,HELD)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(FifthNearestEnemyOf(Myself),0,HELD)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(FourthNearestEnemyOf(Myself),0,HELD)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(ThirdNearestEnemyOf(Myself),0,HELD)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(2)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(SecondNearestEnemyOf(Myself),0,HELD)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	OR(2)
		StateCheck(NearestEnemyOf(Myself),STATE_STUNNED)
		CheckStatGT(NearestEnemyOf(Myself),0,HELD)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Safe attack, target can't escape
/////////////////////////////////////////////////////////////////////
IF
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(2)
		StateCheck(LastSeenBy(Myself),STATE_STUNNED)
		CheckStatGT(LastSeenBy(Myself),0,HELD)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		//AttackReevaluate(LastSeenBy(Myself),15)
		AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Find something to attack, which has bonus on to hit
/////////////////////////////////////////////////////////////////////
IF
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_HELPLESS)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_HELPLESS)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_HELPLESS)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(NearestEnemyOf(Myself),STATE_SLOWED)
		StateCheck(NearestEnemyOf(Myself),STATE_BLIND)
		StateCheck(NearestEnemyOf(Myself),STATE_HELPLESS)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// target is easier to hit
/////////////////////////////////////////////////////////////////////
IF
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_SLOWED)
		StateCheck(LastSeenBy(Myself),STATE_BLIND)
		StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	See(LastSeenBy(Myself))	
THEN
	RESPONSE #100
		//AttackReevaluate(LastSeenBy(Myself),15)
		AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// Find something to attack, which hasn't control of itself
/////////////////////////////////////////////////////////////////////
IF
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(SixthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SixthNearestEnemyOf(Myself),STATE_CONFUSED)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(FifthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(FifthNearestEnemyOf(Myself),STATE_CONFUSED)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(FourthNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(FourthNearestEnemyOf(Myself),STATE_CONFUSED)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(ThirdNearestEnemyOf(Myself),STATE_CONFUSED)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(SecondNearestEnemyOf(Myself),0,SANCTUARY)
	OR(3)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_CONFUSED)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END

IF
	!StateCheck(NearestEnemyOf(Myself),STATE_CHARMED)
	CheckStat(NearestEnemyOf(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
		StateCheck(NearestEnemyOf(Myself),STATE_FEEBLEMINDED)
		StateCheck(NearestEnemyOf(Myself),STATE_CONFUSED)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
END


/////////////////////////////////////////////////////////////////////
// Easy attack, target hasn't control of itself
/////////////////////////////////////////////////////////////////////
IF
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)	
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_PANIC)
		StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
		StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
THEN
	RESPONSE #100
		//AttackReevaluate(LastSeenBy(Myself),15)
		AttackOneRound(LastSeenBy(Myself))
END


/////////////////////////////////////////////////////////////////////
// No easy target found, let's attack randomly
/////////////////////////////////////////////////////////////////////
IF
  RandomNum(9,1)
  See(Player1)
  See(Player2)
  See(Player3)
  See(Player4)
  See(Player5)
  See(Player6)
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(9,2)
  See(Player6)
  See(Player1)
  See(Player2)
  See(Player3)
  See(Player4)
  See(Player5)
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(9,3)
  See(Player5)
  See(Player6)
  See(Player1)
  See(Player2)
  See(Player3)
  See(Player4)
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(9,4)
  See(Player4)
  See(Player5)
  See(Player6)
  See(Player1)
  See(Player2)
  See(Player3)
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(9,5)
  See(Player3)
  See(Player4)
  See(Player5)
  See(Player6)
  See(Player1)
  See(Player2)
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(9,6)
  See(Player2)
  See(Player3)
  See(Player4)
  See(Player5)
  See(Player6)
  See(Player1)
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(9,7)
  See(Player6)
  See(Player5)
  See(Player4)
  See(Player3)
  See(Player2)
  See(Player1)
  See(WeakestOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(9,8)
  See(Player6)
  See(Player5)
  See(Player4)
  See(Player3)
  See(Player2)
  See(Player1)
  See(MostDamagedOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  RandomNum(9,9)
  See(Player6)
  See(Player5)
  See(Player4)
  See(Player3)
  See(Player2)
  See(Player1)
  See(WorstAC(Myself))
  False()
THEN
  RESPONSE #100
END

IF
	ActionListEmpty()
	OR(2)
		!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
		NumCreature([ENEMY],1)
THEN
	RESPONSE #100
		//AttackReevaluate(LastSeenBy(Myself),15)
		AttackOneRound(LastSeenBy(Myself))
END