///////////////////////////////////////////////////////////////////////
// Wolf
///////////////////////////////////////////////////////////////////////


IF
	Delay(5)
	See(NearestEnemyOf(Myself))
	Class(NearestEnemyOf(Myself),DRUID)
	NumCreatureGT([ENEMY],1)
THEN
	RESPONSE #100
		RandomWalk()
END

IF
	Delay(5)
	See(NearestEnemyOf(Myself))
	Class(NearestEnemyOf(Myself),RANGER)
	NumCreatureGT([ENEMY],1)
THEN
	RESPONSE #100
		RandomWalk()
END


